"""
Question bank: NEET 2013 (Code W) - Biology (Solved Answers).

75 questions parsed from NEET 2013 (Code W)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Select the wrong statement:",
        "options": ["Isogametes are similar in structure, function and behaviour", "Anisogametes differ either in structure, function or behaviour", "In Oomycetes female gamete is smaller and motile, while male gamete is larger and nonmotile", "Chlamydomonas Exhibits both isogamy and anisogamy and Fucus shows oogamy"],
        "correct_option_id": 2,
        "explanation": "In Oomycetes, the female gamete is actually large and non-motile while the male gamete is smaller; the statement reverses this fact.",
    },
    {
        "question": "Which one of the following is not a correct statement?",
        "options": ["Herbarium houses dried, pressed and preserved plant specimens", "Botanical gardens have collection of living plants for reference.", "A museum has collection of photographs of plants and animals.", "Key is a taxonomic aid for identification of specimens."],
        "correct_option_id": 2,
        "explanation": "A museum houses preserved plant and animal specimens, not merely photographs.",
    },
    {
        "question": "Isogamous condition with non-flagellated gametes is found in:",
        "options": ["Chlamydomonas", "Spirogyra", "Volvox", "Fucus"],
        "correct_option_id": 1,
        "explanation": "Spirogyra shows isogamy with non-motile (non-flagellated) gametes that fuse via conjugation tubes.",
    },
    {
        "question": "Besides paddy fields, cyanobacteria are also found inside vegetative part of:",
        "options": ["Pinus", "Cycas", "Equisetum", "Psilotum"],
        "correct_option_id": 1,
        "explanation": "Cyanobacteria (Anabaena) reside symbiotically in the coralloid roots of Cycas.",
    },
    {
        "question": "Megasporangium is equivalent to:",
        "options": ["Embryo sac", "Fruit", "Nucellus", "Ovule"],
        "correct_option_id": 2,
        "explanation": "The nucellus of the ovule is functionally equivalent to the megasporangium.",
    },
    {
        "question": "Read the following statements (A-E) and answer the question which follows them: (NEET 2013) (A) In liverworts, mosses, and ferns gametophytes are free-living (B) Gymnosperms and some ferns are heterosporous (C) Sexual reproduction in Fucus, Volvox and Albugo is oogamous (D) The sporophyte in liverworts is more elaborate than that in mosses (E) Both, Pinus and Marchantia are dioecious",
        "options": ["One", "Two", "Three", "Four"],
        "correct_option_id": 2,
        "explanation": "Statements A, B, and C are correct; D is false (mosses have more elaborate sporophytes) and E is false (Pinus is monoecious).",
    },
    {
        "question": "Among bitter gourd, mustard, brinjal, pumpkin, china rose, lupin, cucumber, sunnhemp, gram, guava, bean, chilli, plum, petunia, tomato, rose, withania, potato, onion, aloe and tulip how many plants have hypogynous flower?",
        "options": ["Six", "Ten", "Fifteen", "Eighteen"],
        "correct_option_id": 2,
        "explanation": "Most listed plants (excluding epigynous ones like bitter gourd, pumpkin, cucumber, guava, and perigynous ones like plum, rose) have hypogynous flowers, totaling fifteen.",
    },
    {
        "question": "Interfascicular cambium develops from the cells of:",
        "options": ["Medullary rays", "Xylem parenchyma", "Endodermis", "Pericycle"],
        "correct_option_id": 0,
        "explanation": "Interfascicular cambium arises from parenchymatous cells of the medullary rays located between vascular bundles.",
    },
    {
        "question": "In China rose the flowers are:",
        "options": ["Actinomorphic, hypogynous with twisted aestivation", "Actinomorphic, epigynous with valvate aestivation", "Zygomorphic, hypogynous with imbricate aestivation", "Zygomorphic, epigynous with twisted aestivation"],
        "correct_option_id": 0,
        "explanation": "China rose flowers are actinomorphic, hypogynous, with twisted (contorted) aestivation of petals.",
    },
    {
        "question": "Lenticels are involved in:",
        "options": ["Transpiration", "Gaseous exchange", "Food transport", "Photosynthesis"],
        "correct_option_id": 1,
        "explanation": "Lenticels are pores in the bark that facilitate gaseous exchange.",
    },
    {
        "question": "Age of a tree can be estimated by:",
        "options": ["Its height and girth", "Biomass", "Number of annual rings", "Diameter of its heartwood"],
        "correct_option_id": 2,
        "explanation": "Each annual ring typically represents one year of growth, allowing age estimation.",
    },
    {
        "question": "Seed coat is not thin, membranous in:",
        "options": ["Maize", "Coconut", "Groundnut", "Gram"],
        "correct_option_id": 1,
        "explanation": "Coconut has a thick, fibrous/hard seed coat unlike the thin membranous coats in maize, groundnut, and gram.",
    },
    {
        "question": "Transition state structure of the substrate formed during an enzymatic reaction is:",
        "options": ["Transient but stable", "Permanent but unstable", "Transient and unstable", "Permanent and stable"],
        "correct_option_id": 2,
        "explanation": "The enzyme-substrate transition state is short-lived (transient) and energetically unstable.",
    },
    {
        "question": "A phosphoglyceride is always made up of:",
        "options": ["Only a saturated fatty acid esterified to a glycerol molecule to which a phosphate group is also attached", "Only an unsaturated fatty acid esterified to a glycerol molecule to which a phosphate group is also attached", "A saturated or unsaturated fatty acid esterified to a glycerol molecule to which a phosphate group is also attached", "A saturated or unsaturated fatty acid esterified to a phosphate group which is also attached to a glycerol molecule"],
        "correct_option_id": 2,
        "explanation": "Phosphoglycerides consist of glycerol esterified with fatty acids (saturated or unsaturated) and a phosphate group.",
    },
    {
        "question": "Pigment-containing membranous extensions in some cyanobacteria are:",
        "options": ["Heterocysts", "Basal bodies", "Pneumatophores", "Chromatophores"],
        "correct_option_id": 3,
        "explanation": "Chromatophores are pigmented membranous extensions in cyanobacteria involved in photosynthesis.",
    },
    {
        "question": "A major site for synthesis of lipids is:",
        "options": ["RER", "SER", "Symplast", "Nucleoplasm"],
        "correct_option_id": 1,
        "explanation": "Smooth Endoplasmic Reticulum (SER) is the primary site for lipid synthesis in cells.",
    },
    {
        "question": "The complex formed by a pair of synapsed homologous chromosomes is called:",
        "options": ["Equatorial plate", "Kinetochore", "Bivalent", "Axoneme"],
        "correct_option_id": 2,
        "explanation": "A pair of synapsed homologous chromosomes during meiosis forms a bivalent (tetrad).",
    },
    {
        "question": "The most abundant intracellular cation is:",
        "options": ["Na+", "Ca++", "H+", "K+"],
        "correct_option_id": 3,
        "explanation": "Potassium (K+) is the most abundant cation inside cells.",
    },
    {
        "question": "During seed germination its stored food is mobilized by:",
        "options": ["Ethylene", "Cytokinin", "ABA", "Gibberellin"],
        "correct_option_id": 3,
        "explanation": "Gibberellin stimulates the synthesis of hydrolytic enzymes that mobilize stored food during seed germination.",
    },
    {
        "question": "Which of the following criteria does not pertain to facilitated transport?",
        "options": ["Requirement of special membrane proteins", "High selectivity", "Transport saturation", "Uphill transport"],
        "correct_option_id": 3,
        "explanation": "Facilitated transport is passive (down the concentration gradient), not uphill transport (which requires energy).",
    },
    {
        "question": "The first stable product of fixation of atmospheric nitrogen in leguminous plants is:",
        "options": ["NO2-", "Ammonia", "NO3-", "Glutamate"],
        "correct_option_id": 1,
        "explanation": "Nitrogenase enzyme reduces atmospheric N2 directly to ammonia as the first stable product.",
    },
    {
        "question": "Which of the metabolites is common to respiration mediated breakdown of fats, carbohydrates and proteins?",
        "options": ["Glucose-6-phosphate", "Fructose 1,6-bisphosphate", "Pyruvic acid", "Acetyl CoA"],
        "correct_option_id": 3,
        "explanation": "Acetyl CoA is the common intermediate that enters the Krebs cycle from fat, carbohydrate, and protein breakdown.",
    },
    {
        "question": "Which one of the following statements is correct?",
        "options": ["Hard outer layer of pollen is called intine", "Sporogenous tissue is haploid", "Endothecium produces the microspores", "Tapetum nourishes the developing pollen"],
        "correct_option_id": 3,
        "explanation": "The tapetum is the nutritive layer that nourishes developing pollen grains.",
    },
    {
        "question": "Product of sexual reproduction generally generates:",
        "options": ["Longer viability of seeds", "Prolonged dormancy", "New genetic combination leading to variation", "Large biomass"],
        "correct_option_id": 2,
        "explanation": "Sexual reproduction involves recombination, producing offspring with new genetic combinations and variation.",
    },
    {
        "question": "Meiosis takes place in:",
        "options": ["Meiocyte", "Conidia", "Gemmule", "Megaspore"],
        "correct_option_id": 0,
        "explanation": "Meiocytes (meiocyte/PMCs) are the cells that undergo meiosis to form haploid spores/gametes.",
    },
    {
        "question": "Advantage of cleistogamy is:",
        "options": ["Higher genetic variability", "More vigorous offspring", "No dependence on pollinators", "Vivipary"],
        "correct_option_id": 2,
        "explanation": "Cleistogamous flowers self-pollinate within closed flowers, ensuring seed set without needing pollinators.",
    },
    {
        "question": "Monoecious plant of Chara shows occurrence of:",
        "options": ["Antheridiophore and archegoniophore on the same plant", "Stamen and carpel on the same plant", "Upper antheridium and lower oogonium on the same plant", "Upper oogonium and lower antheridium on the same plant"],
        "correct_option_id": 2,
        "explanation": "In monoecious Chara, the antheridium (globule) is located above and the oogonium (nucule) below on the same plant.",
    },
    {
        "question": "Perisperm differs from endosperm in:",
        "options": ["Being a haploid tissue", "Having no reserve food", "Being a diploid tissue", "Its formation by fusion of secondary nucleus with several sperms"],
        "correct_option_id": 2,
        "explanation": "Perisperm is diploid nucellar tissue, unlike triploid endosperm formed by double fertilization.",
    },
    {
        "question": "Which of the following statements is not true of two genes that show 50% recombination frequency?",
        "options": ["The genes may be on different chromosomes", "The genes are tightly linked", "The genes show independent assortment", "If the genes are present on the same chromosome, they undergo more than one crossovers in every meiosis"],
        "correct_option_id": 1,
        "explanation": "50% recombination indicates genes are unlinked (independently assorting), not tightly linked.",
    },
    {
        "question": "Variation in gene frequencies within populations can occur by chance rather than by natural selection. This is referred to as:",
        "options": ["Genetic flow", "Genetic drift", "Random mating", "Genetic load"],
        "correct_option_id": 1,
        "explanation": "Genetic drift refers to random, chance-based changes in allele frequencies within a population.",
    },
    {
        "question": "If two persons with 'AB' blood group marry and have sufficiently large number of children, these children could be classified as 'A' blood group : 'AB' blood group : 'B' blood group in 1 : 2 : 1 ratio. Modern technique of protein electrophoresis reveals presence of both 'A' and 'B' type proteins in 'AB' blood group individuals. This is an example of:",
        "options": ["Codominance", "Incomplete dominance", "Partial dominance", "Complete dominance"],
        "correct_option_id": 0,
        "explanation": "Both A and B alleles are equally and independently expressed in the heterozygote, characteristic of codominance.",
    },
    {
        "question": "The process by which organisms with different evolutionary history evolve similar phenotypic adaptations in response to a common environmental challenge, is called:",
        "options": ["Natural selection", "Convergent evolution", "Non-random evolution", "Adaptive radiation"],
        "correct_option_id": 1,
        "explanation": "Convergent evolution describes unrelated organisms independently evolving similar traits due to similar environmental pressures.",
    },
    {
        "question": "The tendency of population to remain in genetic equilibrium may be disturbed by:",
        "options": ["Random mating", "Lack of migration", "Lack of mutations", "Lack of random mating"],
        "correct_option_id": 3,
        "explanation": "Non-random mating disrupts Hardy-Weinberg genetic equilibrium in a population.",
    },
    {
        "question": "Which of the following Bt crops is being grown in India by the farmers?",
        "options": ["Maize", "Cotton", "Brinjal", "Soybean"],
        "correct_option_id": 1,
        "explanation": "Bt cotton is the Bt crop commercially cultivated by farmers in India.",
    },
    {
        "question": "A good producer of citric acid is:",
        "options": ["Aspergillus", "Pseudomonas", "Clostridium", "Saccharomyces"],
        "correct_option_id": 0,
        "explanation": "Aspergillus niger is widely used industrially for commercial citric acid production.",
    },
    {
        "question": "DNA fragments generated by the restriction endonucleases in a chemical reaction can be separated by:",
        "options": ["Centrifugation", "Polymerase chain reaction", "Electrophoresis", "Restriction mapping"],
        "correct_option_id": 2,
        "explanation": "Gel electrophoresis separates DNA fragments based on size using an electric field.",
    },
    {
        "question": "Which of the following is not correctly matched for the organism and its cell wall degrading enzyme?",
        "options": ["Bacteria - Lysozyme", "Plant cells - Cellulase", "Algae - Methylase", "Fungi - Chitinase"],
        "correct_option_id": 2,
        "explanation": "Algal cell walls are degraded by enzymes like cellulase/pectinase, not methylase (which acts on DNA/RNA).",
    },
    {
        "question": "The colonies of recombinant bacteria appear white in contrast to blue colonies of non-recombinant bacteria because of:",
        "options": ["Non-recombinant bacteria containing betagalactosidase", "Insertional inactivation of alpha-galactosidase in non-recombinant bacteria", "Insertional inactivation of alpha-galactosidase in recombinant bacteria", "Inactivation of glycosidase enzyme in recombinant bacteria"],
        "correct_option_id": 2,
        "explanation": "Insertion of foreign DNA disrupts (inactivates) the galactosidase gene in recombinant bacteria, preventing blue color formation.",
    },
    {
        "question": "Which of the following are likely to be present in deep sea water?",
        "options": ["Archaebacteria", "Eubacteria", "Blue-green algae", "Saprophytic fungi"],
        "correct_option_id": 0,
        "explanation": "Archaebacteria (extremophiles) can survive extreme deep-sea conditions of high pressure and temperature.",
    },
    {
        "question": "Natural reservoir of phosphorus is:",
        "options": ["Sea water", "Animal bones", "Rock", "Fossils"],
        "correct_option_id": 2,
        "explanation": "Rocks are the primary natural reservoir of phosphorus in the phosphorus cycle.",
    },
    {
        "question": "Secondary productivity is rate of formation of new organic matter by:",
        "options": ["Producer", "Parasite", "Consumer", "Decomposer"],
        "correct_option_id": 2,
        "explanation": "Secondary productivity refers to the rate of biomass formation by consumers (heterotrophs).",
    },
    {
        "question": "Which one of the following is not used for ex situ plant conservation?",
        "options": ["Field gene banks", "Seed banks", "Shifting cultivation", "Botanical Gardens"],
        "correct_option_id": 2,
        "explanation": "Shifting cultivation is an agricultural practice, not a method of ex situ conservation.",
    },
    {
        "question": "Kyoto Protocol was endorsed at:",
        "options": ["CoP - 3", "CoP - 5", "CoP - 6", "CoP - 4"],
        "correct_option_id": 0,
        "explanation": "The Kyoto Protocol was adopted at the third Conference of Parties (CoP-3) in 1997.",
    },
    {
        "question": "Which of the following represent maximum number of species among global biodiversity?",
        "options": ["Algae", "Lichens", "Fungi", "Mosses and Ferns"],
        "correct_option_id": 2,
        "explanation": "Among the given groups, Fungi represents the highest number of described species.",
    },
    {
        "question": "Which group of animals belong to the same phylum?",
        "options": ["Malarial parasite, Amoeba, Mosquito", "Earthworm, Pinworm, Tapeworm", "Prawn, Scorpion, Locusta", "Sponge, Sea anemone, Starfish"],
        "correct_option_id": 2,
        "explanation": "Prawn, scorpion, and Locusta (grasshopper) all belong to Phylum Arthropoda.",
    },
    {
        "question": "One of the representatives of Phylum Arthropoda is:",
        "options": ["Cuttlefish", "Silverfish", "Pufferfish", "Flying fish"],
        "correct_option_id": 1,
        "explanation": "Silverfish (Lepisma) is an insect belonging to Phylum Arthropoda; the others are actually fish (Chordata/Mollusca).",
    },
    {
        "question": "The H-zone in the skeletal muscle fibre is due to:",
        "options": ["The absence of myofibrils in the central portion of A-band", "The central gap between myosin filaments in the A-band", "The central gap between actin filaments extending through myosin filaments in the A-band", "Extension of myosin filaments in the central portion of the A-band"],
        "correct_option_id": 1,
        "explanation": "The H-zone represents the central region of the A-band where only myosin filaments are present, without overlapping actin.",
    },
    {
        "question": "What external changes are visible after the last moult of a cockroach nymph?",
        "options": ["Mandibles become harder", "Anal cerci develop", "Both fore wings and hind wings develop", "Labium develops"],
        "correct_option_id": 2,
        "explanation": "After the final nymphal moult, the cockroach develops both fore wings (tegmina) and hind wings, becoming a winged adult.",
    },
    {
        "question": "The Golgi complex plays a major role:",
        "options": ["In trapping the light and transforming it into chemical energy", "In digesting proteins and carbohydrates", "As energy transferring organelles", "In post translational modification of proteins and glycosidation of lipid"],
        "correct_option_id": 3,
        "explanation": "The Golgi apparatus modifies, packages, and glycosylates proteins and lipids after synthesis.",
    },
    {
        "question": "Macro molecule chitin is:",
        "options": ["Nitrogen containing polysaccharide", "Phosphorus containing polysaccharide", "Sulphur containing polysaccharide", "Simple polysaccharide"],
        "correct_option_id": 0,
        "explanation": "Chitin is a nitrogen-containing polysaccharide made of N-acetylglucosamine units.",
    },
    {
        "question": "The essential chemical components of many coenzymes are:",
        "options": ["Proteins", "Nucleic acids", "Carbohydrates", "Vitamins"],
        "correct_option_id": 3,
        "explanation": "Many coenzymes (like NAD, FAD, CoA) are derived from vitamins.",
    },
    {
        "question": "A pregnant female delivers a baby who suffers from stunted growth, mental retardation low intelligence quotient and abnormal skin. This is the result of:",
        "options": ["Deficiency of iodine in diet", "Low secretion of growth hormone", "Cancer of the thyroid gland", "Over secretion of pars distalis"],
        "correct_option_id": 0,
        "explanation": "Iodine deficiency during pregnancy causes congenital hypothyroidism (cretinism) in the newborn, leading to these symptoms.",
    },
    {
        "question": "Select the correct statement with respect to locomotion in humans:",
        "options": ["A decreased level of progesterone causes osteoporosis in old people.", "Accumulation of uric acid crystals in joints causes their inflammation.", "The vertebral column has 10 thoracic vertebrae.", "The joint between adjacent vertebrae is a fibrous joint."],
        "correct_option_id": 1,
        "explanation": "Gout is caused by the accumulation of uric acid crystals in joints, leading to inflammation.",
    },
    {
        "question": "Which of the following statement is correct in relation to the endocrine system?",
        "options": ["Adenohypophysis is under direct neural regulation of the hypothalamus.", "Organs in the body like gastrointestinal tract, heart, kidney and liver do not produce any hormones.", "Non-nutrient chemicals produced by the body in trace amount that act as intercellular messenger are known as hormones.", "Releasing and inhibitory hormones are produced by the pituitary gland."],
        "correct_option_id": 2,
        "explanation": "Hormones are defined as non-nutrient chemical messengers produced in trace amounts that regulate physiological processes.",
    },
    {
        "question": "What is the correct sequence of sperm formation?",
        "options": ["Spermatid, Spermatocyte, Spermatogonia, Spermatozoa", "Spermatogonia, Spermatocyte, Spermatozoa, Spermatid", "Spermatogonia, Spermatozoa, Spermatocyte, Spermatid", "Spermatogonia, Spermatocyte, Spermatid, Spermatozoa"],
        "correct_option_id": 3,
        "explanation": "Spermatogenesis proceeds: Spermatogonia -> Spermatocyte -> Spermatid -> Spermatozoa (via spermiogenesis).",
    },
    {
        "question": "Menstrual flow occurs due to lack of:",
        "options": ["Progesterone", "FSH", "Oxytocin", "Vasopressin"],
        "correct_option_id": 0,
        "explanation": "A drop in progesterone (and estrogen) levels in the absence of fertilization triggers endometrial breakdown and menstruation.",
    },
    {
        "question": "Which one of the following is not the function of placenta? It:",
        "options": ["Facilitates supply of oxygen and nutrients to embryo.", "Secretes estrogen.", "Facilitates removal of carbon dioxide and waste material from embryo.", "Secretes oxytocin during parturition."],
        "correct_option_id": 3,
        "explanation": "Oxytocin is secreted by the posterior pituitary gland, not the placenta.",
    },
    {
        "question": "One of the legal methods of birth control is:",
        "options": ["Abortion by taking an appropriate medicine", "By abstaining from coitus from day 10 to 17 of the menstrual cycle", "By having coitus at the time of day break", "By a premature ejaculation during coitus"],
        "correct_option_id": 1,
        "explanation": "Abstaining from coitus during the fertile period (day 10-17, the rhythm/safe period method) is a natural, legal contraceptive method.",
    },
    {
        "question": "Which of the following cannot be detected in a developing foetus by amniocentesis?",
        "options": ["Klinefelter syndrome", "Sex of the foetus", "Down syndrome", "Jaundice"],
        "correct_option_id": 3,
        "explanation": "Jaundice is a postnatal/functional condition, not a chromosomal or genetic disorder detectable by amniocentesis.",
    },
    {
        "question": "Artificial insemination means:",
        "options": ["Transfer of sperms of a healthy donor to a test tube containing ova", "Transfer of sperms of husband to a test tube containing ova", "Artificial introduction of sperms of a healthy donor into the vagina", "Introduction of sperms of healthy donor directly into the ovary"],
        "correct_option_id": 2,
        "explanation": "Artificial insemination involves introducing collected semen directly into the female reproductive tract (vagina/uterus) artificially.",
    },
    {
        "question": "Which Mendelian idea is depicted by a cross in which the F1 generation resembles both the parents?",
        "options": ["Incomplete dominance", "Law of dominance", "Inheritance of one gene", "Co-dominance"],
        "correct_option_id": 3,
        "explanation": "Co-dominance results in F1 offspring displaying traits of both parents simultaneously (e.g., AB blood group).",
    },
    {
        "question": "The incorrect statement with regard to Haemophilia is:",
        "options": ["It is a sex-linked disease", "It is a recessive disease", "It is a dominant disease", "A single protein involved in the clotting of blood is affected"],
        "correct_option_id": 2,
        "explanation": "Haemophilia is a recessive (not dominant), X-linked genetic disorder.",
    },
    {
        "question": "If both parents are carriers for thalassemia, which is an autosomal recessive disorder, what are the chances of pregnancy resulting in an affected child?",
        "options": ["No chance", "50%", "25%", "100%"],
        "correct_option_id": 2,
        "explanation": "Cross between two heterozygous carriers (Aa x Aa) gives a 1:2:1 ratio, so 25% chance of an affected (aa) child.",
    },
    {
        "question": "Which enzyme/s will be produced in a cell in which there is a nonsense mutation in the lac Y gene?",
        "options": ["β-galactosidase", "Lactose permease", "Transacetylase", "Lactose permease and transacetylase"],
        "correct_option_id": 0,
        "explanation": "A nonsense mutation in lacY halts translation of permease; since lacZ precedes lacY, beta-galactosidase is still produced normally.",
    },
    {
        "question": "According to Darwin, the organic evolution is due to:",
        "options": ["Intraspecific competition.", "Interspecific competition.", "Competition within closely related species.", "Reduced feeding efficiency in one species due to the presence of interfering species."],
        "correct_option_id": 1,
        "explanation": "Darwin proposed that interspecific competition (struggle for existence between different species) drives natural selection and evolution.",
    },
    {
        "question": "The eye of octopus and eye of cat show different patterns of structure, yet they perform similar function. This is an example of:",
        "options": ["Homologous organs that have evolved due to convergent evolution.", "Homologous organs that have evolved due to divergent evolution.", "Analogous organs that have evolved due to convergent evolution.", "Analogous organs that have evolved due to divergent evolution."],
        "correct_option_id": 2,
        "explanation": "Structurally different organs performing the same function represent analogous organs resulting from convergent evolution.",
    },
    {
        "question": "Infection of Ascaris usually occurs by:",
        "options": ["Drinking water containing eggs of Ascaris", "Eating imperfectly cooked port", "Tse-tse fly", "Mosquito bite"],
        "correct_option_id": 0,
        "explanation": "Ascaris infection typically occurs through ingestion of contaminated water or food containing Ascaris eggs.",
    },
    {
        "question": "The cell-mediated immunity inside the human body is carried out by:",
        "options": ["T-lymphocytes", "B-lymphocytes", "Thrombocytes", "Erythrocytes"],
        "correct_option_id": 0,
        "explanation": "T-lymphocytes mediate cell-mediated immunity, while B-lymphocytes are responsible for humoral immunity.",
    },
    {
        "question": "In plant breeding programmes, the entire collection (of plants/seeds) having all the diverse alleles for all genes in a given crop is called:",
        "options": ["Selection of superior recombinants", "Cross-hybridisation among the selected parents", "Evaluation and selection of parents.", "Germplasm collection"],
        "correct_option_id": 3,
        "explanation": "Germplasm collection is the complete genetic diversity/allele pool of a crop species preserved for breeding.",
    },
    {
        "question": "During sewage treatment, biogases are produced which include:",
        "options": ["Methane, hydrogensulphide, carbon dioxide", "Methane, oxygen, hydrogensulphide", "Hydrogensulphide, methane, sulphur dioxide", "Hydrogensulphide, nitrogen, methane"],
        "correct_option_id": 0,
        "explanation": "Anaerobic sludge digestion during sewage treatment produces methane, hydrogen sulphide, and carbon dioxide as biogases.",
    },
    {
        "question": "A biologist studied the population of rats in a barn. He found that the average natality was 250, average mortality 240, immigration 20 and emigration 30. The net increase in population is:",
        "options": ["10", "15", "05", "Zero"],
        "correct_option_id": 3,
        "explanation": "Net change = (Natality + Immigration) - (Mortality + Emigration) = (250+20) - (240+30) = 270-270 = 0.",
    },
    {
        "question": "Which one of the following processes during decomposition is correctly described?",
        "options": ["Fragmentation - Carried out by organisms such as earthworm", "Humification - Leads to the accumulation of a dark coloured substance humus which undergoes microbial action at a very fast rate", "Catabolism - Last step in the decomposition under fully anaerobic condition", "Leaching - Water soluble inorganic nutrients rise to the top layers of soil"],
        "correct_option_id": 0,
        "explanation": "Fragmentation of detritus into smaller particles is carried out by detritivores such as earthworms.",
    },
    {
        "question": "A sedentary sea anemone gets attached to the shell lining of hermit crab. The association is:",
        "options": ["Ectoparasitism", "Symbiosis", "Commensalism", "Amensalism"],
        "correct_option_id": 2,
        "explanation": "The sea anemone benefits from transport/protection without harming the hermit crab, a classic example of commensalism.",
    },
    {
        "question": "Global warming can be controlled by:",
        "options": ["Reducing deforestation, cutting down use of fossil fuel", "Reducing reforestation, increasing the use of fossil fuel", "Increasing deforestation, slowing down the growth of human population", "Increasing deforestation, reducing efficiency of energy usage"],
        "correct_option_id": 0,
        "explanation": "Reducing deforestation (preserving carbon sinks) and cutting fossil fuel use lowers greenhouse gas emissions, mitigating global warming.",
    },
    {
        "question": "The Air Prevention and Control of Pollution Act came into force in:",
        "options": ["1975", "1981", "1985", "1990a"],
        "correct_option_id": 1,
        "explanation": "The Air (Prevention and Control of Pollution) Act was enacted in India in 1981.",
    },
]
