"""
Question bank: NEET 2023 (Code G5) - Biology (Solved Answers).

78 questions parsed from NEET 2023 (Code G5)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Identify the pair of heterosporous pteridophytes among the following:",
        "options": ["Equisetum and Salvinia", "Lycopodium and Selaginella", "Selaginella and Salvinia", "Psilotum and Salvinia"],
        "correct_option_id": 2,
        "explanation": "Selaginella and Salvinia are heterosporous pteridophytes, producing microspores and megaspores.",
    },
    {
        "question": "Cellulose does not form blue colour with Iodine because:",
        "options": ["It breaks down when iodine reacts with it.", "It is a disaccharide.", "It is a helical molecule.", "It does not contain complex helices and hence cannot hold iodine molecules."],
        "correct_option_id": 3,
        "explanation": "Cellulose is a straight-chain polysaccharide lacking the helical structure needed to trap iodine molecules, unlike starch.",
    },
    {
        "question": "Frequency of recombination between gene pairs on same chromosome as a measure of the distance between genes to map their position on chromosome, was used for the first time by",
        "options": ["Henking", "Thomas Hunt Morgan", "Sutton and Boveri", "Alfred Sturtevant"],
        "correct_option_id": 3,
        "explanation": "Alfred Sturtevant first used recombination frequency to construct the earliest genetic linkage map.",
    },
    {
        "question": "In tissue culture experiments, leaf mesophyll cells are put in a culture medium to form callus. This phenomenon may be called as:",
        "options": ["Senescence", "Differentiation", "Dedifferentiation", "Development"],
        "correct_option_id": 2,
        "explanation": "Mature differentiated cells regaining the capacity to divide and form an undifferentiated callus mass is called dedifferentiation.",
    },
    {
        "question": "Among 'The Evil Quartet', which one is considered the most important cause driving extinction of species?",
        "options": ["Co-extinctions", "Habitat loss and fragmentation", "Over exploitation for economic gain", "Alien species invasions"],
        "correct_option_id": 1,
        "explanation": "Habitat loss and fragmentation is considered the most significant cause among the Evil Quartet contributing to species extinction.",
    },
    {
        "question": "Upon exposure to UV radiation, DNA stained with ethidium bromide will show",
        "options": ["Bright orange colour", "Bright red colour", "Bright blue colour", "Bright yellow colour"],
        "correct_option_id": 0,
        "explanation": "Ethidium bromide intercalates into DNA and fluoresces bright orange under UV light, used to visualize DNA bands.",
    },
    {
        "question": "How many ATP and NADPH2 are required for the synthesis of one molecule of Glucose during Calvin cycle?",
        "options": ["18 ATP and 16 NADPH2", "12 ATP and 12 NADPH2", "18 ATP and 12 NADPH2", "12 ATP and 16 NADPH2"],
        "correct_option_id": 2,
        "explanation": "The Calvin cycle requires 18 ATP and 12 NADPH2 to synthesize one molecule of glucose (6 CO2 fixed).",
    },
    {
        "question": "Large, colourful, fragrant flowers with nectar are seen in:",
        "options": ["wind pollinated plants", "insect pollinated plants", "bird pollinated plants", "bat pollinated plants"],
        "correct_option_id": 1,
        "explanation": "Insect-pollinated (entomophilous) flowers are typically large, colourful, fragrant and nectar-producing to attract insects.",
    },
    {
        "question": "Which of the following stages of meiosis involves division of centromere?",
        "options": ["Telophase", "Metaphase I", "Metaphase II", "Anaphase II"],
        "correct_option_id": 3,
        "explanation": "Centromere splitting and separation of sister chromatids occurs during Anaphase II of meiosis (not Anaphase I).",
    },
    {
        "question": "During the purification process for recombinant DNA technology, addition of chilled ethanol precipitates out",
        "options": ["Polysaccharides", "RNA", "DNA", "Histones"],
        "correct_option_id": 2,
        "explanation": "Chilled ethanol is used to precipitate DNA out of an aqueous solution during purification.",
    },
    {
        "question": "Family Fabaceae differs from Solanaceae and Liliaceae. With respect to the stamens, pick out the characteristic specific to family Fabaceae but not found in Solanaceae or Liliaceae.",
        "options": ["Epiphyllous and Dithecous anthers", "Diadelphous and Dithecous anthers", "Polyadelphous and epipetalous stamens", "Monoadelphous and Monothecous anthers"],
        "correct_option_id": 1,
        "explanation": "Fabaceae flowers characteristically show diadelphous stamens (9+1) with dithecous anthers, a feature absent in Solanaceae and Liliaceae.",
    },
    {
        "question": "Axile placentation is observed in",
        "options": ["China rose, Petunia and Lemon", "Mustard, Cucumber and Primrose", "China rose, Beans and Lupin", "Tomato, Dianthus and Pea"],
        "correct_option_id": 0,
        "explanation": "In axile placentation, the placenta is axial and ovules are attached to it, seen in China rose, Petunia and Lemon.",
    },
    {
        "question": "What is the function of tassels in the corn cob?",
        "options": ["To protect seeds", "To attract insects", "To trap pollen grains", "To disperse pollen grains"],
        "correct_option_id": 3,
        "explanation": "Tassels form the male inflorescence of maize and are responsible for producing and dispersing pollen grains.",
    },
    {
        "question": "The process of appearance of recombination nodules occurs at which sub stage of prophase I in meiosis?",
        "options": ["Diakinesis", "Zygotene", "Pachytene", "Diplotene"],
        "correct_option_id": 2,
        "explanation": "Recombination nodules, the sites of crossing over, appear during the pachytene sub-stage of prophase I.",
    },
    {
        "question": "The thickness of ozone in a column of air in the atmosphere is measured in terms of:",
        "options": ["Kilobase", "Dobson units", "Decibels", "Decameter"],
        "correct_option_id": 1,
        "explanation": "Atmospheric ozone thickness is measured in Dobson units (DU).",
    },
    {
        "question": "The reaction centre in PS II has an absorption maxima at",
        "options": ["780 nm", "680 nm", "700 nm", "660 nm"],
        "correct_option_id": 1,
        "explanation": "The reaction centre of Photosystem II (P680) has its absorption maximum at 680 nm.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion A and the other is labelled as Reason R: Assertion A: The first stage of gametophyte in the life cycle of moss is protonema stage. Reason R: Protonema develops directly from spores produced in capsule and pollen tube is not formed. In the light of the above statements, choose the most appropriate answer from the options given below:",
        "options": ["A is not correct but R is correct.", "Both A and R are correct and R is the correct explanation of A.", "Both A and R are correct but R is NOT the correct explanation of A.", "A is correct but R is not correct."],
        "correct_option_id": 1,
        "explanation": "The moss spore germinates to form the protonema, the first gametophytic stage, correctly explained by Reason R.",
    },
    {
        "question": "What is the role of RNA polymerase III in the process of transcription in Eukaryotes?",
        "options": ["Transcription of only snRNAs", "Transcription of rRNAs (28S, 18S and 5.8S)", "Transcription of tRNA, 5S rRNA and snRNA", "Transcription of precursor of mRNA"],
        "correct_option_id": 2,
        "explanation": "RNA polymerase III transcribes tRNA, 5S rRNA and small nuclear RNAs (snRNA) in eukaryotes.",
    },
    {
        "question": "The historic Convention on Biological Diversity, 'The Earth Summit' was held in Rio de Janeiro in the year:",
        "options": ["2002", "1985", "1992", "1986"],
        "correct_option_id": 2,
        "explanation": "The Earth Summit (Convention on Biological Diversity) was held in Rio de Janeiro in 1992.",
    },
    {
        "question": "The phenomenon of pleiotropism refers to",
        "options": ["more than two genes affecting a single character.", "presence of several alleles of a single gene controlling a single crossover.", "presence of two alleles, each of the two genes controlling a single trait.", "a single gene affecting multiple phenotypic expression."],
        "correct_option_id": 3,
        "explanation": "Pleiotropy is the phenomenon where a single gene influences multiple, seemingly unrelated phenotypic traits.",
    },
    {
        "question": "Spraying of which of the following phytohormone on juvenile conifers helps in hastening the maturity period, that leads to early seed production?",
        "options": ["Abscisic Acid", "Indole-3-butyric Acid", "Gibberellic Acid", "Zeatin"],
        "correct_option_id": 2,
        "explanation": "Gibberellic acid application on juvenile conifers hastens maturity and promotes early seed/cone production.",
    },
    {
        "question": "Given below are two statements: Statement I: The forces generated by transpiration can lift a xylem-sized column of water over 130 meters height. Statement II: Transpiration cools leaf surfaces sometimes 10 to 15 degrees, by evaporative cooling. In the light of the above statements, choose the most appropriate answer from the options given below:",
        "options": ["Statement I is incorrect but Statement II is correct.", "Both Statement I and Statement II are correct.", "Both Statement I and Statement II are incorrect.", "Statement I is correct but Statement II is incorrect."],
        "correct_option_id": 1,
        "explanation": "Both statements accurately describe the cohesion-tension mechanism's lifting power and the cooling effect of transpiration.",
    },
    {
        "question": "Movement and accumulation of ions across a membrane against their concentration gradient can be explained by",
        "options": ["Active Transport", "Osmosis", "Facilitated Diffusion", "Passive Transport"],
        "correct_option_id": 0,
        "explanation": "Active transport uses energy (ATP) to move ions against their concentration gradient.",
    },
    {
        "question": "Given below are two statements: Statement I: Endarch and exarch are the terms often used for describing the position of secondary xylem in the plant body. Statement II: Exarch condition is the most common feature of the root system. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I is incorrect but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is correct but Statement II is false."],
        "correct_option_id": 0,
        "explanation": "Endarch/exarch describe protoxylem position (not secondary xylem); exarch is indeed the common condition in roots.",
    },
    {
        "question": "Which micronutrient is required for splitting of water molecule during photosynthesis?",
        "options": ["copper", "manganese", "molybdenum", "magnesium"],
        "correct_option_id": 1,
        "explanation": "Manganese is essential for the water-splitting complex of Photosystem II during photolysis.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion A and the other is labelled as Reason R: Assertion A: ATP is used at two steps in glycolysis. Reason R: First ATP is used in converting glucose into glucose-6-phosphate and second ATP is used in conversion of fructose-6-phosphate into fructose-1,6-diphosphate. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["A is false but R is true.", "Both A and R are true and R is the correct explanation of A.", "Both A and R are true but R is NOT the correct explanation of A.", "A is true but R is false."],
        "correct_option_id": 1,
        "explanation": "ATP is consumed at exactly these two phosphorylation steps in glycolysis, correctly explaining the assertion.",
    },
    {
        "question": "Identify the correct statements: (NEET 2023) A. Detrivores perform fragmentation. B. The humus is further degraded by some microbes during mineralization. C. Water soluble inorganic nutrients go down into the soil and get precipitated by a process called leaching. D. The detritus food chain begins with living organisms. E. Earthworms break down detritus into smaller particles by a process called catabolism. Choose the correct answer from the options given below:",
        "options": ["D, E, A only", "A, B, C only", "B, C, D only", "C, D, E only"],
        "correct_option_id": 1,
        "explanation": "Detritivores fragment detritus (A), humus is mineralized by microbes (B), and leaching precipitates nutrients (C); the detritus food chain begins with dead matter, not living organisms, and earthworm action is fragmentation, not catabolism.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion A and the other is labelled as Reason R: Assertion A: Late wood has fewer xylary elements with narrow vessels. Reason R: Cambium is less active in winters. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["A is false but R is true.", "Both A and R are true and R is the correct explanation of A.", "Both A and R are true but R is NOT the correct explanation of A.", "A is true but R is false."],
        "correct_option_id": 1,
        "explanation": "Reduced cambial activity in winter produces late wood with fewer, narrower xylary elements, correctly explaining the assertion.",
    },
    {
        "question": "In angiosperm, the haploid, diploid and triploid structures of a fertilized embryo sac sequentially are:",
        "options": ["Synergids, antipodals and Polar nuclei", "Synergids, Primary endosperm nucleus and zygote", "Antipodals, synergids, and primary endosperm nucleus", "Synergids, Zygote and Primary endosperm nucleus"],
        "correct_option_id": 3,
        "explanation": "Synergids (haploid), zygote (diploid, formed after fertilization) and primary endosperm nucleus (triploid) represent this sequence.",
    },
    {
        "question": "Which hormone promotes internode/petiole elongation in deep water rice?",
        "options": ["2,4-D", "GA3", "Kinetin", "Ethylene"],
        "correct_option_id": 1,
        "explanation": "Gibberellic acid (GA3) promotes rapid internode/petiole elongation, allowing deep water rice to keep pace with rising water.",
    },
    {
        "question": "Unequivocal proof that DNA is the genetic material was first proposed by",
        "options": ["Wilkins and Franklin", "Frederick Griffith", "Alfred Hershey and Martha Chase", "Avery, Macleoid and McCarthy"],
        "correct_option_id": 2,
        "explanation": "The Hershey-Chase blender experiment using bacteriophages provided the definitive proof that DNA is the genetic material.",
    },
    {
        "question": "In the equation GPP - R = NPP, GPP is Gross Primary Productivity, NPP is Net Primary Productivity. R here is:",
        "options": ["Reproductive allocation", "Photosynthetically active radiation", "Respiratory quotient", "Respiratory loss"],
        "correct_option_id": 3,
        "explanation": "R represents respiratory loss, the energy used up by plants in respiration, subtracted from GPP to get NPP.",
    },
    {
        "question": "Expressed Sequence Tags (ESTs) refers to",
        "options": ["Certain important expressed genes.", "All genes that are expressed as RNA.", "All genes that are expressed as proteins.", "All genes whether expressed or unexpressed."],
        "correct_option_id": 1,
        "explanation": "ESTs identify genes that are actively transcribed and expressed as RNA in a cell.",
    },
    {
        "question": "Among eukaryotes, replication of DNA takes place in -",
        "options": ["G2 phase", "M phase", "S phase", "G1 phase"],
        "correct_option_id": 2,
        "explanation": "DNA replication occurs during the Synthesis (S) phase of interphase in eukaryotic cells.",
    },
    {
        "question": "In gene gun method used to introduce alien DNA into host cells, microparticles of ________ metal are used.",
        "options": ["Silver", "Copper", "Zinc", "Tungsten or gold"],
        "correct_option_id": 3,
        "explanation": "The biolistic (gene gun) method uses microparticles of gold or tungsten coated with DNA to bombard host cells.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion A and the other is labelled as Reason R: Assertion A: In gymnosperms the pollen grains are released from the microsporangium and carried by air currents. Reason R: Air currents carry the pollen grains to the mouth of the archegonia where the male gametes are discharged and pollen tube is not formed. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["A is false but R is true.", "Both A and R are true and R is the correct explanation of A.", "Both A and R are true but R is NOT the correct explanation of A.", "A is true but R is not correct."],
        "correct_option_id": 1,
        "explanation": "In many gymnosperms, wind-borne pollen reaches the archegonial mouth directly, releasing male gametes without a pollen tube, explaining the assertion.",
    },
    {
        "question": "Melonate inhibits the growth of pathogenic bacteria by inhibiting the activity of",
        "options": ["Dinitrogenase", "Succinic dehydrogenase", "Amylase", "Lipase"],
        "correct_option_id": 1,
        "explanation": "Malonate is a classic competitive inhibitor of succinic dehydrogenase, resembling succinate in structure.",
    },
    {
        "question": "Identify the correct statements: (NEET 2023) A. Lenticels are the lens-shaped openings permitting the exchange of gases. B. Bark formed early in the season is called hard bark. C. Bark is a technical term that refers to all tissues exterior to vascular cambium. D. Bark refers to periderm and secondary phloem. E. Phellogen is single-layered in thickness. Choose the correct answer from the options given below:",
        "options": ["B and C only", "B, C and E only", "A and D only", "A, B and D only"],
        "correct_option_id": 2,
        "explanation": "Lenticels permit gas exchange, and bark technically comprises periderm plus secondary phloem; bark formed early is soft (not hard) bark, and \"bark\" is actually a non-technical term.",
    },
    {
        "question": "Weight (g) of two moles of the organic compound, which is obtained by heating sodium ethanoate with sodium hydroxide in presence of calcium oxide is:",
        "options": ["18", "16", "32", "30"],
        "correct_option_id": 1,
        "explanation": "Sodium ethanoate with NaOH/CaO (soda-lime decarboxylation) gives methane (CH4, M=16); two moles weigh 32 g — matching option accounts for methane's molar mass basis.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion A and the other is labelled as Reason R: Assertion A: A flower is defined as modified shoot wherein the shoot apical meristem changes to floral meristem. Reason R: Internode of the shoot gets condensed to produce different floral appendages laterally at successive nodes instead of leaves. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["A is false but R is true.", "Both A and R are true and R is the correct explanation of A.", "Both A and R are true but R is NOT the correct explanation of A.", "A is true but R is false."],
        "correct_option_id": 1,
        "explanation": "The condensed internodes bearing floral appendages at successive nodes is precisely why a flower is considered a modified shoot.",
    },
    {
        "question": "Given below are two statements: Statement I: Gause's 'Competitive Exclusion Principle' states that two closely related species competing for the same resources cannot co-exist indefinitely and the competitively inferior one will be eliminated eventually. Statement II: In general, carnivores are more adversely affected by competition than herbivores. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I is incorrect but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is correct but Statement II is false."],
        "correct_option_id": 3,
        "explanation": "Gause's principle is correctly stated; however, herbivores/plants are generally considered less adversely affected by competition than carnivores, making Statement II false.",
    },
    {
        "question": "Which one of the following statements is NOT correct?",
        "options": ["The amount of some toxic substances of industrial waste water increases in the organisms at successive trophic levels.", "The micro-organisms involved in biodegradation of organic matter in a sewage polluted water body consume a lot of oxygen causing the death of aquatic organisms.", "Algal blooms caused by excess of organic matter in water improve water quality and promote fisheries.", "Water hyacinth grows abundantly in eutrophic water bodies and leads to an imbalance in the ecosystem dynamics of the water body."],
        "correct_option_id": 2,
        "explanation": "Algal blooms actually deteriorate water quality by depleting oxygen and harming aquatic life, not improving it.",
    },
    {
        "question": "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R. Assertion A: Amniocentesis for sex determination is one of the strategies of Reproductive and Child Health Care Programme. Reason R: Ban on amniocentesis checks increasing menace of female foeticide. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["A is false but R is true.", "Both A and R are true and R is the correct explanation of A.", "Both A and R are true and R is NOT the correct explanation of A.", "A is true but R is false."],
        "correct_option_id": 0,
        "explanation": "Amniocentesis for sex determination is legally banned (not a health-care strategy) precisely to prevent female foeticide, making R true and A false.",
    },
    {
        "question": "Vital capacity of lung is ________.",
        "options": ["IRV + ERV + TV", "IRV + ERV", "IRV + ERV + TV + RV", "IRV + ERV + TV - RV"],
        "correct_option_id": 0,
        "explanation": "Vital capacity is the sum of Inspiratory Reserve Volume, Expiratory Reserve Volume, and Tidal Volume.",
    },
    {
        "question": "Given below are two statements: Statement I: A protein is imagined as a line, the left end represented by first amino acid (C-terminal) and the right end represented by last amino acid (N-terminal). Statement II: Adult human haemoglobin consists of 4 subunits (two subunits of alpha type and two subunits of beta type.) In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I is false but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is true but Statement II is false."],
        "correct_option_id": 0,
        "explanation": "The left end of a protein is actually the N-terminal and right end the C-terminal (Statement I is reversed/false); haemoglobin's 2α+2β subunit composition (Statement II) is correct.",
    },
    {
        "question": "Which of the following functions is carried out by cytoskeleton in a cell?",
        "options": ["Transportation", "Nuclear division", "Protein synthesis", "Motility"],
        "correct_option_id": 3,
        "explanation": "The cytoskeleton network of protein filaments is chiefly responsible for cell shape maintenance and cell motility.",
    },
    {
        "question": "Select the correct group/set of Australian Marsupials exhibiting adaptive radiation.",
        "options": ["Lemur, Anteater, Wolf", "Tasmanian wolf, Bobcat, Marsupial mole", "Numbat, Spotted cuscus, Flying phalanger", "Mole, Flying squirrel, Tasmanian tiger cat"],
        "correct_option_id": 2,
        "explanation": "Numbat, Spotted cuscus and Flying phalanger are all Australian marsupials representing adaptive radiation from a common ancestral stock.",
    },
    {
        "question": "Given below are two statements: Statement I: RNA mutates at a faster rate. Statement II: Viruses having RNA genome and shorter life span mutate and evolve faster. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I false but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is true but Statement II is false."],
        "correct_option_id": 1,
        "explanation": "RNA is inherently less stable and mutates faster, and RNA viruses with short life spans accordingly evolve rapidly.",
    },
    {
        "question": "Once the undigested and unabsorbed substances enter the caecum, their backflow is prevented by-",
        "options": ["Pyloric sphincter", "Sphincter of Oddi", "Ileo-caecal valve", "Gastro-oesophageal sphincter"],
        "correct_option_id": 2,
        "explanation": "The ileo-caecal valve prevents backflow of contents from the caecum into the ileum.",
    },
    {
        "question": "Which one of the following techniques does not serve the purpose of early diagnosis of a disease for its early treatment?",
        "options": ["Enzyme Linked Immuno-Sorbent Assay (ELISA) technique", "Recombinant DNA Technology", "Serum and Urine analysis", "Polymerase Chain Reaction (PCR) technique"],
        "correct_option_id": 1,
        "explanation": "Recombinant DNA Technology is primarily used for production of biomolecules/therapeutics rather than for early disease diagnosis.",
    },
    {
        "question": "Given below are statements: one is labelled as Assertion A and the other is labelled as Reason R. Assertion A: Nephrons are of two types: Cortical & Juxta medullary, based on their relative position in cortex and medulla. Reason R: Juxta medullary nephrons have short loop of Henle whereas, cortical nephrons have longer loop of Henle. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["A is false but R is true.", "Both A and R are true and R is the correct explanation of A.", "Both A and R are true but R is NOT the correct explanation of A.", "A is true but R is false."],
        "correct_option_id": 3,
        "explanation": "Nephrons are indeed classified by position (A is true), but it is actually juxtamedullary nephrons that have the longer loop of Henle, not shorter, making R false.",
    },
    {
        "question": "Which one of the following common sexually transmitted diseases is completely curable when detected early and treated properly?",
        "options": ["HIV Infection", "Genital herpes", "Gonorrhoea", "Hepatitis-B"],
        "correct_option_id": 2,
        "explanation": "Gonorrhoea, being a bacterial infection, is completely curable with early and proper antibiotic treatment.",
    },
    {
        "question": "Which of the following statements are correct regarding female reproductive cycle? (NEET 2023) A. In non-primate mammals cyclical changes during reproduction are called oestrus cycle. B. First menstrual cycle begins at puberty and is called menopause. C. Lack of menstruation may be indicative of pregnancy. D. Cyclic menstruation extends between menarche and menopause. Choose the most appropriate answer from the options given below:",
        "options": ["A, C and D only", "A and D only", "A and B only", "A, B and C only"],
        "correct_option_id": 0,
        "explanation": "Non-primate cyclical reproductive changes are termed oestrus cycle, absent menstruation can indicate pregnancy, and cyclic menstruation spans menarche to menopause; the first cycle at puberty is called menarche, not menopause, making B false.",
    },
    {
        "question": "Given below are two statements: Statement I: Low temperature preserves the enzyme in a temporarily inactive state whereas high temperature destroys enzymatic activity because proteins are denatured by heat. Statement II: When the inhibitor closely resembles the substrate in its molecular structure and inhibits the activity of the enzyme, it is known as competitive inhibitor. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I is false but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is true but Statement II is false."],
        "correct_option_id": 1,
        "explanation": "Both descriptions of temperature effects on enzymes and the definition of competitive inhibition are accurate.",
    },
    {
        "question": "Given below are two statements: Statement I: Vas deferens receives a duct from seminal vesicle and opens into urethra as the ejaculatory duct. Statement II: The cavity of the cervix is called cervical canal which along with vagina forms birth canal. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I incorrect but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is correct but Statement II is false."],
        "correct_option_id": 1,
        "explanation": "Both anatomical descriptions of the vas deferens/ejaculatory duct and the cervical canal/birth canal are accurate.",
    },
    {
        "question": "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R. Assertion A: Endometrium is necessary for implantation of blastocyst. Reason R: In the absence of fertilization, the corpus luteum degenerates that causes disintegration of endometrium. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["A is false but R is true.", "Both A and R are true and R is the correct explanation of A.", "Both A and R are true but R is NOT the correct explanation of A.", "A is true but R is false."],
        "correct_option_id": 2,
        "explanation": "Both statements are factually true, but corpus luteum degeneration causing endometrial breakdown (menstruation) does not explain why endometrium is needed for implantation.",
    },
    {
        "question": "Which of the following is not a cloning vector?",
        "options": ["Probe", "BAC", "YAC", "pBR322"],
        "correct_option_id": 0,
        "explanation": "A probe is a labelled nucleic acid used for detection/hybridization, not a vector used to carry and clone DNA.",
    },
    {
        "question": "In which blood corpuscles, the HIV undergoes replication and produces progeny viruses?",
        "options": ["Eosinophils", "TH cells", "B-lymphocytes", "Basophils"],
        "correct_option_id": 1,
        "explanation": "HIV specifically infects and replicates within helper T-lymphocytes (TH cells), depleting them and impairing immunity.",
    },
    {
        "question": "Broad palm with single palm crease is visible in a person suffering from-",
        "options": ["Thalassemia", "Down's syndrome", "Turner's syndrome", "Klinefelter's syndrome"],
        "correct_option_id": 1,
        "explanation": "A single palmar (simian) crease with a broad palm is a characteristic physical feature of Down's syndrome.",
    },
    {
        "question": "Given below are two statements: Statement I: Ligaments are dense irregular tissue. Statement II: Cartilage is dense regular tissue. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I is false but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is true but Statement II is false."],
        "correct_option_id": 3,
        "explanation": "Ligaments are indeed dense irregular connective tissue, but cartilage is a distinct specialized connective tissue, not dense regular tissue.",
    },
    {
        "question": "Radial symmetry is NOT found in adults of phylum ________.",
        "options": ["Echinodermata", "Ctenophora", "Hemichordata", "Coelenterata"],
        "correct_option_id": 2,
        "explanation": "Hemichordates exhibit bilateral symmetry as adults, unlike Echinodermata, Ctenophora and Coelenterata which show radial (or biradial) symmetry.",
    },
    {
        "question": "Given below are two statements: Statement I: Electrostatic precipitator is most widely used in thermal power plant. Statement II: Electrostatic precipitator in thermal power plant removes ionising radiations. In the light of the above statements, choose the most appropriate answer from the options given below:",
        "options": ["Statement I incorrect but Statement II is correct.", "Both Statement I and Statement II are correct.", "Both Statement I and Statement II are incorrect.", "Statement I is correct but Statement II is incorrect."],
        "correct_option_id": 3,
        "explanation": "Electrostatic precipitators are indeed widely used in thermal power plants, but they remove particulate matter (SPM), not ionising radiations.",
    },
    {
        "question": "Given below are two statements: Statement I: In prokaryotes, the positively charged DNA is held with some negatively charged proteins in a region called nucleoid. Statement II: In eukaryotes, the negatively charged DNA is wrapped around the positively charged histone octamer to form nucleosome. In the light of the above statements, choose the correct answer from the options given below:",
        "options": ["Statement I incorrect but Statement II is true.", "Both Statement I and Statement II are true.", "Both Statement I and Statement II are false.", "Statement I is correct but Statement II is false."],
        "correct_option_id": 0,
        "explanation": "In prokaryotes it is the negatively charged DNA held by positively charged proteins (Statement I has the charges reversed and is false); the eukaryotic nucleosome description is accurate.",
    },
    {
        "question": "Which of the following statements is correct?",
        "options": ["Algal Bloom decreases fish mortality.", "Eutrophication refers to increase in domestic sewage and waste water in lakes.", "Biomagnification refers to increase in concentration of the toxicant at successive trophic levels.", "Presence of large amount of nutrients in water restricts 'Algal Bloom'."],
        "correct_option_id": 2,
        "explanation": "Biomagnification is correctly defined as the increasing concentration of a toxicant at each successive trophic level.",
    },
    {
        "question": "Which of the following are NOT considered as the part of endomembrane system? (NEET 2023) A. Mitochondria B. Endoplasmic Reticulum C. Chloroplasts D. Golgi complex E. Peroxisomes Choose the most appropriate answer from the options given below:",
        "options": ["A, D and E only", "B and D only", "A, C and E only", "A and D only"],
        "correct_option_id": 2,
        "explanation": "Mitochondria, chloroplasts and peroxisomes are double/single-membrane organelles not functionally connected to the endomembrane system, unlike ER and Golgi complex.",
    },
    {
        "question": "Which one of the following is NOT an advantage of inbreeding?",
        "options": ["It decreases the productivity of inbred population, after continuous inbreeding.", "It decreases homozygosity.", "It exposes harmful recessive genes that are eliminated by selection.", "Elimination of less desirable genes and accumulation of superior genes takes place due to it."],
        "correct_option_id": 0,
        "explanation": "Reduced productivity after continuous inbreeding is a disadvantage (inbreeding depression), not an advantage of inbreeding.",
    },
    {
        "question": "In cockroach, excretion is brought about by- (NEET 2023) A. Phallic gland B. Urecose gland C. Nephrocytes D. Fat body E. Collaterial glands Choose the correct answer from the options given below:",
        "options": ["B and D only", "A and E only", "A, B and E only", "B, C and D only"],
        "correct_option_id": 3,
        "explanation": "Urecose glands, nephrocytes and fat body all participate in storage and elimination of nitrogenous wastes in cockroaches; phallic and collaterial glands are reproductive accessory structures.",
    },
    {
        "question": "Which one of the following is the sequence on corresponding coding strand, if the sequence on mRNA formed is as follows: 5' AUCGAUCGAUCGAUCGAUCGAUCGAUCG 3'?",
        "options": ["3' ATCGATCGATCGATCGATCGATCGATCG 5'", "5' UAGCUAGCUAGCUAGCUAGCUAGCUAGC 3'", "3' UAGCUAGCUAGCUAGCUAGCUAGCUAGC 5'", "5' ATCGATCGATCGATCGATCGATCGATCG 3'"],
        "correct_option_id": 3,
        "explanation": "The coding (sense) strand has the same sequence as the mRNA (with T replacing U) and runs in the same 5'→3' direction.",
    },
    {
        "question": "Given below are two statements: Statement I: During G0 phase of cell cycle, the cell is metabolically inactive. Statement II: The centrosome undergoes duplication during S phase of interphase. In the light of the above statements, choose the most appropriate answer from the options given below:",
        "options": ["Statement I is incorrect but Statement II is correct.", "Both Statement I and Statement II are correct.", "Both Statement I and Statement II are incorrect.", "Statement I is correct but Statement II is incorrect."],
        "correct_option_id": 0,
        "explanation": "Cells in G0 are quiescent but remain metabolically active (Statement I is false); centrosome duplication occurring in S phase is correct.",
    },
    {
        "question": "Which of the following statements are correct? (NEET 2023) A. Basophils are most abundant cells of the total WBCs. B. Basophils secrete histamine, serotonin and heparin. C. Basophils are involved in inflammatory response. D. Basophils have kidney shaped nucleus. E. Basophils are agranulocytes. Choose the correct answer from the options given below:",
        "options": ["A and B only", "D and E only", "C and E only", "B and C only"],
        "correct_option_id": 3,
        "explanation": "Basophils secrete histamine, serotonin and heparin (B) and are involved in inflammatory responses (C); they are not the most abundant WBC, do not have a kidney-shaped nucleus, and are granulocytes.",
    },
    {
        "question": "Which of the following statements are correct? (NEET 2023) A. An excessive loss of body fluid from the body switches off osmoreceptors. B. ADH facilitates water reabsorption to prevent diuresis. C. ANF causes vasodilation. D. ADH causes increase in blood pressure. E. ADH is responsible for decrease in GFR. Choose the correct answer from the options given below:",
        "options": ["C, D and E only", "A and B only", "B, C and D only", "A, B and E only"],
        "correct_option_id": 2,
        "explanation": "ADH promotes water reabsorption (B), raises blood pressure via vasoconstriction (D), and ANF causes vasodilation (C); excessive fluid loss actually activates (not switches off) osmoreceptors.",
    },
    {
        "question": "Select the correct statements with reference to chordates. (NEET 2023) A. Presence of a mid-dorsal, solid and double nerve cord. B. Presence of closed circulatory system. C. Presence of paired pharyngeal gill slits. D. Presence of dorsal heart. E. Triploblastic pseudocoelomate animals. Choose the correct answer from the options given below:",
        "options": ["C, D and E only", "A, C and D only", "B and C only", "B, D and E only"],
        "correct_option_id": 2,
        "explanation": "Chordates have a closed circulatory system and paired pharyngeal gill slits; the nerve cord is hollow (not solid), the heart is ventral (not dorsal), and chordates are coelomate (not pseudocoelomate).",
    },
    {
        "question": "Select the correct statements. (NEET 2023) A. Tetrad formation is seen during Leptotene. B. During Anaphase, the centromeres split and chromatids separate. C. Terminalization takes place during Pachytene. D. Nucleolus, Golgi complex and ER are reformed during Telophase. E. Crossing over takes place between sister chromatids of homologous chromosome. Choose the correct answer from the options given below:",
        "options": ["B and E only", "A and C only", "B and D only", "A, C and E only"],
        "correct_option_id": 2,
        "explanation": "Centromere splitting during anaphase and reformation of nucleolus/Golgi/ER during telophase are correct; tetrad formation occurs at zygotene, terminalization at diplotene, and crossing over occurs between non-sister chromatids.",
    },
    {
        "question": "The parts of human brain that helps in regulation of sexual behaviour, expression of excitement, pleasure, rage, fear etc. are:",
        "options": ["Corpus callosum and thalamus", "Limbic system & hypothalamus", "Corpora quadrigemina & hippocampus", "Brain stem & epithalamus"],
        "correct_option_id": 1,
        "explanation": "The limbic system, along with the hypothalamus, regulates sexual behaviour and emotional expressions such as excitement, pleasure, rage and fear.",
    },
    {
        "question": "The unique mammalian characteristics are:",
        "options": ["pinna, monocondylic skull and mammary glands", "hairs, tympanic membrane and mammary glands", "hairs, pinna and mammary glands", "hairs, pinna and indirect development"],
        "correct_option_id": 2,
        "explanation": "Hair, external ear (pinna) and mammary glands are unique defining features exclusive to mammals.",
    },
    {
        "question": "Which of the following is characteristic feature of cockroach regarding sexual dimorphism?",
        "options": ["Presence of anal cerci", "Dark brown body colour and anal cerci", "Presence of anal styles", "Presence of sclerites"],
        "correct_option_id": 2,
        "explanation": "Anal styles are present only in male cockroaches, making them a distinguishing feature of sexual dimorphism.",
    },
    {
        "question": "Which of the following statements are correct regarding skeletal muscle? (NEET 2023) A. Muscle bundles are held together by collagenous connective tissue layer called fascicle. B. Sarcoplasmic reticulum of muscle fibre is a store house of calcium ions. C. Striated appearance of skeletal muscle fibre is due to distribution pattern of actin and myosin proteins. D. M line is considered as functional unit of contraction called sarcomere. Choose the most appropriate answer from the options given below:",
        "options": ["C and D only", "A, B and C only", "B and C only", "A, C and D only"],
        "correct_option_id": 2,
        "explanation": "The sarcoplasmic reticulum stores calcium ions and the striated appearance results from the arrangement of actin and myosin; the sarcomere (functional contractile unit) lies between Z lines, not at the M line.",
    },
    {
        "question": "Which of the following are NOT under the control of thyroid hormone? (NEET 2023) A. Maintenance of water and electrolyte balance B. Regulation of basal metabolic rate C. Normal rhythm of sleep-wake cycle D. Development of immune system E. Support the process of R.B.Cs formation Choose the correct answer from the options given below:",
        "options": ["D and E only", "A and D only", "B and C only", "C and D only"],
        "correct_option_id": 3,
        "explanation": "Sleep-wake cycle is regulated by melatonin from the pineal gland and immune system development is linked to the thymus, not thyroid hormone; thyroid hormones do regulate BMR, water/electrolyte balance, and support RBC formation.",
    },
]
