"""
Question bank: NEET 2021 (Code P3) - Biology (Solved Answers).

83 questions parsed from NEET 2021 (Code P3)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Which of the following statements is not correct?",
        "options": ["Pyramid of numbers in a grassland ecosystem is upright.", "Pyramid of biomass in sea is generally inverted.", "Pyramid of biomass in sea is generally upright.", "Pyramid of energy is always upright."],
        "correct_option_id": 2,
        "explanation": "Biomass pyramids in sea/aquatic ecosystems are generally inverted (small fish-biomass producers, large consumer biomass), so statement 3 is the incorrect one.",
    },
    {
        "question": "Which of the following plants is monoecious?",
        "options": ["Cycas circinalis", "Carica papaya", "Chara", "Marchantia polymorpha"],
        "correct_option_id": 2,
        "explanation": "Chara bears both male (antheridium) and female (oogonium) reproductive structures on the same plant, making it monoecious.",
    },
    {
        "question": "The first stable product of CO2 fixation in sorghum is:",
        "options": ["Phosphoglyceric acid", "Pyruvic acid", "Oxaloacetic acid", "Succinic acid"],
        "correct_option_id": 2,
        "explanation": "Sorghum is a C4 plant; CO2 is first fixed by PEP carboxylase to form the 4-carbon compound oxaloacetic acid (OAA).",
    },
    {
        "question": "Diadelphous stamens are found in:",
        "options": ["China rose and citrus", "China rose", "Citrus", "Pea"],
        "correct_option_id": 3,
        "explanation": "In pea (Fabaceae), stamens are diadelphous (9+1) - nine fused and one free stamen.",
    },
    {
        "question": "DNA strands on a gel stained with ethidium bromide, when viewed under UV radiation, appear as:",
        "options": ["Bright blue bands", "Yellow bands", "Bright orange bands", "Dark red bands"],
        "correct_option_id": 2,
        "explanation": "Ethidium bromide intercalates into DNA and fluoresces bright orange under UV light, allowing visualization of DNA bands.",
    },
    {
        "question": "Plants follow different pathways in response to environment or phases of life to form different kinds of structures. This ability is called:",
        "options": ["Maturity", "Elasticity", "Flexibility", "Plasticity"],
        "correct_option_id": 3,
        "explanation": "The ability of plants to follow different developmental pathways in response to environment/phase of life is called plasticity.",
    },
    {
        "question": "In the equation GPP - R = NPP, R represents:",
        "options": ["Respiration losses", "Radiant energy", "Retardation factor", "Environment factor"],
        "correct_option_id": 0,
        "explanation": "Net Primary Productivity (NPP) is Gross Primary Productivity (GPP) minus respiratory losses (R).",
    },
    {
        "question": "The production of gametes by the parents, formation of zygotes, the F1 and F2 plants, can be understood from a diagram called:",
        "options": ["Net square", "Bullet square", "Punch square", "Punnett square"],
        "correct_option_id": 3,
        "explanation": "A Punnett square is used to represent gamete formation and predict genotypes/phenotypes of F1 and F2 generations.",
    },
    {
        "question": "Which of the following is an incorrect statement?",
        "options": ["Nuclear pores act as passages for proteins and RNA molecules in both directions between nucleus and cytoplasm.", "Mature sieve tube elements possess a conspicuous nucleus and usual cytoplasmic organelles.", "Microbodies are present both in plant and animal cells.", "The perinuclear space forms a barrier between the materials present inside the nucleus and that of the cytoplasm."],
        "correct_option_id": 1,
        "explanation": "Mature sieve tube elements lose their nucleus at maturity, so they do NOT possess a conspicuous nucleus, making statement 2 incorrect.",
    },
    {
        "question": "The amount of nutrients, such as carbon, nitrogen, phosphorus and calcium present in the soil at any given time, is referred to as:",
        "options": ["Standing crop", "Climax", "Climax community", "Standing state"],
        "correct_option_id": 3,
        "explanation": "The pool of available nutrients present in the soil at any given time is called the standing state.",
    },
    {
        "question": "The term used for transfer of pollen grains from anthers of one plant to stigma of a different plant which, during pollination, brings genetically different types of pollen grains to stigma, is:",
        "options": ["Cleistogamy", "Xenogamy", "Geitonogamy", "Chasmogamy"],
        "correct_option_id": 1,
        "explanation": "Xenogamy involves transfer of pollen from one plant to the stigma of a genetically different plant, introducing new genetic variation.",
    },
    {
        "question": "Which of the following stages of meiosis involves division of centromere?",
        "options": ["Telophase II", "Metaphase I", "Metaphase II", "Anaphase II"],
        "correct_option_id": 3,
        "explanation": "The centromere splits and sister chromatids separate during Anaphase II of meiosis.",
    },
    {
        "question": "Which of the following is a correct sequence of steps in a PCR (Polymerase Chain Reaction)?",
        "options": ["Annealing, Denaturation, Extension", "Denaturation, Annealing, Extension", "Denaturation, Extension, Annealing", "Extension, Denaturation, Annealing"],
        "correct_option_id": 1,
        "explanation": "PCR proceeds in the order: Denaturation (strand separation), Annealing (primer binding), and Extension (DNA synthesis).",
    },
    {
        "question": "When gene targeting involving gene amplification is attempted in an individual's tissue to treat disease, it is known as:",
        "options": ["Safety testing", "Biopiracy", "Gene therapy", "Molecular diagnosis"],
        "correct_option_id": 2,
        "explanation": "Correcting a gene defect in an individual's tissue by gene delivery/amplification to treat disease is called gene therapy.",
    },
    {
        "question": "The factor that leads to Founder effect in a population is:",
        "options": ["Genetic drift", "Natural selection", "Genetic recombination", "Mutation"],
        "correct_option_id": 0,
        "explanation": "The Founder effect is a special case of genetic drift, occurring when a small group establishes a new population with reduced genetic variability.",
    },
    {
        "question": "When the centromere is situated in the middle of two equal arms of chromosomes, the chromosome is referred to as:",
        "options": ["Acrocentric", "Metacentric", "Telocentric", "Sub-metacentric"],
        "correct_option_id": 1,
        "explanation": "A chromosome with the centromere in the middle, giving two equal arms, is called metacentric.",
    },
    {
        "question": "Gemmae are present in:",
        "options": ["Some Liverworts", "Mosses", "Pteridophytes", "Some Gymnosperms"],
        "correct_option_id": 0,
        "explanation": "Gemmae are green, multicellular, asexual reproductive structures found in the gemma cups of some liverworts (e.g., Marchantia).",
    },
    {
        "question": "During the purification process for recombinant DNA technology, addition of chilled ethanol precipitates out:",
        "options": ["Polysaccharides", "RNA", "DNA", "Histones"],
        "correct_option_id": 2,
        "explanation": "Chilled ethanol is used to precipitate out purified DNA from the aqueous solution after other cellular components are removed.",
    },
    {
        "question": "The site of perception of light in plants during photoperiodism is:",
        "options": ["Leaf", "Shoot apex", "Stem", "Axillary bud"],
        "correct_option_id": 0,
        "explanation": "The leaf is the site where light/dark duration is perceived during photoperiodism, triggering flowering hormone signals.",
    },
    {
        "question": "The plant hormone used to destroy weeds in a field is:",
        "options": ["IBA", "IAA", "NAA", "2, 4-D"],
        "correct_option_id": 3,
        "explanation": "2,4-D is a synthetic auxin widely used as a selective herbicide to kill dicot weeds without affecting monocot crops.",
    },
    {
        "question": "Which of the following algae produce Carrageen?",
        "options": ["Blue-green algae", "Green algae", "Brown algae", "Red algae"],
        "correct_option_id": 3,
        "explanation": "Carrageenan is a cell-wall polysaccharide extracted from red algae, used commercially as a gelling/thickening agent.",
    },
    {
        "question": "Complete the flow chart on central dogma: DNA -(a)-> DNA -(b)-> mRNA -(c)-> (d)",
        "options": ["(a)-Transduction; (b)-Translation; (c)-Replication; (d)-Protein", "(a)-Replication; (b)-Transduction; (c)-Transcription; (d)-Protein", "(a)-Translation; (b)-Replication; (c)-Transcription; (d)-Transduction", "(a)-Replication; (b)-Transcription; (c)-Translation; (d)-Protein"],
        "correct_option_id": 3,
        "explanation": "The central dogma flows: DNA replicates (Replication) to give more DNA, DNA is transcribed (Transcription) into mRNA, and mRNA is translated (Translation) into Protein.",
    },
    {
        "question": "Which of the following are not secondary metabolites in plants?",
        "options": ["Rubber, gums", "Morphine, codeine", "Amino acids, glucose", "Vinblastin, curcumin"],
        "correct_option_id": 2,
        "explanation": "Amino acids and glucose are primary metabolites essential for basic metabolic processes, unlike rubber, morphine, or vinblastin which are secondary metabolites.",
    },
    {
        "question": "Inspite of interspecific competition in nature, which mechanism the competing species might have evolved for their survival?",
        "options": ["Predation", "Resource partitioning", "Competitive release", "Mutualism"],
        "correct_option_id": 1,
        "explanation": "Competing species can coexist by resource partitioning - dividing the resource (e.g., different foraging times/areas) to reduce direct competition.",
    },
    {
        "question": "Which of the following is not an application of PCR (Polymerase Chain Reaction)?",
        "options": ["Detection of gene mutation", "Molecular diagnosis", "Gene amplification", "Purification of isolated protein"],
        "correct_option_id": 3,
        "explanation": "PCR amplifies DNA/genes; it has no role in protein purification, which is done by techniques like chromatography and electrophoresis.",
    },
    {
        "question": "A typical angiosperm embryo sac at maturity is:",
        "options": ["8-nucleate and 8-celled", "8-nucleate and 7-celled", "7-nucleate and 8-celled", "7-nucleate and 7-celled"],
        "correct_option_id": 1,
        "explanation": "The mature (Polygonum-type) embryo sac has 8 nuclei but only 7 cells, since the central cell contains 2 polar nuclei within a single cell.",
    },
    {
        "question": "Which of the following algae contains mannitol as reserve food material?",
        "options": ["Ulothrix", "Ectocarpus", "Gracilaria", "Volvox"],
        "correct_option_id": 1,
        "explanation": "Brown algae such as Ectocarpus store food in the form of complex carbohydrates like laminarin and mannitol.",
    },
    {
        "question": "Genera like Selaginella and Salvinia produce two kinds of spores. Such plants are known as:",
        "options": ["Heterosporous", "Homosorus", "Heterosorus", "Homosporous"],
        "correct_option_id": 0,
        "explanation": "Plants producing two different types (micro and mega) of spores, such as Selaginella and Salvinia, are called heterosporous.",
    },
    {
        "question": "Mutations in plant cells can be induced by:",
        "options": ["Zeatin", "Kinetin", "Infrared rays", "Gamma rays"],
        "correct_option_id": 3,
        "explanation": "Gamma rays are a form of ionizing radiation that can damage DNA and induce mutations, and are used in mutation breeding.",
    },
    {
        "question": "Amensalism can be represented as:",
        "options": ["Species A (+); Species B (0)", "Species A (-); Species B (0)", "Species A (+); Species B (+)", "Species A (-); Species B (-)"],
        "correct_option_id": 1,
        "explanation": "In amensalism, one species (A) is harmed while the other (B) is unaffected, represented as A(-); B(0).",
    },
    {
        "question": "What is the role of RNA polymerase III in the process of transcription in eukaryotes?",
        "options": ["Transcribes only snRNAs", "Transcribes rRNAs (28S, 18S and 5.8S)", "Transcribes tRNA, 5s rRNA and snRNA", "Transcribes precursor of mRNA"],
        "correct_option_id": 2,
        "explanation": "RNA polymerase III transcribes small RNAs such as tRNA, 5S rRNA, and snRNAs in eukaryotic cells.",
    },
    {
        "question": "Which of the following describes the correct pairing?",
        "options": ["Loose parenchyma cells rupturing the epidermis and forming a lens-shaped opening in bark - Spongy parenchyma", "Large colorless empty cells in the epidermis of grass leaves - Subsidiary cells", "In dicot leaves, vascular bundles are surrounded by large thick-walled cells - Conjunctive tissue", "Cells of medullary rays that form part of cambial ring - Interfascicular cambium"],
        "correct_option_id": 3,
        "explanation": "Medullary ray cells that become meristematic and join the vascular cambium to form a continuous ring are known as interfascicular cambium.",
    },
    {
        "question": "Plasmid pBR322 has PstI restriction enzyme site within gene ampR that confers ampicillin resistance. If this enzyme is used for inserting a gene for beta-galactosidase production and the recombinant plasmid is inserted in an E.coli strain:",
        "options": ["it will be able to produce a novel protein with dual ability.", "it will not be able to confer ampicillin resistance to the host cell.", "the transformed cells will have the ability to resist ampicillin as well as produce beta-galactoside.", "it will lead to lysis of host cell."],
        "correct_option_id": 1,
        "explanation": "Inserting foreign DNA at the PstI site within the ampR gene causes insertional inactivation, so the recombinant plasmid loses its ability to confer ampicillin resistance.",
    },
    {
        "question": "DNA fingerprinting involves identifying differences in some specific regions in DNA sequence, called as:",
        "options": ["Polymorphic DNA", "Satellite DNA", "Repetitive DNA", "Single nucleotides"],
        "correct_option_id": 2,
        "explanation": "DNA fingerprinting relies on variable-number repeat sequences (repetitive DNA) that differ between individuals.",
    },
    {
        "question": "In the exponential growth equation Nt = N0.e^rt, e represents:",
        "options": ["The base of geometric logarithms", "The base of number logarithms", "The base of exponential logarithms", "The base of natural logarithms"],
        "correct_option_id": 3,
        "explanation": "In the exponential growth equation, 'e' is the base of natural logarithms (approximately 2.71828).",
    },
    {
        "question": "Which of the following statements is incorrect?",
        "options": ["Cyclic photophosphorylation involves both PS I and PS II.", "Both ATP and NADPH + H+ are synthesized during non-cyclic photophosphorylation.", "Stroma lamellae have PS I only and lack NADP reductase.", "Grana lamellae have both PS I and PS II."],
        "correct_option_id": 0,
        "explanation": "Cyclic photophosphorylation involves only PS I, not both photosystems, making this statement incorrect.",
    },
    {
        "question": "Which of the following statements is correct?",
        "options": ["Some of the organisms can fix atmospheric nitrogen in specialized cells called sheath cells.", "Fusion of two cells is called Karyogamy.", "Fusion of protoplasms between two motile or non-motile gametes is called plasmogamy.", "Organisms that depend on living plants are called saprophytes."],
        "correct_option_id": 2,
        "explanation": "Plasmogamy is defined as the fusion of the protoplasm of two gametes (motile or non-motile), which is a correct statement.",
    },
    {
        "question": "Which of the following statements is incorrect?",
        "options": ["Oxidation-reduction reactions produce proton gradient in respiration.", "During aerobic respiration, role of oxygen is limited to the terminal stage.", "In ETC (Electron Transport Chain), one molecule of NADH + H+ gives rise to 2 ATP molecules, and one FADH2 gives rise to 3 ATP molecules.", "ATP is synthesized through complex V."],
        "correct_option_id": 2,
        "explanation": "The values are reversed; NADH+H+ typically yields about 3 ATP and FADH2 yields about 2 ATP, making statement 3 incorrect.",
    },
    {
        "question": "In some members of which of the following pairs of families, pollen grains retain their viability for months after release?",
        "options": ["Rosaceae; Leguminosae", "Poaceae; Rosaceae", "Poaceae; Leguminosae", "Poaceae; Solanaceae"],
        "correct_option_id": 2,
        "explanation": "In some members of Poaceae and Leguminosae, pollen grains can retain viability for months, unlike most angiosperms where it lasts only hours to days.",
    },
    {
        "question": "Identify the correct statement.",
        "options": ["Split gene arrangement is characteristic of prokaryotes.", "In capping, methyl guanosine triphosphate is added to the 3' end of hnRNA.", "RNA polymerase binds with Rho factor to terminate the process of transcription in bacteria.", "The coding strand in a transcription unit is copied to an mRNA."],
        "correct_option_id": 2,
        "explanation": "In bacteria, the Rho factor binds to RNA polymerase to help terminate transcription at Rho-dependent terminators, making this statement correct.",
    },
    {
        "question": "Now a days it is possible to detect the mutated gene causing cancer by allowing radioactive probe to hybridise its complementary DNA in a clone of cells, followed by its detection using autoradiography because:",
        "options": ["mutated gene does not appear on photographic film as the probe has complementarity with it.", "mutated gene partially appears on a photographic film.", "mutated gene completely and clearly appears on a photographic film.", "mutated gene does not appear on a photographic film as the probe has no complementarity with it."],
        "correct_option_id": 3,
        "explanation": "Since the radioactive probe is complementary to the normal gene, it cannot hybridize with the mutated gene sequence, so no signal (no dark spot) appears on the film where the mutated gene is located.",
    },
    {
        "question": "Erythropoietin hormone which stimulates R.B.C. formation is produced by:",
        "options": ["Juxtaglomerular cells of the kidney", "Alpha cells of pancreas", "The cells of rostral adenohypophysis", "The cells of bone marrow"],
        "correct_option_id": 0,
        "explanation": "Erythropoietin, which stimulates RBC formation (erythropoiesis), is produced mainly by juxtaglomerular-associated cells of the kidney.",
    },
    {
        "question": "Which of the following characteristics is incorrect with respect to cockroach?",
        "options": ["10th abdominal segment in both sexes, bears a pair of anal cerci.", "A ring of gastric caeca is present at the junction of midgut and hind gut.", "Hypopharynx lies within the cavity enclosed by the mouth parts.", "In females, 7th-9th sterna together form a genital pouch."],
        "correct_option_id": 1,
        "explanation": "Gastric caeca in cockroaches are located at the junction of the foregut and midgut, not the midgut and hindgut, making statement 2 incorrect.",
    },
    {
        "question": "Succus entericus is referred to as:",
        "options": ["Chyme", "Pancreatic juice", "Intestinal juice", "Gastric juice"],
        "correct_option_id": 2,
        "explanation": "Succus entericus is the Latin term for intestinal juice, secreted by glands in the small intestine.",
    },
    {
        "question": "Which stage of meiotic prophase shows terminalisation of chiasmata as its distinctive feature?",
        "options": ["Pachytene", "Leptotene", "Zygotene", "Diakinesis"],
        "correct_option_id": 3,
        "explanation": "Diakinesis is characterized by terminalisation of chiasmata, chromosome condensation, and disappearance of the nucleolus and nuclear envelope.",
    },
    {
        "question": "The partial pressures (in mm Hg) of oxygen (O2) and carbon dioxide (CO2) at alveoli (the site of diffusion) are:",
        "options": ["pO2 = 159 and pCO2 = 0.3", "pO2 = 104 and pCO2 = 40", "pO2 = 40 and pCO2 = 45", "pO2 = 95 and pCO2 = 40"],
        "correct_option_id": 1,
        "explanation": "At the alveoli, the partial pressure of oxygen is about 104 mm Hg and that of carbon dioxide is about 40 mm Hg, favoring gas exchange.",
    },
    {
        "question": "During the process of gene amplification using PCR, if very high temperature is not maintained in the beginning, then which of the following steps of PCR will be affected first?",
        "options": ["Ligation", "Annealing", "Extension", "Denaturation"],
        "correct_option_id": 3,
        "explanation": "Denaturation is the first step, requiring high temperature (~94-96°C) to separate the double-stranded DNA; if not maintained, this step fails first.",
    },
    {
        "question": "Which of the following statements wrongly represents the nature of smooth muscle?",
        "options": ["These muscles are present in the wall of blood vessels.", "These muscles have no striations.", "They are involuntary muscles.", "Communication among the cells is performed by intercalated discs."],
        "correct_option_id": 3,
        "explanation": "Intercalated discs are a feature of cardiac muscle, not smooth muscle, making statement 4 incorrect.",
    },
    {
        "question": "Chronic auto immune disorder affecting neuromuscular junction leading to fatigue, weakening and paralysis of skeletal muscle is called as:",
        "options": ["Gout", "Arthritis", "Muscular dystrophy", "Myasthenia gravis"],
        "correct_option_id": 3,
        "explanation": "Myasthenia gravis is an autoimmune disorder affecting the neuromuscular junction, causing muscle weakness and fatigue.",
    },
    {
        "question": "Persons with 'AB' blood group are called as \"Universal recipients\". This is due to:",
        "options": ["Absence of antibodies, anti-A and anti-B, in plasma", "Absence of antigens A and B on the surface of RBCs", "Absence of antigens A and B in plasma", "Presence of antibodies, anti-A and anti-B, on RBCs"],
        "correct_option_id": 0,
        "explanation": "AB blood group individuals lack anti-A and anti-B antibodies in their plasma, so they can receive blood from any ABO group without agglutination.",
    },
    {
        "question": "The fruit fly has 8 chromosomes (2n) in each cell. During interphase of Mitosis if the number of chromosomes at G1 phase is 8, what would be the number of chromosomes after S phase?",
        "options": ["32", "8", "16", "4"],
        "correct_option_id": 1,
        "explanation": "During S phase, DNA content doubles but the chromosome number remains unchanged (8), as each chromosome now has two sister chromatids.",
    },
    {
        "question": "Receptors for sperm binding in mammals are present on:",
        "options": ["Zona pellucida", "Corona radiata", "Vitelline membrane", "Perivitelline space"],
        "correct_option_id": 0,
        "explanation": "The zona pellucida of the ovum contains species-specific receptors that bind to sperm to initiate fertilization.",
    },
    {
        "question": "Which one of the following belongs to the family Muscidae?",
        "options": ["House fly", "Fire fly", "Grasshopper", "Cockroach"],
        "correct_option_id": 0,
        "explanation": "The house fly belongs to the family Muscidae within the order Diptera.",
    },
    {
        "question": "Identify the incorrect pair.",
        "options": ["Drugs - Ricin", "Alkaloids - Codeine", "Toxin - Abrin", "Lectins - Concanavalin A"],
        "correct_option_id": 0,
        "explanation": "Ricin is a toxin (not a drug), so pairing \"Drugs - Ricin\" is incorrect.",
    },
    {
        "question": "Venereal diseases can spread through: (a) Using sterile needles (b) Transfusion of blood from infected person (c) Infected mother to foetus (d) Kissing (e) Inheritance",
        "options": ["(a) and (c) only", "(a), (b) and (c) only", "(b), (c) and (d) only", "(b) and (c) only"],
        "correct_option_id": 3,
        "explanation": "Venereal (sexually transmitted) diseases spread mainly through blood transfusion from an infected person and from infected mother to foetus, not through sterile needles, kissing, or inheritance.",
    },
    {
        "question": "The organelles that are included in the endomembrane system are:",
        "options": ["Golgi complex, Endoplasmic reticulum, Mitochondria and Lysosomes", "Endoplasmic reticulum, Mitochondria, Ribosomes and Lysosomes", "Endoplasmic reticulum, Golgi complex, Lysosomes and Vacuoles", "Golgi complex, Mitochondria, Ribosomes and Lysosomes"],
        "correct_option_id": 2,
        "explanation": "The endomembrane system comprises the endoplasmic reticulum, Golgi complex, lysosomes, and vacuoles, since mitochondria and ribosomes function independently.",
    },
    {
        "question": "For effective treatment of the disease, early diagnosis and understanding its pathophysiology is very important. Which of the following molecular diagnostic techniques is very useful for early detection?",
        "options": ["Hybridization Technique", "Western Blotting Technique", "Southern Blotting Technique", "ELISA Technique"],
        "correct_option_id": 3,
        "explanation": "ELISA (Enzyme-Linked Immunosorbent Assay) is widely used for early detection of diseases based on antigen-antibody interaction.",
    },
    {
        "question": "With regard to insulin choose correct options: (a) C-peptide is not present in mature insulin. (b) The insulin produced by rDNA technology has C-peptide. (c) The pro-insulin has C-peptide. (d) A-peptide and B-peptide of insulin are interconnected by disulphide bridges.",
        "options": ["(a) and (d) only", "(b) and (d) only", "(b) and (c) only", "(a), (c) and (d) only"],
        "correct_option_id": 3,
        "explanation": "Mature insulin lacks the C-peptide (removed during processing), pro-insulin contains it, and the A and B chains of mature insulin are joined by disulfide bridges - matching statements (a), (c), and (d).",
    },
    {
        "question": "A specific recognition sequence identified by endonucleases to make cuts at specific positions within the DNA is:",
        "options": ["Poly(A) tail sequences", "Degenerate primer sequence", "Okazaki sequences", "Palindromic Nucleotide sequences"],
        "correct_option_id": 3,
        "explanation": "Restriction endonucleases recognize specific palindromic nucleotide sequences and cut the DNA at those sites.",
    },
    {
        "question": "Which is the \"Only enzyme\" that has \"Capability\" to catalyse Initiation, Elongation and Termination of transcription in prokaryotes?",
        "options": ["DNase", "DNA dependent DNA polymerase", "DNA dependent RNA polymerase", "DNA Ligase"],
        "correct_option_id": 2,
        "explanation": "In prokaryotes, a single DNA-dependent RNA polymerase enzyme carries out all three stages of transcription: initiation, elongation, and termination.",
    },
    {
        "question": "Which one of the following organisms bears hollow and pneumatic long bones?",
        "options": ["Ornithorhynchus", "Neophron", "Hemidactylus", "Macropus"],
        "correct_option_id": 1,
        "explanation": "Neophron (a vulture, a bird) has hollow, pneumatic long bones, an adaptation for flight, unlike the mammal and reptile options.",
    },
    {
        "question": "Read the following statements: (a) Metagenesis is observed in Helminths. (b) Echinoderms are triploblastic and coelomate animals. (c) Round worms have organ-system level of body organization. (d) Comb plates present in ctenophores help in digestion. (e) Water vascular system is characteristic of Echinoderms.",
        "options": ["(b), (c) and (e) are correct", "(c), (d) and (e) are correct", "(a), (b) and (c) are correct", "(a), (d) and (e) are correct"],
        "correct_option_id": 0,
        "explanation": "Echinoderms are triploblastic coelomates with a water vascular system, and roundworms show organ-system level organization; metagenesis is not typical of helminths and comb plates aid locomotion, not digestion.",
    },
    {
        "question": "Sphincter of oddi is present at:",
        "options": ["Junction of jejunum and duodenum", "Ileo-caecal junction", "Junction of hepato-pancreatic duct and duodenum", "Gastro-oesophageal junction"],
        "correct_option_id": 2,
        "explanation": "The sphincter of Oddi controls the opening of the common hepato-pancreatic duct into the duodenum.",
    },
    {
        "question": "If Adenine makes 30% of the DNA molecule, what will be the percentage of Thymine, Guanine and Cytosine in it?",
        "options": ["T : 20; G : 25; C : 25", "T : 20; G : 30; C : 20", "T : 20; G : 20; C : 30", "T : 30; G : 20; C : 20"],
        "correct_option_id": 3,
        "explanation": "Since A = T (Chargaff's rule), T = 30%; the remaining 40% is shared equally between G and C, giving G = C = 20% each.",
    },
    {
        "question": "Which enzyme is responsible for the conversion of inactive fibrinogens to fibrins?",
        "options": ["Thrombokinase", "Thrombin", "Renin", "Epinephrine"],
        "correct_option_id": 1,
        "explanation": "Thrombin catalyzes the conversion of soluble fibrinogen into insoluble fibrin threads during blood clotting.",
    },
    {
        "question": "Which of the following is not an objective of Biofortification in crops?",
        "options": ["Improve micronutrient and mineral content", "Improve protein content", "Improve resistance to diseases", "Improve vitamin content"],
        "correct_option_id": 2,
        "explanation": "Biofortification aims to enhance nutritional value (vitamins, minerals, proteins) of crops; improving disease resistance is not its primary objective.",
    },
    {
        "question": "Dobson units are used to measure thickness of:",
        "options": ["Troposphere", "CFCs", "Stratosphere", "Ozone"],
        "correct_option_id": 3,
        "explanation": "Dobson units (DU) are used to express the thickness/concentration of the ozone layer in the atmosphere.",
    },
    {
        "question": "Which one of the following is an example of Hormone releasing IUD?",
        "options": ["Multiload 375", "CuT", "LNG 20", "Cu 7"],
        "correct_option_id": 2,
        "explanation": "LNG-20 (levonorgestrel-releasing IUD) is a hormone-releasing intrauterine device, unlike copper-based IUDs like CuT or Cu7.",
    },
    {
        "question": "The centriole undergoes duplication during:",
        "options": ["G2 phase", "S-phase", "Prophase", "Metaphase"],
        "correct_option_id": 1,
        "explanation": "Centriole duplication occurs during the S-phase of interphase, coinciding with DNA replication.",
    },
    {
        "question": "Which of the following RNAs is not required for the synthesis of protein?",
        "options": ["siRNA", "mRNA", "tRNA", "rRNA"],
        "correct_option_id": 0,
        "explanation": "siRNA (small interfering RNA) is involved in gene silencing/RNA interference, not directly in protein synthesis, unlike mRNA, tRNA, and rRNA.",
    },
    {
        "question": "In a cross between a male and female, both heterozygous for sickle cell anaemia gene, what percentage of the progeny will be diseased?",
        "options": ["100%", "50%", "75%", "25%"],
        "correct_option_id": 3,
        "explanation": "A cross between two heterozygous (HbA HbS) individuals follows a monohybrid ratio; 25% of the progeny will be homozygous recessive (HbS HbS) and diseased.",
    },
    {
        "question": "Select the favourable conditions required for the formation of oxyhaemoglobin at the alveoli.",
        "options": ["Low pO2, low pCO2, more H+, higher temperature", "High pO2, low pCO2, less H+, lower temperature", "Low pO2, high pCO2, more H+, higher temperature", "High pO2, high pCO2, less H+, higher temperature"],
        "correct_option_id": 1,
        "explanation": "Oxyhaemoglobin formation at the alveoli is favoured by high pO2, low pCO2, less H+ concentration, and lower temperature.",
    },
    {
        "question": "Which of these is not an important component of initiation of parturition in humans?",
        "options": ["Release of Prolactin", "Increase in estrogen and progesterone ratio", "Synthesis of prostaglandins", "Release of Oxytocin"],
        "correct_option_id": 0,
        "explanation": "Prolactin is involved in milk production (lactation) after birth, not in triggering the initiation of parturition, which involves oxytocin, prostaglandins, and the estrogen:progesterone ratio.",
    },
    {
        "question": "Which one of the following statements about Histones is wrong?",
        "options": ["Histones carry positive charge in the side chain.", "Histones are organized to form a unit of 8 molecules.", "The pH of histones is slightly acidic.", "Histones are rich in amino acids - Lysine and Arginine."],
        "correct_option_id": 2,
        "explanation": "Histones are basic (alkaline) proteins due to their high lysine and arginine content, so describing them as \"slightly acidic\" is incorrect.",
    },
    {
        "question": "During muscular contraction which of the following events occur? (a) 'H' zone disappears (b) 'A' band widens (c) 'I' band reduces in width (d) Myosine hydrolyzes ATP, releasing the ADP and Pi (e) Z-lines attached to actins are pulled inwards",
        "options": ["(b), (d), (e), (a) only", "(a), (c), (d), (e) only", "(a), (b), (c), (d) only", "(b), (c), (d), (e) only"],
        "correct_option_id": 1,
        "explanation": "During muscle contraction, the H-zone and I-band shorten/disappear, myosin hydrolyzes ATP releasing ADP and Pi, and the Z-lines are pulled inward - the A-band length itself does not change.",
    },
    {
        "question": "Assertion (A): A person goes to high altitude and experiences 'altitude sickness' with symptoms like breathing difficulty and heart palpitations. Reason (R): Due to low atmospheric pressure at high altitude, the body does not get sufficient oxygen.",
        "options": ["(A) is false but (R) is true", "Both (A) and (R) are true and (R) is the correct explanation of (A)", "Both (A) and (R) are true but (R) is not the correct explanation of (A)", "(A) is true but (R) is false"],
        "correct_option_id": 1,
        "explanation": "At high altitude, lower atmospheric pressure reduces available oxygen, correctly explaining the symptoms of altitude sickness described in the assertion.",
    },
    {
        "question": "The Adenosine deaminase deficiency results into:",
        "options": ["Addison's disease", "Dysfunction of Immune system", "Parkinson's disease", "Digestive disorder"],
        "correct_option_id": 1,
        "explanation": "Adenosine deaminase (ADA) deficiency causes Severe Combined Immunodeficiency (SCID), a dysfunction of the immune system.",
    },
    {
        "question": "Which of the following is not a step in Multiple Ovulation Embryo Transfer Technology (MOET)?",
        "options": ["Fertilized eggs are transferred to surrogate mothers at 8-32 cell stage", "Cow is administered hormone having LH like activity for super ovulation", "Cow yields about 6-8 eggs at a time", "Cow is fertilized by artificial insemination"],
        "correct_option_id": 1,
        "explanation": "Superovulation in MOET is induced using FSH-like hormones, not LH-like hormones, making statement 2 incorrect.",
    },
    {
        "question": "Following are the statements with reference to 'lipids': (a) Lipids having only single bonds are called unsaturated fatty acids. (b) Lecithin is a phospholipid. (c) Trihydroxy propane is glycerol. (d) Palmitic acid has 20 carbon atoms including carboxyl carbon. (e) Arachidonic acid has 16 carbon atoms.",
        "options": ["(b) and (e) only", "(a) and (b) only", "(c) and (d) only", "(b) and (c) only"],
        "correct_option_id": 3,
        "explanation": "Lecithin is a phospholipid and glycerol (trihydroxy propane) is correct; single-bonded fatty acids are actually saturated (not unsaturated), palmitic acid has 16 carbons, and arachidonic acid has 20 carbons.",
    },
    {
        "question": "Following are the statements about prostomium of earthworm: (a) It serves as a covering for mouth. (b) It helps to open cracks in the soil into which it can crawl. (c) It is one of the sensory structures. (d) It is the first body segment.",
        "options": ["(b) and (c) are correct", "(a), (b) and (c) are correct", "(a), (b) and (d) are correct", "(a), (b), (c) and (d) are correct"],
        "correct_option_id": 1,
        "explanation": "The prostomium covers the mouth, helps in burrowing by prying open soil cracks, and functions as a sensory lobe, but it is not considered a true body segment.",
    },
    {
        "question": "Which of the following secretes the hormone, relaxin, during the later phase of pregnancy?",
        "options": ["Uterus", "Graafian follicle", "Corpus luteum", "Foetus"],
        "correct_option_id": 2,
        "explanation": "Relaxin is secreted by the corpus luteum (and placenta) during late pregnancy, helping relax the pelvic ligaments and cervix for parturition.",
    },
    {
        "question": "Statement I: The codon 'AUG' codes for methionine and phenylalanine. Statement II: 'AAA' and 'AAG' both codons code for the amino acid lysine.",
        "options": ["Statement I is incorrect but Statement II is true", "Both Statement I and Statement II are true", "Both Statement I and Statement II are false", "Statement I is correct but Statement II is false"],
        "correct_option_id": 0,
        "explanation": "AUG codes only for methionine (also acting as the start codon), not phenylalanine, making Statement I incorrect; AAA and AAG both correctly code for lysine, making Statement II true.",
    },
    {
        "question": "Identify the types of cell junctions that help to stop the leakage of the substances across a tissue and facilitation of communication with neighbouring cells via rapid transfer of ions and molecules.",
        "options": ["Adhering junctions and Gap junctions, respectively.", "Gap junctions and Adhering junctions, respectively.", "Tight junctions and Gap junctions, respectively.", "Adhering junctions and Tight junctions, respectively."],
        "correct_option_id": 2,
        "explanation": "Tight junctions prevent leakage of substances across tissues by sealing adjacent cells, while gap junctions form channels allowing rapid transfer of ions and small molecules between cells.",
    },
]
