"""
Question bank: NEET 2022 (Code R5) - Biology (Solved Answers).

92 questions parsed from NEET 2022 (Code R5)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Which one of the following never occurs during mitotic cell division?",
        "options": ["Coiling and condensation of the chromatids", "Spindle fibres attach to kinetochores of chromosomes", "Movement of centrioles towards opposite poles", "Pairing of homologous chromosomes"],
        "correct_option_id": 3,
        "explanation": "Pairing of homologous chromosomes (synapsis) occurs only during prophase-I of meiosis, never in mitosis.",
    },
    {
        "question": "Which one of the following statements cannot be connected to Predation?",
        "options": ["It is necessitated by nature to maintain the ecological balance", "It helps in maintaining species diversity in a community", "It might lead to extinction of a species", "Both the interacting species are negatively impacted"],
        "correct_option_id": 3,
        "explanation": "In predation only the prey is harmed while the predator benefits (+ − interaction), so both species being negatively impacted is incorrect.",
    },
    {
        "question": "Which one of the following plants does not show plasticity?",
        "options": ["Maize", "Cotton", "Coriander", "Buttercup"],
        "correct_option_id": 0,
        "explanation": "Plasticity (heterophylly) is seen in cotton, coriander, larkspur and buttercup; maize does not show this phenomenon.",
    },
    {
        "question": "The flowers are Zygomorphic in: (a) Mustard (b) Gulmohar (c) Cassia (d) Datura (e) Chilly",
        "options": ["(c), (d), (e) Only", "(a), (b), (c) Only", "(b), (c) Only", "(d), (e) Only"],
        "correct_option_id": 2,
        "explanation": "Gulmohar and Cassia flowers are zygomorphic (divisible into two equal halves in only one plane); Mustard, Datura and Chilly are actinomorphic.",
    },
    {
        "question": "Which one of the following is not true regarding the release of energy during ATP synthesis through chemiosmosis? It involves:",
        "options": ["Reduction of NADP to NADPH2 on the stroma side of the membrane", "Breakdown of proton gradient", "Breakdown of electron gradient", "Movement of protons across the membrane to the stroma"],
        "correct_option_id": 2,
        "explanation": "Chemiosmosis works through a proton (H+) gradient, not an \"electron gradient\" — breakdown of an electron gradient is not part of the mechanism.",
    },
    {
        "question": "Assertion (A): Polymerase chain reaction is used in DNA amplification. Reason (R): The ampicillin resistant gene is used as a selectable marker to check transformation.",
        "options": ["(A) is not correct but (R) is correct", "Both (A) and (R) are correct and (R) is the correct explanation of (A)", "Both (A) and (R) are correct but (R) is not the correct explanation of (A)", "(A) is correct but (R) is not correct"],
        "correct_option_id": 2,
        "explanation": "Both statements are independently true, but the ampicillin-resistance marker explanation has nothing to do with PCR-based amplification.",
    },
    {
        "question": "Habitat loss and fragmentation, over exploitation, alien species invasion and co-extinction are causes for:",
        "options": ["Natality", "Population explosion", "Competition", "Biodiversity loss"],
        "correct_option_id": 3,
        "explanation": "These four factors are the well-known NCERT-listed causes of biodiversity loss.",
    },
    {
        "question": "Statement I: The primary CO2 acceptor in C4 plants is phosphoenolpyruvate and is found in the mesophyll cells. Statement II: Mesophyll cells of C4 plants lack RuBisCo enzyme.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 1,
        "explanation": "PEP (a 3-C compound) is the CO2 acceptor in mesophyll cells of C4 plants, and RuBisCo is confined to the bundle sheath cells, absent from mesophyll.",
    },
    {
        "question": "Identify the incorrect statement related to Pollination.",
        "options": ["Moths and butterflies are the most dominant pollinating agents among insects", "Pollination by water is quite rare in flowering plants", "Pollination by wind is more common amongst abiotic pollination", "Flowers produce foul odours to attract flies and beetles to get pollinated"],
        "correct_option_id": 0,
        "explanation": "Among insects, bees (not moths/butterflies) are the most dominant pollinating agents.",
    },
    {
        "question": "Hydrocolloid carrageen is obtained from:",
        "options": ["Phaeophyceae only", "Chlorophyceae and Phaeophyceae", "Phaeophyceae and Rhodophyceae", "Rhodophyceae only"],
        "correct_option_id": 3,
        "explanation": "Carrageen is a hydrocolloid obtained from red algae (Rhodophyceae).",
    },
    {
        "question": "The appearance of recombination nodules on homologous chromosomes during meiosis characterizes:",
        "options": ["Terminalization", "Synaptonemal complex", "Bivalent", "Sites at which crossing over occurs"],
        "correct_option_id": 3,
        "explanation": "Recombination nodules mark the pachytene-stage sites where crossing over occurs between non-sister chromatids.",
    },
    {
        "question": "Which one of the following statements is not true regarding gel electrophoresis technique?",
        "options": ["Bright orange coloured bands of DNA can be observed in the gel when exposed to UV light", "The process of extraction of separated DNA strands from gel is called elution", "The separated DNA fragments are stained by using ethidium bromide", "The presence of chromogenic substrate gives blue coloured DNA bands on the gel"],
        "correct_option_id": 3,
        "explanation": "Blue-white colour with a chromogenic substrate relates to blue-white bacterial colony selection, not DNA staining in gel electrophoresis (which uses ethidium bromide, visualised as orange bands under UV).",
    },
    {
        "question": "The gaseous plant growth regulator is used in plants to:",
        "options": ["kill dicotyledonous weeds in the fields", "speed up the malting process", "promote root growth and roothair formation to increase the absorption surface", "help overcome apical dominance"],
        "correct_option_id": 2,
        "explanation": "Ethylene (the gaseous PGR) promotes root growth and root-hair formation, increasing the absorption surface. (Weed-killing is by 2,4-D auxin; malting is sped by gibberellin; apical dominance is overcome by cytokinin.)",
    },
    {
        "question": "Which of the following is incorrectly matched?",
        "options": ["Volvox – Starch", "Ectocarpus – Fucoxanthin", "Ulothrix – Mannitol", "Porphyra – Floridian Starch"],
        "correct_option_id": 2,
        "explanation": "Ulothrix (a green alga) stores starch as reserve food; mannitol is the reserve food of brown algae (Phaeophyceae), not Ulothrix.",
    },
    {
        "question": "What amount of energy is released from glucose during lactic acid fermentation?",
        "options": ["Less than 7%", "Approximately 15%", "More than 18%", "About 10%"],
        "correct_option_id": 0,
        "explanation": "Less than 7% of the energy present in glucose is released during lactic acid fermentation, and not all of it is trapped as ATP.",
    },
    {
        "question": "XO type of sex determination can be found in:",
        "options": ["Monkeys", "Drosophila", "Birds", "Grasshoppers"],
        "correct_option_id": 3,
        "explanation": "In grasshoppers, males have a single X chromosome (XO) while females have XX; this is the classic XO sex-determination example.",
    },
    {
        "question": "What is the net gain of ATP when each molecule of glucose is converted to two molecules of pyruvic acid?",
        "options": ["Eight", "Four", "Six", "Two"],
        "correct_option_id": 3,
        "explanation": "Glycolysis produces 4 ATP but consumes 2 ATP, giving a net gain of 2 ATP molecules.",
    },
    {
        "question": "\"Girdling Experiment\" was performed by Plant Physiologists to identify the plant tissue through which:",
        "options": ["osmosis is observed", "water is transported", "food is transported", "for both water and food transportation"],
        "correct_option_id": 2,
        "explanation": "Girdling (removing bark including phloem) stops food movement below the cut, proving phloem transports food (translocation).",
    },
    {
        "question": "Which of the following is not a method of ex situ conservation?",
        "options": ["Cryopreservation", "In vitro fertilization", "National Parks", "Micropropagation"],
        "correct_option_id": 2,
        "explanation": "National Parks protect species within their natural habitat, making this an in-situ, not ex-situ, conservation method.",
    },
    {
        "question": "Statement I: Decomposition is a process in which the detritus is degraded into simpler substances by microbes. Statement II: Decomposition is faster if the detritus is rich in lignin and chitin.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 3,
        "explanation": "Decomposition is actually slower, not faster, when detritus is rich in lignin and chitin; it is faster with nitrogen- and sugar-rich material.",
    },
    {
        "question": "Statements on chromatin/nucleosome.",
        "options": ["(a), (c), (e) Only", "(b), (d), (e) Only", "(a), (c), (d) Only", "(b), (e) Only"],
        "correct_option_id": 2,
        "explanation": "Euchromatin is loosely packed (true); heterochromatin is transcriptionally inactive (so statement b is false); histone octamer is wrapped by negatively-charged DNA (true); histones are rich in lysine and arginine (true); a nucleosome contains ~200 bp, not 400 bp (so e is false).",
    },
    {
        "question": "Statements on plant structural modifications.",
        "options": ["(a), (b), (d) and (e) Only", "(b) and (c) Only", "(a) and (d) Only", "(b), (c), (d) and (e) Only"],
        "correct_option_id": 3,
        "explanation": "Tendrils in cucumber/pumpkin, flattened fleshy stem of Opuntia, upward \"breathing\" roots of Rhizophora, and subaerial runners in grasses/strawberry are all correct plant modifications; thorns in Citrus/Bougainvillea arise from axillary buds, not leaflets, making (a) incorrect.",
    },
    {
        "question": "Which one of the following produces nitrogen fixing nodules on the roots of Alnus?",
        "options": ["Beijerinckia", "Rhizobium", "Frankia", "Rhodospirillum"],
        "correct_option_id": 2,
        "explanation": "Frankia, an actinomycete, forms nitrogen-fixing root nodules in non-leguminous plants such as Alnus.",
    },
    {
        "question": "Which one of the following plants shows vexillary aestivation and diadelphous stamens?",
        "options": ["Solanum nigrum", "Colchicum autumnale", "Pisum sativum", "Allium cepa"],
        "correct_option_id": 2,
        "explanation": "Vexillary aestivation and diadelphous stamens are characteristic of family Fabaceae, to which Pisum sativum (pea) belongs.",
    },
    {
        "question": "Statement I: Cleistogamous flowers are invariably autogamous. Statement II: Cleistogamy is disadvantageous as there is no chance for cross pollination.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 1,
        "explanation": "Cleistogamous flowers never open, so only self (autogamous) pollination is possible, and this indeed prevents cross-pollination.",
    },
    {
        "question": "The process of translation of mRNA to proteins begins as soon as:",
        "options": ["The tRNA is activated and the larger subunit of ribosome encounters mRNA", "The small subunit of ribosome encounters mRNA", "The larger subunit of ribosome encounters mRNA", "Both the subunits join together to bind with mRNA"],
        "correct_option_id": 1,
        "explanation": "Translation begins when the small ribosomal subunit binds the mRNA; the larger subunit joins subsequently.",
    },
    {
        "question": "The device which can remove particulate matter present in the exhaust from a thermal power plant is:",
        "options": ["Catalytic Convertor", "STP", "Incinerator", "Electrostatic Precipitator"],
        "correct_option_id": 3,
        "explanation": "An Electrostatic Precipitator removes over 99% of particulate matter from thermal power plant exhaust by charging and collecting dust particles.",
    },
    {
        "question": "Exoskeleton of arthropods is composed of:",
        "options": ["Glucosamine", "Cutin", "Cellulose", "Chitin"],
        "correct_option_id": 3,
        "explanation": "Chitin (a polymer of N-acetylglucosamine) forms the arthropod exoskeleton.",
    },
    {
        "question": "DNA polymorphism forms the basis of:",
        "options": ["Translation", "Genetic mapping", "DNA finger printing", "Both genetic mapping and DNA finger printing"],
        "correct_option_id": 3,
        "explanation": "DNA sequence polymorphism underlies both human genome genetic mapping and DNA fingerprinting techniques.",
    },
    {
        "question": "In old trees the greater part of secondary xylem is dark brown and resistant to insect attack due to: (options a-e)",
        "options": ["(b) and (d) Only", "(a) and (b) Only", "(c) and (d) Only", "(d) and (e) Only"],
        "correct_option_id": 1,
        "explanation": "Dark colouration and resistance result from secretion and deposition of tannins, resins and other organic substances in the central/inner layers (heartwood) of the stem, matching statements (a) and (b).",
    },
    {
        "question": "Which of the following is not observed during apoplastic pathway?",
        "options": ["Apoplast is continuous and does not provide any barrier to water movement", "Movement of water occurs through intercellular spaces and wall of the cells", "The movement does not involve crossing of cell membrane", "The movement is aided by cytoplasmic streaming"],
        "correct_option_id": 3,
        "explanation": "Cytoplasmic streaming aids the symplastic pathway (through plasmodesmata), not the apoplastic pathway, which occurs through cell walls and intercellular spaces without crossing membranes.",
    },
    {
        "question": "Statement I: Mendel studied seven pairs of contrasting traits in pea plants and proposed the Laws of Inheritance. Statement II: Seven characters examined were seed shape and colour, flower colour, pod shape and colour, flower position and stem height.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 1,
        "explanation": "Both statements accurately describe Mendel's pea plant experiments and the seven contrasting characters he studied.",
    },
    {
        "question": "Application of which phytohormone increased cucumber yield by producing female flowers?",
        "options": ["Cytokinin", "ABA", "Gibberellin", "Ethylene"],
        "correct_option_id": 3,
        "explanation": "Ethylene increases the number of female flowers (and hence fruit yield) in cucurbits such as cucumber.",
    },
    {
        "question": "Which interaction can be assigned (+) for one species and (−) for another?",
        "options": ["Competition", "Predation", "Amensalism", "Commensalism"],
        "correct_option_id": 1,
        "explanation": "Predation is a (+, −) interaction — the predator benefits while the prey is harmed.",
    },
    {
        "question": "If a geneticist sequences a whole genome blindly and then assigns function to different segments, the methodology is called:",
        "options": ["Bioinformatics", "Sequence annotation", "Gene mapping", "Expressed sequence tags"],
        "correct_option_id": 1,
        "explanation": "Sequencing the whole genome first and later assigning functions to specific segments is called sequence annotation.",
    },
    {
        "question": "Which of the following occurs due to the presence of autosome linked dominant trait?",
        "options": ["Thalassemia", "Sickle cell anaemia", "Myotonic dystrophy", "Haemophilia"],
        "correct_option_id": 2,
        "explanation": "Myotonic dystrophy is an autosomal dominant disorder, unlike haemophilia (X-linked recessive) or thalassemia/sickle-cell anaemia (autosomal recessive).",
    },
    {
        "question": "Which one of the following will accelerate phosphorus cycle?",
        "options": ["Rain fall and storms", "Burning of fossil fuels", "Volcanic activity", "Weathering of rocks"],
        "correct_option_id": 3,
        "explanation": "The phosphorus cycle is sedimentary, with earth's crust as its reservoir; weathering of rocks releases phosphorus, accelerating the cycle.",
    },
    {
        "question": "Statements on lipids (a)-(e).",
        "options": ["(a), (b) and (d) only", "(a), (b) and (c) only", "(a), (d) and (e) only", "(c), (d) and (e) only"],
        "correct_option_id": 3,
        "explanation": "Gingely (sesame) oil has a low melting point and stays liquid in winter (true); lipids are insoluble in water but soluble in organic solvents (true); esterification of fatty acid with glycerol forms monoglycerides (true). Lecithin is a phospholipid, not a glycolipid, and saturated fatty acids lack C=C double bonds, so (a) and (b) are false.",
    },
    {
        "question": "In the following palindromic base sequences of DNA, which one can be cut easily by a particular restriction enzyme?",
        "options": ["5'GTATTC3'; 3'CATAAG5'", "5'GATACT3'; 3'CTATGA5'", "5'GAATTC3'; 3'CTTAAG5'", "5'CTCAGT3'; 3'GAGTCA5'"],
        "correct_option_id": 2,
        "explanation": "Only the sequence 5'GAATTC3'/3'CTTAAG5' reads identically on both strands in the same (5'→3') direction — a true palindrome, making it recognisable and cleavable by a restriction enzyme (e.g., EcoRI).",
    },
    {
        "question": "Assertion (A): Mendel's law of Independent assortment does not hold good for the genes that are located closely on the same chromosome. Reason (R): Closely located genes assort independently.",
        "options": ["(A) is not correct but (R) is correct", "Both (A) and (R) are correct and (R) is the correct explanation of (A)", "Both (A) and (R) are correct but (R) is not the correct explanation of (A)", "(A) is correct but (R) is not correct"],
        "correct_option_id": 3,
        "explanation": "The assertion is correct — closely linked genes violate independent assortment — but the reason contradicts this fact, since closely located (linked) genes do NOT assort independently.",
    },
    {
        "question": "Delhi buses converted from diesel to CNG. Which statement is false?",
        "options": ["It cannot be adulterated like diesel", "CNG burns more efficiently than diesel", "The same diesel engine is used in CNG buses making the cost of conversion low", "It is cheaper than diesel"],
        "correct_option_id": 2,
        "explanation": "CNG buses require modified/different engines, not the same diesel engine, so this statement is false.",
    },
    {
        "question": "What is the role of large bundle sheath cells found around vascular bundles in C4 plants?",
        "options": ["To protect the vascular tissue from high light intensity", "To provide the site for photorespiratory pathway", "To increase the number of chloroplast for the operation of Calvin cycle", "To enable the plant to tolerate high temperature"],
        "correct_option_id": 2,
        "explanation": "Bundle sheath cells in C4 plants contain numerous chloroplasts that carry out the Calvin cycle (C3 pathway) using CO2 released from the C4 acids.",
    },
    {
        "question": "Transposons can be used during which one of the following?",
        "options": ["Gene sequencing", "Polymerase Chain Reaction", "Gene Silencing", "Autoradiography"],
        "correct_option_id": 2,
        "explanation": "Transposons (mobile genetic elements) can act as the source of complementary RNA used in RNA interference/gene silencing.",
    },
    {
        "question": "Addition of more solutes in a given solution will:",
        "options": ["not affect the water potential at all", "raise its water potential", "lower its water potential", "make its water potential zero"],
        "correct_option_id": 2,
        "explanation": "Adding solute lowers the solute potential (and hence overall water potential) of a solution compared to pure water.",
    },
    {
        "question": "Statements about springwood.",
        "options": ["(c), (d) and (e) Only", "(a), (b), (d) and (e) Only", "(a), (c), (d) and (e) Only", "(a), (b) and (d) Only"],
        "correct_option_id": 2,
        "explanation": "Springwood (earlywood) is lighter in colour, has lower density, and alternates with autumnwood to form annual rings; however, vessels formed in spring are wider (not narrower), making statement (b) false.",
    },
    {
        "question": "Under normal physiological conditions, every 100 ml of oxygenated blood can deliver ________ ml of O2 to the tissues.",
        "options": ["10 ml", "2 ml", "5 ml", "4 ml"],
        "correct_option_id": 2,
        "explanation": "Under normal conditions, 100 mL of oxygenated blood delivers approximately 5 mL of O2 to the tissues.",
    },
    {
        "question": "Nitrogenous waste is excreted in the form of pellet or paste by:",
        "options": ["Pavo", "Ornithorhynchus", "Salamandra", "Hippocampus"],
        "correct_option_id": 0,
        "explanation": "Birds like Pavo (peacock) are uricotelic and excrete nitrogenous waste as a semi-solid pellet/paste of uric acid to conserve water.",
    },
    {
        "question": "Which of the following is present between the adjacent bones of the vertebral column?",
        "options": ["Smooth muscle", "Intercalated discs", "Cartilage", "Areolar tissue"],
        "correct_option_id": 2,
        "explanation": "Cartilage forms the intervertebral discs between adjacent vertebrae (a cartilaginous joint).",
    },
    {
        "question": "In-situ conservation refers to:",
        "options": ["Conserve only extinct species", "Protect and conserve the whole ecosystem", "Conserve only high-risk species", "Conserve only endangered species"],
        "correct_option_id": 1,
        "explanation": "In-situ conservation protects species along with their entire natural habitat/ecosystem.",
    },
    {
        "question": "Statement I: Autoimmune disorder is a condition where body defense mechanism recognizes its own cells as foreign bodies. Statement II: Rheumatoid arthritis is a condition where body does not attack self cells.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 3,
        "explanation": "Statement I correctly defines autoimmune disorders; Statement II is wrong because rheumatoid arthritis is itself an autoimmune disease where the body does attack self cells (synovial membrane).",
    },
    {
        "question": "Which of the following is not the function of conducting part of respiratory system?",
        "options": ["Provides surface for diffusion of O2 and CO2", "It clears inhaled air from foreign particles", "Inhaled air is humidified", "Temperature of inhaled air is brought to body temperature"],
        "correct_option_id": 0,
        "explanation": "Gas diffusion occurs in the exchange part (alveoli), not the conducting part; the conducting part only transports, cleans, warms and humidifies the air.",
    },
    {
        "question": "Statement I: The coagulum is formed of network of threads called thrombins. Statement II: Spleen is the graveyard of erythrocytes.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 0,
        "explanation": "The clot/coagulum is made of fibrin threads, not thrombin (thrombin is the enzyme that converts fibrinogen to fibrin); the spleen is indeed correctly called the graveyard of RBCs.",
    },
    {
        "question": "Assertion (A): All vertebrates are chordates but all chordates are not vertebrates. Reason (R): Notochord is replaced by vertebral column in the adult vertebrates.",
        "options": ["(A) is not correct but (R) is correct", "Both (A) and (R) are correct and (R) is the correct explanation of (A)", "Both (A) and (R) are correct but (R) is not the correct explanation of (A)", "(A) is correct but (R) is not correct"],
        "correct_option_id": 1,
        "explanation": "Vertebrata is one of three chordate subphyla; in vertebrates the notochord is replaced by the vertebral column in adults, which correctly explains why all vertebrates are chordates but not vice versa.",
    },
    {
        "question": "Assertion (A): Osteoporosis is characterised by decreased bone mass and increased chance of fractures. Reason (R): Common cause of osteoporosis is increased levels of estrogen.",
        "options": ["(A) is not correct but (R) is correct", "Both (A) and (R) are correct and (R) is the correct explanation of (A)", "Both (A) and (R) are correct but (R) is not the correct explanation of (A)", "(A) is correct but (R) is not correct"],
        "correct_option_id": 3,
        "explanation": "Osteoporosis is correctly described in the assertion, but it is caused by decreased (not increased) estrogen levels, typically after menopause.",
    },
    {
        "question": "Statement I: Mycoplasma can pass through less than 1 micron filter size. Statement II: Mycoplasma are bacteria with cell wall.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 3,
        "explanation": "Mycoplasma are extremely small (~0.3 micron) and can pass through fine filters, but they lack a cell wall entirely.",
    },
    {
        "question": "A dehydration reaction links two glucose molecules to produce maltose. If the formula for glucose is C6H12O6, what is the formula for maltose?",
        "options": ["C12H24O11", "C12H20O10", "C12H24O12", "C12H22O11"],
        "correct_option_id": 3,
        "explanation": "Two glucose molecules (C6H12O6 each) condense losing one H2O, giving C12H22O11 (maltose).",
    },
    {
        "question": "Regarding Meiosis, which of the statements is incorrect?",
        "options": ["Four haploid cells are formed at the end of Meiosis-II", "There are two stages in Meiosis, Meiosis-I and II", "DNA replication occurs in S phase of Meiosis-II", "Pairing of homologous chromosomes and recombination occurs in Meiosis-I"],
        "correct_option_id": 2,
        "explanation": "DNA replication occurs only once, before Meiosis-I (in interphase); there is no S phase or DNA replication before Meiosis-II.",
    },
    {
        "question": "Natural selection where more individuals acquire a specific character value other than the mean character value, leads to:",
        "options": ["Random change", "Stabilising change", "Directional change", "Disruptive change"],
        "correct_option_id": 2,
        "explanation": "When more individuals acquire a character value away from the mean (in one direction), it is directional selection.",
    },
    {
        "question": "In gene therapy of Adenosine Deaminase (ADA) deficiency, the patient requires periodic infusion of genetically engineered lymphocytes because:",
        "options": ["Genetically engineered lymphocytes are not immortal cells", "Retroviral vector is introduced into these lymphocytes", "Gene isolated from marrow cells producing ADA is introduced into cells at embryonic stages", "Lymphocytes from patient's blood are grown in culture, outside the body"],
        "correct_option_id": 0,
        "explanation": "Since the genetically engineered lymphocytes are not immortal, they eventually die, requiring periodic re-infusion until a permanent cure via stem cells becomes available.",
    },
    {
        "question": "If '8' Drosophila in a laboratory population of '80' died during a week, the death rate in the population is ______ individuals per Drosophila per week.",
        "options": ["zero", "0.1", "10", "1.0"],
        "correct_option_id": 1,
        "explanation": "Death rate = 8/80 = 0.1 individuals per Drosophila per week.",
    },
    {
        "question": "In the taxonomic categories, which hierarchical arrangement in ascending order is correct in case of animals?",
        "options": ["Kingdom, Order, Phylum, Class, Family, Genus, Species", "Kingdom, Phylum, Class, Order, Family, Genus, Species", "Kingdom, Class, Phylum, Family, Order, Genus, Species", "Kingdom, Order, Class, Phylum, Family, Genus, Species"],
        "correct_option_id": 1,
        "explanation": "Note: The true ascending hierarchy is actually Species → Genus → Family → Order → Class → Phylum → Kingdom; the official key selected option 2 (Kingdom→Species, i.e., descending order) since it lists the categories in the standard nested sequence, though the question's wording (\"ascending order\") was inconsistent with the listed direction — this discrepancy was acknowledged in official solutions.",
    },
    {
        "question": "Statement I: Restriction endonucleases recognise specific sequence to cut DNA known as palindromic nucleotide sequence. Statement II: Restriction endonucleases cut the DNA strand a little away from the centre of the palindromic site.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 1,
        "explanation": "Both statements correctly describe restriction endonuclease action on palindromic DNA sequences.",
    },
    {
        "question": "Breeding crops with higher levels of vitamins and minerals or higher proteins and healthier fats is called:",
        "options": ["Bio-accumulation", "Bio-magnification", "Bio-remediation", "Bio-fortification"],
        "correct_option_id": 3,
        "explanation": "Breeding crops for enhanced nutritional value (vitamins, minerals, proteins, fats) is called biofortification.",
    },
    {
        "question": "Identify the microorganism which is responsible for the production of an immunosuppressive molecule cyclosporin A.",
        "options": ["Streptococcus cerevisiae", "Trichoderma polysporum", "Clostridium butylicum", "Aspergillus niger"],
        "correct_option_id": 1,
        "explanation": "Cyclosporin A, an immunosuppressive drug used in organ transplants, is produced by the fungus Trichoderma polysporum.",
    },
    {
        "question": "Which of the following is a correct match for disease and its symptoms?",
        "options": ["Muscular dystrophy – An auto immune disorder causing progressive degeneration of skeletal muscle", "Arthritis – Inflamed joints", "Tetany – High Ca2+ level causing rapid spasms", "Myasthenia gravis – Genetic disorder resulting in weakening and paralysis of skeletal muscle"],
        "correct_option_id": 1,
        "explanation": "Arthritis is correctly defined as inflammation of joints; muscular dystrophy is genetic (not autoimmune), tetany is caused by LOW (not high) Ca2+, and myasthenia gravis is an autoimmune (not genetic) disorder.",
    },
    {
        "question": "Which of the following statements with respect to Endoplasmic Reticulum is incorrect?",
        "options": ["SER are the sites for lipid synthesis", "RER has ribosomes attached to ER", "SER is devoid of ribosomes", "In prokaryotes only RER are present"],
        "correct_option_id": 3,
        "explanation": "Prokaryotes lack endoplasmic reticulum entirely — neither RER nor SER is present in them.",
    },
    {
        "question": "Statement I: The release of sperms into the seminiferous tubules is called spermiation. Statement II: Spermiogenesis is the process of formation of sperms from spermatogonia.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 3,
        "explanation": "Spermiation (release of mature sperms into the seminiferous tubule lumen) is correctly described; spermiogenesis is actually the transformation of spermatids into spermatozoa, not the process from spermatogonia (that overall process is spermatogenesis).",
    },
    {
        "question": "Identify the asexual reproductive structure associated with Penicillium.",
        "options": ["Buds", "Zoospores", "Conidia", "Gemmules"],
        "correct_option_id": 2,
        "explanation": "Penicillium reproduces asexually by producing conidia.",
    },
    {
        "question": "In an E. coli strain, the i gene gets mutated and its product cannot bind the inducer molecule. If the growth medium is provided with lactose, what will be the outcome?",
        "options": ["RNA polymerase will bind the promoter region", "Only z gene will get transcribed", "z, y, a genes will be transcribed", "z, y, a genes will not be translated"],
        "correct_option_id": 3,
        "explanation": "The mutated repressor can no longer bind the inducer, so it remains permanently bound to the operator, blocking transcription (and hence translation) of z, y, and a genes even in the presence of lactose.",
    },
    {
        "question": "Tegmina in cockroach arises from:",
        "options": ["Prothorax and Mesothorax", "Prothorax", "Mesothorax", "Metathorax"],
        "correct_option_id": 2,
        "explanation": "The forewings (tegmina) of a cockroach arise from the mesothorax.",
    },
    {
        "question": "In which of the following animals does the digestive tract have additional chambers like crop and gizzard?",
        "options": ["Pavo, Psittacula, Corvus", "Corvus, Columba, Chameleon", "Bufo, Balaenoptera, Bangarus", "Catla, Columba, Crocodilus"],
        "correct_option_id": 0,
        "explanation": "Crop and gizzard are present in birds; Pavo (peacock), Psittacula (parrot) and Corvus (crow) are all birds.",
    },
    {
        "question": "Which of the following statements are true for spermatogenesis but do not hold true for Oogenesis?",
        "options": ["(b), (c) and (e) only", "(c) and (e) only", "(b) and (c) only", "(b), (d) and (e) only"],
        "correct_option_id": 0,
        "explanation": "Differentiation of gametes after completion of meiosis, continuous meiosis in a mitotically dividing stem cell population, and initiation at puberty are all true only for spermatogenesis; oogenesis begins in embryonic stage and its gamete differentiation pattern differs.",
    },
    {
        "question": "Statement I: Fatty acids and glycerols cannot be absorbed into the blood. Statement II: Specialized lymphatic capillaries called lacteals carry chylomicrons into lymphatic vessels and ultimately into the blood.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 1,
        "explanation": "Being insoluble in water, fatty acids/glycerol cannot enter the blood directly — they are packaged as chylomicrons and transported via lacteals (lymphatic capillaries) into the bloodstream.",
    },
    {
        "question": "Lippe's loop is a type of contraceptive used as:",
        "options": ["Copper releasing IUD", "Cervical barrier", "Vault barrier", "Non-Medicated IUD"],
        "correct_option_id": 3,
        "explanation": "Lippe's loop is a classic example of a non-medicated (inert) intrauterine device (IUD).",
    },
    {
        "question": "Which of the following functions is not performed by secretions from salivary glands?",
        "options": ["Digestion of disaccharides", "Control bacterial population in mouth", "Digestion of complex carbohydrates", "Lubrication of oral cavity"],
        "correct_option_id": 0,
        "explanation": "Disaccharide digestion occurs in the small intestine, not through salivary secretions, which act on starch (a polysaccharide) in the mouth.",
    },
    {
        "question": "Which of the following is not a connective tissue?",
        "options": ["Neuroglia", "Blood", "Adipose tissue", "Cartilage"],
        "correct_option_id": 0,
        "explanation": "Neuroglia are supportive cells of nervous tissue, not connective tissue.",
    },
    {
        "question": "Detritivores breakdown detritus into smaller particles. This process is called:",
        "options": ["Decomposition", "Catabolism", "Fragmentation", "Humification"],
        "correct_option_id": 2,
        "explanation": "The breakdown of detritus into smaller particles by detritivores (e.g., earthworms) is called fragmentation.",
    },
    {
        "question": "Select the incorrect statement with reference to mitosis.",
        "options": ["Splitting of centromere occurs at anaphase", "All the chromosomes lie at the equator at metaphase", "Spindle fibres attach to centromere of chromosomes", "Chromosomes decondense at telophase"],
        "correct_option_id": 2,
        "explanation": "Spindle fibres attach to the kinetochores (disc-shaped structures on the centromere), not directly to the centromere itself.",
    },
    {
        "question": "If the length of a DNA molecule is 1.1 metres, what will be the approximate number of base pairs?",
        "options": ["6.6 × 10^6 bp", "3.3 × 10^9 bp", "6.6 × 10^9 bp", "3.3 × 10^6 bp"],
        "correct_option_id": 1,
        "explanation": "Using 0.34 nm rise per base pair: 1.1 m ÷ (0.34×10⁻⁹ m) ≈ 3.3 × 10^9 base pairs.",
    },
    {
        "question": "At which stage of life is the oogenesis process initiated?",
        "options": ["Adult", "Puberty", "Embryonic development stage", "Birth"],
        "correct_option_id": 2,
        "explanation": "Oogenesis begins during embryonic development, when oogonia are formed within the fetal ovary; no new oogonia form after birth.",
    },
    {
        "question": "Which of the following is not a desirable feature of a cloning vector?",
        "options": ["Presence of two or more recognition sites", "Presence of origin of replication", "Presence of a marker gene", "Presence of single restriction enzyme site"],
        "correct_option_id": 0,
        "explanation": "A good cloning vector should have very few, preferably a single, recognition site for commonly used restriction enzymes — not two or more, which could cut the vector at multiple undesired points.",
    },
    {
        "question": "Select the incorrect statement regarding synapses.",
        "options": ["Impulse transmission across a chemical synapse is always faster than that across an electrical synapse", "The membranes of presynaptic and postsynaptic neurons are in close proximity in an electrical synapse", "Electrical current can flow directly from one neuron into the other across the electrical synapse", "Chemical synapses use neurotransmitters"],
        "correct_option_id": 0,
        "explanation": "Transmission across an electrical synapse is actually faster than across a chemical synapse, not the reverse.",
    },
    {
        "question": "Which statement(s) is/are correct about genetically engineered Insulin?",
        "options": ["(c), (d) and (e) only", "(a), (b) and (d) only", "(b) only", "(c) and (d) only"],
        "correct_option_id": 2,
        "explanation": "Only statement (b) is correct: A and B peptide chains of insulin are produced separately using E. coli, then extracted and combined via disulphide bonds; genetically engineered insulin lacks the C-peptide, doesn't need pro-insulin processing, and isn't extracted from cattle/pigs (allergy issues arise mainly with animal-derived insulin).",
    },
    {
        "question": "Which of the following are not the effects of Parathyroid hormone?",
        "options": ["(b) and (c) only", "(a) and (c) only", "(b), (d) and (e) only", "(a) and (e) only"],
        "correct_option_id": 2,
        "explanation": "PTH actually increases (not decreases) blood Ca2+, increases (not decreases) Ca2+ absorption from food, and does not regulate carbohydrate metabolism — so statements b, d and e are the effects it does NOT have.",
    },
    {
        "question": "Which of the following statements is not true?",
        "options": ["Flippers of penguins and dolphins are a pair of homologous organs", "Analogous structures are a result of convergent evolution", "Sweet potato and potato is an example of analogy", "Homology indicates common ancestry"],
        "correct_option_id": 0,
        "explanation": "Flippers of penguins (a bird) and dolphins (a mammal) have different structural origins but perform similar functions, making them analogous, not homologous, organs.",
    },
    {
        "question": "Which one of the following statements is correct?",
        "options": ["Increased ventricular pressure causes closing of the semilunar valves", "The atrio-ventricular node (AVN) generates an action potential to stimulate atrial contraction", "The tricuspid and the bicuspid valves open due to the pressure exerted by the simultaneous contraction of the atria", "Blood moves freely from atrium to the ventricle during joint diastole"],
        "correct_option_id": 3,
        "explanation": "During joint diastole, both AV valves are open, allowing blood to flow freely from atria to ventricles.",
    },
    {
        "question": "Select the incorrect statement with respect to acquired immunity.",
        "options": ["Acquired immunity is non-specific type of defense present at the time of birth", "Primary response is produced when our body encounters a pathogen for the first time", "Anamnestic response is elicited on subsequent encounters with the same pathogen", "Anamnestic response is due to memory of first encounter"],
        "correct_option_id": 0,
        "explanation": "Acquired immunity is specific and develops after birth upon pathogen exposure; it is not the non-specific, innate defense present at birth (that describes innate immunity).",
    },
    {
        "question": "Ten E. coli cells with 15N-dsDNA are incubated in medium containing 14N nucleotide. After 60 minutes (assume generation time allows sufficient replications), how many E. coli cells will have DNA totally free from 15N?",
        "options": ["80 cells", "20 cells", "40 cells", "60 cells"],
        "correct_option_id": 3,
        "explanation": "Following semi-conservative replication through successive generations from 10 parent cells, the official solution works out to 60 cells having DNA completely free of the original 15N label.",
    },
    {
        "question": "Which of the following is a correct statement?",
        "options": ["Mycoplasma have DNA, ribosome and cell wall", "Cyanobacteria are a group of autotrophic organisms classified under kingdom Monera", "Bacteria are exclusively heterotrophic organisms", "Slime moulds are saprophytic organisms classified under Kingdom Monera"],
        "correct_option_id": 1,
        "explanation": "Cyanobacteria are photosynthetic autotrophic prokaryotes classified under Kingdom Monera. (Mycoplasma lack a cell wall; bacteria can be autotrophic or heterotrophic; slime moulds belong to Kingdom Protista, not Monera.)",
    },
    {
        "question": "The recombination frequency between the genes a & c is 5%, b & c is 15%, b & d is 9%, a & b is 20%, c & d is 24% and a & d is 29%. What will be the sequence of these genes on a linear chromosome?",
        "options": ["a, c, b, d", "a, d, b, c", "d, b, a, c", "a, b, c, d"],
        "correct_option_id": 0,
        "explanation": "Using recombination frequency (≈ map distance) to order the genes on the chromosome, the sequence that fits all the given distances is a–c–b–d.",
    },
    {
        "question": "If a colour blind female marries a man whose mother was also colour blind, what are the chances of her progeny having colour blindness?",
        "options": ["100%", "25%", "50%", "75%"],
        "correct_option_id": 0,
        "explanation": "The man's mother being colour blind (XᶜXᶜ) means the man himself is colour blind (XᶜY). Crossing a colour-blind woman (XᶜXᶜ) with a colour-blind man (XᶜY) gives all daughters XᶜXᶜ (colour blind) and all sons XᶜY (colour blind) — i.e., 100% of the progeny will be colour blind.",
    },
    {
        "question": "Statement I: In a scrubber the exhaust from the thermal plant is passed through the electric wires to charge the dust particles. Statement II: Particulate matter (PM 2.5) cannot be removed by scrubber but can be removed by an electrostatic precipitator.",
        "options": ["Statement I is incorrect but Statement II is correct", "Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect"],
        "correct_option_id": 0,
        "explanation": "Charging dust particles using electric wires describes an electrostatic precipitator, not a scrubber (which typically uses water spray to remove gaseous pollutants); Statement II is a correct description of the limitation of scrubbers versus electrostatic precipitators for PM2.5 removal.",
    },
]
