"""
Question bank: AIPMT 2014 (Code P) - Biology (Solved Answers).

80 questions parsed from AIPMT 2014 (Code P)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Which one of the following shows isogamy with non – flagellated gametes?",
        "options": ["Sargassum", "Ectocarpus", "Ulothrix", "Spirogyra"],
        "correct_option_id": 3,
        "explanation": "Spirogyra reproduces by isogamy, but its gametes are non-motile (aplanogametes) that fuse via conjugation tubes.",
    },
    {
        "question": "Five kingdom system of classification suggested by R.H. Whittaker is not based on:",
        "options": ["Presence or absence of a well defined nucleus", "Mode of reproduction", "Mode of nutrition", "Complexity of body organization"],
        "correct_option_id": 1,
        "explanation": "Whittaker's classification is based on cell structure, body organization, mode of nutrition, and phylogenetic relationships — not specifically on mode of reproduction.",
    },
    {
        "question": "Which one of the following fungi contains hallucinogens?",
        "options": ["Morchella esculenta", "Amanita muscaria", "Neurospora sp.", "Ustilago sp."],
        "correct_option_id": 1,
        "explanation": "Amanita muscaria (fly agaric) mushroom contains hallucinogenic/psychoactive compounds such as muscimol.",
    },
    {
        "question": "Archaebacteria differ from eubacteria in:",
        "options": ["Cell membrane structure", "Mode of nutrition", "Cell shape", "Mode of reproduction"],
        "correct_option_id": 0,
        "explanation": "Archaebacteria have a distinct cell membrane (ether-linked lipids) that allows them to survive extreme conditions, unlike eubacteria.",
    },
    {
        "question": "Which one of the following is wrong about chara?",
        "options": ["Upper oogonium and lower round antheridium", "Globule and nucule present on the same plant", "Upper antheridium and lower oogonium", "Globule is male reproductive structure"],
        "correct_option_id": 2,
        "explanation": "In Chara, the globule (antheridium, male) is located below the nucule (oogonium, female) at each node — not above it as stated in option 3.",
    },
    {
        "question": "Which of the following is responsible for peat formation?",
        "options": ["Marchantia", "Riccia", "Funaria", "Sphagnum"],
        "correct_option_id": 3,
        "explanation": "Sphagnum, a moss, accumulates in large amounts in bogs and forms peat upon decomposition.",
    },
    {
        "question": "Placenta and pericarp are both edible portions in:",
        "options": ["Apple", "Banana", "Tomato", "Potato"],
        "correct_option_id": 2,
        "explanation": "In tomato (a berry), both the placenta bearing the seeds and the pericarp (fruit wall) are fleshy and edible.",
    },
    {
        "question": "When the margins of sepals or petals overlap one another without any particular direction, the condition is termed as:",
        "options": ["Vexillary", "Imbricate", "Twisted", "Valvate"],
        "correct_option_id": 1,
        "explanation": "Imbricate aestivation is when petal/sepal margins overlap each other irregularly, without a fixed pattern of direction.",
    },
    {
        "question": "You are given a fairly old piece of dicot stem and a dicot root. Which of the following anatomical structures will you use to distinguish between the two?",
        "options": ["Secondary xylem", "Secondary phloem", "Protoxylem", "Cortical cells"],
        "correct_option_id": 2,
        "explanation": "The position of protoxylem (exarch in roots, endarch in stems) helps distinguish a dicot root from a dicot stem even in older secondary-growth tissue.",
    },
    {
        "question": "Which one of the following statements is correct?",
        "options": ["The seed in grasses is not endospermic", "Mango is parthenocarpic fruit", "A proteinaceous aleurone layer is present in maize grain", "A sterile pistil is called a staminode"],
        "correct_option_id": 2,
        "explanation": "Maize (and other cereal) grains have an outer proteinaceous aleurone layer surrounding the endosperm.",
    },
    {
        "question": "Tracheids differ from other tracheary elements in:",
        "options": ["Having casparian strips", "Being imperforate", "Lacking nucleus", "Being lignified"],
        "correct_option_id": 1,
        "explanation": "Unlike vessels, tracheids are imperforate (lack perforation plates) and conduct water only through pits.",
    },
    {
        "question": "An example of edible underground stem is:",
        "options": ["Carrot", "Groundnut", "Sweet potato", "Potato"],
        "correct_option_id": 3,
        "explanation": "Potato is a modified underground stem (tuber), while carrot and sweet potato are modified roots.",
    },
    {
        "question": "Which structure performs the function of mitochondria in bacteria?",
        "options": ["Nucleoid", "Ribosomes", "Cell wall", "Mesosomes"],
        "correct_option_id": 3,
        "explanation": "Mesosomes, infoldings of the plasma membrane, help in respiration and other functions in bacteria, similar to mitochondria in eukaryotes.",
    },
    {
        "question": "The solid linear cytoskeletal elements having a diameter of 6 nm and made up of a single type of monomer are known as:",
        "options": ["Microtubules", "Microfilaments", "Intermediate filaments", "Lamins"],
        "correct_option_id": 1,
        "explanation": "Microfilaments are solid, ~6 nm thick actin filaments built from a single monomer, actin.",
    },
    {
        "question": "The osmotic expansion of a cell kept in water is chiefly regulated by:",
        "options": ["Mitochondria", "Vacuoles", "Plastids", "Ribosomes"],
        "correct_option_id": 1,
        "explanation": "Vacuoles regulate the osmotic balance and water content of the cell.",
    },
    {
        "question": "During which phase(s) of cell cycle, amount of DNA in a cell remains at 4C level if the initial amount is denoted as 2C?",
        "options": ["G0 and G1", "G1 and S", "Only G2", "G2 and M"],
        "correct_option_id": 3,
        "explanation": "DNA content doubles to 4C after S phase and stays at 4C throughout G2 and M phase until cell division is complete.",
    },
    {
        "question": "Dr. F. Went noted that if coleoptile tips were removed and placed on agar for one hour, the agar would produce a bending when placed on one side of freshly-cut coleoptile stumps. Of what significance is this experiment?",
        "options": ["It made possible the isolation and exact identification of auxin", "It is the basis for quantitative determination of small amounts of growth-promoting substances", "It supports the hypothesis that IAA is auxin", "It demonstrated polar movement of auxins"],
        "correct_option_id": 1,
        "explanation": "Went's avena curvature test established a quantitative bioassay for measuring the concentration of growth-promoting substances (auxins) based on degree of curvature.",
    },
    {
        "question": "Deficiency symptoms of nitrogen and potassium are visible first in:",
        "options": ["Senescent leaves", "Young leaves", "Roots", "Buds"],
        "correct_option_id": 0,
        "explanation": "Nitrogen and potassium are mobile elements, so deficiency symptoms first appear in older (senescent) leaves as nutrients are relocated to younger tissues.",
    },
    {
        "question": "In which one of the following processes CO2 is not released?",
        "options": ["Aerobic respiration in plants", "Aerobic respiration in animals", "Alcoholic fermentation", "Lactate fermentation"],
        "correct_option_id": 3,
        "explanation": "Lactic acid fermentation converts pyruvate directly into lactate without releasing CO2, unlike alcoholic fermentation and aerobic respiration.",
    },
    {
        "question": "Anoxygenic photosynthesis is characteristic of:",
        "options": ["Rhodospirillum", "Spirogyra", "Chlamydomonas", "Ulva"],
        "correct_option_id": 0,
        "explanation": "Purple and green sulphur/non-sulphur bacteria like Rhodospirillum carry out anoxygenic photosynthesis, which does not release oxygen.",
    },
    {
        "question": "A few normal seedlings of tomato were kept in a dark room. After a few days they were found to have become white-coloured like albinos. Which of the following terms will you use to describe them?",
        "options": ["Mutated", "Embolised", "Etiolated", "Defoliated"],
        "correct_option_id": 2,
        "explanation": "Plants grown in darkness fail to synthesize chlorophyll and show elongated, pale/yellowish-white growth called etiolation.",
    },
    {
        "question": "Which one of the following growth regulators is known as 'stress hormone'?",
        "options": ["Abscisic acid", "Ethylene", "GA3", "Indole acetic acid"],
        "correct_option_id": 0,
        "explanation": "Abscisic acid (ABA) is called the stress hormone as it helps plants cope with adverse conditions like drought.",
    },
    {
        "question": "Geitonogamy involves:",
        "options": ["Fertilization of a flower by the pollen from another flower of the same plant", "Fertilization of a flower by the pollen from the same flower", "Fertilization of a flower by the pollen from a flower of another plant in the same population", "Fertilization of a flower by the pollen from a flower of another plant belonging to a distant population"],
        "correct_option_id": 0,
        "explanation": "Geitonogamy is pollination between two flowers of the same plant, genetically similar to self-pollination.",
    },
    {
        "question": "Male gametophyte with least number of cells is present in:",
        "options": ["Pteris", "Funaria", "Lilium", "Pinus"],
        "correct_option_id": 2,
        "explanation": "In angiosperms like Lilium, the mature male gametophyte (pollen grain) has only 3 cells (2 male gametes + 1 vegetative cell), fewer than in ferns, mosses, or gymnosperms.",
    },
    {
        "question": "An aggregate fruit is one which develops from:",
        "options": ["Multicarpellary syncarpous gynoecium", "Multicarpellary apocarpous gynoecium", "Complete inflorescence", "Multicarpellary superior ovary"],
        "correct_option_id": 1,
        "explanation": "Aggregate fruits develop from a single flower with a multicarpellary apocarpous gynoecium, where each free carpel develops into a fruitlet.",
    },
    {
        "question": "Pollen tablets are available in the market for:",
        "options": ["In vitro fertilization", "Breeding programmes", "Supplementing food", "Ex situ conservation"],
        "correct_option_id": 2,
        "explanation": "Pollen is nutritionally rich and pollen tablets are sold commercially as food/dietary supplements.",
    },
    {
        "question": "Function of filiform apparatus is to:",
        "options": ["Recognize the suitable pollen at stigma", "Stimulate division of generative cell", "Produce nectar", "Guide the entry of pollen tube"],
        "correct_option_id": 3,
        "explanation": "The filiform apparatus, present at the micropylar end of a synergid, guides the pollen tube's entry into the embryo sac.",
    },
    {
        "question": "Non – albuminous seed is produced in:",
        "options": ["Maize", "Castor", "Wheat", "Pea"],
        "correct_option_id": 3,
        "explanation": "Pea seeds lack persistent endosperm at maturity, as it is consumed by the developing embryo, making them non-albuminous (exalbuminous).",
    },
    {
        "question": "Which of the following shows coiled RNA strand and capsomers?",
        "options": ["Polio virus", "Tobacco mosaic virus", "Measles virus", "Retrovirus"],
        "correct_option_id": 1,
        "explanation": "Tobacco mosaic virus (TMV) has a helical (coiled) single-stranded RNA genome surrounded by protein capsomers arranged helically.",
    },
    {
        "question": "Which one of the following is wrongly matched?",
        "options": ["Transcription – Writing information From DNA to t – RNA", "Translation – Using information in m – RNA to make protein", "Repressor protein – Binds to operator to stop enzyme synthesis", "Operon - Structural genes, operator and promoter"],
        "correct_option_id": 0,
        "explanation": "Transcription copies genetic information from DNA to mRNA, not tRNA, making this statement incorrect.",
    },
    {
        "question": "Transformation was discovered by:",
        "options": ["Meselson and Stahl", "Hershey and Chase", "Griffith", "Watson and Crick"],
        "correct_option_id": 2,
        "explanation": "Frederick Griffith discovered the phenomenon of bacterial transformation in his experiments with Streptococcus pneumoniae strains.",
    },
    {
        "question": "Fruit colour in squash is an example of:",
        "options": ["Recessive epistasis", "Dominant epistasis", "Complementary genes", "Inhibitory genes"],
        "correct_option_id": 1,
        "explanation": "Fruit colour inheritance in squash (white masking yellow and green) is a classic example of dominant epistasis.",
    },
    {
        "question": "Viruses have:",
        "options": ["DNA enclosed in a protein coat", "Prokaryotic nucleus", "Single chromosome", "Both DNA and RNA"],
        "correct_option_id": 0,
        "explanation": "Viruses consist of genetic material (either DNA or RNA, not both together) enclosed within a protective protein coat (capsid).",
    },
    {
        "question": "The first human hormone produced by recombinant DNA technology is:",
        "options": ["Insulin", "Estrogen", "Thyroxin", "Progesterone"],
        "correct_option_id": 0,
        "explanation": "Human insulin was the first hormone produced commercially using recombinant DNA technology (Humulin, by Eli Lilly).",
    },
    {
        "question": "An analysis of chromosomal DNA using the southern hybridization technique does not use:",
        "options": ["Electrophoresis", "Blotting", "Autoradiography", "PCR"],
        "correct_option_id": 3,
        "explanation": "Southern hybridization uses gel electrophoresis, blotting onto a membrane, and autoradiography for detection — PCR is not an inherent step of this technique.",
    },
    {
        "question": "In vitro propagation in plants is characterized by:",
        "options": ["PCR and RAPD", "Northern blotting", "Electrophoresis and HPLC", "Microscopy"],
        "correct_option_id": 0,
        "explanation": "PCR and RAPD-based molecular markers are used to check genetic/clonal fidelity of plants raised through in vitro propagation (micropropagation).",
    },
    {
        "question": "An alga which can be employed as food for human being is:",
        "options": ["Ulothrix", "Chlorella", "Spirogyra", "Polysiphonia"],
        "correct_option_id": 1,
        "explanation": "Chlorella is a single-celled green alga rich in protein and is used as a food supplement (single-cell protein) for humans.",
    },
    {
        "question": "Which vector can clone only small fragment of DNA?",
        "options": ["Bacterial artificial chromosome", "Yeast artificial chromosome", "Plasmid", "Cosmid"],
        "correct_option_id": 2,
        "explanation": "Plasmid vectors have a limited cloning capacity and can carry only small DNA inserts, unlike BAC, YAC, or cosmid vectors.",
    },
    {
        "question": "An example of ex situ conservation is:",
        "options": ["National park", "Seed Bank", "Wildlife Sanctuary", "Sacred Grove"],
        "correct_option_id": 1,
        "explanation": "Seed banks preserve genetic material outside its natural habitat, making them a classic example of ex situ conservation.",
    },
    {
        "question": "A location with luxuriant growth of lichens on the trees indicates that the:",
        "options": ["Trees are very healthy", "Trees are heavily infested", "Location is highly polluted", "Location is not polluted"],
        "correct_option_id": 3,
        "explanation": "Lichens are highly sensitive to air pollution (especially SO2) and thrive only in unpolluted or clean air locations, acting as pollution indicators.",
    },
    {
        "question": "A species facing extremely high risk of extinction in the immediate future is called:",
        "options": ["Vulnerable", "Endemic", "Critically Endangered", "Extinct"],
        "correct_option_id": 2,
        "explanation": "\"Critically Endangered\" is the IUCN category for species facing an extremely high risk of extinction in the immediate future.",
    },
    {
        "question": "The zone of atmosphere in which the ozone layer is present is called:",
        "options": ["Ionosphere", "Mesosphere", "Stratosphere", "Troposphere"],
        "correct_option_id": 2,
        "explanation": "The ozone layer is located in the stratosphere, roughly 16–50 km above the Earth's surface.",
    },
    {
        "question": "The organization which publishes the Red list of species is:",
        "options": ["ICFRE", "IUCN", "UNEP", "WWF"],
        "correct_option_id": 1,
        "explanation": "The International Union for Conservation of Nature (IUCN) compiles and publishes the Red List of threatened species.",
    },
    {
        "question": "Select the Taxon mentioned that represents both marine and fresh water species:",
        "options": ["Echinoderms", "Ctenophora", "Cephalochordata", "Cnidaria"],
        "correct_option_id": 3,
        "explanation": "Cnidaria includes both marine forms (jellyfish, corals) and freshwater forms (Hydra), unlike the other exclusively marine groups listed.",
    },
    {
        "question": "Which one of the following living organisms completely lacks of cell wall?",
        "options": ["Cyanobacteria", "Sea – Fan (Gorgonia)", "Saccharomyces", "Blue – Green algae"],
        "correct_option_id": 1,
        "explanation": "Sea-Fan (Gorgonia) is an animal (cnidarian) and, like all animals, completely lacks a cell wall, unlike bacteria and fungi listed in the other options.",
    },
    {
        "question": "Planaria possess high capacity of:",
        "options": ["Metamorphosis", "Regeneration", "Alteration of generation", "Bioluminescence"],
        "correct_option_id": 1,
        "explanation": "Planaria (flatworms) are well known for their remarkable ability to regenerate lost body parts.",
    },
    {
        "question": "A marine cartilaginous fish that can produce electric current is:",
        "options": ["Pristis", "Torpedo", "Trygon", "Scoliodon"],
        "correct_option_id": 1,
        "explanation": "Torpedo (electric ray) is a cartilaginous fish capable of generating electric shocks using specialized electric organs.",
    },
    {
        "question": "In 's' phase of the cell cycle:",
        "options": ["Amount of DNA doubles in each cell", "Amount of DNA remains same in each cell", "Chromosome number is increased", "Amount of DNA is reduced to half in each cell"],
        "correct_option_id": 0,
        "explanation": "During the S (synthesis) phase, DNA replication occurs, doubling the DNA content from 2C to 4C, while chromosome number stays the same.",
    },
    {
        "question": "The motile bacteria are able to move by:",
        "options": ["Fimbriae", "Flagella", "Cilia", "Pili"],
        "correct_option_id": 1,
        "explanation": "Bacterial flagella are whip-like appendages that provide motility to bacteria.",
    },
    {
        "question": "Select the option which is not correct with respect to enzyme action:",
        "options": ["Substrate binds with enzyme at its active site", "Addition of lot of succinate does not reverse the inhibition of succinic dehydrogenase by malonate", "A non – competitive inhibitor binds the enzyme at a site distinct from that which binds the substrate", "Malonate is a competitive inhibitor of succinic dehydrogenase"],
        "correct_option_id": 1,
        "explanation": "Since malonate is a competitive inhibitor, its inhibitory effect on succinic dehydrogenase CAN be reversed by adding excess substrate (succinate), making this statement incorrect.",
    },
    {
        "question": "Which one of the following is a non – reducing carbohydrate?",
        "options": ["Maltose", "Sucrose", "Lactose", "Ribose 5 – phosphate"],
        "correct_option_id": 1,
        "explanation": "Sucrose has no free anomeric (reducing) hydroxyl group since both glucose and fructose units are joined through their anomeric carbons, making it a non-reducing sugar.",
    },
    {
        "question": "The enzyme recombinase is required at which stage of meiosis?",
        "options": ["Pachytene", "Zygotene", "Diplotene", "Diakinesis"],
        "correct_option_id": 0,
        "explanation": "Recombinase enzymes mediate crossing over between homologous chromosomes, which occurs during the pachytene stage of prophase I.",
    },
    {
        "question": "The initial step in the digestion of milk in human is carried out by:",
        "options": ["Lipase", "Trypsin", "Rennin", "Pepsin"],
        "correct_option_id": 2,
        "explanation": "Rennin, secreted in infants, curdles milk protein (caseinogen into casein) as the first step of milk digestion.",
    },
    {
        "question": "Fructose is absorbed into the blood through mucosa cells of intestine by the process called:",
        "options": ["Active transport", "Facilitated transport", "Simple diffusion", "Co-transport mechanism"],
        "correct_option_id": 1,
        "explanation": "Fructose is absorbed across the intestinal mucosa via facilitated diffusion (transport), not requiring energy.",
    },
    {
        "question": "Approximately seventy percent of carbon – dioxide absorbed by the blood will be transported to the lungs:",
        "options": ["As bicarbonate ions", "In the form of dissolved gas molecules", "By binding to R.B.C", "As carbamino – haemoglobin"],
        "correct_option_id": 0,
        "explanation": "About 70% of CO2 is transported in blood as bicarbonate ions (HCO3-), formed with the help of carbonic anhydrase in RBCs.",
    },
    {
        "question": "Person with blood group AB is considered as universal recipient because he has:",
        "options": ["Both A and B antigens on RBC but no antibodies in the plasma", "Both A and B antibodies in the plasma", "No antigen on RBC and no antibody in the plasma", "Both A and antigens in the plasma but no antibodies"],
        "correct_option_id": 0,
        "explanation": "AB blood group individuals have both A and B antigens on their RBCs but lack anti-A and anti-B antibodies in plasma, so they can receive blood from any group.",
    },
    {
        "question": "How do parasympathetic neural signals affect the working of the heart?",
        "options": ["Reduce both heart rate and cardiac output", "Heart rate is increased without affecting the cardiac output", "Both heart rate and cardiac output increase", "Heart rate decreases but cardiac output increases"],
        "correct_option_id": 0,
        "explanation": "Parasympathetic stimulation slows the heart rate and, correspondingly, reduces cardiac output.",
    },
    {
        "question": "Which of the following causes an increase in sodium reabsorption in the distal convoluted tubule?",
        "options": ["Increase in aldosterone levels", "Increase in antidiuretic hormone levels", "Decrease in aldosterone levels", "Decrease in antidiuretic hormone levels"],
        "correct_option_id": 0,
        "explanation": "Aldosterone acts on the DCT to increase sodium and water reabsorption, thereby regulating blood pressure and volume.",
    },
    {
        "question": "Stimulation of a muscle fiber by a motor neuron occurs at:",
        "options": ["The neuromuscular junction", "The transverse tubules", "The myofibril", "The sarcoplasmic reticulum"],
        "correct_option_id": 0,
        "explanation": "The neuromuscular junction is the synapse where a motor neuron transmits its signal to the muscle fiber, initiating contraction.",
    },
    {
        "question": "Injury localized to the hypothalamus would most likely disrupt:",
        "options": ["Short – term memory", "Co-ordination during locomotion", "Executive function, such as decision making", "Regulation of body temperature"],
        "correct_option_id": 3,
        "explanation": "The hypothalamus contains the thermoregulatory centre that controls body temperature, among other homeostatic functions.",
    },
    {
        "question": "Which one of the following statements is not correct?",
        "options": ["Retinal is the light absorbing portion of visual photo pigments", "In retina the rods have the photopigment rhodopsin while cones have three different photopigments", "Retinal is a derivative of vitamin C", "Rhodopsin is the purplish red protein present in rods only"],
        "correct_option_id": 2,
        "explanation": "Retinal is actually a derivative of vitamin A, not vitamin C, making this statement incorrect.",
    },
    {
        "question": "Identify the hormone with its correct matching of source and function:",
        "options": ["Oxytocin – posterior pituitary, growth and maintenance of mammary glands", "Melatonin – pineal gland, regulates the normal rhythm of sleep-wake cycle", "Progesterone – corpus – luteum, stimulation of growth and activities of female secondary sex organs", "Atrial natriuretic factor – ventricular wall increases the blood pressure"],
        "correct_option_id": 1,
        "explanation": "Melatonin is secreted by the pineal gland and plays a key role in regulating the body's sleep-wake (circadian) rhythm.",
    },
    {
        "question": "Fight – or – flight reactions cause activation of:",
        "options": ["The parathyroid glands, leading to increased metabolic rate", "The kidney, leading to suppression of renin-angiotensin – aldosterone pathway", "The adrenal medulla, leading to increased secretion of epinephrine and norepinephrine", "The pancreas leading to a reduction in the blood sugar levels"],
        "correct_option_id": 2,
        "explanation": "The adrenal medulla releases epinephrine and norepinephrine during stress, producing the classic \"fight-or-flight\" response.",
    },
    {
        "question": "The shared terminal duct of the reproductive and urinary system in the human male is:",
        "options": ["Urethra", "Ureter", "Vas deferens", "Vasa efferentia"],
        "correct_option_id": 0,
        "explanation": "In the human male, the urethra serves as the common passage for both urine and semen.",
    },
    {
        "question": "The main function of mammalian corpus luteum is to produce:",
        "options": ["Estrogen only", "Progesterone", "Human chorionic gonadotropin", "Relaxin only"],
        "correct_option_id": 1,
        "explanation": "The corpus luteum's primary function is to secrete progesterone, which maintains the uterine lining for potential pregnancy.",
    },
    {
        "question": "Select the correct option describing gonadotropin activity in a normal pregnant female:",
        "options": ["High level of FSH and LH stimulates the thickening of endometrium", "High level of FSH and LH facilitate implantation of the embryo", "High level of hCG stimulates the synthesis of estrogen and progesterone", "High level of hCG stimulates the thickening of endometrium"],
        "correct_option_id": 2,
        "explanation": "hCG secreted by the developing embryo maintains the corpus luteum, stimulating continued secretion of estrogen and progesterone during pregnancy.",
    },
    {
        "question": "Tubectomy is a method of sterilization in which:",
        "options": ["Small part of fallopian tube is removed or tied up", "Ovaries are removed surgically", "Small part of vas deferens is removed or tied up", "Uterus is removed surgically"],
        "correct_option_id": 0,
        "explanation": "Tubectomy involves removing or blocking (tying/cutting) a small part of the fallopian tube in females to prevent fertilization.",
    },
    {
        "question": "Assisted reproductive technology, IVF involves transfer of:",
        "options": ["Ovum into fallopian tube", "Zygote into the fallopian tube", "Zygote into the uterus", "Embryo with 16 blastomeres into the fallopian tube"],
        "correct_option_id": 1,
        "explanation": "In IVF (test tube baby program), the zygote (or early embryo up to 8 blastomeres) formed outside the body is transferred into the fallopian tube (ZIFT).",
    },
    {
        "question": "A man whose father was colour blind marries a woman who had a colour blind mother and normal father. What percentage of male children of this couple will be colour blind?",
        "options": ["25%", "0%", "50%", "75%"],
        "correct_option_id": 2,
        "explanation": "The man is normal (X^A Y) since he inherits Y from his colour-blind father; the woman is an obligate carrier (X^A X^a) since her mother was colour blind. Crossing X^A Y × X^A X^a gives sons: half normal (X^A Y) and half colour blind (X^a Y), i.e., 50%.",
    },
    {
        "question": "In a population of 1000 individuals 360 belong to genotype AA, 480 to Aa, and the remaining 160 to aa. Based on this data, the frequency of allele a in the population is:",
        "options": ["0.4", "0.5", "0.6", "0.7"],
        "correct_option_id": 0,
        "explanation": "q (frequency of a) = (2×160 + 480) / (2×1000) = 800/2000 = 0.4.",
    },
    {
        "question": "A human female with Turner's syndrome:",
        "options": ["Has 45 chromosome with XO", "Has one additional X chromosome", "Exhibits male characters", "Is able to produce children with normal husband"],
        "correct_option_id": 0,
        "explanation": "Turner's syndrome results from monosomy of the X chromosome, giving an individual 45 chromosomes with karyotype XO.",
    },
    {
        "question": "Commonly used vectors for human genome sequencing are:",
        "options": ["T – DNA", "BAC and YAC", "Expression Vectors", "T/A Cloning Vectors"],
        "correct_option_id": 1,
        "explanation": "Bacterial Artificial Chromosomes (BAC) and Yeast Artificial Chromosomes (YAC), which can carry very large DNA inserts, were used to clone and sequence the human genome.",
    },
    {
        "question": "Forelimbs of cat, lizard used in walking, forelimbs of whale used in swimming, and forelimbs of bats used in flying are an example of:",
        "options": ["Analogous organs", "Adaptive radiation", "Homologous organs", "Convergent evolution"],
        "correct_option_id": 2,
        "explanation": "These forelimbs share the same basic bone structure and origin despite different functions, making them homologous organs illustrating divergent evolution.",
    },
    {
        "question": "Which one of the following are analogous structures?",
        "options": ["Wings of Bat and wings of Pigeon", "Gills of Prawn and Lungs of Man", "Thorns of Bougainvillea and Tendrils of Cucurbita", "Flippers of Dolphin and Legs of Horse"],
        "correct_option_id": 0,
        "explanation": "Bat wings and bird wings perform the same function (flight) but arose independently from different structures, making them analogous organs.",
    },
    {
        "question": "At which stage of HIV infection does one usually show symptoms of AIDS?",
        "options": ["Within 15 days of sexual contact with an infected person", "When the infected retro virus enters host cells", "When HIV damages large number of helper T – Lymphocytes", "When the viral DNA is produced by reverse transcriptase"],
        "correct_option_id": 2,
        "explanation": "AIDS symptoms appear once HIV has significantly depleted the number of helper T-lymphocytes, crippling the immune system.",
    },
    {
        "question": "To obtain virus – free healthy plants from a diseased one by tissue culture technique, which part/parts of the diseased plant will be taken?",
        "options": ["Apical meristem only", "Palisade parenchyma", "Both apical and axillary meristem", "Epidermis only"],
        "correct_option_id": 0,
        "explanation": "The apical meristem is generally free of viruses, so culturing it (meristem culture) produces virus-free plants.",
    },
    {
        "question": "What gases are produced in anaerobic sludge digesters?",
        "options": ["Methane and CO2 only", "Methane, Hydrogen, sulphide and CO2", "Methane, Hydrogen sulphide and O2", "Hydrogen sulphide and CO2"],
        "correct_option_id": 1,
        "explanation": "Anaerobic microbial activity in sludge digesters produces a mixture of gases, including methane, hydrogen, hydrogen sulphide, and carbon dioxide (biogas).",
    },
    {
        "question": "Just as a person moving from Delhi to Shimla to escape the heat for the duration of hot summer, thousands of migratory birds from Siberia and other extremely cold northern regions move to:",
        "options": ["Western Ghat", "Meghalaya", "Corbett National Park", "Keoladeo National Park"],
        "correct_option_id": 3,
        "explanation": "Keoladeo National Park (Bharatpur, Rajasthan) is a famous wintering ground for migratory birds arriving from Siberia and other cold regions.",
    },
    {
        "question": "A scrubber in the exhaust of a chemical industrial plant removes:",
        "options": ["Gases like sulphur dioxide", "Particulate matter of the size 5 micrometer or above", "Gases like ozone and methane", "Particulate matter of the size 2.5 micrometer or less"],
        "correct_option_id": 0,
        "explanation": "A scrubber removes gaseous pollutants like sulphur dioxide from industrial exhaust by passing the gas through a water or chemical spray.",
    },
    {
        "question": "If 20 J of energy is trapped at producer level, then how much energy will be available to peacock as food in the following chain? Plant → mice → snake → peacock",
        "options": ["0.02 J", "0.002 J", "0.2 J", "0.0002 J"],
        "correct_option_id": 0,
        "explanation": "Applying the 10% law across three trophic transfers: 20 × 0.1 × 0.1 × 0.1 = 0.02 J available to the peacock.",
    },
]
