"""
Question bank: NEET 2025 (Code 45) - Biology (Solved Answers).

75 questions parsed from NEET 2025 (Code 45)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "The complex II of mitochondrial electron transport chain is also known as",
        "options": ["Cytochrome bc1", "Succinate dehydrogenase", "Cytochrome c oxidase", "NADH dehydrogenase"],
        "correct_option_id": 1,
        "explanation": "Complex II of the ETC is the succinate dehydrogenase complex, which oxidizes succinate to fumarate and feeds electrons into the chain via FADH2.",
    },
    {
        "question": "Polymerase chain reaction (PCR) amplifies DNA following the equation",
        "options": ["N^2", "2^n", "2n + 1", "2N^2"],
        "correct_option_id": 1,
        "explanation": "Each PCR cycle doubles the number of DNA copies, so after n cycles the DNA is amplified 2^n fold.",
    },
    {
        "question": "What are the potential drawbacks in adoption of the IVF method? (NEET 2025) A. High fatality risk to mother B. Expensive instruments and reagents C. Husband/wife necessary for being donors D. Less adoption of orphans E. Not available in India F. Possibility that the early embryo does not survive",
        "options": ["B, D, F only", "A, C, D, F only", "A, B, C, D only", "A, B, C, E, F only"],
        "correct_option_id": 0,
        "explanation": "IVF is expensive (needs costly instruments/reagents), reduces incentive for adopting orphans, and carries the risk that the early embryo transferred may not survive/implant.",
    },
    {
        "question": "What is the name of the blood vessel that carries deoxygenated blood from the body to the heart in a frog?",
        "options": ["Aorta", "Pulmonary artery", "Pulmonary vein", "Vena cava"],
        "correct_option_id": 3,
        "explanation": "The vena cavae (anterior and posterior) collect deoxygenated blood from the body and return it to the sinus venosus/right atrium of the frog's heart.",
    },
    {
        "question": "Which one of the following statements refers to Reductionist Biology?",
        "options": ["Physico-chemical approach to study and understand living organisms", "Physiological approach to study and understand living organisms", "Chemical approach to study and understand living organisms", "Behavioural approach to study and understand living organisms"],
        "correct_option_id": 0,
        "explanation": "Reductionist biology explains living systems and their properties in terms of physics and chemistry, i.e., a physico-chemical approach.",
    },
    {
        "question": "Given below are two statements: (NEET 2025) Statement I: In the RNA world, RNA is considered the first genetic material evolved to carry out essential life processes. RNA acts as a genetic material and also as a catalyst for some important biochemical reactions in living systems. Being reactive, RNA is unstable. Statement II: DNA evolved from RNA and is a more stable genetic material. Its double helical strands being complementary, resist changes by evolving repairing mechanism.",
        "options": ["Both statement I and statement II are correct", "Both statement I and statement II are incorrect", "Statement I is correct but statement II is incorrect", "Statement II is incorrect but statement I is correct"],
        "correct_option_id": 0,
        "explanation": "Both statements accurately describe the RNA-world hypothesis and the subsequent evolutionary transition to the more stable, repairable DNA as genetic material.",
    },
    {
        "question": "Epiphytes that are growing on a mango branch is an example of which of the following?",
        "options": ["Commensalism", "Mutualism", "Predation", "Amensalism"],
        "correct_option_id": 0,
        "explanation": "The epiphyte benefits by getting support/space while the mango tree is neither helped nor harmed, which is the definition of commensalism.",
    },
    {
        "question": "From the statements given below choose the correct option: (NEET 2025) A. The eukaryotic ribosomes are 80S and prokaryotic ribosomes are 70S. B. Each ribosome has two sub-units. C. The two sub-units of 80S ribosome are 60S and 40S while that of 70S are 50S and 30S. D. The two sub-units of 80S ribosome are 60S and 20S and that of 70S are 50S and 20S. E. The two sub-units of 80S are 60S and 30S and that of 70S are 50S and 30S.",
        "options": ["A, B, C are true", "A, B, D are true", "A, B, E are true", "B, D, E are true"],
        "correct_option_id": 0,
        "explanation": "Eukaryotic ribosomes (80S) are made of 60S and 40S subunits, and prokaryotic ribosomes (70S) are made of 50S and 30S subunits.",
    },
    {
        "question": "Which one of the following is an example of ex-situ conservation?",
        "options": ["National Park", "Wildlife Sanctuary", "Zoos and botanical gardens", "Protected areas"],
        "correct_option_id": 2,
        "explanation": "Ex-situ conservation involves protecting species outside their natural habitat, as done in zoos, botanical gardens, and gene banks.",
    },
    {
        "question": "Given below are two statements: (NEET 2025) Statement I: The primary source of energy in an ecosystem is solar energy. Statement II: The rate of production of organic matter during photosynthesis in an ecosystem is called net primary productivity (NPP).",
        "options": ["Both statement I and statement II are correct", "Both statement I and statement II are incorrect", "Statement I is correct but statement II is incorrect", "Statement I is incorrect but statement II is correct"],
        "correct_option_id": 0,
        "explanation": "Solar energy is indeed the primary energy source for ecosystems, and NPP is correctly defined as the rate of organic matter production during photosynthesis.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion (A) and the other is labelled as Reason (R). (NEET 2025) Assertion (A): Both wind and water pollinated flowers are not very colourful and do not produce nectar. Reason (R): The flowers produce enormous amount of pollen grains in wind and water pollinated flowers.",
        "options": ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is NOT the correct explanation of A", "A is true but R is false", "A is false but R is true"],
        "correct_option_id": 1,
        "explanation": "Both statements are individually true, but the large pollen output is not the reason wind/water-pollinated flowers lack colour and nectar — that is because they don't need to attract pollinators.",
    },
    {
        "question": "Which of the following is an example of non-distilled alcoholic beverage produced by yeast?",
        "options": ["Whisky", "Brandy", "Beer", "Rum"],
        "correct_option_id": 2,
        "explanation": "Beer is produced by fermentation without distillation, unlike whisky, brandy, and rum which undergo distillation.",
    },
    {
        "question": "Given below are two statements: (NEET 2025) Statement I: In a floral formula ⊕ stands for zygomorphic nature of the flower, and G (underlined) stands for inferior ovary. Statement II: In a floral formula ⊕ stands for actinomorphic nature of the flower and G (underlined) stands for superior ovary.",
        "options": ["Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect", "Statement I is incorrect but Statement II is correct"],
        "correct_option_id": 3,
        "explanation": "By convention, ⊕ denotes an actinomorphic (regular) flower, and the position of the line under/over G denotes ovary position — Statement II correctly represents this convention.",
    },
    {
        "question": "Streptokinase produced by bacterium Streptococcus is used for",
        "options": ["Curd production", "Ethanol production", "Liver disease treatment", "Removing clots from blood vessels"],
        "correct_option_id": 3,
        "explanation": "Streptokinase, modified by genetic engineering, is used as a clot-buster drug to dissolve blood clots in patients who have suffered a heart attack.",
    },
    {
        "question": "Which chromosome in the human genome has the highest number of genes?",
        "options": ["Chromosome X", "Chromosome Y", "Chromosome 1", "Chromosome 10"],
        "correct_option_id": 2,
        "explanation": "Chromosome 1 is the largest human chromosome and carries the highest number of genes.",
    },
    {
        "question": "Which of the following statement is correct about location of the male frog copulatory pad?",
        "options": ["First and Second digit of fore limb", "First digit of hind limb", "Second digit of fore limb", "First digit of the fore limb"],
        "correct_option_id": 3,
        "explanation": "Male frogs develop a copulatory (nuptial) pad on the first digit of the forelimb, used for clasping the female during amplexus.",
    },
    {
        "question": "Which one of the following phytohormones promotes nutrient mobilization which helps in the delay of leaf senescence in plants?",
        "options": ["Ethylene", "Abscisic acid", "Gibberellin", "Cytokinin"],
        "correct_option_id": 3,
        "explanation": "Cytokinins promote nutrient mobilization towards the site of application and delay leaf senescence.",
    },
    {
        "question": "While trying to find out the characteristic of a newly found animal, a researcher did the histology of adult animal and observed a cavity with presence of mesodermal tissue towards the body wall but no mesodermal tissue was observed towards the alimentary canal. What could be the possible coelome of that animal?",
        "options": ["Acoelomate", "Pseudocoelomate", "Schizocoelomate", "Spongocoelomate"],
        "correct_option_id": 1,
        "explanation": "A body cavity lined by mesoderm only on the body-wall side (not around the gut) is a pseudocoel, characteristic of pseudocoelomate animals like Aschelminthes.",
    },
    {
        "question": "Given below are the stages in the life cycle of pteridophytes. Arrange the following stages in the correct sequence. (NEET 2025) A. Prothallus stage B. Meiosis in spore mother cells C. Fertilisation D. Formation of archegonia and antheridia in gametophyte. E. Transfer of antherozoids to the archegonia in presence of water.",
        "options": ["B, A, D, E, C", "B, A, E, C, D", "D, E, C, A, B", "E, D, C, B, A"],
        "correct_option_id": 0,
        "explanation": "The sequence follows: meiosis produces spores (B) → spores germinate into a prothallus (A) → sex organs develop on it (D) → antherozoids swim to archegonia in water (E) → fertilisation occurs (C).",
    },
    {
        "question": "Cardiac activities of the heart are regulated by: (NEET 2025) A. Nodal tissue B. A special neural centre in the medulla oblongata C. Adrenal medullary hormones D. Adrenal cortical hormones",
        "options": ["A, B and C Only", "A, B, C and D", "A, C and D Only", "A, B and D Only"],
        "correct_option_id": 0,
        "explanation": "Cardiac activity is regulated intrinsically by the nodal tissue (SA node), and extrinsically by a neural centre in the medulla oblongata and by adrenal medullary hormones (adrenaline) — not by adrenal cortical hormones.",
    },
    {
        "question": "Which of the following organisms cannot fix nitrogen? (NEET 2025) A. Azotobacter B. Oscillatoria C. Anabaena D. Volvox E. Nostoc",
        "options": ["A only", "D only", "B only", "E only"],
        "correct_option_id": 1,
        "explanation": "Azotobacter, Oscillatoria, Anabaena, and Nostoc are all nitrogen fixers, whereas Volvox is a colonial green alga with no nitrogen-fixing ability.",
    },
    {
        "question": "Given below are two statements: (NEET 2025) Statement I: Transfer RNAs and ribosomal RNA do not interact with mRNA. Statement II: RNA interference (RNAi) takes place in all eukaryotic organisms as a method of cellular defence.",
        "options": ["Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect", "Statement I is incorrect but Statement II is correct"],
        "correct_option_id": 3,
        "explanation": "Statement I is false since tRNA (via anticodon) and rRNA (as part of ribosomes) do interact with mRNA during translation; RNAi is indeed found widely across eukaryotes as a defence mechanism.",
    },
    {
        "question": "Which of the following genetically engineered organisms was used by Eli Lilly to prepare human insulin?",
        "options": ["Bacterium", "Yeast", "Virus", "Phage"],
        "correct_option_id": 0,
        "explanation": "Eli Lilly used a genetically engineered strain of the bacterium E. coli to produce the two insulin chains, which were then combined to form human insulin.",
    },
    {
        "question": "Name the class of enzyme that usually catalyze the following reaction: S-G + S# → S + S#-G",
        "options": ["Hydrolase", "Lyase", "Transferase", "Ligase"],
        "correct_option_id": 2,
        "explanation": "This reaction transfers a group (G) from one substrate to another, which is the defining activity of transferase enzymes.",
    },
    {
        "question": "Find the statement that is NOT correct with regard to the structure of monocot stem.",
        "options": ["Hypodermis is parenchymatous.", "Vascular bundles are scattered.", "Vascular bundles are conjoint and closed.", "Phloem parenchyma is absent."],
        "correct_option_id": 0,
        "explanation": "In monocot stems, the hypodermis is typically sclerenchymatous (for mechanical support), not parenchymatous.",
    },
    {
        "question": "The correct sequence of events in the life cycle of bryophytes is (NEET 2025) A. Fusion of antherozoid with egg. B. Attachment of gametophyte to substratum. C. Reduction division to produce haploid spores. D. Formation of sporophyte. E. Release of antherozoids into water.",
        "options": ["D, E, A, C, B", "B, E, A, C, D", "B, E, A, D, C", "D, E, A, B, C"],
        "correct_option_id": 2,
        "explanation": "The gametophyte first attaches to the substratum (B), releases antherozoids into water (E), fertilisation occurs (A), sporophyte forms (D), and finally meiosis in the sporophyte produces haploid spores (C).",
    },
    {
        "question": "Which are correct: (NEET 2025) A. Computed tomography and magnetic resonance imaging detect cancers of internal organs. B. Chemotherapeutics drugs are used to kill non-cancerous cells. C. α-interferon activate the cancer patients' immune system and helps in destroying the tumour. D. Chemotherapeutic drugs are biological response modifiers. E. In the case of leukaemia blood cell counts are decreased.",
        "options": ["B and D only", "D and E only", "C and D only", "A and C only"],
        "correct_option_id": 3,
        "explanation": "CT/MRI are used to detect internal tumours, and alpha-interferon boosts the immune system to help destroy tumour cells; chemotherapy targets cancerous (not non-cancerous) cells, biological response modifiers are a separate category, and leukaemia is marked by increased (not decreased) abnormal WBC counts.",
    },
    {
        "question": "Find the correct statements: (NEET 2025) A. In human pregnancy, the major organ systems are formed at the end of 12 weeks. B. In human pregnancy the major organ systems are formed at the end of 8 weeks. C. In human pregnancy heart is formed after one month of gestation. D. In human pregnancy, limbs and digits develop by the end of second month. E. In human pregnancy the appearance of hair is usually observed in the fifth month.",
        "options": ["A and E Only", "B and C Only", "B, C, D and E Only", "A, C, D and E Only"],
        "correct_option_id": 3,
        "explanation": "Major organ systems are formed by the end of the 12th week (first trimester); the heart begins functioning after about a month; limbs/digits develop by the second month; and hair appearance is typically noted around the fifth month.",
    },
    {
        "question": "In the seeds of cereals, the outer covering of endosperm separates the embryo by a protein-rich layer called:",
        "options": ["Coleoptile", "Coleorhiza", "Integument", "Aleurone layer"],
        "correct_option_id": 3,
        "explanation": "The aleurone layer is the protein-rich outer layer of the endosperm that separates it from the embryo in cereal grains.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion (A) and the other is labelled as Reason (R). (NEET 2025) Assertion (A): A typical unfertilised, angiosperm embryo sac at maturity is 8 nucleate and 7-celled. Reason (R): The egg apparatus has 2 polar nuclei.",
        "options": ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is NOT the correct explanation of A", "A is true but R is false", "A is false but R is true"],
        "correct_option_id": 2,
        "explanation": "The 8-nucleate, 7-celled embryo sac description is correct, but the egg apparatus consists of the egg cell and two synergids — the polar nuclei belong to the central cell, not the egg apparatus.",
    },
    {
        "question": "A specialised membranous structure in a prokaryotic cell which helps in cell wall formation, DNA replication and respiration is:",
        "options": ["Mesosome", "Chromatophores", "Cristae", "Endoplasmic Reticulum"],
        "correct_option_id": 0,
        "explanation": "Mesosomes are infoldings of the plasma membrane in bacteria that assist in cell wall formation, DNA replication and segregation, and respiration.",
    },
    {
        "question": "Which of the following are the post-transcriptional events in an eukaryotic cell? (NEET 2025) A. Transport of pre-mRNA to cytoplasm prior to splicing. B. Removal of introns and joining of exons. C. Addition of methyl group at 5' end of hnRNA. D. Addition of adenine residues at 3' end of hnRNA. E. Base pairing of two complementary RNAs.",
        "options": ["A, B, C only", "B, C, D only", "B, C, E only", "C, D, E only"],
        "correct_option_id": 1,
        "explanation": "Post-transcriptional processing of hnRNA into mature mRNA involves splicing (removal of introns/joining exons), 5' capping, and 3' polyadenylation; pre-mRNA is spliced before export, not transported prior to splicing.",
    },
    {
        "question": "What is the pattern of inheritance for polygenic trait?",
        "options": ["Mendelian inheritance pattern", "Non-mendelian inheritance pattern", "Autosomal dominant pattern", "X-linked recessive inheritance pattern"],
        "correct_option_id": 1,
        "explanation": "Polygenic traits (like human skin colour or height) are controlled by multiple genes and show continuous variation, which is a non-Mendelian inheritance pattern.",
    },
    {
        "question": "Which one of the following enzymes contains 'Haem' as the prosthetic group?",
        "options": ["RuBisCo", "Carbonic anhydrase", "Succinate dehydrogenase", "Catalase"],
        "correct_option_id": 3,
        "explanation": "Catalase is a haem-containing enzyme that breaks down hydrogen peroxide into water and oxygen.",
    },
    {
        "question": "Each of the following characteristics represent a Kingdom proposed by Whittaker. Arrange the following in increasing order of complexity of body organization. (NEET 2025) A. Multicellular heterotrophs with cell wall made of chitin. B. Heterotrophs with tissue/organ/organ system level of body organization. C. Prokaryotes with cell wall made of polysaccharides and amino acids. D. Eukaryotic autotrophs with tissue/organ level of body organization. E. Eukaryotes with cellular body organization.",
        "options": ["A, C, E, B, D", "C, E, A, D, B", "A, C, E, D, B", "C, E, A, B, D"],
        "correct_option_id": 1,
        "explanation": "In increasing complexity: Monera (C, prokaryotic) → Protista (E, single-celled eukaryotes) → Fungi (A, multicellular with chitin walls) → Plantae (D, tissue-level autotrophs) → Animalia (B, organ-system level heterotrophs).",
    },
    {
        "question": "Who is known as the father of Ecology in India?",
        "options": ["S. R. Kashyap", "Ramdeo Misra", "Ram Udar", "Birbal Sahni"],
        "correct_option_id": 1,
        "explanation": "Prof. Ramdeo Misra is widely recognized as the father of Ecology in India for his pioneering work in the field.",
    },
    {
        "question": "Neoplastic characteristics of cells refer to: (NEET 2025) A. A mass of proliferating cell B. Rapid growth of cells C. Invasion and damage to the surrounding tissue D. Those confined to original location",
        "options": ["A, B only", "A, B, C only", "A, B, D only", "B, C, D only"],
        "correct_option_id": 1,
        "explanation": "Neoplastic (tumour) cells are characterized by uncontrolled proliferation forming a mass, rapid growth, and (in malignant cases) invasion of surrounding tissue.",
    },
    {
        "question": "Given below are two statements: (NEET 2025) Statement I: The DNA fragments extracted from gel electrophoresis can be used in construction of recombinant DNA. Statement II: Smaller size DNA fragments are observed near anode while larger fragments are found near the wells in an agarose gel.",
        "options": ["Both statement I and statement II are correct", "Both statement I and statement II are incorrect", "Statement I is correct but statement II is incorrect", "Statement I is incorrect but statement II is correct"],
        "correct_option_id": 0,
        "explanation": "DNA fragments eluted from gels are indeed used to construct recombinant DNA; and since DNA is negatively charged, smaller fragments migrate faster toward the anode, staying farther from the wells than larger fragments.",
    },
    {
        "question": "Consider the following: (NEET 2025) A. The reductive division for the human female gametogenesis starts earlier than that of the male gametogenesis. B. The gap between the first meiotic division and the second meiotic division is much shorter for males compared to females. C. The first polar body is associated with the formation of the primary oocyte. D. Luteinizing Hormone (LH) surge leads to disintegration of the endometrium and onset of menstrual bleeding.",
        "options": ["A and B are true", "A and C are true", "B and D are true", "B and C are true"],
        "correct_option_id": 0,
        "explanation": "Meiosis begins during fetal life in females (much earlier than in males, where it starts at puberty), and in females meiosis I is arrested for years, so the gap between meiotic divisions is far shorter in males; the polar body forms after meiosis I from the secondary oocyte (not during primary oocyte formation), and menstruation is triggered by hormone decline, not the LH surge.",
    },
    {
        "question": "All living members of the class Cyclostomata are:",
        "options": ["Free living", "Endoparasite", "Symbiotic", "Ectoparasite"],
        "correct_option_id": 3,
        "explanation": "Living cyclostomes (like lampreys and hagfish) are ectoparasites/scavengers that attach to and feed on other fish externally.",
    },
    {
        "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R). (NEET 2025) Assertion (A): The primary function of the Golgi apparatus is to package the materials made by the endoplasmic reticulum and deliver it to intracellular targets and outside the cell. Reason (R): Vesicles containing materials made by the endoplasmic reticulum fuse with the cis face of the Golgi apparatus, and they are modified and released from the trans face of the Golgi apparatus.",
        "options": ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"],
        "correct_option_id": 0,
        "explanation": "Both statements correctly describe the Golgi apparatus's role in packaging and processing materials, with vesicle traffic moving from the cis to the trans face.",
    },
    {
        "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R). (NEET 2025) Assertion (A): All vertebrates are chordates but all chordates are not vertebrate. Reason (R): The members of subphylum vertebrata possess notochord during the embryonic period, the notochord is replaced by a cartilaginous or bony vertebral column in adults.",
        "options": ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is not the correct explanation of A", "A is true but R is false", "A is false but R is true"],
        "correct_option_id": 0,
        "explanation": "Vertebrata is a subphylum of Chordata, so all vertebrates are chordates, but the reverse isn't true; the reason correctly explains why vertebrates are a distinct, more advanced subgroup.",
    },
    {
        "question": "Identify the statement that is NOT correct.",
        "options": ["Each antibody has two light and two heavy chains.", "The heavy and light chains are held together by disulfide bonds.", "Antigen binding site is located at C-terminal region of antibody molecules.", "Constant region of heavy and light chains are located at C-terminus of antibody molecules."],
        "correct_option_id": 2,
        "explanation": "The antigen-binding site is located at the N-terminal variable region of the antibody, not the C-terminal region.",
    },
    {
        "question": "Silencing of specific mRNA is possible via RNAi because of -",
        "options": ["Complementary dsRNA", "Inhibitory ssRNA", "Complementary tRNA", "Non-complementary ssRNA"],
        "correct_option_id": 0,
        "explanation": "RNAi uses double-stranded RNA complementary to the target mRNA, which triggers its degradation and silences gene expression.",
    },
    {
        "question": "Genes R and Y follow independent assortment. If RRYY produce round yellow seeds and rryy produce wrinkled green seeds, what will be the phenotypic ratio of the F2 generation?",
        "options": ["Phenotypic ratio - 1 : 2 : 1", "Phenotypic ratio - 3 : 1", "Phenotypic ratio - 9 : 3 : 3 : 1", "Phenotypic ratio - 9 : 7"],
        "correct_option_id": 2,
        "explanation": "This is a standard dihybrid cross; independent assortment of two genes gives the classic 9:3:3:1 phenotypic ratio in F2.",
    },
    {
        "question": "Histones are enriched with -",
        "options": ["Lysine & Arginine", "Leucine & Lysine", "Phenylalanine & Leucine", "Phenylalanine & Arginine"],
        "correct_option_id": 0,
        "explanation": "Histones are rich in the basic amino acids lysine and arginine, which give them a positive charge to bind the negatively charged DNA.",
    },
    {
        "question": "The first menstruation is called:",
        "options": ["Menopause", "Menarche", "Diapause", "Ovulation"],
        "correct_option_id": 1,
        "explanation": "Menarche refers to the onset of the first menstrual cycle at puberty.",
    },
    {
        "question": "The protein portion of an enzyme is called:",
        "options": ["Cofactor", "Coenzyme", "Apoenzyme", "Prosthetic group"],
        "correct_option_id": 2,
        "explanation": "The protein component of an enzyme (without its non-protein cofactor) is called the apoenzyme.",
    },
    {
        "question": "Which of the following is the unit of productivity of an Ecosystem?",
        "options": ["gm^-2", "KCal m^-2", "KCal m^-3", "(KCal m^-2) yr^-1"],
        "correct_option_id": 3,
        "explanation": "Productivity is expressed as the amount of energy fixed per unit area per unit time, i.e., KCal m^-2 yr^-1.",
    },
    {
        "question": "Sweet potato and potato represent a certain type of evolution. Select the correct combination of terms to explain the evolution.",
        "options": ["Analogy, convergent", "Homology, divergent", "Homology, convergent", "Analogy, divergent"],
        "correct_option_id": 0,
        "explanation": "Sweet potato (root modification) and potato (stem modification) perform a similar function (storage) despite different origins, making them analogous structures resulting from convergent evolution.",
    },
    {
        "question": "Given below are two statements: One is labelled as Assertion (A) and the other is labelled as Reason (R). (NEET 2025) Assertion (A): Cells of the tapetum possess dense cytoplasm and generally have more than one nucleus. Reason (R): Presence of more than one nucleus in the tapetum increases the efficiency of nourishing the developing microspore mother cells.",
        "options": ["Both A and R are true and R is the correct explanation of A", "Both A and R are true but R is NOT the correct explanation of A", "A is true but R is false", "A is false but R is true"],
        "correct_option_id": 0,
        "explanation": "The tapetum is a nutritive layer with dense cytoplasm and often multiple nuclei, and this multinucleate condition helps it efficiently nourish the developing pollen/microspores.",
    },
    {
        "question": "How many meiotic and mitotic divisions need to occur for the development of a mature female gametophyte from the megaspore mother cell in an angiosperm plant?",
        "options": ["2 Meiosis and 3 Mitosis", "1 Meiosis and 3 Mitosis", "1 Meiosis and 3 Mitosis", "No Meiosis and 2 Mitosis"],
        "correct_option_id": 1,
        "explanation": "The megaspore mother cell undergoes one meiotic division to form four haploid megaspores; the functional megaspore then undergoes three successive mitotic divisions to form the 8-nucleate embryo sac.",
    },
    {
        "question": "Which of the following is an example of a zygomorphic flower?",
        "options": ["Petunia", "Datura", "Pea", "Chilli"],
        "correct_option_id": 2,
        "explanation": "Pea flowers can be divided into equal halves only along one plane, making them zygomorphic (bilaterally symmetrical).",
    },
    {
        "question": "After maturation, in primary lymphoid organs, the lymphocytes migrate for interaction with antigens to secondary lymphoid organ(s)/tissue(s) like: (NEET 2025) A. thymus B. bone marrow C. spleen D. lymph nodes E. Peyer's patches",
        "options": ["B, C, D only", "A, B, C only", "E, A, B only", "C, D, E only"],
        "correct_option_id": 3,
        "explanation": "Thymus and bone marrow are primary lymphoid organs (where lymphocytes mature), while spleen, lymph nodes, and Peyer's patches are secondary lymphoid organs where lymphocytes encounter antigens.",
    },
    {
        "question": "Given below are two statements: (NEET 2025) Statement I: Fig fruit is a non-vegetarian fruit as it has enclosed fig wasps in it. Statement II: Fig wasp and fig tree exhibit mutual relationship as fig wasp completes its life cycle in fig fruit and fig fruit gets pollinated by fig wasp.",
        "options": ["Both statement I and statement II are correct", "Both statement I and statement II are incorrect", "Statement I is correct but statement II is incorrect", "Statement I is incorrect but statement II is correct"],
        "correct_option_id": 0,
        "explanation": "The fig-fig wasp relationship is a classic example of obligate mutualism: the wasp completes its life cycle inside the fig, and in return pollinates the flowers, giving rise to the popular notion of fig as a \"non-vegetarian\" fruit.",
    },
    {
        "question": "What is the main function of the spindle fibers during mitosis?",
        "options": ["To separate the chromosomes", "To synthesize new DNA", "To repair damaged DNA", "To regulate cell growth"],
        "correct_option_id": 0,
        "explanation": "Spindle fibers attach to chromosomes at the kinetochore and pull the sister chromatids apart to opposite poles during anaphase.",
    },
    {
        "question": "Which one of the following is the characteristic feature of gymnosperms?",
        "options": ["Seeds are enclosed in fruits.", "Seeds are naked.", "Seeds are absent.", "Gymnosperms have flowers for reproduction."],
        "correct_option_id": 1,
        "explanation": "Gymnosperms bear \"naked\" seeds, i.e., seeds not enclosed within a fruit, distinguishing them from angiosperms.",
    },
    {
        "question": "Consider the following statements regarding function of adrenal medullary hormones: (NEET 2025) A. It causes pupillary constriction B. It is a hyperglycemic hormone C. It causes piloerection D. It increases strength of heart contraction",
        "options": ["C and D Only", "B, C and D Only", "A, C and D Only", "D Only"],
        "correct_option_id": 1,
        "explanation": "Adrenal medullary hormones (adrenaline/noradrenaline) raise blood glucose (hyperglycemic), cause piloerection, and increase the strength of heart contraction; they cause pupil dilation, not constriction.",
    },
    {
        "question": "Why can't insulin be given orally to diabetic patients?",
        "options": ["Human body will elicit strong immune response", "It will be digested in Gastro-Intestinal (GI) tract", "Because of structural variation", "Its bioavailability will be increased"],
        "correct_option_id": 1,
        "explanation": "Insulin is a protein, so if taken orally, it would be broken down by digestive proteases in the GI tract before it could act, hence it must be injected.",
    },
    {
        "question": "Who proposed that the genetic code for amino acids should be made up of three nucleotides?",
        "options": ["George Gamow", "Francis Crick", "Jacque Monod", "Franklin Stahl"],
        "correct_option_id": 0,
        "explanation": "George Gamow first theoretically proposed that a triplet code (three nucleotides per amino acid) was needed to encode all 20 amino acids.",
    },
    {
        "question": "Which of the following hormones released from the pituitary is actually synthesized in the hypothalamus?",
        "options": ["Luteinizing hormone (LH)", "Anti-diuretic hormone (ADH)", "Follicle-stimulating hormone (FSH)", "Adenocorticotrophic hormone (ACTH)"],
        "correct_option_id": 1,
        "explanation": "ADH (and oxytocin) is synthesized by hypothalamic neurons and merely stored/released from the posterior pituitary, unlike LH, FSH, and ACTH which are synthesized in the anterior pituitary itself.",
    },
    {
        "question": "Role of the water vascular system in Echinoderms is: (NEET 2025) A. Respiration and Locomotion B. Excretion and Locomotion C. Capture and transport of food D. Digestion and Respiration E. Digestion and Excretion",
        "options": ["A and B Only", "A and C Only", "B and C Only", "B, D and E Only"],
        "correct_option_id": 1,
        "explanation": "The water vascular system (with tube feet) in echinoderms functions in locomotion, respiration, and capture/transport of food.",
    },
    {
        "question": "Which of the following type of immunity is present at the time of birth and is a non-specific type of defence in the human body?",
        "options": ["Acquired Immunity", "Innate Immunity", "Cell-mediated Immunity", "Humoral Immunity"],
        "correct_option_id": 1,
        "explanation": "Innate immunity is the non-specific defence system present from birth, comprising physical, physiological, cellular, and cytokine barriers.",
    },
    {
        "question": "In bryophytes, the gemmae help in which one of the following?",
        "options": ["Sexual reproduction", "Asexual reproduction", "Nutrient absorption", "Gaseous exchange"],
        "correct_option_id": 1,
        "explanation": "Gemmae are multicellular, asexual reproductive structures found in gemma cups that detach and grow into new plants, i.e., a mode of vegetative/asexual reproduction.",
    },
    {
        "question": "In frog, the Renal portal system is a special venous connection that acts to link:",
        "options": ["Liver and intestine", "Liver and kidney", "Kidney and intestine", "Kidney and lower part of body"],
        "correct_option_id": 3,
        "explanation": "The renal portal system in frogs carries deoxygenated blood from the lower body/hind limbs to the kidneys before it returns to the heart.",
    },
    {
        "question": "Given below are two statements: (NEET 2025) Statement I: In ecosystem, there is unidirectional flow of energy of sun from producers to consumers. Statement II: Ecosystems are exempted from 2nd law of thermodynamics.",
        "options": ["Both statement I and statement II are correct", "Both statement I and statement II are incorrect", "Statement I is correct but statement II is incorrect", "Statement I is incorrect but statement II is correct"],
        "correct_option_id": 2,
        "explanation": "Energy flow in an ecosystem is indeed unidirectional (sun to producers to consumers), but ecosystems still obey the laws of thermodynamics, including the second law; they are not exempt from it.",
    },
    {
        "question": "Which of the following statements about RuBisCO is true?",
        "options": ["It is active only in the dark.", "It has higher affinity for oxygen than carbon dioxide.", "It is an enzyme involved in the photolysis of water.", "It catalyzes the carboxylation of RuBP."],
        "correct_option_id": 3,
        "explanation": "RuBisCO catalyzes the carboxylation of ribulose-1,5-bisphosphate (RuBP) with CO2 as the first step of the Calvin cycle (it also catalyzes oxygenation, but with lower affinity for O2 than CO2).",
    },
    {
        "question": "Which of the following enzyme(s) are NOT essential for gene cloning? (NEET 2025) A. Restriction enzymes B. DNA ligase C. DNA mutase D. DNA recombinase E. DNA polymerase",
        "options": ["C and D only", "A and B only", "D and E only", "B and C only"],
        "correct_option_id": 0,
        "explanation": "Restriction enzymes, DNA ligase, and DNA polymerase are all essential tools for gene cloning, whereas DNA mutase and DNA recombinase are not standard/essential enzymes used in the process.",
    },
    {
        "question": "Read the following statements on plant growth and development. (NEET 2025) A. Parthenocarpy can be induced by auxins. B. Plant growth regulators can be involved in promotion as well as inhibition of growth. C. Dedifferentiation is a pre-requisite for re-differentiation. D. Abscisic acid is a plant growth promoter. E. Apical dominance promotes the growth of lateral buds.",
        "options": ["A, B, C only", "A, C, E only", "A, D, E only", "B, D, E only"],
        "correct_option_id": 0,
        "explanation": "Auxins can induce fruit development without fertilisation (parthenocarpy); PGRs can both promote and inhibit growth; and dedifferentiated cells must form first before they can re-differentiate. ABA is actually a growth inhibitor, and apical dominance suppresses (not promotes) lateral bud growth.",
    },
    {
        "question": "Which factor is important for termination of transcription?",
        "options": ["α (alpha)", "σ (sigma)", "ρ (rho)", "γ (gamma)"],
        "correct_option_id": 2,
        "explanation": "The rho (ρ) factor is required for termination of transcription at rho-dependent terminators in prokaryotes, while sigma factor is involved in initiation.",
    },
    {
        "question": "Frogs respire in water by skin and buccal cavity, and on land by skin, buccal cavity and lungs. Choose the correct answer from the following:",
        "options": ["The statement is true for water but false for land", "The statement is true for both the environment", "The statement is false for water but true for land", "The statement is false for both the environment"],
        "correct_option_id": 1,
        "explanation": "Frogs use cutaneous (skin) and buccal respiration in water, and additionally use their lungs when on land, making the statement true for both environments.",
    },
    {
        "question": "Twins are born to a family that lives next door to you. The twins are a boy and a girl. Which of the following must be true?",
        "options": ["They are monozygotic twins.", "They are fraternal twins.", "They were conceived through in vitro fertilization.", "They have 75% identical genetic content."],
        "correct_option_id": 1,
        "explanation": "Monozygotic (identical) twins are always the same sex, so a boy-girl twin pair must be dizygotic/fraternal twins, arising from two separately fertilized eggs.",
    },
    {
        "question": "Which of the following microbes is NOT involved in the preparation of household products? (NEET 2025) A. Aspergillus niger B. Lactobacillus C. Trichoderma polysporum D. Saccharomyces cerevisiae E. Propionibacterium sharmanii",
        "options": ["A and B only", "A and C only", "C and D only", "C and E only"],
        "correct_option_id": 1,
        "explanation": "Lactobacillus (curd), Saccharomyces cerevisiae (bread/beverages), and Propionibacterium sharmanii (Swiss cheese) are used in household/food products, whereas Aspergillus niger (citric acid) and Trichoderma polysporum (cyclosporin A drug) are used for industrial/pharmaceutical purposes, not household products.",
    },
    {
        "question": "The blue and white selectable markers have been developed which differentiate recombinant colonies from non-recombinant colonies on the basis of their ability to produce colour in the presence of a chromogenic substrate. Given below are two statements about this method: (NEET 2025) Statement I: The blue coloured colonies have DNA insert in the plasmid and they are identified as recombinant colonies. Statement II: The colonies without blue colour have DNA insert in the plasmid and are identified as recombinant colonies.",
        "options": ["Both Statement I and Statement II are correct", "Both Statement I and Statement II are incorrect", "Statement I is correct but Statement II is incorrect", "Statement I is incorrect but Statement II is correct"],
        "correct_option_id": 3,
        "explanation": "Insertion of foreign DNA disrupts the lacZ gene (insertional inactivation), so colonies with the insert stay white, while blue colonies (without insert) indicate non-recombinants — meaning white colonies are the recombinant ones.",
    },
    {
        "question": "Which one of the following equations represents the Verhulst-Pearl Logistic Growth of population?",
        "options": ["dN/dt = r(K-N)/K", "dN/dt = rN(K-N)/K", "dN/dt = rN(N-K)/N", "dN/dt = N(r-K)/K"],
        "correct_option_id": 1,
        "explanation": "The Verhulst-Pearl logistic growth equation is dN/dt = rN(K-N)/K, where population growth slows as N approaches the carrying capacity K.",
    },
]
