"""
Question bank: AIPMT 2012 (Code D) - Biology (Solved Answers).

88 questions parsed from AIPMT 2012 (Code D)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Motile zygote of Plasmodium occurs in:",
        "options": ["Gut of female Anopheles", "Salivary glands of Anopheles", "Human RBCs", "Human liver"],
        "correct_option_id": 0,
        "explanation": "The ookinete (motile zygote) forms after fertilization inside the mosquito's gut.",
    },
    {
        "question": "The human hind brain comprises three parts, one of which is:",
        "options": ["Spinal cord", "Corpus callosum", "Cerebellum", "Hypothalamus"],
        "correct_option_id": 2,
        "explanation": "Hindbrain consists of medulla, pons, and cerebellum.",
    },
    {
        "question": "Which part of the human ear plays no role in hearing as such but is otherwise very much required?",
        "options": ["Eustachian tube", "Organ of corti", "Vestibular apparatus", "Ear ossicles"],
        "correct_option_id": 2,
        "explanation": "Vestibular apparatus is responsible for balance/equilibrium, not hearing.",
    },
    {
        "question": "The most abundant prokaryotes helpful to humans in making curd from milk and in production of antibiotics are the ones categorised as:",
        "options": ["Cyanobacteria", "Archaebacteria", "Chemosynthetic autotrophs", "Heterotrophic bacteria"],
        "correct_option_id": 3,
        "explanation": "E.g., Lactobacillus (curd) and Streptomyces (antibiotics) are heterotrophic bacteria.",
    },
    {
        "question": "Which one of the following statements is false in respect of viability of mammalian sperm?",
        "options": ["Sperm is viable for only up to 24 hours.", "Survival of sperm depends on the pH of the medium and is more active in alkaline medium.", "Viability of sperm is determined by its motility.", "Sperms must be concentrated in a thick suspension"],
        "correct_option_id": 3,
        "explanation": "Thick suspension reduces motility/viability; this statement is false.",
    },
    {
        "question": "Evolution of different species in a given area starting from a point and spreading to other geographical areas is known as:",
        "options": ["Adaptive radiation", "Natural selection", "Migration", "Divergent evolution"],
        "correct_option_id": 0,
        "explanation": "Classic example: Darwin's finches on Galapagos Islands.",
    },
    {
        "question": "In an area where DDT had been used extensively, the population of birds declined significantly because:",
        "options": ["birds stopped laying eggs", "earthworms in the area got eradicated", "cobras were feeding exclusively on birds", "many of the birds laid, did not hatch"],
        "correct_option_id": 3,
        "explanation": "DDT causes eggshell thinning (biomagnification), leading to breakage before hatching.",
    },
    {
        "question": "The common bottle cork is a product of:",
        "options": ["Dermatogen", "Phellogen", "Xylem", "Vascular Cambium"],
        "correct_option_id": 1,
        "explanation": "Cork cambium (phellogen) produces cork (phellem) on its outer side.",
    },
    {
        "question": "Widal Test is carried out to test:",
        "options": ["Malaria", "Diabetes mellitus", "HIV/AIDS", "Typhoid fever"],
        "correct_option_id": 3,
        "explanation": "Detects antibodies against Salmonella typhi.",
    },
    {
        "question": "Which part would be most suitable for raising virus-free plants for micropropagation?",
        "options": ["Bark", "Vascular tissue", "Meristem", "Node"],
        "correct_option_id": 2,
        "explanation": "Meristematic tissue is generally free of viral infection.",
    },
    {
        "question": "Which one of the following is a wrong statement?",
        "options": ["Most of the forests have been lost in tropical areas.", "Ozone in upper part of atmosphere is harmful to animals.", "Greenhouse effect is a natural phenomenon.", "Eutrophication is a natural phenomenon in freshwater bodies."],
        "correct_option_id": 1,
        "explanation": "Upper atmospheric (stratospheric) ozone is protective, not harmful; it shields from UV radiation.",
    },
    {
        "question": "Companion cells are closely associated with:",
        "options": ["Sieve elements", "Vessel elements", "Trichomes", "Guard cells"],
        "correct_option_id": 0,
        "explanation": "Companion cells regulate the metabolic activities of sieve tube elements.",
    },
    {
        "question": "Common cold differs from pneumonia in, that:",
        "options": ["Pneumonia is a communicable disease whereas the common cold is a nutritional deficiency disease.", "Pneumonia can be prevented by a live attenuated bacterial vaccine whereas the common cold has no effective vaccine.", "Pneumonia is caused by a virus while the common cold is caused by the bacterium Haemophilus influenzae.", "Pneumonia pathogen infects alveoli whereas the common cold affects nose and respiratory passage but not the lungs."],
        "correct_option_id": 3,
        "explanation": "Pneumonia infects alveoli (Streptococcus pneumoniae); common cold affects upper respiratory tract (Rhinovirus).",
    },
    {
        "question": "Pheretima and its close relatives derive nourishment from:",
        "options": ["sugarcane roots", "decaying fallen leaves and soil organic matter.", "soil insects", "small pieces of fresh fallen leaves of maize, etc."],
        "correct_option_id": 1,
        "explanation": "Earthworms feed on decaying organic matter in soil.",
    },
    {
        "question": "Removal of RNA polymerase III from nucleoplasm will affect the synthesis of:",
        "options": ["tRNA", "hnRNA", "mRNA", "rRNA"],
        "correct_option_id": 0,
        "explanation": "RNA Pol III synthesizes tRNA, 5S rRNA, and other small RNAs.",
    },
    {
        "question": "A process that makes important difference between C3 and C4 plants is:",
        "options": ["Transpiration", "Glycolysis", "Photosynthesis", "Photorespiration"],
        "correct_option_id": 3,
        "explanation": "C4 plants minimize photorespiration via Kranz anatomy/PEP carboxylase pathway.",
    },
    {
        "question": "PCR and Restriction Fragment Length Polymorphism are the methods for:",
        "options": ["Study of enzymes", "Genetic transformation", "DNA sequencing", "Genetic Fingerprinting"],
        "correct_option_id": 3,
        "explanation": "Both are core techniques used in DNA fingerprinting.",
    },
    {
        "question": "Best defined function of Manganese in green plants is:",
        "options": ["Photolysis of water", "Calvin cycle", "Nitrogen fixation", "Water absorption"],
        "correct_option_id": 0,
        "explanation": "Mn is essential for the water-splitting complex of Photosystem II.",
    },
    {
        "question": "Measuring Biochemical Oxygen Demand (BOD) is a method used for:",
        "options": ["estimating the amount of organic matter in sewage water.", "working out the efficiency of oil driven automobile engines.", "measuring the activity of Saccharomyces cerevisiae in producing curd on a commercial scale.", "working out the efficiency of R.B.Cs. about their capacity to carry oxygen"],
        "correct_option_id": 0,
        "explanation": "BOD reflects the amount of biodegradable organic matter in water.",
    },
    {
        "question": "Which one of the following is not a part of a transcription unit in DNA?",
        "options": ["The inducer", "A terminator", "A promoter", "The structural gene"],
        "correct_option_id": 0,
        "explanation": "The inducer is a regulatory molecule (operon control), not part of the transcription unit structure.",
    },
    {
        "question": "A certain road accident patient with unknown blood group needs immediate blood transfusion. His one doctor friend at once offers his blood. What was the blood group of the donor?",
        "options": ["Blood group B", "Blood group AB", "Blood group O", "Blood group A"],
        "correct_option_id": 2,
        "explanation": "Blood group O is the universal donor (no A/B antigens).",
    },
    {
        "question": "Consumption of which one of the following foods can prevent the kind of blindness associated with vitamin 'A' deficiency?",
        "options": ["Flavr Savr tomato", "Canola", "Golden rice", "Bt-Brinjal"],
        "correct_option_id": 2,
        "explanation": "Golden rice is genetically engineered to produce beta-carotene (vitamin A precursor).",
    },
    {
        "question": "The maximum amount of electrolytes and water (70-80 percent) from the glomerular filtrate is reabsorbed in which part of the nephron?",
        "options": ["Ascending limb of loop of Henle", "Distal convoluted tubule", "Proximal convoluted tubule", "Descending limb of loop of Henle"],
        "correct_option_id": 2,
        "explanation": "PCT reabsorbs ~70-80% of filtrate content.",
    },
    {
        "question": "Both, autogamy and geitonogamy are prevented in:",
        "options": ["Papaya", "Cucumber", "Castor", "Maize"],
        "correct_option_id": 2,
        "explanation": "Castor is monoecious with dichogamy, preventing both self-pollination types.",
    },
    {
        "question": "Placentation in tomato and lemon is:",
        "options": ["Parietal", "Free central", "Marginal", "Axile"],
        "correct_option_id": 3,
        "explanation": "Both belong to families with axile placentation (Solanaceae/Rutaceae).",
    },
    {
        "question": "A person entering an empty room suddenly finds a snake right in front on opening the door. Which one of the following is likely to happen in his neuro-hormonal control system?",
        "options": ["Sympathetic nervous system is activated releasing epinephrin and norepinephrin from adrenal medulla.", "Neurotransmitters diffuse rapidly across the cleft and transmit a nerve impulse.", "Hypothalamus activates the parasympathetic division of brain.", "Sympathetic nervous system is activated releasing epinephrin and norepinephrin from adrenal cortex."],
        "correct_option_id": 0,
        "explanation": "Fight-or-flight response activates sympathetic nervous system via adrenal medulla hormones.",
    },
    {
        "question": "Which one of the following is not a gaseous biogeochemical cycle in ecosystem?",
        "options": ["Sulphur cycle", "Phosphorus cycle", "Nitrogen cycle", "Carbon cycle"],
        "correct_option_id": 1,
        "explanation": "Phosphorus cycle is a sedimentary cycle, not gaseous.",
    },
    {
        "question": "A single strand of nucleic acid tagged with a radioactive molecule is called:",
        "options": ["Vector", "Selectable marker", "Plasmid", "Probe"],
        "correct_option_id": 3,
        "explanation": "Used in hybridization techniques to detect complementary sequences.",
    },
    {
        "question": "An organic substance that can withstand environmental extremes and cannot be degraded by any enzyme is:",
        "options": ["Cuticle", "Sporopollenin", "Lignin", "Cellulose"],
        "correct_option_id": 1,
        "explanation": "Sporopollenin (pollen wall) is one of the most resistant organic materials known.",
    },
    {
        "question": "Cycas and Adiantum resemble each other in having:",
        "options": ["Seeds", "Motile Sperms", "Cambium", "Vessels"],
        "correct_option_id": 1,
        "explanation": "Both are seedless/gymnosperm groups with flagellated, motile sperm cells.",
    },
    {
        "question": "What was the most significant trend in the evolution of modern man (Homo sapiens) from his ancestors?",
        "options": ["Shortening of jaws", "Binocular vision", "Increasing cranial capacity", "Upright posture"],
        "correct_option_id": 2,
        "explanation": "Progressive increase in brain size/cranial capacity marks human evolution.",
    },
    {
        "question": "Cymose inflorescence is present in:",
        "options": ["Solanum", "Sesbania", "Trifolium", "Brassica"],
        "correct_option_id": 0,
        "explanation": "Solanum shows cymose (determinate) inflorescence pattern.",
    },
    {
        "question": "Ribosomal RNA is actively synthesized in:",
        "options": ["Lysosomes", "Nucleolus", "Nucleoplasm", "Ribosomes"],
        "correct_option_id": 1,
        "explanation": "Nucleolus is the site of rRNA transcription and ribosome assembly.",
    },
    {
        "question": "During gamete formation, the enzyme recombinase participates during:",
        "options": ["Metaphase-I", "Anaphase-II", "Prophase-I", "Prophase-II"],
        "correct_option_id": 2,
        "explanation": "Crossing over (facilitated by recombinase) occurs during pachytene of prophase I.",
    },
    {
        "question": "Identify the possible link \"A\" in the following food chain: Plant -> insect -> frog -> \"A\" -> Eagle",
        "options": ["Rabbit", "Wolf", "Cobra", "Parrot"],
        "correct_option_id": 2,
        "explanation": "Snakes prey on frogs and are in turn preyed upon by eagles.",
    },
    {
        "question": "Phyllode is present in:",
        "options": ["Asparagus", "Euphorbia", "Australian Acacia", "Opuntia"],
        "correct_option_id": 2,
        "explanation": "Australian Acacia has flattened petioles (phyllodes) functioning as leaves.",
    },
    {
        "question": "Monascus purpureus is a yeast used commercially in the production of:",
        "options": ["ethanol", "streptokinase for removing clots from the blood vessels.", "Citric acid", "blood cholesterol lowering statins"],
        "correct_option_id": 3,
        "explanation": "Monascus purpureus produces statins used to lower blood cholesterol.",
    },
    {
        "question": "Which one of the following is correctly matched?",
        "options": ["Passive transport of nutrients - ATP", "Apoplast - Plasmodesmata", "Potassium - Readily immobilisation", "Bakane of rice seedlings - F. Skoog"],
        "correct_option_id": 2,
        "explanation": "Potassium is a highly mobile nutrient, readily translocated in plants.",
    },
    {
        "question": "A normal-visioned man whose father was colour-blind, marries a woman whose father was also colour-blind. They have their first child as a daughter. What are the chances that this child would be colour-blind?",
        "options": ["100%", "zero percent", "25%", "50%"],
        "correct_option_id": 1,
        "explanation": "Father is X^N Y (normal vision, colour-blindness is X-linked recessive); daughter gets father's normal X, so daughter cannot be colour-blind regardless of mother's genotype.",
    },
    {
        "question": "Signals for parturition originate from:",
        "options": ["Both placenta as well as fully developed foetus", "Oxytocin released from maternal pituitary", "Placenta only", "Fully developed foetus only"],
        "correct_option_id": 0,
        "explanation": "Both maternal (placenta) and foetal signals trigger labor via hormonal cascades.",
    },
    {
        "question": "A patient brought to a hospital with myocardial infarction is normally immediately given:",
        "options": ["Penicillin", "Streptokinase", "Cyclosporin-A", "Statins"],
        "correct_option_id": 1,
        "explanation": "Streptokinase is a clot-dissolving enzyme used in emergency treatment of heart attacks.",
    },
    {
        "question": "Which one of the following is not a property of cancerous cells whereas the remaining three are?",
        "options": ["They compete with normal cells for vital nutrients.", "They do not remain confined in the area of formation.", "They divide in an uncontrolled manner", "They show contact inhibition."],
        "correct_option_id": 3,
        "explanation": "Cancer cells lose contact inhibition, allowing continued uncontrolled growth.",
    },
    {
        "question": "The gynoecium consists of many free pistils in flowers of:",
        "options": ["Aloe", "Tomato", "Papaver", "Michelia"],
        "correct_option_id": 3,
        "explanation": "Michelia shows apocarpous gynoecium with numerous free carpels.",
    },
    {
        "question": "Which one of the following is not a functional unit of an ecosystem?",
        "options": ["Energy flow", "Decomposition", "Productivity", "Stratification"],
        "correct_option_id": 3,
        "explanation": "Stratification is a structural feature, not a functional process.",
    },
    {
        "question": "In a normal pregnant woman, the amount of total gonadotropin activity was assessed. The result expected was:",
        "options": ["High level of circulating FSH and LH in the uterus to stimulate implantation of the embryo", "High level of circulating HCG to stimulate endometrial thickening", "High level of FSH and LH in uterus to stimulate endometrial thickening", "High level of circulating HCG to stimulate estrogen and progesterone synthesis"],
        "correct_option_id": 3,
        "explanation": "HCG maintains the corpus luteum, sustaining estrogen/progesterone production during pregnancy.",
    },
    {
        "question": "Which one of the following areas in India, is a hotspot of biodiversity:",
        "options": ["Eastern Ghats", "Gangetic Plain", "Sunderbans", "Western Ghats"],
        "correct_option_id": 3,
        "explanation": "Western Ghats is a recognized global biodiversity hotspot.",
    },
    {
        "question": "Which one of the following is a correct statement:",
        "options": ["Pteridophyte gametophyte has a protonemal and leafy stage", "In gymnosperms female gametophyte is free-living", "Antheridiophores and archegoniophores are present in pteridophytes.", "Origin of seed habit can be traced in pteridophytes"],
        "correct_option_id": 3,
        "explanation": "Heterosporous pteridophytes (e.g., Selaginella) show early evolutionary trends toward seed habit.",
    },
    {
        "question": "Which one of the following does not differ in E. coli and Chlamydomonas:",
        "options": ["Ribosomes", "Chromosomal Organization", "Cell wall", "Cell membrane"],
        "correct_option_id": 3,
        "explanation": "Both possess a similar phospholipid bilayer plasma membrane structure.",
    },
    {
        "question": "The cyanobacteria are also referred to as:",
        "options": ["proists", "golden algae", "Slime moulds", "blue green algae"],
        "correct_option_id": 3,
        "explanation": "Cyanobacteria are commonly known as blue-green algae.",
    },
    {
        "question": "The test-tube Baby Programme employs which one of the following techniques:",
        "options": ["Intra cytoplasmic sperm injection (ICSI)", "Intra uterine insemination (IUI)", "Gamete intra fallopian transfer (GIFT)", "Zygote intra fallopian transfer (ZIFT)"],
        "correct_option_id": 3,
        "explanation": "ZIFT involves transferring the zygote (formed in vitro) into the fallopian tube.",
    },
    {
        "question": "The highest number of species in the world is represented by:",
        "options": ["Fungi", "Mosses", "Algae", "Lichens"],
        "correct_option_id": 0,
        "explanation": "Among the given options, Fungi represents the highest species diversity.",
    },
    {
        "question": "Which one of the following is wrong statement:",
        "options": ["Anabaena and Nostoc are capable of fixing nitrogen in free living state also.", "Root nodule forming nitrogen fixers live as aerobes under free-living conditions.", "Phosphorus is a constituent of cell membranes, certain nucleic acids and cell proteins.", "Nitrosomonas and Nitrobacter are chemoautotrophs."],
        "correct_option_id": 1,
        "explanation": "Rhizobium is microaerophilic/anaerobic in free-living state, not simply aerobic.",
    },
    {
        "question": "Anxiety and eating spicy food together in an otherwise normal human, may lead to:",
        "options": ["Indigestion", "Jaundice", "Diarrhoea", "Vomiting"],
        "correct_option_id": 0,
        "explanation": "Combined stress and spicy food commonly cause indigestion.",
    },
    {
        "question": "The Leydig cells found in the human body are the secretory source of:",
        "options": ["Progesterone", "intestinal mucus", "glucagon", "androgens"],
        "correct_option_id": 3,
        "explanation": "Leydig cells in testes secrete androgens (testosterone).",
    },
    {
        "question": "Compared to those of humans, the erythrocytes in frog are:",
        "options": ["Without nucleus but with haemoglobin", "nucleated and with haemoglobin", "very much smaller and fewer", "nucleated and without haemoglobin."],
        "correct_option_id": 1,
        "explanation": "Frog RBCs are nucleated (unlike mammalian RBCs) and contain haemoglobin.",
    },
    {
        "question": "What is true about ribosomes:",
        "options": ["The prokaryotic ribosomes are 80S, where \"S\" stands for sedimentation coefficient", "These are composed of ribonucleic acid and proteins", "These are found only in eukaryotic cells", "These are self-splicing introns of some RNAs."],
        "correct_option_id": 1,
        "explanation": "Ribosomes are ribonucleoprotein particles (rRNA + proteins).",
    },
    {
        "question": "Cirrhosis of liver is caused by the chronic intake of:",
        "options": ["Opium", "Alcohol", "Tobacco (Chewing)", "Cocaine"],
        "correct_option_id": 1,
        "explanation": "Chronic alcohol consumption is the leading cause of liver cirrhosis.",
    },
    {
        "question": "Which one is a true statement regarding DNA polymerase used in PCR:",
        "options": ["It is used to ligate introduced DNA in recipient cell", "It serves as a selectable marker", "It is isolated from a virus", "It remains active at high temperature"],
        "correct_option_id": 3,
        "explanation": "Taq polymerase (from Thermus aquaticus) is thermostable, essential for PCR cycling.",
    },
    {
        "question": "Which statement is wrong for viruses:",
        "options": ["All are parasites", "All of them have helical symmetry", "They have ability to synthesize nucleic acids and proteins", "Antibiotics have no effect on them"],
        "correct_option_id": 1,
        "explanation": "Viruses can show helical, icosahedral, or complex symmetry - not all are helical.",
    },
    {
        "question": "Which one of the following is correctly matched:",
        "options": ["Onion - Bulb", "Ginger - Sucker", "Chlamydomonas - Conidia", "Yeast - Zoospores"],
        "correct_option_id": 0,
        "explanation": "Onion reproduces vegetatively via bulbs.",
    },
    {
        "question": "How many plants in the list given below have composite fruits that develop from an inflorescence: Walnut, poppy, radish, fig, pineapple, apple, tomato, mulberry",
        "options": ["Four", "Five", "Two", "Three"],
        "correct_option_id": 3,
        "explanation": "Fig, pineapple, and mulberry develop as composite (multiple) fruits from an inflorescence.",
    },
    {
        "question": "Which one of the following microbes forms symbiotic association with plants and helps them in their nutrition?",
        "options": ["Azotobacter", "Aspergillus", "Glomus", "Trichoderma"],
        "correct_option_id": 2,
        "explanation": "Glomus forms mycorrhizal (symbiotic) associations aiding nutrient absorption.",
    },
    {
        "question": "The extinct human who lived 1,00,000 to 40,000 years ago, in Europe, Asia and parts of Africa, with short stature, heavy eyebrows, retreating fore heads, large jaws with heavy teeth, stocky bodies, a lumbering gait and stooped posture was:",
        "options": ["Homo habilis", "Neanderthal human", "Cro-magnon humans", "Ramapithecus"],
        "correct_option_id": 1,
        "explanation": "This description matches Neanderthal man (Homo neanderthalensis).",
    },
    {
        "question": "If one strand of DNA has the nitrogenous base sequence ATCTG, what would be the complementary RNA strand sequence:",
        "options": ["TTAGU", "UAGAC", "AACTG", "ATCGU"],
        "correct_option_id": 1,
        "explanation": "Complementary base pairing (DNA->RNA): A-U, T-A, C-G, T-A, G-C -> UAGAC.",
    },
    {
        "question": "Which one of the following pairs of hormones are examples of those that can easily pass through the cell membrane of the target cell and bind to a receptor inside it (mostly in the nucleus):",
        "options": ["Insulin, glucagon", "Thyroxin, insulin", "Somatostatin, oxytocin", "Cortisol, testosterone"],
        "correct_option_id": 3,
        "explanation": "Steroid hormones (cortisol, testosterone) are lipophilic and act via intracellular/nuclear receptors.",
    },
    {
        "question": "Nuclear membrane is absent in:",
        "options": ["Penicillium", "Agaricus", "Volvox", "Nostoc"],
        "correct_option_id": 3,
        "explanation": "Nostoc is a prokaryote (cyanobacterium) lacking a nuclear membrane.",
    },
    {
        "question": "Which one is the most abundant protein in the animal world:",
        "options": ["Trypsin", "Hemoglobin", "Collagen", "Insulin"],
        "correct_option_id": 2,
        "explanation": "Collagen is the most abundant structural protein in animals.",
    },
    {
        "question": "Which one of the following is common to multicellular fungi, filamentous algae and protonema of mosses:",
        "options": ["Diplontic life cycle", "Members of kingdom plantae", "Mode of Nutrition", "Multiplication by fragmentation"],
        "correct_option_id": 3,
        "explanation": "All these organisms can reproduce vegetatively via fragmentation.",
    },
    {
        "question": "Even in absence of pollinating agents seed setting is assured in:",
        "options": ["Commelina", "Zostera", "Salvia", "Fig"],
        "correct_option_id": 0,
        "explanation": "Commelina has cleistogamous flowers ensuring self-pollination without external agents.",
    },
    {
        "question": "Yeast is used in the production of:",
        "options": ["Citric acid and lactic acid", "Lipase and pectinase", "Bread and beer", "Cheese and butter"],
        "correct_option_id": 2,
        "explanation": "Saccharomyces cerevisiae (yeast) ferments sugars for bread leavening and beer production.",
    },
    {
        "question": "The upright pyramid of number is absent in:",
        "options": ["Pond", "Forest", "Lake", "Grassland"],
        "correct_option_id": 1,
        "explanation": "Forest ecosystems show a spindle-shaped (inverted at top) pyramid due to few large producers.",
    },
    {
        "question": "What is correct to say about the hormone action in humans:",
        "options": ["Glucagon is secreted by alpha-cells of Islets of Langerhans and stimulates glycogenolysis", "Secretion of thymosins is stimulated with aging", "In females FSH first binds with specific receptors on ovarian cell membrane", "FSH stimulates the secretion of estrogen and progesterone"],
        "correct_option_id": 0,
        "explanation": "Glucagon (from pancreatic alpha-cells) promotes glycogen breakdown (glycogenolysis).",
    },
    {
        "question": "Closed vascular bundles lack:",
        "options": ["Ground tissue", "conjunctive tissue", "Cambium", "Pith"],
        "correct_option_id": 2,
        "explanation": "Closed vascular bundles lack cambium (no secondary growth), typical of monocots.",
    },
    {
        "question": "Which one of the following is the correct statement for respiration in human:",
        "options": ["Cigarette smoking may lead to inflammation of bronchi", "Neural signals from pneumotaxic centre in pons region of brain can increase the duration of inspiration", "Workers in grinding and stone-breaking industries may suffer from lung fibrosis", "About 90% of carbon dioxide (CO2) is carried by haemoglobin as carbamino haemoglobin"],
        "correct_option_id": 2,
        "explanation": "Silicosis/lung fibrosis is common among stone-breaking and grinding industry workers due to silica dust inhalation.",
    },
    {
        "question": "Removal of introns and joining of exons in a defined order during transcription is called:",
        "options": ["Looping", "Inducing", "Slicing", "Splicing"],
        "correct_option_id": 3,
        "explanation": "RNA splicing removes introns and joins exons to form mature mRNA.",
    },
    {
        "question": "F2 generation in a Mendelian cross showed that both genotypic and phenotypic ratios are same as 1:2:1. It represents a case of:",
        "options": ["Co-dominance", "Dihybrid cross", "Monohybrid cross with complete dominance", "Monohybrid cross with incomplete dominance"],
        "correct_option_id": 3,
        "explanation": "In incomplete dominance, phenotypic ratio matches genotypic ratio (1:2:1) as heterozygotes show intermediate phenotype.",
    },
    {
        "question": "People who have migrated from the plains to an area adjoining Rohatang Pass about six months back:",
        "options": ["have more RBCs and their haemoglobin has a lower binding affinity to O2.", "are not physically fit to play games like football.", "suffer from altitude sickness with symptoms like nausea, fatigue, etc.", "have the usual RBC count but their haemoglobin has very high binding affinity to O2."],
        "correct_option_id": 0,
        "explanation": "Long-term high-altitude acclimatization increases RBC count; haemoglobin's O2 affinity decreases to aid tissue oxygen delivery.",
    },
    {
        "question": "For transformation, micro-particles coated with DNA to be bombarded with gene gun are made up of:",
        "options": ["Silver or Platinum", "Platinum or Zinc", "Silicon or Platinum", "Gold or Tungsten"],
        "correct_option_id": 3,
        "explanation": "Gold or tungsten particles are used in biolistic (gene gun) transformation.",
    },
    {
        "question": "A nitrogen-fixing microbe associated with Azolla in rice fields is:",
        "options": ["Spirulina", "Anabaena", "Frankia", "Tolypothrix"],
        "correct_option_id": 1,
        "explanation": "Anabaena azollae lives symbiotically with Azolla, fixing atmospheric nitrogen.",
    },
    {
        "question": "Select the correct statement regarding the specific disorder of muscular or skeletal system:",
        "options": ["Muscular dystrophy - age related shortening of muscles.", "Osteoporosis - decrease in bone mass and higher chance of fractures with advancing age.", "Myasthenia gravis - Auto immune disorder which inhibits sliding of myosin filaments", "Gout - inflammation of joints due to extra deposition of calcium."],
        "correct_option_id": 1,
        "explanation": "Osteoporosis is characterized by decreased bone mass and increased fracture risk with age.",
    },
    {
        "question": "Water containing cavities in vascular bundles are found in:",
        "options": ["Sunflower", "Maize", "Cycas", "Pinus"],
        "correct_option_id": 1,
        "explanation": "Maize vascular bundles have water-containing cavities (lysigenous cavities).",
    },
    {
        "question": "Select the correct statement from the following regarding cell membrane:",
        "options": ["Na+ and K+ ions move across cell membrane by passive transport", "Proteins make up 60 to 70% of the cell membrane.", "Lipids are arranged in a bilayer with polar heads towards the inner part.", "Fluid mosaic model of cell membrane was proposed by Singer and Nicolson"],
        "correct_option_id": 3,
        "explanation": "The fluid mosaic model was proposed by Singer and Nicolson in 1972.",
    },
    {
        "question": "Gymnosperms are also called soft wood spermatophytes because they lack:",
        "options": ["Cambium", "Phloem fibres", "Thick-walled tracheids", "Xylem fibres"],
        "correct_option_id": 3,
        "explanation": "Absence of xylem fibres gives gymnosperm wood its \"soft\" characteristic.",
    },
    {
        "question": "The coconut water and the edible part of coconut are equivalent to:",
        "options": ["Endosperm", "Endocarp", "Mesocarp", "Embryo"],
        "correct_option_id": 0,
        "explanation": "Both liquid (free-nuclear) and solid (cellular) endosperm form the coconut's water and flesh.",
    },
    {
        "question": "Vexillary aestivation is characteristic of the family:",
        "options": ["Fabaceae", "Asteraceae", "Solanaceae", "Brassicaceae"],
        "correct_option_id": 0,
        "explanation": "Vexillary (papilionaceous) aestivation is a hallmark of Fabaceae flowers.",
    },
    {
        "question": "Which one of the following is an example of carrying out biological control of pests/diseases using microbes?",
        "options": ["Trichoderma sp. against certain plant pathogens", "Nucleopolyhedrovirus against white rust in Brassica", "Bt-cotton to increase cotton yield", "Lady bird beetle against aphids in mustard"],
        "correct_option_id": 0,
        "explanation": "Trichoderma is a fungal biocontrol agent used against various plant pathogens.",
    },
    {
        "question": "Select the correct statement from the ones given below with respect to Periplaneta americana:",
        "options": ["Nervous system located dorsally, consists of segmentally arranged ganglia joined by a pair of longitudinal connectives.", "Males bear a pair of short thread-like anal styles.", "There are 16 very long Malpighian tubules present at the junctions of midgut and hindgut.", "Grinding of food is carried out only by the mouth parts."],
        "correct_option_id": 2,
        "explanation": "Cockroaches have Malpighian tubules present at the midgut-hindgut junction for excretion (per official answer key, option 3).",
    },
    {
        "question": "Maximum nutritional diversity is found in the group:",
        "options": ["Fungi", "Animalia", "Monera", "Plantae"],
        "correct_option_id": 2,
        "explanation": "Monera includes autotrophic, heterotrophic, chemosynthetic, and photosynthetic organisms - showing the widest nutritional diversity.",
    },
]
