"""
Question bank: NEET 2017 (Code W) - Biology (Solved Answers).

89 questions parsed from NEET 2017 (Code W)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Which one of the following statements is correct with reference to enzymes?",
        "options": ["Apoenzyme = Holoenzyme + Coenzyme", "Holoenzyme = Apoenzyme + Coenzyme", "Coenzyme = Apoenzyme + Holoenzyme", "Holoenzyme = Coenzyme + Co-factor"],
        "correct_option_id": 1,
        "explanation": "Holoenzyme is the catalytically active enzyme formed by the combination of an apoenzyme (protein part) and a coenzyme (non-protein part).",
    },
    {
        "question": "Which cells of 'Crypts of Lieberkuhn' secrete antibacterial lysozyme?",
        "options": ["Argentaffin cells", "Paneth cells", "Zymogen cells", "Kupffer cells"],
        "correct_option_id": 1,
        "explanation": "Paneth cells, present in the crypts of Lieberkuhn, secrete the antibacterial enzyme lysozyme.",
    },
    {
        "question": "Phosphoenol pyruvate (PEP) is the primary CO2 acceptor in:",
        "options": ["C3 plants", "C4 plants", "C2 plants", "C3 and C4 plants"],
        "correct_option_id": 1,
        "explanation": "In C4 plants, PEP present in mesophyll cells acts as the primary CO2 acceptor via the enzyme PEP carboxylase.",
    },
    {
        "question": "Which among the following are the smallest living cells, known without a definite cell wall, pathogenic to plants as well as animals and can survive without oxygen?",
        "options": ["Bacillus", "Pseudomonas", "Mycoplasma", "Nostoc"],
        "correct_option_id": 2,
        "explanation": "Mycoplasma are the smallest known living cells, lack a definite cell wall, are pathogenic to plants/animals and can survive without oxygen.",
    },
    {
        "question": "Which one from those given below is the period for Mendel's hybridization experiments?",
        "options": ["1856 - 1863", "1840 - 1850", "1857 - 1869", "1870 - 1877"],
        "correct_option_id": 0,
        "explanation": "Mendel carried out his pea hybridization experiments between 1856 and 1863.",
    },
    {
        "question": "Flowers which have single ovule in the ovary and are packed into inflorescence are usually pollinated by:",
        "options": ["Water", "Bee", "Wind", "Bat"],
        "correct_option_id": 2,
        "explanation": "Wind-pollinated (anemophilous) flowers typically have a single ovule and are packed into inflorescences, e.g., grasses.",
    },
    {
        "question": "Asymptote in a logistic growth curve is obtained when:",
        "options": ["The value of 'r' approaches zero", "K = N", "K > N", "K < N"],
        "correct_option_id": 1,
        "explanation": "The logistic growth curve reaches its asymptote (plateau) when the population size (N) equals the carrying capacity (K).",
    },
    {
        "question": "Out of 'X' pairs of ribs in humans only 'Y' pairs are true ribs. Select the option that correctly represents values of X and Y and provides their explanation:",
        "options": ["X = 12, Y = 7; True ribs are attached dorsally to vertebral column and ventrally to the sternum", "X = 12, Y = 5; True ribs are attached dorsally to vertebral column and sternum on the two ends", "X = 24, Y = 7; True ribs are dorsally attached to vertebral column but are free on ventral side", "X = 24, Y = 12; True ribs are dorsally attached to vertebral column but are free on ventral side"],
        "correct_option_id": 0,
        "explanation": "Humans have 12 pairs of ribs; the first 7 pairs (true ribs) are attached dorsally to the vertebral column and ventrally to the sternum.",
    },
    {
        "question": "MALT constitutes about __________ percent of the lymphoid tissue in human body.",
        "options": ["50%", "20%", "70%", "10%"],
        "correct_option_id": 0,
        "explanation": "Mucosa-Associated Lymphoid Tissue (MALT) makes up nearly 50% of the lymphoid tissue in the human body.",
    },
    {
        "question": "Homozygous purelines in cattle can be obtained by:",
        "options": ["mating of related individuals of same breed", "mating of unrelated individuals of same breed", "mating of individuals of different breed", "mating of individuals of different species"],
        "correct_option_id": 0,
        "explanation": "Inbreeding (mating of related individuals of the same breed) increases homozygosity, producing pure lines.",
    },
    {
        "question": "Among the following characters, which one was not considered by Mendel in his experiments on pea?",
        "options": ["Stem - Tall or Dwarf", "Trichomes - Glandular or non-glandular", "Seed - Green or Yellow", "Pod - Inflated or Constricted"],
        "correct_option_id": 1,
        "explanation": "Mendel studied seven contrasting pea traits; trichome (glandular/non-glandular) type was not among them.",
    },
    {
        "question": "Which of the following cell organells is responsible for extracting energy from carbohydrates to form ATP?",
        "options": ["Lysosome", "Ribosome", "Chloroplast", "Mitochondrion"],
        "correct_option_id": 3,
        "explanation": "Mitochondria carry out cellular respiration, extracting energy from carbohydrates to synthesize ATP.",
    },
    {
        "question": "If there are 999 bases in RNA that codes for a protein with 333 amino acids, and the base at position 901 is deleted such that the length of the RNA becomes 998 bases, how many codons will be altered?",
        "options": ["1", "11", "33", "333"],
        "correct_option_id": 2,
        "explanation": "The deletion at base 901 causes a frameshift starting from codon 301 (approx.) onward, altering the remaining 33 codons of the reading frame.",
    },
    {
        "question": "Which of the following are found in extreme saline conditions?",
        "options": ["Archaebacteria", "Eubacteria", "Cyanobacteria", "Mycobacteria"],
        "correct_option_id": 0,
        "explanation": "Halophilic Archaebacteria are adapted to survive in extreme saline environments such as salt lakes.",
    },
    {
        "question": "Receptor sites for neurotransmitters are present on:",
        "options": ["membranes of synaptic vesicles", "pre-synaptic membrane", "tips of axons", "post-synaptic membrane"],
        "correct_option_id": 3,
        "explanation": "Neurotransmitter receptor sites are located on the post-synaptic membrane.",
    },
    {
        "question": "Artificial selection to obtain cows yielding higher milk output represents:",
        "options": ["stabilizing selection as it stabilizes this character in the population", "directional selection as it pushes the mean of the character in one direction", "disruptive selection as it splits the population into two, one yielding higher output and the other lower output", "stabilizing followed by disruptive selection as it stabilizes the population to produce higher yielding cows"],
        "correct_option_id": 1,
        "explanation": "Selecting for progressively higher milk yield shifts the population mean in a single direction, which is characteristic of directional selection.",
    },
    {
        "question": "The hepatic portal vein drains blood to liver from:",
        "options": ["Heart", "Stomach", "Kidneys", "Intestine"],
        "correct_option_id": 3,
        "explanation": "The hepatic portal vein carries nutrient-rich blood from the intestine to the liver.",
    },
    {
        "question": "The water potential of pure water is:",
        "options": ["Zero", "Less than zero", "More than zero but less than one", "More than one"],
        "correct_option_id": 0,
        "explanation": "Pure water has the maximum water potential and is taken as the reference value of zero.",
    },
    {
        "question": "Which of the following represents order of 'Horse'?",
        "options": ["Equidae", "Perissodactyla", "Caballus", "Ferus"],
        "correct_option_id": 1,
        "explanation": "The horse belongs to the order Perissodactyla (odd-toed ungulates).",
    },
    {
        "question": "Alexander Von Humbolt described for the first time:",
        "options": ["Ecological Biodiversity", "Laws of limiting factor", "Species area relationship", "Population Growth equation"],
        "correct_option_id": 2,
        "explanation": "Alexander von Humboldt was the first to describe the species-area relationship.",
    },
    {
        "question": "DNA fragments are:",
        "options": ["Positively charged", "Negatively charged", "Neutral", "Either positively or negatively charged depending on their size"],
        "correct_option_id": 1,
        "explanation": "The phosphate backbone gives DNA fragments a negative charge, causing them to migrate toward the anode in gel electrophoresis.",
    },
    {
        "question": "A baby boy aged two years is admitted to play school and passes through a dental check-up. The dentist observed that boy had twenty teeth. Which teeth were absent?",
        "options": ["Incisors", "Canines", "Pre-molars", "Molars"],
        "correct_option_id": 2,
        "explanation": "The deciduous (milk) dental formula is 2102/2102, meaning premolars are absent in milk teeth.",
    },
    {
        "question": "Anaphase promoting Complex (APC) is a protein degradation machinery necessary for proper mitosis of animal cells. If APC is defective in a human cell, which of the following is expected to occur?",
        "options": ["Chromosomes will not condense", "Chromosomes will be fragmented", "Chromosomes will not segregate", "Recombination of chromosome arms will occur"],
        "correct_option_id": 2,
        "explanation": "APC normally triggers degradation of proteins holding sister chromatids together; if defective, chromosomes fail to segregate.",
    },
    {
        "question": "An important characterstic that hemichordates share with Chordates is",
        "options": ["Absence of notochord", "Ventral tubular nerve cord", "Pharynx with gill slits", "Pharynx without gill slits"],
        "correct_option_id": 2,
        "explanation": "Hemichordates possess pharyngeal gill slits, a feature shared with chordates.",
    },
    {
        "question": "The genotypes of a Husband and Wife are IAIB and IAi. Among the blood types of their children how many different genotypes and phenotypes are possible",
        "options": ["3 genotypes; 3 phenotypes", "3 genotypes; 4 phenotypes", "4 genotypes; 3 Phenotypes", "4 genotypes; 4 phenotypes"],
        "correct_option_id": 2,
        "explanation": "The cross yields genotypes IAIA, IAIB, IAi, IBi (4 genotypes) but only 3 phenotypes (A, AB, B), since IAIA and IAi both show blood group A.",
    },
    {
        "question": "Transplantation of tissues/organs fails often due to non-acceptance by the patient's body. Which type of immune response is responsible for such rejection",
        "options": ["Autoimmune response", "Cell-mediated immune response", "Hormonal immune response", "Physiological immune response"],
        "correct_option_id": 1,
        "explanation": "Graft/organ rejection is mediated primarily by cell-mediated immunity involving T-lymphocytes.",
    },
    {
        "question": "Adult human RBCs are enucleate. Which of the following statement(s) is/are not most appropriate explanation for this feature? (NEET 2017) (a) They do not need to reproduce (b) They are somatic cells (c) They do not metabolize (d) All their internal space is available for oxygen transport",
        "options": ["only (d)", "Only (a)", "(a), (c) and (d)", "(b) and (c)"],
        "correct_option_id": 0,
        "explanation": "Although statements (a), (b) and (c) are factually true of RBCs, only statement (d) — maximum internal space for oxygen transport — is directly the functional reason for their enucleation.",
    },
    {
        "question": "Lungs are made up of air-filled sacs, the alveoli. They do not collapse even after forceful expiration because of",
        "options": ["Residual Volume", "Inspiratory Reserve Volume", "Tidal Volume", "Expirtory Reserve Volume"],
        "correct_option_id": 3,
        "explanation": "According to the given answer key, Expiratory Reserve Volume is credited as correct; note that conventionally, the presence of Residual Volume (air that always remains in the lungs) is the standard reason alveoli never fully collapse.",
    },
    {
        "question": "Zygotic meiosis is characteristic of",
        "options": ["Marchantia", "Fucus", "Funnaria", "Chlamydomonas"],
        "correct_option_id": 3,
        "explanation": "In Chlamydomonas, meiosis occurs immediately after zygote formation (zygotic meiosis), making the life cycle haplontic.",
    },
    {
        "question": "Select the correct route for the passage of sperms in male frogs",
        "options": ["Testes → Bidder's canal →Kideny →Vasa efferentia →Urinogenital duct →Cloaca", "Testes → Vasa efferentia →Kideny →Seminal vesicle →Urinogenital duct →Cloaca", "Testes → Vasa efferentia → Bidder's canal →Ureter →Cloaca", "Testes → Vasa efferentia →Kideny → Bidder's canal →Urinogenital duct →Cloaca"],
        "correct_option_id": 3,
        "explanation": "Sperm passes from the testes through the vasa efferentia into the kidney, then via Bidder's canal to the urinogenital duct and finally the cloaca.",
    },
    {
        "question": "Which one of the following statements in not valid for aerosols",
        "options": ["They are harmful to human health", "They alter rainfall and monsoon patterns", "They cause increased agricultural productivity", "They have negative impact on agricultural land"],
        "correct_option_id": 2,
        "explanation": "Aerosols do not increase agricultural productivity; they generally have harmful/negative effects on health, climate, and agriculture.",
    },
    {
        "question": "Viroids differ from viruses in having",
        "options": ["DNA molecules with protein coat", "DNA molecules without protein coat", "RNA molecules with protein coat", "RNA molecules without protein coat"],
        "correct_option_id": 3,
        "explanation": "Viroids consist of free RNA molecules lacking a protein coat, unlike viruses which have a protein coat.",
    },
    {
        "question": "During DNA replication, Okazaki fragments are used to elongte",
        "options": ["The leading strand towards replication fork", "The lagging strand towards replication fork", "The leading strand away form replication fork", "The lagging strand away form the replication fork"],
        "correct_option_id": 3,
        "explanation": "Okazaki fragments are synthesized discontinuously on the lagging strand, extending away from the replication fork.",
    },
    {
        "question": "Plants which produce characteristic Pneumatophores and show vivipary belong to",
        "options": ["Mesophytes", "halophytes", "Psammophytes", "Hydrophytes"],
        "correct_option_id": 1,
        "explanation": "Mangrove halophytes develop pneumatophores (breathing roots) and exhibit vivipary (seed germination while still on the parent plant).",
    },
    {
        "question": "The process of separation and purification of expressed protein before marketing is called",
        "options": ["Upstream processing", "Downstream processing", "Bioprocessing", "Postproduction processing"],
        "correct_option_id": 1,
        "explanation": "Downstream processing involves the separation and purification of the expressed protein/product before it is marketed.",
    },
    {
        "question": "Identify the worng statement in context of heartwood",
        "options": ["Organic compounds are deposited in it", "It is highly durable", "It conducts water and minerals efficiently", "It comprises dead elements with highly lignified walls"],
        "correct_option_id": 2,
        "explanation": "Heartwood is non-functional in conduction; it does not conduct water and minerals (that is the function of sapwood).",
    },
    {
        "question": "Spliceosomes are not found in cells of",
        "options": ["Plants", "Fungi", "Animals", "Bacteria"],
        "correct_option_id": 3,
        "explanation": "Bacteria, being prokaryotes without introns/RNA splicing machinery, lack spliceosomes.",
    },
    {
        "question": "Which of the following statements is correct",
        "options": ["The ascending limb of loop of henle is impermeable to water", "The descending limb of loop of henle is impermeable to water", "The ascending limb of loop of Henle is permeable to water", "The descending limb of loop of Henle is permeable to electrolytes"],
        "correct_option_id": 0,
        "explanation": "The ascending limb of the loop of Henle is impermeable to water but actively transports electrolytes out.",
    },
    {
        "question": "Which ecosystem has the maximum biomass",
        "options": ["Forest ecosystem", "Grassland ecosystem", "Pond ecosystem", "Lake ecosystem"],
        "correct_option_id": 0,
        "explanation": "Forest ecosystems, with their large trees, have the maximum standing biomass among the given options.",
    },
    {
        "question": "The final proof for DNA as the genetic material came from the experiments of",
        "options": ["Griffith", "Hershey and Chase", "Avery, Mcleod and McCarty", "Hargobind Khorana"],
        "correct_option_id": 1,
        "explanation": "The Hershey-Chase blender experiment with bacteriophages provided the final conclusive proof that DNA is the genetic material.",
    },
    {
        "question": "The function of copper ions in copper releasing IUD's is",
        "options": ["They suppress sperm motility and fertilizing capacity of sperms", "They inhibit gametogenesis", "They make uterus unsuitable for implantation", "They inhibit ovulation"],
        "correct_option_id": 0,
        "explanation": "Copper ions released by Cu-based IUDs suppress sperm motility and their fertilizing capacity.",
    },
    {
        "question": "An example of colonial alga is",
        "options": ["Chlorella", "Volvox", "Ulothrix", "Spirogyra"],
        "correct_option_id": 1,
        "explanation": "Volvox forms colonies of many cells organized into a hollow spherical arrangement, making it a colonial alga.",
    },
    {
        "question": "Root hairs develop from the region of:",
        "options": ["Maturation", "Elongation", "Root cap", "Meristematic acticvity"],
        "correct_option_id": 0,
        "explanation": "Root hairs arise from the region of maturation of the root.",
    },
    {
        "question": "Hypersecretion of Growth Hormone in adults does not cause further increase in height, because:",
        "options": ["Growth Hormone becomes inactive in adults", "Epiphyseal plates close after adolescence", "Bones loose their sensitivity of Growth Hormone in adults", "Muscle fibres do not grow in size after birth"],
        "correct_option_id": 1,
        "explanation": "After adolescence, the epiphyseal (growth) plates of long bones close/fuse, preventing further increase in height regardless of GH levels.",
    },
    {
        "question": "Which of the following in sewage treatment removes suspended solids?",
        "options": ["Tertiary treatment", "Secondary treatment", "Primary treatment", "Sludge treatment"],
        "correct_option_id": 2,
        "explanation": "Primary treatment involves physical processes (sedimentation, filtration) that remove suspended solids from sewage.",
    },
    {
        "question": "Select the mismatch:",
        "options": ["Pinus - Dioecious", "Cycas - Dioecuous", "Salvinia - Heterosporous", "Equisetum - Homosporous"],
        "correct_option_id": 0,
        "explanation": "Pinus is monoecious (bearing both male and female cones on the same plant), not dioecious, making this the mismatched pair.",
    },
    {
        "question": "What is the criterion for DNA fragments movement on agarose gel during gel electrophoresis?",
        "options": ["The larger the fragment size, the farther it moves", "The smaller the fragment size, the farther it moves", "Positive charged fragment moves to farther end", "Negatively charged fragments do not move"],
        "correct_option_id": 1,
        "explanation": "Smaller DNA fragments move faster and travel farther through the agarose gel matrix than larger fragments.",
    },
    {
        "question": "In Bougainvillea thorns are the modification of:",
        "options": ["Stipules", "Adventitious root", "Stem", "Leaf"],
        "correct_option_id": 2,
        "explanation": "In Bougainvillea, thorns are modified axillary stem branches.",
    },
    {
        "question": "The association of histone H1 with a nucleosome indicates:",
        "options": ["Transcription is occurring", "DNA replication is occurring", "The DNA is condensed into a Chromatin Fibre", "The DNA double helix is exposed"],
        "correct_option_id": 2,
        "explanation": "Histone H1 (the linker histone) binds to link DNA between nucleosomes and helps condense the nucleosome chain into a higher-order chromatin fibre.",
    },
    {
        "question": "A temporary endocrine gland in the human body is:",
        "options": ["Pineal gland", "Corpus cardiacum", "Corpus luteum", "Corpus allatum"],
        "correct_option_id": 2,
        "explanation": "The corpus luteum is a temporary endocrine structure formed post-ovulation that secretes progesterone.",
    },
    {
        "question": "Select the mismatch:",
        "options": ["Frankia - Alnus", "Rhodospirillum - Mycorrhiza", "Anabaena - nitrogen fixer", "Rhizobium - Alfalfa"],
        "correct_option_id": 1,
        "explanation": "Rhodospirillum is a photosynthetic purple bacterium, not associated with mycorrhiza formation; hence this pairing is mismatched.",
    },
    {
        "question": "GnRH, a hypothalamic hormone, needed in reproduction, acts on:",
        "options": ["anterior pituitary gland and stimulates secretion of LH and oxytocin", "anterior pituitary gland and stimulates secretion of LH and FSH", "Poserior pituitary gland and stimulates secretion of oxytocin and FSH", "Poserior pituitary gland and stimulates secretion of LH and relaxin"],
        "correct_option_id": 1,
        "explanation": "GnRH acts on the anterior pituitary gland, stimulating the secretion of both LH and FSH.",
    },
    {
        "question": "A gene whose expression helps to identify transformed cell is known as:",
        "options": ["Selectable marker", "Vector", "plasmid", "Structural gene"],
        "correct_option_id": 0,
        "explanation": "Selectable marker genes help distinguish transformed cells from non-transformed ones.",
    },
    {
        "question": "Presence of plants arranged into well defined vertical layers depending on their height can be seen best in",
        "options": ["Tropical Savannah", "Tropical Rain Forest", "Grassland", "Temperate Forest"],
        "correct_option_id": 1,
        "explanation": "Tropical rain forests show pronounced vertical stratification of plants due to high species diversity and multiple canopy layers.",
    },
    {
        "question": "Functional megaspore in an angiosperm develops into:",
        "options": ["Ovule", "Endosperm", "Embryo sac", "Embryo"],
        "correct_option_id": 2,
        "explanation": "The functional megaspore undergoes successive mitotic divisions to form the embryo sac (female gametophyte).",
    },
    {
        "question": "DNA replication in bacteria occurs:",
        "options": ["Durings S phase", "Within nucleolus", "Prior to fission", "Just before transcription"],
        "correct_option_id": 2,
        "explanation": "In bacteria, DNA replication occurs just prior to binary fission (cell division).",
    },
    {
        "question": "Which among these is the correct combination of aquatic mammals?",
        "options": ["Seals, Dolphins, Sharks", "Dolphins, Seals, Trygon", "Whales, Dolphins, Seals", "Trygon, Whales, Seals"],
        "correct_option_id": 2,
        "explanation": "Whales, dolphins, and seals are all mammals adapted to aquatic life; sharks and Trygon are fishes, not mammals.",
    },
    {
        "question": "Coconut fruit is a",
        "options": ["Drupe", "Berry", "Nut", "Capsule"],
        "correct_option_id": 0,
        "explanation": "Coconut is classified as a fibrous drupe, having a hard stony endocarp (shell).",
    },
    {
        "question": "Double fertilization is exhibited by:",
        "options": ["Gymnosperms", "Algae", "Fungi", "Angiosperms"],
        "correct_option_id": 3,
        "explanation": "Double fertilization, resulting in formation of both the zygote and the primary endosperm nucleus, is a unique feature of angiosperms.",
    },
    {
        "question": "Which of the following components provides sticky character to the bacterial cell?",
        "options": ["Cell wall", "Nuclear membrane", "plasma membrane", "Glycocalyx"],
        "correct_option_id": 3,
        "explanation": "The glycocalyx (slime layer/capsule outside the cell wall) gives bacterial cells their sticky property.",
    },
    {
        "question": "Life cycle of Ectocarpus and fucus respectively are:",
        "options": ["Haplontic, Diplontic", "Diplontic, Haplodiplontic", "Haplodiplontic, Diplontic", "Haplodiplontic, Haplontic"],
        "correct_option_id": 2,
        "explanation": "Ectocarpus exhibits a haplodiplontic life cycle while Fucus exhibits a diplontic life cycle.",
    },
    {
        "question": "Which one of the following is related to Ex-situ conservation of threatened animals and plants?",
        "options": ["Wildlife Safari parks", "Biodiversity hot spots", "Amazon rainforest", "Himalayan region"],
        "correct_option_id": 0,
        "explanation": "Wildlife safari parks/zoological parks represent ex-situ conservation, i.e., conservation outside the natural habitat.",
    },
    {
        "question": "Good vision depends on adequate intake of carotene rich food. Select the best option from the following statements. (NEET 2017) (a) Vitamin A derivatives are formed from carotene (b) The photopigments are embedded in the membrane discs of the inner segment (c) Retinal is a derivative of Vitamin A (d) Retinal is a light absorbing part of all the visual photopigments",
        "options": ["(a) and (b)", "(a), (c) and (d)", "(a) and (c)", "(b), (c) and (d)"],
        "correct_option_id": 1,
        "explanation": "Vitamin A derivatives (retinal) form from carotene (a), retinal is indeed a Vitamin A derivative (c), and retinal is the light-absorbing part of all visual photopigments (d); statement (b) is incorrect since photopigments are in the outer segment, not inner segment.",
    },
    {
        "question": "Thalassemia and sickle cell anemia are caused due to a problem in globin molecule synthesis. Select the correct statement.",
        "options": ["Both are due to a qualitative defect in globin chain synthesis", "Both are due to a quantitative defect in globin chain synthesis", "Thalassemia is due to less synthesis of globin molecules", "Sickle cell anemia is due to a quantitative problem of globin molecules"],
        "correct_option_id": 2,
        "explanation": "Thalassemia results from reduced (quantitative) synthesis of globin chains, whereas sickle cell anemia results from a qualitative (structural) defect in the globin chain.",
    },
    {
        "question": "Which of the following are not polymeric?",
        "options": ["nucleic acids", "proteins", "polysaccharides", "Lipids"],
        "correct_option_id": 3,
        "explanation": "Lipids are not polymers; unlike nucleic acids, proteins, and polysaccharides, they are not built from repeating monomeric units.",
    },
    {
        "question": "A disease caused by an autosomal primary non-disjunction is:",
        "options": ["Down's Syndrome", "klinefelter's Syndrome", "Turner's Syndrome", "Sickle Cell Anemia"],
        "correct_option_id": 0,
        "explanation": "Down's syndrome (trisomy of chromosome 21) results from non-disjunction of an autosome.",
    },
    {
        "question": "With reference to factors affecting the rate of photosynthesis, which of the following statements is not correct?",
        "options": ["Light saturation for CO2 fixation occurs at 10% of full sunlight", "increasing atmospheric CO2 concentration up to 0.05% can enhance CO2 fixation rate", "C3 plants respond to higher temperatures with enhanced photosynthesis while C4 plants have much lower temperature optimum", "Tomato is a greenhouse crop which can be grown in CO2 enriched atmosphere for higher yield"],
        "correct_option_id": 2,
        "explanation": "This statement is incorrect because C4 plants (not C3) actually show enhanced photosynthesis at higher temperatures, while C3 plants have a lower temperature optimum.",
    },
    {
        "question": "Fruit and leaf drop at early stages can be prevented by the application of:",
        "options": ["Cytokinins", "Ethylene", "Auxins", "Gibberellic acid"],
        "correct_option_id": 2,
        "explanation": "Auxins help prevent the premature abscission (dropping) of fruits and leaves.",
    },
    {
        "question": "The region of Biosphere Reserve which is legally protected and where no human activity is allowed is known as:",
        "options": ["Core zone", "Buffer zone", "Transition zone", "Restoration zone"],
        "correct_option_id": 0,
        "explanation": "The core zone of a Biosphere Reserve is legally protected, and no human activity is permitted there.",
    },
    {
        "question": "In case of poriferans, the spongocoel is lined with flagellated cells called:",
        "options": ["ostia", "oscula", "choanocytes", "mesenchymal cells"],
        "correct_option_id": 2,
        "explanation": "Choanocytes (collar cells) line the spongocoel and their flagellar movement generates water currents through the sponge.",
    },
    {
        "question": "A decrease in blood pressure/volume will not cause the release of:",
        "options": ["Renin", "Atrial natriuretic Factor", "Aldosterone", "ADH"],
        "correct_option_id": 1,
        "explanation": "Atrial Natriuretic Factor (ANF) is released in response to an increase (not decrease) in blood volume/pressure, and it acts to lower blood pressure.",
    },
    {
        "question": "A dioecious flowering plant prevents both:",
        "options": ["Autogamy and xenogamy", "Autogamy and geitonogamy", "Geitonogamy and xenogamy", "Cleistogamy and xenogamy"],
        "correct_option_id": 1,
        "explanation": "Since male and female flowers occur on separate plants in dioecious species, both self-pollination (autogamy) and geitonogamy (pollination between flowers of the same plant) are prevented.",
    },
    {
        "question": "Which of the following facilitates opening of stomatal aperture?",
        "options": ["Contraction of outer wall of guard cells", "Decrease in turgidity of tuard cells", "Radial orientation of cellulose microfibrils in the cell wall of guard cells", "Longitudinal orientation of cellulose microfibrils in the cell wall of guard cells"],
        "correct_option_id": 2,
        "explanation": "The radial orientation of cellulose microfibrils in guard cell walls causes them to bulge outward (rather than expand in length) when turgid, opening the stomatal pore.",
    },
    {
        "question": "The DNA fragments separated on an agarose gel can be visualised after staining with",
        "options": ["Bromophenol blue", "Acetocarmine", "Aniline blue", "Ethidium bromide"],
        "correct_option_id": 3,
        "explanation": "Ethidium bromide intercalates into DNA and fluoresces under UV light, enabling visualization of separated DNA fragments.",
    },
    {
        "question": "Which statement is wrong for Krebs' cycle?",
        "options": ["There are three points in the cycle where NAD+ is reduced to NADH+H+", "There is one point in the cycle where FAD+ is reduced to FADH2", "During conversion of succinyl CoA to succinic acid, a molecule of GTP is synthesised", "The cycle starts with condensation of acetyl group (acetyl CoA) with pyruvic acid yield citric acid"],
        "correct_option_id": 3,
        "explanation": "The Krebs cycle starts with the condensation of acetyl CoA with oxaloacetic acid (not pyruvic acid) to form citric acid.",
    },
    {
        "question": "Mycorrhizae are the example of",
        "options": ["Fungistasis", "Amensalism", "Antibiosis", "Mutualism"],
        "correct_option_id": 3,
        "explanation": "Mycorrhizae represent a mutualistic symbiotic association between fungi and plant roots.",
    },
    {
        "question": "The pivot joing between atlas and axis is a type of",
        "options": ["fibrous joint", "Cartilaginous joint", "Synovial joint", "saddle joint"],
        "correct_option_id": 2,
        "explanation": "The atlanto-axial joint (between atlas and axis vertebrae) is a pivot-type synovial joint.",
    },
    {
        "question": "Which of the following is correctly matched for the product produced by them?",
        "options": ["Acetoacter aceti : Antibiotics", "Methanobacterium : lactic acid", "Penicillium notatum : Acetic acid", "Sacchromyces cerevsiae : Ethanol"],
        "correct_option_id": 3,
        "explanation": "Saccharomyces cerevisiae (yeast) ferments sugars to produce ethanol.",
    },
    {
        "question": "Frog's heart when taken out of the body continues to beat for sometime. Select the best option from following statements (NEET 2017) (a) Frog is a poikilotherm (b) Frog does not have any coronary circulation (c) Heart is \"Myogenic\" in nature (d) heat is autoexcitable",
        "options": ["Only (c)", "Only (d)", "(a) and (b)", "(c) and (d)"],
        "correct_option_id": 3,
        "explanation": "The heart continues to beat outside the body because it is myogenic in nature (c) — the heartbeat originates within the heart itself — and is autoexcitable (d), not dependent on external nervous stimulation.",
    },
    {
        "question": "Myelin sheath is produced by",
        "options": ["Schwann cell and Oligodendrocytes", "Astrocytes and Schwann cells", "Oligodendrocytes and Osteoclasts", "Osteoclasts and Astrocytes"],
        "correct_option_id": 0,
        "explanation": "In the peripheral nervous system, Schwann cells produce the myelin sheath, while in the central nervous system it is produced by oligodendrocytes.",
    },
    {
        "question": "Capacitation occurs in",
        "options": ["Rete testis", "Epididymis", "Vas deferens", "Female Reproductive tract"],
        "correct_option_id": 3,
        "explanation": "Capacitation, the process by which sperm gain fertilizing capability, occurs within the female reproductive tract.",
    },
    {
        "question": "The morphological nature of the edible part of coconut is",
        "options": ["Perisperm", "Cotyledon", "Endosperm", "Pericarp"],
        "correct_option_id": 2,
        "explanation": "The edible white portion of the coconut is the endosperm.",
    },
    {
        "question": "Which of the following is made up of dead cells",
        "options": ["Xylem parenchyma", "Collenchyma", "Phellem", "Phloem"],
        "correct_option_id": 2,
        "explanation": "Phellem (cork) is composed of dead cells with suberin-impregnated (suberized) walls.",
    },
    {
        "question": "In case of a couple where the male is having a very low sperm count, which technique will be suitable for fertilisation",
        "options": ["Intrauterine transfer", "Gamete intracytoplasmic fallopian transfer", "Artificial Insemination", "Intracytoplasmic sperm injection"],
        "correct_option_id": 2,
        "explanation": "According to the given answer key, Artificial Insemination is credited as correct; note that for very low sperm counts, Intracytoplasmic Sperm Injection (ICSI) is generally the more specific assisted reproductive technique used.",
    },
    {
        "question": "Which of the following RNAs should be most abundant in animal cell",
        "options": ["r-RNA", "t-RNA", "m-RNA", "mi-RNA"],
        "correct_option_id": 0,
        "explanation": "Ribosomal RNA (rRNA) constitutes the majority (about 80%) of total cellular RNA, as it is a structural component of ribosomes.",
    },
    {
        "question": "The vascular cambium normally gives rise to",
        "options": ["Phelloderm", "Primary phloem", "Secondary xylem", "Periderm"],
        "correct_option_id": 2,
        "explanation": "The vascular cambium produces secondary xylem (wood) and secondary phloem through its cell divisions.",
    },
    {
        "question": "Which of the following options gives the correct sequences of events during mitosis?",
        "options": ["Condensation → nuclear membrane disassembly → crossing over → segregation → telophase", "Condensation → nuclear membrane disassembly → arrangement at equator → centromere division → segregation → telophase", "Condensation → crossing over → nuclear membrane disassembly → segregation → telophase", "Condensation → arrangement at equator → centromere division → segregation → telophase"],
        "correct_option_id": 1,
        "explanation": "The correct mitotic sequence is: chromosome condensation, nuclear envelope breakdown, alignment at the metaphase plate (equator), centromere division, segregation of chromatids (anaphase), and telophase.",
    },
    {
        "question": "Which of the following option best represents the enzyme composition of pancreatic juice?",
        "options": ["amylase, peptidase, trypsinogen, rennin", "amylase, pepsin, trypsinogen, maltase", "peptidase, amylase, pepsin, rennin", "lipase, amylase, trypsinogen, procarboxypeptidase"],
        "correct_option_id": 3,
        "explanation": "Pancreatic juice contains lipase, amylase, trypsinogen, and procarboxypeptidase (along with other enzymes) for digestion of fats, carbohydrates, and proteins.",
    },
    {
        "question": "Attractants and rewards are required for:",
        "options": ["Anemophily", "Entomophily", "Hydrophily", "Cleistogamy"],
        "correct_option_id": 1,
        "explanation": "Entomophily (insect pollination) requires attractants such as color, fragrance, and rewards like nectar to lure pollinating insects.",
    },
]
