"""
Question bank: AIPMT 2011 (Prelim Examination) - Biology (Solved Answers).

92 questions parsed from AIPMT 2011 (Prelim Examination)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "The \"Eyes\" of the potato tuber are",
        "options": ["Axillary buds", "Root buds", "Flower buds", "Shoot buds"],
        "correct_option_id": 0,
        "explanation": "Axillary buds develop at the nodes/notches (eyes) of the potato tuber.",
    },
    {
        "question": "Organisms called Methanogens are most abundant in a",
        "options": ["Hot spring", "Sulphur rock", "Cattle yard", "Polluted stream"],
        "correct_option_id": 2,
        "explanation": "Methanogens are archaebacteria abundant in cattle yards and paddy fields.",
    },
    {
        "question": "Which one of the following have the highest number of species in nature?",
        "options": ["Angiosperms", "Fungi", "Insects", "Birds"],
        "correct_option_id": 2,
        "explanation": "The largest phylum in the animal kingdom is Arthropoda, and the largest class is Insecta with about 7,50,000 species.",
    },
    {
        "question": "Archegoniophore is present in",
        "options": ["Funaria", "Marchantia", "Chara", "Adiantum"],
        "correct_option_id": 1,
        "explanation": "The archegoniophore is a stalk bearing an archegonial cluster at its tip, found in Marchantia.",
    },
    {
        "question": "Compared with the gametophytes of the bryophytes the gametophytes of vascular plants tend to be",
        "options": ["Smaller and to have smaller sex organs", "Smaller but to have larger sex organs", "Larger but to have smaller sex organs", "Larger and to have larger sex organs"],
        "correct_option_id": 0,
        "explanation": "Gametophytes are reduced and few-celled in all vascular plants.",
    },
    {
        "question": "The gametophyte is not an independent, free-living generation in",
        "options": ["Pinus", "Polytrichum", "Adiantum", "Marchantia"],
        "correct_option_id": 0,
        "explanation": "In gymnosperms (like Pinus) and angiosperms, the gametophyte is dependent on the sporophyte.",
    },
    {
        "question": "Important site for formation of glycoproteins and glycolipids is",
        "options": ["Lysosome", "Vacuole", "Golgi apparatus", "Plastid"],
        "correct_option_id": 2,
        "explanation": "The Golgi complex performs glycosyl transferase activity, adding glycans to lipids and proteins.",
    },
    {
        "question": "Peptide synthesis inside a cell takes place in",
        "options": ["Ribosomes", "Chloroplast", "Mitochondria", "Chromoplast"],
        "correct_option_id": 0,
        "explanation": "Ribosomes are the site of peptide bond formation.",
    },
    {
        "question": "In eubacteria, a cellular component that resembles eukaryotic cell is",
        "options": ["Cell wall", "Plasma membrane", "Nucleus", "Ribosomes"],
        "correct_option_id": 1,
        "explanation": "A lipoprotein cell membrane is found in both eubacteria and eukaryotes, though their ribosomes differ in kind.",
    },
    {
        "question": "Mutations can be induced with",
        "options": ["Gamma radiations", "Infra Red radiations", "I A A", "Ethylene"],
        "correct_option_id": 0,
        "explanation": "Mutations can be induced by high-energy radiations like UV and gamma rays, which alter DNA structure.",
    },
    {
        "question": "A collection of plants and seeds having diverse alleles of all the genes of a crop is called",
        "options": ["Genome", "Herbarium", "Germplasm", "Gene library"],
        "correct_option_id": 2,
        "explanation": "Germplasm can be selected as seeds or plantlets for their superior traits.",
    },
    {
        "question": "Which one of the following also acts as a catalyst in a bacterial cell?",
        "options": ["23s rRNA", "5s rRNA", "snRNA", "hnRNA"],
        "correct_option_id": 0,
        "explanation": "23S rRNA is a catalytic RNA (ribozyme).",
    },
    {
        "question": "Which one of the following statements is correct?",
        "options": ["Flower of tulip is a modified shoot", "In tomato, fruit is a capsule", "Seeds of orchids have oil-rich endosperms", "Placentation in primrose is basal"],
        "correct_option_id": 0,
        "explanation": "Tomato fruit is a berry, orchid seeds lack endosperm, and primrose has free central placentation — making option 1 correct.",
    },
    {
        "question": "The correct floral formula of chilli is",
        "options": ["⊕♀ K5 C5 A(5) G2", "⊕♀ K(5) C5 A5 G(2)", "⊕♀ K(5) C(5) A5 G(2)", "⊕♀ K5 C(5) A(5) G2"],
        "correct_option_id": 2,
        "explanation": "Chilli belongs to family Solanaceae, whose floral formula has gamosepalous calyx, gamopetalous corolla, polyandrous stamens, and a syncarpous bicarpellary superior ovary — matching option 3.",
    },
    {
        "question": "Nitrifying bacteria",
        "options": ["Reduce nitrates to free nitrogen", "Oxidize ammonia to nitrates", "Convert free nitrogen to nitrogen compounds", "Convert proteins into ammonia"],
        "correct_option_id": 1,
        "explanation": "Nitrification occurs in two steps: NH3 → NO2⁻ (by Nitrosomonas) → NO3⁻ (by Nitrobacter/Nitrocystis); i.e. ammonia is oxidized to nitrate.",
    },
    {
        "question": "The function of leghaemoglobin in the root nodules of legumes is",
        "options": ["Expression of nif gene", "Inhibition of nitrogenase activity", "Oxygen removal", "Nodule differentiation"],
        "correct_option_id": 2,
        "explanation": "Leghaemoglobin is an oxygen scavenger that protects nitrogenase from inactivation by oxygen.",
    },
    {
        "question": "Which one of the following elements in plants is not remobilised?",
        "options": ["Sulphur", "Phosphorus", "Calcium", "Potassium"],
        "correct_option_id": 2,
        "explanation": "Calcium is not remobilised as it is a structural component of the cell.",
    },
    {
        "question": "A drupe develops in",
        "options": ["Tomato", "Mango", "Wheat", "Pea"],
        "correct_option_id": 1,
        "explanation": "Mango develops a drupe fruit; tomato is a berry, wheat a caryopsis, and pea a legume.",
    },
    {
        "question": "Ground tissue includes",
        "options": ["All tissues internal to endodermis", "All tissues external to endodermis", "All tissues except epidermis and vascular bundles", "Epidermis and cortex"],
        "correct_option_id": 2,
        "explanation": "The ground tissue system includes cortex, endodermis, pericycle and pith — i.e. all tissues except epidermis and vascular bundles.",
    },
    {
        "question": "In land plants the guard cells differ from other epidermal cells in having",
        "options": ["Chloroplasts", "Cytoskeleton", "Mitochondria", "Endoplasmic reticulum"],
        "correct_option_id": 0,
        "explanation": "Guard cells are specialised chlorophyllous (chloroplast-containing) epidermal cells, unlike other epidermal cells.",
    },
    {
        "question": "The ovary is half inferior in flowers of",
        "options": ["Guava", "Peach", "Cucumber", "Cotton"],
        "correct_option_id": 1,
        "explanation": "A half-inferior ovary occurs in perigynous flowers, as seen in peach.",
    },
    {
        "question": "The cork cambium, cork and secondary cortex are collectively called",
        "options": ["Phellem", "Phelloderm", "Phellogen", "Periderm"],
        "correct_option_id": 3,
        "explanation": "Phellem (cork), phellogen (cork cambium) and phelloderm (secondary cortex) together are called the periderm.",
    },
    {
        "question": "Which one of the following is wrongly matched?",
        "options": ["Cassia – Imbricate aestivation", "Root pressure – Guttation", "Puccinia – Smut", "Root – Exarch protoxylem"],
        "correct_option_id": 2,
        "explanation": "Puccinia is a rust fungus, not a smut fungus, making this pairing incorrect.",
    },
    {
        "question": "Flowers are Zygomorphic in",
        "options": ["Datura", "Mustard", "Gulmohur", "Tomato"],
        "correct_option_id": 2,
        "explanation": "Datura, mustard and tomato have actinomorphic flowers, while Gulmohur has zygomorphic flowers.",
    },
    {
        "question": "CAM helps the plants in",
        "options": ["Reproduction", "Conserving water", "Secondary growth", "Disease resistance"],
        "correct_option_id": 1,
        "explanation": "CAM plants are succulents with water-storing cells, helping them conserve water in arid conditions.",
    },
    {
        "question": "Of the total incident solar radiation the proportion of PAR is",
        "options": ["More than 80%", "About 70%", "About 60%", "Less than 50%"],
        "correct_option_id": 3,
        "explanation": "Photosynthetically Active Radiation (PAR) constitutes less than 50% of total incident solar radiation, of which plants capture only 2-10%.",
    },
    {
        "question": "A prokaryotic autotrophic nitrogen fixing symbiont found in",
        "options": ["Pisum", "Alnus", "Cycas", "Cicer"],
        "correct_option_id": 2,
        "explanation": "Anabaena cycadae, a blue-green alga (BGA), is found as a symbiont in the coralloid roots of Cycas.",
    },
    {
        "question": "Nucellar polyembryony is reported in species of",
        "options": ["Brassica", "Citrus", "Gossypium", "Triticum"],
        "correct_option_id": 1,
        "explanation": "Nucellar polyembryony is common in Citrus, mango and Opuntia.",
    },
    {
        "question": "Filiform apparatus is a characteristic feature of",
        "options": ["Zygote", "Suspensor", "Egg", "Synergid"],
        "correct_option_id": 3,
        "explanation": "The filiform apparatus consists of finger-like projections at the micropylar end of synergids.",
    },
    {
        "question": "What would be the number of chromosomes of the aleurone cells of a plant with 42 chromosomes in its root tip cells?",
        "options": ["21", "42", "63", "84"],
        "correct_option_id": 2,
        "explanation": "The aleurone layer is triploid (3n), while root tip cells are diploid (2n = 42), so aleurone has 63 chromosomes.",
    },
    {
        "question": "Wind pollination is common in",
        "options": ["Orchids", "Legumes", "Lilies", "Grasses"],
        "correct_option_id": 3,
        "explanation": "Wind pollination (anemophily) is common in grasses and gymnosperms.",
    },
    {
        "question": "In which one of the following pollination is autogamous?",
        "options": ["Cleistogamy", "Geitonogamy", "Xenogamy", "Chasmogamy"],
        "correct_option_id": 0,
        "explanation": "Self-pollination (autogamy) is favoured by cleistogamy, where flowers do not open.",
    },
    {
        "question": "Mass of living matter at a trophic level in an area at any time is called",
        "options": ["Standing state", "Standing crop", "Detritus", "Humus"],
        "correct_option_id": 1,
        "explanation": "The standing crop represents the mass of living matter at a given trophic level in an area at a given time.",
    },
    {
        "question": "Which one of the following statements is wrong in case of Bhopal tragedy?",
        "options": ["It took place in the night of December 2/3/1984", "Methyl Isocyanate gas leakage took place", "Thousands of human beings died", "Radioactive fall out engulfed Bhopal"],
        "correct_option_id": 3,
        "explanation": "The Bhopal tragedy was caused by Methyl Isocyanate gas leakage, not radioactivity.",
    },
    {
        "question": "Secondary sewage treatment is mainly a",
        "options": ["Biological process", "Physical process", "Mechanical process", "Chemical process"],
        "correct_option_id": 0,
        "explanation": "Secondary sewage treatment involves the activity of aerobic and anaerobic microbes, making it a biological process.",
    },
    {
        "question": "Eutrophication is often seen in",
        "options": ["Mountains", "Deserts", "Fresh water lakes", "Ocean"],
        "correct_option_id": 2,
        "explanation": "Eutrophication is the enrichment of lakes with phosphates, nitrates etc., commonly seen in freshwater lakes.",
    },
    {
        "question": "Large Woody Vines are more commonly found in",
        "options": ["Alpine forests", "Temperate forests", "Mangroves", "Tropical rainforests"],
        "correct_option_id": 3,
        "explanation": "Lianas (woody vines) and epiphytes are more common in tropical rainforests.",
    },
    {
        "question": "Which one of the following expanded forms of the following acronyms is correct?",
        "options": ["IUCN = International Union for Conservation of Nature and Natural Resources", "IPCC = International Panel for Climate Change", "UNEP = United Nations Environmental Policy", "EPA = Environmental Pollution Agency"],
        "correct_option_id": 0,
        "explanation": "IUCN correctly stands for International Union for Conservation of Nature and Natural Resources (IPCC actually stands for Intergovernmental Panel for Climate Change).",
    },
    {
        "question": "Which one of the following statements is correct for secondary succession?",
        "options": ["It is similar to primary succession except that it has a relatively fast pace", "It begins on a bare rock", "It occurs on a deforested site", "It follows primary succession"],
        "correct_option_id": 2,
        "explanation": "Secondary succession occurs on abandoned farmlands, burned or cut forests, and flooded lands, i.e. deforested sites.",
    },
    {
        "question": "Which one of the following shows maximum genetic diversity in India?",
        "options": ["Mango", "Groundnut", "Rice", "Maize"],
        "correct_option_id": 2,
        "explanation": "Rice has more than 50,000 genetically different strains in India, more than mango's 1000 varieties.",
    },
    {
        "question": "Which one of the following is not a biofertilizer?",
        "options": ["Mycorrhiza", "Agrobacterium", "Rhizobium", "Nostoc"],
        "correct_option_id": 1,
        "explanation": "Agrobacterium is a gene transfer agent used in genetic engineering, not a biofertilizer.",
    },
    {
        "question": "Which one of the following acts as a physiological barrier to the entry of microorganisms in human body?",
        "options": ["Skin", "Epithelium of Urogenital tract", "Tears", "Monocytes"],
        "correct_option_id": 2,
        "explanation": "Physiological barriers to microbial entry include tears in the eyes, saliva in the mouth, and HCl in the stomach.",
    },
    {
        "question": "Which one of the following helps in absorption of phosphorus from soil by plants?",
        "options": ["Anabaena", "Glomus", "Rhizobium", "Frankia"],
        "correct_option_id": 1,
        "explanation": "Glomus is an endomycorrhizal fungus that helps in phosphorus absorption.",
    },
    {
        "question": "'Himgiri' developed by hybridisation and selection for disease resistance against rust pathogens is a variety of",
        "options": ["Wheat", "Chilli", "Maize", "Sugarcane"],
        "correct_option_id": 0,
        "explanation": "Himgiri is a wheat variety resistant to leaf and stripe rust, and hill bunt.",
    },
    {
        "question": "Which of the followings is mainly produced by the activity of anaerobic bacteria on sewage?",
        "options": ["Marsh gas", "Laughing gas", "Propane", "Mustard gas"],
        "correct_option_id": 0,
        "explanation": "Marsh gas (methane) is produced by the activity of methanogens (anaerobic bacteria) on sewage.",
    },
    {
        "question": "Agarose extracted from sea weeds finds use in",
        "options": ["Gel electrophoresis", "Spectrophotometry", "Tissue culture", "PCR"],
        "correct_option_id": 0,
        "explanation": "Agarose extracted from seaweeds is used in gel electrophoresis.",
    },
    {
        "question": "Maximum number of existing transgenic animals is of",
        "options": ["Pig", "Fish", "Mice", "Cow"],
        "correct_option_id": 2,
        "explanation": "About 95% of existing transgenic animals are mice.",
    },
    {
        "question": "Continuous addition of sugars in 'fed batch' fermentation is done to",
        "options": ["Degrade sewage", "Produce methane", "Obtain antibiotics", "Purify enzymes"],
        "correct_option_id": 3,
        "explanation": "Continuous addition of sugar in fed-batch fermentation is done to purify enzymes.",
    },
    {
        "question": "The process of RNA interference has been used in the development of plants resistant to",
        "options": ["Insects", "Nematodes", "Fungi", "Viruses"],
        "correct_option_id": 1,
        "explanation": "RNAi has been used to develop plants resistant to nematodes such as Meloidogyne incognita.",
    },
    {
        "question": "\"Jaya\" and \"Ratna\" developed for green revolution in India are the varieties of",
        "options": ["Bajra", "Maize", "Rice", "Wheat"],
        "correct_option_id": 2,
        "explanation": "Jaya and Ratna are high-yielding rice varieties released throughout the rice growing belts of India.",
    },
    {
        "question": "Which one of the following organisms is not an example of eukaryotic cells",
        "options": ["Amoeba proteus", "Paramecium caudatum", "Escherichia coli", "Euglena viridis"],
        "correct_option_id": 2,
        "explanation": "E. coli is a prokaryotic bacterium, unlike the other listed eukaryotic organisms.",
    },
    {
        "question": "Which one of the following animals is correctly matched with its particular named taxonomic category?",
        "options": ["Housefly - Musca, an order", "Tiger - Tigris, the species", "Cuttlefish - Mollusca, a class", "Humans - Primata, the family"],
        "correct_option_id": 1,
        "explanation": "The zoological name of tiger is Panthera tigris, where Panthera is the genus and tigris is the species.",
    },
    {
        "question": "Which one of the following groups of animals is correctly matched with its one characteristic feature without even a single exception?",
        "options": ["Mammalia: give birth to young ones", "Reptilia: possess 3-chambered heart with one incompletely divided ventricle", "Chordata: possess a mouth provided with an upper and a lower jaw", "Chondrichthyes: possess cartilaginous endoskeleton"],
        "correct_option_id": 3,
        "explanation": "All Chondrichthyes possess a cartilaginous endoskeleton without exception.",
    },
    {
        "question": "What will you look for to identify the sex of the following?",
        "options": ["Male shark - Claspers borne on pelvic fins", "Female Ascaris - Sharply curved posterior end", "Male frog - A copulatory pad on the first digit of the hind limb", "Female cockroach - Anal cerci"],
        "correct_option_id": 0,
        "explanation": "In class Chondrichthyes, males possess claspers on the pelvic fins.",
    },
    {
        "question": "The ciliated columnar epithelial cells in humans are known to occur in",
        "options": ["Fallopian tubes and urethra", "Eustachian tube and stomach lining", "Bronchioles and Fallopian tubes", "Bile duct and oesophagus"],
        "correct_option_id": 2,
        "explanation": "Ciliated columnar epithelium lines the bronchioles and fallopian tubes.",
    },
    {
        "question": "Select the correct option with respect to mitosis",
        "options": ["Chromosomes move to the spindle equator and get aligned along equatorial plate in metaphase", "Chromatids separate but remain in the centre of the cell in anaphase", "Chromatids start moving towards opposite poles in telophase", "Golgi complex and endoplasmic reticulum are still visible at the end of prophase"],
        "correct_option_id": 0,
        "explanation": "In metaphase, chromosomes align along the equatorial plate; chromatids show poleward movement in anaphase (not telophase), and Golgi/ER disappear by late prophase.",
    },
    {
        "question": "What was the most significant trend in the evolution of modern man (Homo sapiens) from his ancestors?",
        "options": ["Increasing brain capacity", "Upright posture", "Shortening of jaws", "Binocular vision"],
        "correct_option_id": 0,
        "explanation": "The most significant evolutionary trend in modern man was increasing brain capacity.",
    },
    {
        "question": "Which one of the following conditions correctly describes the manner of determining the sex in the given example?",
        "options": ["Homozygous sex chromosomes (XX) produce male in Drosophila", "Homozygous sex chromosomes (ZZ) determine female sex in birds", "XO type of sex chromosomes determine male sex in grasshopper", "XO condition in humans as found in Turner Syndrome, determines female sex"],
        "correct_option_id": 2,
        "explanation": "In grasshoppers, the XO condition (absence of a second sex chromosome) determines maleness.",
    },
    {
        "question": "A person with unknown blood group under ABO system, has suffered much blood loss in an accident and needs immediate blood transfusion. His one friend who has a valid certificate of his own blood type, offers for blood donation without delay. What would have been the type of blood group of the donor friend?",
        "options": ["Type A", "Type B", "Type AB", "Type O"],
        "correct_option_id": 3,
        "explanation": "Blood group O is the universal donor since there are no antigens on the surface of RBCs.",
    },
    {
        "question": "What are those structures that appear as 'beads-on-string' in the chromosomes when viewed under electron microscope?",
        "options": ["Base pairs", "Genes", "Nucleotides", "Nucleosomes"],
        "correct_option_id": 3,
        "explanation": "Nucleosomes, consisting of an octameric histone core wrapped by dsDNA, appear as \"beads-on-a-string.\"",
    },
    {
        "question": "Which of the following is correctly stated as happens in the common cockroach?",
        "options": ["The food is ground by mandibles and gizzard", "Malpighian tubules are excretory organ projecting out from the colon", "Oxygen is transported by haemoglobin in blood", "Nitrogenous excretory product is urea"],
        "correct_option_id": 0,
        "explanation": "In cockroaches, food is ground by mandibles and the gizzard; they lack an oxygen-transporting pigment and excrete uric acid, not urea.",
    },
    {
        "question": "A large proportion of oxygen is left unused in the human blood even after its uptake by the body tissues. This O2",
        "options": ["Helps in releasing more O2 to the epithelium tissues", "Acts as a reserve during muscular exercise", "Raises the pCO2 of blood to 75 mm of Hg", "Is enough to keep oxyhaemoglobin saturation at 96%"],
        "correct_option_id": 1,
        "explanation": "Tissues utilise only 25% of the O2 carried by arterial blood; the remaining O2 acts as a reserve during muscular exercise.",
    },
    {
        "question": "Which one of the following enzymes carries on the initial step in the digestion of milk in humans?",
        "options": ["Trypsin", "Pepsin", "Rennin", "Lipase"],
        "correct_option_id": 1,
        "explanation": "In humans, pepsin acts on the milk protein caseinogen in the stomach as the initial digestive step; rennin is present only in small amounts in infants.",
    },
    {
        "question": "Which one of the following is not a part of a renal pyramid?",
        "options": ["Loops of Henle", "Peritubular capillaries", "Convoluted tubules", "Collecting ducts"],
        "correct_option_id": 2,
        "explanation": "Convoluted tubules (PCT and DCT) are located in the renal cortex, whereas loops of Henle are found in the medullary pyramids.",
    },
    {
        "question": "One very special feature in the earthworm pheretima is that",
        "options": ["It has a long dorsal tubular heart", "Fertilisation of eggs occurs inside the body", "The typhlosole greatly increases the effective absorption area of the digested food in the intestine", "The S-shaped setae embedded in the integument are the defensive weapons used against the enemies"],
        "correct_option_id": 2,
        "explanation": "The mid-dorsal villi (typhlosole) in earthworms greatly increases the effective absorption area of digested food.",
    },
    {
        "question": "Two friends are eating together on a dining table. One of them suddenly starts coughing while swallowing some food. This coughing would have been due to improper movement of",
        "options": ["Tongue", "Epiglottis", "Diaphragm", "Neck"],
        "correct_option_id": 1,
        "explanation": "Sudden coughing while swallowing food is due to improper movement of the epiglottis, allowing food to enter the respiratory tract.",
    },
    {
        "question": "Arteries are best defined as the vessels which",
        "options": ["Carry blood from one visceral organ to another visceral organ", "Supply oxygenated blood to the different organs", "Carry blood away from the heart to different organs", "Break up into capillaries which reunite to form a vein"],
        "correct_option_id": 2,
        "explanation": "Arteries are best defined as vessels that carry blood away from the heart to different organs.",
    },
    {
        "question": "'Bundle of His' is a part of which one of the following organs in humans?",
        "options": ["Pancreas", "Brain", "Heart", "Kidney"],
        "correct_option_id": 2,
        "explanation": "The Bundle of His is part of the conducting system of the human heart.",
    },
    {
        "question": "The purplish red pigment rhodopsin contained in the rods type of photoreceptor cells of the human eye, is a derivative of",
        "options": ["Vitamin A", "Vitamin B1", "Vitamin C", "Vitamin D"],
        "correct_option_id": 0,
        "explanation": "Vitamin A is the precursor of rhodopsin, the purplish-red pigment found in rod cells of the human eye.",
    },
    {
        "question": "Which one of the following plasma proteins is involved in the coagulation of blood?",
        "options": ["Fibrinogen", "An albumin", "Serum amylase", "A globulin"],
        "correct_option_id": 0,
        "explanation": "Fibrinogen is a plasma protein directly involved in the clotting of blood.",
    },
    {
        "question": "When a neuron is in resting state i.e. not conducting any impulse, the axonal membrane is",
        "options": ["Comparatively more permeable to K+ ions and nearly impermeable to Na+ ions", "Comparatively more permeable to Na+ ions and nearly impermeable to K+ ions", "Equally permeable to both Na+ and K+ ions", "Impermeable to both Na+ and K+ ions"],
        "correct_option_id": 0,
        "explanation": "At resting state, the axonal membrane is more permeable to K+ ions and nearly impermeable to Na+ ions.",
    },
    {
        "question": "Which one of following correctly explains the function of a specific part of a human nephron?",
        "options": ["Afferent arteriole: Carries the blood away from the glomerulus towards renal vein", "Podocytes: Create minute spaces (slit pores) for the filtration of blood into the Bowman's capsule", "Henle's loop: Most reabsorption of the major substances from the glomerular filtrate", "Distal convoluted tubule: Reabsorption of K+ ions into the surrounding blood capillaries"],
        "correct_option_id": 1,
        "explanation": "Podocytes are specialised epithelial cells in Bowman's capsule that form foot-like processes creating filtration slits for blood filtration.",
    },
    {
        "question": "Uricotelic mode of passing out nitrogenous wastes is found in",
        "options": ["Insects and Amphibians", "Reptiles and Birds", "Birds and Annelids", "Amphibians and Reptiles"],
        "correct_option_id": 1,
        "explanation": "Reptiles and birds excrete nitrogenous wastes mainly as uric acid, i.e. they are uricotelic.",
    },
    {
        "question": "Which one of the following statements is correct regarding blood",
        "options": ["190/110 mmHg may harm vital organs like brain and kidney", "130/90 mmHg is considered high and requires treatment", "100/55 mmHg is considered an ideal blood pressure", "105/50 mmHg makes one very active"],
        "correct_option_id": 0,
        "explanation": "Hypertension at 190/110 mmHg can harm vital organs like the brain and kidneys.",
    },
    {
        "question": "Which one of the following statements is correct with respect to kidney function regulation?",
        "options": ["During summer when body loses lot of water by evaporation, the release of ADH is suppressed", "When someone drinks lot of water, ADH release is suppressed", "Exposure to cold temperature stimulates ADH release", "An increase in glomerular blood flow stimulates formation of Angiotensin II"],
        "correct_option_id": 1,
        "explanation": "Drinking excess water decreases blood osmolarity, which inhibits ADH release, causing more water to be eliminated.",
    },
    {
        "question": "The testes in humans are situated outside the abdominal cavity inside a pouch called scrotum. The purpose served is for",
        "options": ["Providing a secondary sexual feature for exhibiting the male sex", "Maintaining the scrotal temperature lower than the internal body temperature", "Escaping any possible compression by the visceral organs", "Providing more space for the growth of epididymis"],
        "correct_option_id": 1,
        "explanation": "The scrotal sac maintains a temperature about 2.5°C lower than internal body temperature, necessary for spermatogenesis.",
    },
    {
        "question": "Which one of the following is the most widely accepted method of contraception in India, as at present?",
        "options": ["IUDs' (Intra uterine devices)", "Cervical caps", "Tubectomy", "Diaphragms"],
        "correct_option_id": 0,
        "explanation": "IUDs are the most widely accepted method of contraception in India.",
    },
    {
        "question": "If for some reason, the vasa efferentia in the human reproductive system get blocked, the gametes will not be transported from",
        "options": ["Vagina to uterus", "Testes to epididymis", "Epididymis to vas deferens", "Ovary to uterus"],
        "correct_option_id": 1,
        "explanation": "Gametes travel from seminiferous tubules → rete testis → vasa efferentia → epididymis; blockage prevents transport from testes to epididymis.",
    },
    {
        "question": "Medical Termination of Pregnancy (MTP) is considered safe up to how many weeks of pregnancy?",
        "options": ["Six weeks", "Eight weeks", "Twelve weeks", "Eighteen weeks"],
        "correct_option_id": 2,
        "explanation": "MTPs are considered safe up to twelve weeks of pregnancy.",
    },
    {
        "question": "Which one of the following is categorised as a parasite in true sense?",
        "options": ["The cuckoo (koel) lays its egg in crow's nest", "The female Anopheles bites and sucks blood from humans", "Human foetus developing inside the uterus draws nourishment from the mother", "Head louse living on the human scalp as well as laying eggs on human hair"],
        "correct_option_id": 3,
        "explanation": "The head louse living and reproducing on the human scalp is a true parasite, unlike the mosquito or the brood-parasitic koel.",
    },
    {
        "question": "Which one of the following statements for pyramid of energy is incorrect, whereas the remaining three are correct?",
        "options": ["It is upright in shape", "Its base is broad", "It shows energy content of different trophic level organisms", "It is inverted in shape"],
        "correct_option_id": 3,
        "explanation": "The pyramid of energy is always upright and is never inverted.",
    },
    {
        "question": "Ethanol is commercially produced through a particular species of",
        "options": ["Aspergillus", "Saccharomyces (Yeast)", "Clostridium", "Trichoderma"],
        "correct_option_id": 1,
        "explanation": "Ethanol is produced commercially using a species of yeast (Saccharomyces).",
    },
    {
        "question": "Consider the following four conditions (a-d) and select the correct pair of them as adaptation to environment in desert lizards: (AIPMT 2011) (a) Burrowing in soil to escape high temperature (b) Losing heat rapidly from the body during high temperature (c) Bask in sun when temperature is low (d) Insulating body due to thick fatty dermis",
        "options": ["(a), (b)", "(c), (d)", "(a), (c)", "(b), (d)"],
        "correct_option_id": 2,
        "explanation": "Desert lizards adapt by burrowing in soil during high temperatures and basking in the sun when temperatures are low.",
    },
    {
        "question": "Which one of the following pairs of gases are the major cause of \"Greenhouse Effect\"?",
        "options": ["CO2 and N2O", "CO2 and O3", "CO2 and CO", "CFCs and SO2"],
        "correct_option_id": 0,
        "explanation": "CO2, CH4, N2O and CFCs are the common greenhouse gases.",
    },
    {
        "question": "Where will you look for the sporozoites of the malarial parasite?",
        "options": ["Salivary glands of freshly moulted female Anopheles mosquito", "Saliva of infected female Anopheles mosquito", "Red blood corpuscles of humans suffering from malaria", "Spleen of infected humans"],
        "correct_option_id": 1,
        "explanation": "Sporozoites, the infective stage of the malarial parasite, are present in the saliva of an infected female Anopheles mosquito.",
    },
    {
        "question": "When two unrelated individuals or lines are crossed, the performance of F1 hybrid is often superior to both its parents. This phenomenon is called",
        "options": ["Metamorphosis", "Heterosis", "Transformation", "Spheing"],
        "correct_option_id": 1,
        "explanation": "Heterosis is equivalent to hybrid vigour, where the F1 hybrid outperforms both parents.",
    },
    {
        "question": "A certain patient is suspected to be suffering from Acquired Immuno Deficiency Syndrome. Which diagnostic technique will you recommend for its detection?",
        "options": ["WIDAL", "ELISA", "MRI", "Ultra sound"],
        "correct_option_id": 1,
        "explanation": "ELISA is a standard diagnostic test used for the detection of AIDS.",
    },
    {
        "question": "At which stage of HIV infection does one usually show symptoms of AIDS?",
        "options": ["Within 15 days of sexual contact with an infected person", "When the infecting retrovirus enters host cells", "When viral DNA is produced by reverse transcriptase", "When HIV replicates rapidly in helper T-lymphocytes and damages large number of these"],
        "correct_option_id": 3,
        "explanation": "Symptoms of AIDS appear when there is significant depletion of helper T-cells due to rapid HIV replication.",
    },
    {
        "question": "Given below is a sample of a portion of DNA strand giving the base sequence on the opposite strands. What is so special shown in it? (AIPMT 2011) 5' ______ GAATTC ________ 3' 3' ________CTTAAG ________ 5'",
        "options": ["Palindromic sequence of base pairs", "Replication completed", "Deletion mutation", "Start codon at the 5' end"],
        "correct_option_id": 0,
        "explanation": "The given sequence is a palindromic sequence recognised by the restriction enzyme EcoRI.",
    },
    {
        "question": "The most common substrate used in distilleries for the production of ethanol is",
        "options": ["Molasses", "Corn meal", "Soya meal", "Ground gram"],
        "correct_option_id": 0,
        "explanation": "Molasses are the most commonly used substrate in distilleries for ethanol production.",
    },
    {
        "question": "An organism used as biofertilizer for raising soyabean crop is",
        "options": ["Nostoc", "Azotobacter", "Azospirillum", "Rhizobium"],
        "correct_option_id": 3,
        "explanation": "Soyabean is a legume that is symbiotically associated with Rhizobium.",
    },
    {
        "question": "There is a restriction endonuclease called EcoRI. What does \"co\" part in it stand for?",
        "options": ["coli", "colon", "coelom", "coenzyme"],
        "correct_option_id": 0,
        "explanation": "In EcoRI, 'co' stands for coli, the species of bacteria (E. coli) from which it was obtained.",
    },
]
