"""
Question bank: AIPMT 2015 (Code D) - Biology (Solved Answers).

82 questions parsed from AIPMT 2015 (Code D)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "In his classic experiments on pea plants, Mendel did not use",
        "options": ["Pod length", "Seed shape", "Flower position", "Seed colour"],
        "correct_option_id": 0,
        "explanation": "Mendel studied seed shape, seed colour, flower position/colour, pod shape/colour, stem height — but not pod length.",
    },
    {
        "question": "Which one of the following is not applicable to RNA?",
        "options": ["5' phosphoryl and 3' hydroxyl ends", "Heterocyclic nitrogenous bases", "Chargaff's rule", "Complementary base pairing"],
        "correct_option_id": 2,
        "explanation": "Chargaff's rule (A=T, G=C equivalence) applies to double-stranded DNA, not to single-stranded RNA.",
    },
    {
        "question": "Male gametophyte in angiosperms produces:",
        "options": ["Single sperm and a vegetative cell", "Single sperm and two vegetative cells", "Three sperms", "Two sperms and a vegetative cell"],
        "correct_option_id": 3,
        "explanation": "The mature male gametophyte (pollen grain) is 3-celled, containing 2 male gametes (sperms) and one vegetative cell.",
    },
    {
        "question": "Which of the following are not membrane-bound?",
        "options": ["Ribosomes", "Lysosomes", "Mesosomes", "Vacuoles"],
        "correct_option_id": 0,
        "explanation": "Ribosomes are naked cell organelles without a surrounding membrane.",
    },
    {
        "question": "The chitinous exoskeleton of arthropods is formed by the polymerisation of:",
        "options": ["D-glucosamine", "N-acetyl glucosamine", "lipoglycans", "keratin sulphate and chondroitin sulphate"],
        "correct_option_id": 1,
        "explanation": "Chitin, the arthropod exoskeleton material, is a polymer of N-acetyl glucosamine.",
    },
    {
        "question": "Among china rose, mustard, brinjal, potato, guava, cucumber, onion and tulip, how many plants have superior ovary?",
        "options": ["Six", "Three", "Four", "Five"],
        "correct_option_id": 0,
        "explanation": "China rose, mustard, brinjal, potato, onion and tulip (six plants) have a superior (hypogynous) ovary; guava and cucumber have inferior ovaries.",
    },
    {
        "question": "The function of the gap junction is to",
        "options": ["facilitate communication between adjoining cells by connecting the cytoplasm for rapid transfer of ions, small molecules and some large molecules.", "separate two cells from each other", "stop substance from leaking across a tissue", "performing cementing to keep neighbouring cells together."],
        "correct_option_id": 0,
        "explanation": "Gap junctions form cytoplasmic bridges between adjacent cells, enabling rapid transfer of ions and small molecules for cell-to-cell communication.",
    },
    {
        "question": "Which of the following immunoglobulins does constitute the largest percentage in human milk?",
        "options": ["Ig M", "Ig A", "Ig G", "Ig D"],
        "correct_option_id": 1,
        "explanation": "Colostrum (early human milk) has high levels of IgA, which provides passive immunity to the newborn.",
    },
    {
        "question": "In mammalian eye, the 'fovea' is the center of the visual field, where:",
        "options": ["the optic nerve leaves the eye.", "only rods are present.", "more rods than cones are found.", "high density of cones occur, but has no rods."],
        "correct_option_id": 3,
        "explanation": "The fovea centralis, at the centre of the macula lutea, has the highest density of cones (for sharpest vision) and no rods.",
    },
    {
        "question": "Doctors use stethoscope to hear the sounds produced during each cardiac cycle. The second sound is heard when:",
        "options": ["Ventricular walls vibrate due to gushing in of blood from atria", "Semilunar valves close down after the blood flows into vessels from ventricles", "AV node receives signal from SA node", "AV valves open up"],
        "correct_option_id": 1,
        "explanation": "The second heart sound (\"dub\") is produced by the closure of the semilunar valves after blood has been ejected from the ventricles into the great vessels.",
    },
    {
        "question": "Coconut water from a tender coconut is:",
        "options": ["Free nuclear endosperm", "Innermost layers of the seed coat", "Degenerated nucellus", "Immature embryo"],
        "correct_option_id": 0,
        "explanation": "Coconut water represents the free-nuclear (liquid) stage of endosperm development before cellularisation.",
    },
    {
        "question": "The cutting of DNA at specific locations became possible with the discovery of:",
        "options": ["Probes", "Selectable markers", "Ligases", "Restriction enzymes"],
        "correct_option_id": 3,
        "explanation": "Restriction endonuclease enzymes cut DNA at specific recognition sequences, enabling precise DNA cutting.",
    },
    {
        "question": "Which of the following structures is not found in a prokaryotic cell?",
        "options": ["Ribosome", "Mesosome", "Plasma membrane", "Nuclear envelope"],
        "correct_option_id": 3,
        "explanation": "Prokaryotic cells lack a well-defined nucleus and hence a nuclear envelope/membrane.",
    },
    {
        "question": "Arrange the following events of meiosis in correct sequence: (a) Crossing over (b) Synapsis (c) Terminalisation of chiasmata (d) Disappearance of nucleolus",
        "options": ["(b), (a), (c), (d)", "(a), (b), (c), (d)", "(b), (c), (d), (a)", "(b), (a), (d), (c)"],
        "correct_option_id": 0,
        "explanation": "During prophase I of meiosis, synapsis occurs in zygotene, crossing over in pachytene, terminalisation of chiasmata and disappearance of nucleolus follow in diplotene/diakinesis — sequence: synapsis → crossing over → terminalisation → disappearance of nucleolus.",
    },
    {
        "question": "A column of water within xylem vessels of tall trees does not break under its weight because of:",
        "options": ["Tensile strength of water", "Lignification of xylem vessels", "Positive root pressure", "Dissolved sugars in water"],
        "correct_option_id": 0,
        "explanation": "The cohesive tensile strength of water molecules (due to hydrogen bonding) allows the continuous water column in xylem to resist breaking under gravity/tension.",
    },
    {
        "question": "The imperfect fungi which are decomposer of litter and help in mineral cycling belong to:",
        "options": ["Basidiomycetes", "Phycomycetes", "Ascomycetes", "Deuteromycetes"],
        "correct_option_id": 3,
        "explanation": "Deuteromycetes (Fungi Imperfecti) lack a known sexual stage; many are litter decomposers that aid mineral cycling.",
    },
    {
        "question": "The structures that help some bacteria to attach to rocks and/or host tissues are:",
        "options": ["Fimbriae", "Mesosomes", "Holdfast", "Rhizoids"],
        "correct_option_id": 0,
        "explanation": "Fimbriae are hair-like appendages that help bacteria attach to rocks or host tissues, and to each other.",
    },
    {
        "question": "The DNA molecule to which the gene of interest is integrated for cloning is called:",
        "options": ["Vector", "Template", "Carrier", "Transformer"],
        "correct_option_id": 0,
        "explanation": "A vector (such as a plasmid) is the DNA molecule into which the gene of interest is inserted for cloning.",
    },
    {
        "question": "Pick up the wrong statement:",
        "options": ["Protista have photosynthetic and heterotrophic modes of nutrition", "Some fungi are edible", "Nuclear membrane is present in Monera", "Cell wall is absent in Animalia"],
        "correct_option_id": 2,
        "explanation": "Monera consists of prokaryotes, which by definition lack a nuclear membrane (no true nucleus).",
    },
    {
        "question": "Metagenesis refers to:",
        "options": ["Alternation of generation between asexual and sexual phases of an organisms", "Occurrence of a drastic change in form during post-embryonic development", "Presence of a segmented body and parthenogenetic mode of reproduction", "Presence of different morphic forms"],
        "correct_option_id": 0,
        "explanation": "Metagenesis is the alternation of generations between asexual (polyp) and sexual (medusa) phases, seen in cnidarians such as Obelia.",
    },
    {
        "question": "Which of the following events is not associated with ovulation in human female?",
        "options": ["Full development of Graffian follicle", "Release of secondary oocyte", "LH surge", "Decrease in estradiol"],
        "correct_option_id": 3,
        "explanation": "At ovulation, estrogen (estradiol) hypersecretion causes an LH surge (positive feedback), not a decrease.",
    },
    {
        "question": "Which of the following joints would allow no movement?",
        "options": ["Cartilaginous joint", "Synovial joint", "Ball and Socket joint", "Fibrous joint"],
        "correct_option_id": 3,
        "explanation": "Fibrous joints (e.g., skull sutures) are fixed joints that permit no movement.",
    },
    {
        "question": "The UN conference of Parties on climate change in the year 2012 was held at:",
        "options": ["Doha", "Lima", "Warsaw", "Durban"],
        "correct_option_id": 0,
        "explanation": "The 2012 UN Climate Change Conference (COP18) was held in Doha, Qatar.",
    },
    {
        "question": "If you suspect major deficiency of antibodies in a person, to which of the following would you look for confirmatory evidences?",
        "options": ["Serum albumins", "Haemocytes", "Serum globulins", "Fibrinogin in plasma"],
        "correct_option_id": 2,
        "explanation": "Antibodies are gamma-globulins, so serum globulin levels would confirm antibody deficiency.",
    },
    {
        "question": "Chromatophores take part in:",
        "options": ["Growth", "Movement", "Respiration", "Photosynthesis"],
        "correct_option_id": 3,
        "explanation": "Chromatophores (pigment-containing structures found e.g. in blue-green algae) function in photosynthesis.",
    },
    {
        "question": "Acid rain is caused by increase in the atmospheric concentration of:",
        "options": ["SO3 and CO", "CO2 and CO", "O3 and dust", "SO2 and NO2"],
        "correct_option_id": 3,
        "explanation": "Acid rain results mainly from increased atmospheric SO2 (60-70%) and NO2 (20-30%).",
    },
    {
        "question": "During ecological succession:",
        "options": ["the establishment of a new biotic community is very fast in its primary phase.", "the numbers and types of animals remain constant.", "the changes lead to a community that is in near equilibrium with the environment and is called pioneer community", "the gradual and predictable change in species composition occurs in a given area"],
        "correct_option_id": 3,
        "explanation": "Ecological succession is characterised by a gradual, predictable, sequential change in species composition in a given area over time.",
    },
    {
        "question": "The oxygen evolved during photosynthesis comes from water molecules. Which one of the following pairs of elements is involved in this reaction?",
        "options": ["Manganese and Potassium", "Magnesium and Molybdenum", "Magnesium and Chlorine", "Manganese and Chlorine"],
        "correct_option_id": 3,
        "explanation": "Photolysis of water (splitting of water to release O2) is initiated by Mn++ and Cl– ions associated with the water-splitting complex.",
    },
    {
        "question": "Which one of the following animals has two separate circulatory pathways?",
        "options": ["Lizard", "Whale", "Shark", "Frog"],
        "correct_option_id": 1,
        "explanation": "Whales (mammals) have a 4-chambered heart with completely separate pulmonary and systemic (oxygenated/deoxygenated) circulatory pathways.",
    },
    {
        "question": "Flowers are unisexual in:",
        "options": ["Cucumber", "China rose", "Onion", "Pea"],
        "correct_option_id": 0,
        "explanation": "Cucumber bears unisexual (monoecious) flowers, unlike China rose, onion, and pea, which have bisexual flowers.",
    },
    {
        "question": "Which one of the following fruits is parthenocarpic?",
        "options": ["Apple", "Jackfruit", "Banana", "Brinjal"],
        "correct_option_id": 2,
        "explanation": "Banana develops without fertilization, making it a parthenocarpic (seedless) fruit.",
    },
    {
        "question": "A pleiotropic gene:",
        "options": ["is a gene evolved during Pliocene.", "controls a trait only in combination with another gene", "controls multiple traits in an individual.", "is expressed only in primitive plants"],
        "correct_option_id": 2,
        "explanation": "A pleiotropic gene influences multiple, seemingly unrelated phenotypic traits in an individual.",
    },
    {
        "question": "Which of the following is not a function of the skeletal system?",
        "options": ["Storage of minerals", "Production of body heat", "Locomotion", "Production of erythrocytes"],
        "correct_option_id": 1,
        "explanation": "Production of body heat is not a function of the skeletal system; bones store minerals, aid locomotion, and produce blood cells (via bone marrow) but do not generate heat as a primary function.",
    },
    {
        "question": "A jawless fish, which lays eggs in fresh water and whose ammocoetes larvae after metamorphosis return to the ocean is:",
        "options": ["myxine", "Neomyxine", "Petormyzon", "Eptatretus"],
        "correct_option_id": 2,
        "explanation": "Petromyzon (lamprey) is jawless, lays eggs in fresh water, and its ammocoetes larvae migrate back to the ocean after metamorphosis.",
    },
    {
        "question": "Filiform apparatus is characteristic feature of:",
        "options": ["Nucellar embryo", "Aleurone cell", "Synergids", "Generative cell"],
        "correct_option_id": 2,
        "explanation": "The filiform apparatus, a set of finger-like wall projections that guide the pollen tube, is a characteristic feature of synergid cells.",
    },
    {
        "question": "Which one of the following hormones is not involved in sugar metabolism?",
        "options": ["Aldosterone", "Insulin", "Glucagon", "Cortisone"],
        "correct_option_id": 0,
        "explanation": "Aldosterone regulates Na+ and K+ levels in the body and is not involved in sugar (carbohydrate) metabolism.",
    },
    {
        "question": "Golden rice is a genetically modified crop plant where the incorporated gene is meant for biosynthesis of:",
        "options": ["Vitamin C", "Omega 3", "Vitamin A", "Vitamin B"],
        "correct_option_id": 2,
        "explanation": "Golden rice is genetically engineered to biosynthesize beta-carotene, a precursor of Vitamin A.",
    },
    {
        "question": "Outbreeding is an important strategy of animal husbandry because it:",
        "options": ["is useful in producing pure lines of animals.", "is useful in overcoming inbreeding depression.", "exposes harmful recessive genes that are eliminated by selection.", "helps in accumulation of superior genes."],
        "correct_option_id": 1,
        "explanation": "Outbreeding avoids mating of closely related individuals and thereby overcomes the ill effects (depression) associated with inbreeding.",
    },
    {
        "question": "A gene showing codominance has:",
        "options": ["alleles tightly linked on the same chromosome", "alleles that are recessive to each other", "both alleles independently expressed in the heterozygote", "one allele dominant on the other"],
        "correct_option_id": 2,
        "explanation": "In codominance, both alleles of a gene are independently and fully expressed in the heterozygous condition (e.g., AB blood group).",
    },
    {
        "question": "Which one of the following hormones through synthesised elsewhere is stored and released by the master gland?",
        "options": ["Luteinizing hormone", "Prolactin", "Melanocyte stimulating hormone", "Antidiuretic hormone"],
        "correct_option_id": 3,
        "explanation": "ADH (and oxytocin) is synthesized by the hypothalamus but stored and released by the posterior pituitary (the \"master gland\" here referring to pituitary).",
    },
    {
        "question": "Increase in concentration of the toxicant at successive trophic levels is known as:",
        "options": ["Biodeterioration", "Biotransformation", "Biogeochemical", "Biomagnification"],
        "correct_option_id": 3,
        "explanation": "Biomagnification refers to the progressive increase in concentration of a toxicant as it moves up successive trophic levels.",
    },
    {
        "question": "Industrial melanism is an example of:",
        "options": ["Natural selection", "Mutation", "Neo Lamarckism", "Neo Darwinism"],
        "correct_option_id": 0,
        "explanation": "Industrial melanism (darkening of moth populations near industrial/polluted areas) is a classic example of natural selection.",
    },
    {
        "question": "The primary dentition in human differs from permanent dentition in not having one of the following type of teeth:",
        "options": ["Premolars", "Molars", "Incisors", "Canine"],
        "correct_option_id": 0,
        "explanation": "The milk (primary) dental formula is 2102/2102, lacking premolars, which are present only in the permanent dentition.",
    },
    {
        "question": "The wheat grain has an embryo with one, large, shield-shaped cotyledon known as:",
        "options": ["Coleorrhiza", "Scutellum", "Coleoptile", "Epiblast"],
        "correct_option_id": 1,
        "explanation": "In cereal grains like wheat, the large shield-shaped cotyledon is called the scutellum.",
    },
    {
        "question": "The body cells in cockroach discharge their nitrogenous waste in the haemolymph mainly in the form of:",
        "options": ["Potassium urate", "Urea", "Calcium carbonate", "Ammonia"],
        "correct_option_id": 0,
        "explanation": "Cockroach body cells release nitrogenous waste into the haemolymph mainly as potassium urate (uricotelic excretion).",
    },
    {
        "question": "Which of the following biomolecules does have phosphodiester bond?",
        "options": ["Monosaccharides in a polysaccharide", "Amino acids in a polypeptide", "Nucleic acids in a nucleotide", "Fatty acids in a diglyceride"],
        "correct_option_id": 2,
        "explanation": "Nucleotides in a nucleic acid (DNA/RNA) are joined by phosphodiester bonds between the phosphate group and sugar of adjacent nucleotides.",
    },
    {
        "question": "The term \"linkage\" was coined by:",
        "options": ["T. Boveri", "G. Mendel", "W. Sutton", "T.H. Morgan"],
        "correct_option_id": 3,
        "explanation": "T.H. Morgan coined the term \"linkage\" based on his studies on Drosophila.",
    },
    {
        "question": "Which one is wrong statement?",
        "options": ["Mucor has biflagellate zoospores", "Haploid endosperm is typical feature of gymnosperms", "Brown algae have chlorophyll a and c and fucoxanthin", "Archegonia are found in Bryophyta, Pteridophyta and Gymnosperms."],
        "correct_option_id": 0,
        "explanation": "Mucor produces non-motile (aplanospores), not biflagellate, zoospores; this statement is incorrect.",
    },
    {
        "question": "Ectopic pregnancies are referred to as:",
        "options": ["Implantation of embryo at site other than uterus.", "Implantation of defective embryo in the uterus", "Pregnancies terminated due to hormonal imbalance.", "Pregnancies with genetic abnormality."],
        "correct_option_id": 0,
        "explanation": "Ectopic pregnancy refers to implantation of the embryo at a site other than the uterus (e.g., fallopian tube).",
    },
    {
        "question": "Most animals that live in deep oceanic waters are:",
        "options": ["secondary consumers", "tertiary consumers", "detritivores", "primary consumers"],
        "correct_option_id": 2,
        "explanation": "Deep oceanic waters lack sunlight for photosynthesis, so most animals there are detritivores, feeding on organic debris sinking from above.",
    },
    {
        "question": "Which of the following diseases is caused by a protozoan?",
        "options": ["Influenza", "Babesiosis", "Blastomycosis", "Syphilis"],
        "correct_option_id": 1,
        "explanation": "Babesiosis is caused by the sporozoan protozoan Babesia, producing haemoglobinuric fever.",
    },
    {
        "question": "In which of the following interactions both partners are adversely affected?",
        "options": ["Predation", "Parasitism", "Mutualism", "Competition"],
        "correct_option_id": 3,
        "explanation": "In competition, both interacting species are adversely affected as they compete for the same limited resources.",
    },
    {
        "question": "Identify the correct order of organisation of genetic material from largest to smallest:",
        "options": ["Genome, chromosome, nucleotide, gene", "Genome, chromosome, gene, nucleotide", "Chromosome, genome, nucleotide, gene", "Chromosome, gene, genome, nucleotide"],
        "correct_option_id": 1,
        "explanation": "From largest to smallest: genome (entire genetic material) > chromosome > gene > nucleotide.",
    },
    {
        "question": "A colour blind man marries a woman with normal sight who has no history of colour blindness in her family. What is the probability of their grandson being colour blind?",
        "options": ["1", "Nil", "0.25", "0.5"],
        "correct_option_id": 2,
        "explanation": "The daughters of this couple are all carriers (XX^c); if a carrier daughter marries a normal-sighted man, 25% of the grandsons will be colour blind.",
    },
    {
        "question": "Photosynthesis the light-independent reactions take place at:",
        "options": ["Photosystem-I", "Photosystem-II", "Stromal matrix", "Thylakoid lumen"],
        "correct_option_id": 2,
        "explanation": "The light-independent (dark) reactions of photosynthesis, i.e., the Calvin cycle, occur in the stromal matrix of the chloroplast.",
    },
    {
        "question": "The introduction of t-DNA into plants involves:",
        "options": ["Altering the pH of the soil, then heat shocking the plants", "Exposing the plants to cold for a brief period", "Allowing the plant roots to stand in water", "Infection of the plant by Agrobacterium tumefaciens"],
        "correct_option_id": 3,
        "explanation": "T-DNA is naturally introduced into plants through infection by Agrobacterium tumefaciens, which is exploited as a vector in plant genetic engineering.",
    },
    {
        "question": "The wings of a bird and the wings of an insect are:",
        "options": ["analogous structures and represent convergent evolution", "phylogenetic structures and represent divergent evolution", "homologous structures and represent convergent evolution", "homologous structures and represent divergent evolution"],
        "correct_option_id": 0,
        "explanation": "Bird and insect wings have different origins but similar functions, making them analogous structures resulting from convergent evolution.",
    },
    {
        "question": "Root pressure develops due to:",
        "options": ["Low osmotic potential in soil", "Passive absorption", "Increase in transpiration", "Active absorption"],
        "correct_option_id": 3,
        "explanation": "Root pressure develops due to active absorption of water and ions by root cells, generating pressure that pushes water up the xylem.",
    },
    {
        "question": "Human urine is usually acidic because:",
        "options": ["excreted plasma proteins are acidic", "potassium and sodium exchange generates acidity", "hydrogen ions are actively secreted into the filtrate.", "the sodium transporter exchanges one hydrogen ion for each sodium ion, in peritubular capillaries."],
        "correct_option_id": 2,
        "explanation": "Hydrogen ions are actively secreted into the tubular filtrate, making human urine typically acidic.",
    },
    {
        "question": "A protoplast is a cell:",
        "options": ["without nucleus", "undergoing division", "without cell wall", "without plasma membrane"],
        "correct_option_id": 2,
        "explanation": "A protoplast is a plant cell from which the cell wall has been removed, leaving only the plasma membrane intact.",
    },
    {
        "question": "The species confined to a particular region and not found elsewhere is termed as:",
        "options": ["Alien", "Endemic", "Rare", "Keystone"],
        "correct_option_id": 1,
        "explanation": "A species restricted to a particular geographic region and not found elsewhere is called an endemic species.",
    },
    {
        "question": "Select the wrong statements:",
        "options": ["W.M. Stanley showed that viruses could be crystallized", "The term 'contagium vivum fluidum' was coined by M.W. Bejerinek", "Mosaic disease in tobacco and AIDS in human being are caused by viruses", "The viroids were discovered by D.J. Ivanowski"],
        "correct_option_id": 3,
        "explanation": "Viroids were discovered by T.O. Diener, not D.J. Ivanowski (who discovered viruses as sub-bacterial infectious agents); hence this statement is incorrect.",
    },
    {
        "question": "Axile placentation is present in",
        "options": ["Lemon", "Pea", "Argemaone", "Dianthus"],
        "correct_option_id": 0,
        "explanation": "Lemon (Citrus) shows axile placentation, where the placenta is at the central axis in a multilocular ovary.",
    },
    {
        "question": "A childless couple can be assisted to have a child through a technique called GIFT. The full form of this technique is:",
        "options": ["Gamete intra fallopian transfer", "Gamete internal fertillization and transfer", "Germ cell internal fallopian transfer", "Gemete inseminated fallopian transfer"],
        "correct_option_id": 0,
        "explanation": "GIFT stands for Gamete Intra-Fallopian Transfer, a technique used to assist couples with fertility issues.",
    },
    {
        "question": "Destruction of the anterior horn cell of the spinal cord would result in loss of:",
        "options": ["voluntary motor impulses", "commissural impulses", "integrating impulses", "sensory impulses"],
        "correct_option_id": 0,
        "explanation": "Anterior horn cells of the spinal cord (destroyed in poliomyelitis) carry motor impulses; their destruction causes loss of voluntary motor activity.",
    },
    {
        "question": "During biological nitrogen fixation, inactivation of nitrogenase by oxygen poisoning is prevented by:",
        "options": ["Xanthophyll", "Carotene", "Cytochrome", "Leghemoglobin"],
        "correct_option_id": 3,
        "explanation": "Leghemoglobin, present in root nodules, scavenges oxygen and protects the oxygen-sensitive nitrogenase enzyme from inactivation.",
    },
    {
        "question": "An association of individuals of different species living in the same habitat and having functional interactions is:",
        "options": ["Biotic community", "Ecosystem", "Population", "Ecological niche"],
        "correct_option_id": 0,
        "explanation": "A biotic community consists of individuals of different species living in the same habitat with functional interactions among them.",
    },
    {
        "question": "Name the pulmonary disease in which alveolar surface area involved in gas exchange is drastically reduced due to damage in the alveolar walls.",
        "options": ["Emphysema", "Pneumonia", "Asthma", "Pleurisy"],
        "correct_option_id": 0,
        "explanation": "Emphysema involves damage to alveolar walls, drastically reducing surface area available for gas exchange.",
    },
    {
        "question": "Balbiani rings are sites of:",
        "options": ["Nucleotide synthesis", "Polysaccharide synthesis", "RNA and protein synthesis", "Lipid synthesis"],
        "correct_option_id": 2,
        "explanation": "Balbiani rings, seen as puffs on polytene chromosomes, are sites of intense RNA and protein synthesis.",
    },
    {
        "question": "Cellular organelles with membranes are:",
        "options": ["chromosomes, ribosomes and endoplasmic reticulum", "endoplasmic reticulum, ribosomes and nuclei", "lysosomes, Golgi apparatus and mitochondria", "nuclei, ribosomes and mitochondria"],
        "correct_option_id": 2,
        "explanation": "Lysosomes, Golgi apparatus, and mitochondria are all membrane-bound cell organelles.",
    },
    {
        "question": "Auxin can be bioassayed by:",
        "options": ["Hydroponics", "Potometer", "Lettuce hypocotyl elongation", "Avena coleoptile curvature"],
        "correct_option_id": 3,
        "explanation": "The Avena (oat) coleoptile curvature test is the classical bioassay method for detecting and quantifying auxin activity.",
    },
    {
        "question": "Satellite DNA in important because it:",
        "options": ["shows high degree of polymorphism in population and also the same degree of polymorphism in an individual, which is heritable from parents to children.", "does not code for proteins and is same in all members of the population", "codes for enzymes needed for DNA replication", "codes for proteins needed in cell cycle."],
        "correct_option_id": 0,
        "explanation": "Satellite DNA shows a high degree of polymorphism in a population, and the pattern is heritable from parents to children, forming the basis of DNA fingerprinting.",
    },
    {
        "question": "Cell wall is absent in:",
        "options": ["Funaria", "Mycoplasma", "Nostoc", "Aspergillus"],
        "correct_option_id": 1,
        "explanation": "Mycoplasma lacks a cell wall, unlike Funaria, Nostoc, and Aspergillus.",
    },
    {
        "question": "In angiosperms, microsporogenesis and megasporogenesis:",
        "options": ["form gametes without further divisions", "Involve meiosis", "occur in ovule", "occur in anther"],
        "correct_option_id": 1,
        "explanation": "Both microsporogenesis (in anther) and megasporogenesis (in ovule) involve meiotic division of mother cells to form haploid spore tetrads.",
    },
    {
        "question": "Roots play insignificant role in absorption of water in:",
        "options": ["Pistia", "Pea", "Wheat", "Sunflower"],
        "correct_option_id": 0,
        "explanation": "Pistia is a free-floating hydrophyte, and water absorption by its roots is insignificant since it absorbs water/nutrients directly through its body surface.",
    },
    {
        "question": "Which of the following are most suitable indicators of SO2 pollution in the environment?",
        "options": ["Conifers", "Algae", "Fungi", "Lichens"],
        "correct_option_id": 3,
        "explanation": "Lichens are highly sensitive to SO2 pollution and serve as bioindicators of air quality.",
    },
    {
        "question": "Grafted kidney may be rejected in a patient due to:",
        "options": ["Cell-mediated immune response", "Passive immune response", "Innate immune response", "Humoral immune response"],
        "correct_option_id": 0,
        "explanation": "Organ (kidney) transplant rejection occurs mainly due to the cell-mediated immune response, where T-cells attack the foreign graft tissue.",
    },
    {
        "question": "Body having meshwork of cell, internal cavities lined with food filtering flagellated cells and indirect development are the characteristics of phylum.",
        "options": ["Porifera", "Mollusca", "Protozoa", "Coelenterate"],
        "correct_option_id": 0,
        "explanation": "Porifera (sponges) have a cellular meshwork body, internal cavities lined with flagellated choanocytes that filter food, and indirect development.",
    },
    {
        "question": "Choose the wrong statements:",
        "options": ["Neurospora is used in the study of biochemical genetics", "Morels and truffles are poisonous mushrooms", "Yeast is unicellular and useful in fermentation", "Penicillium is multicellular and produces antibiotics"],
        "correct_option_id": 1,
        "explanation": "Morels and truffles are edible fungi belonging to Ascomycetes, not poisonous mushrooms; this statement is incorrect.",
    },
    {
        "question": "In human females, meiosis-II is not complete until?",
        "options": ["fertilization", "uterine implantation", "birth", "puberty"],
        "correct_option_id": 0,
        "explanation": "In human females, the secondary oocyte remains arrested at metaphase-II and completes meiosis-II only upon fertilization.",
    },
    {
        "question": "Eutrophication of water bodies leading to killing of fishes is mainly due to non-availability of:",
        "options": ["light", "essential minerals", "oxygen", "food"],
        "correct_option_id": 2,
        "explanation": "Eutrophication leads to excessive algal growth and subsequent decomposition, which depletes dissolved oxygen, causing fish deaths.",
    },
    {
        "question": "The enzyme that is not present in succus Entericus is:",
        "options": ["nucleases", "nucleosidase", "lipase", "maltase"],
        "correct_option_id": 0,
        "explanation": "Nucleases are not present in succus entericus (intestinal juice); nucleosidase, lipase, and maltase are present.",
    },
]
