"""
Question bank: NEET 2018 - Biology (Solved Answers).

82 questions parsed from NEET 2018's solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "The experimental proof for semiconservative replication of DNA was first shown in a-",
        "options": ["Fungus", "Bacterium", "Plant", "Virus"],
        "correct_option_id": 1,
        "explanation": "The Meselson-Stahl experiment, using E. coli (a bacterium) and density-gradient centrifugation, provided the first experimental proof of semiconservative DNA replication.",
    },
    {
        "question": "Select the correct statement:",
        "options": ["Franklin Stahl coined the term \"linkage\".", "Punnett square was developed by a British scientist.", "Spliceosomes take part in translation.", "Transduction was discovered by S. Altman."],
        "correct_option_id": 1,
        "explanation": "The Punnett square was devised by Reginald Punnett, a British geneticist. Linkage was described by Morgan, spliceosomes function in RNA splicing (not translation), and transduction was discovered by Zinder and Lederberg.",
    },
    {
        "question": "Offsets are produced by",
        "options": ["Meiotic divisions", "Mitotic divisions", "Parthenocarpy", "Parthenogenesis"],
        "correct_option_id": 1,
        "explanation": "Offsets are a form of vegetative propagation produced through mitotic (asexual) cell divisions, giving genetically identical clones of the parent plant.",
    },
    {
        "question": "Which of the following pairs is wrongly matched?",
        "options": ["Starch synthesis in pea: Multiple alleles", "ABO blood grouping: Co-dominance", "XO type sex determination: Grasshopper", "T.H Morgan: Linkage"],
        "correct_option_id": 0,
        "explanation": "Starch synthesis in pea seeds (round/wrinkled trait) is governed by a single gene with two alleles, not a multiple allelic series; ABO blood grouping (multiple alleles), grasshopper XO sex determination, and Morgan's discovery of linkage are all correctly matched.",
    },
    {
        "question": "Which of the following flowers only once in its life-time?",
        "options": ["Bamboo species", "Jackfruit", "Mango", "Papaya"],
        "correct_option_id": 0,
        "explanation": "Many bamboo species are monocarpic — they flower only once after several decades of vegetative growth and then die.",
    },
    {
        "question": "Select the correct match:",
        "options": ["Alec Jeffreys – Streptococcus pneumoniae", "Alfred Hershey and Martha Chase – TMV", "Matthew Meselson and F. Stahl – Pisum sativum", "Francois Jacob and Jacques Monod – Lac operon"],
        "correct_option_id": 3,
        "explanation": "Jacob and Monod proposed the operon model, based on the lac operon of E. coli. The other pairings are incorrect (Jeffreys - DNA fingerprinting; Hershey-Chase - bacteriophage; Meselson-Stahl - E. coli).",
    },
    {
        "question": "Which of the following has proved helpful in preserving pollen as fossils?",
        "options": ["Pollenkitt", "Cellulosic intine", "Oil content", "Sporopollenin"],
        "correct_option_id": 3,
        "explanation": "Sporopollenin, present in the exine of pollen grains, is one of the most resistant organic materials known and can withstand high temperatures, acids, and enzymes, allowing pollen to fossilize well.",
    },
    {
        "question": "Stomatal movement is not affected by",
        "options": ["Temperature", "Light", "O2 concentration", "CO2 concentration"],
        "correct_option_id": 2,
        "explanation": "Stomatal opening and closing are regulated mainly by light, CO2 concentration, and water status (temperature also has some influence), but ambient O2 concentration does not significantly affect guard cell movement.",
    },
    {
        "question": "The stage during which separation of the paired homologous chromosomes begins is",
        "options": ["Pachytene", "Diplotene", "Diakinesis", "Zygotene"],
        "correct_option_id": 1,
        "explanation": "At diplotene, the synaptonemal complex dissolves and homologous chromosomes of each bivalent start separating, remaining attached only at chiasmata.",
    },
    {
        "question": "The two functional groups characteristic of sugars are",
        "options": ["Hydroxyl and methyl", "Carbonyl and methyl", "Carbonyl and phosphate", "Carbonyl and hydroxyl"],
        "correct_option_id": 3,
        "explanation": "Sugars (monosaccharides) are polyhydroxy aldehydes or ketones, characterized by hydroxyl groups and a carbonyl group (aldehyde or ketone).",
    },
    {
        "question": "Which of the following is not a product of light reaction of photosynthesis?",
        "options": ["ATP", "NADH", "NADPH", "Oxygen"],
        "correct_option_id": 1,
        "explanation": "The light reactions of photosynthesis generate ATP, NADPH, and oxygen; NADH is a product of respiration, not photosynthesis's light reaction.",
    },
    {
        "question": "Stomata in grass leaf are",
        "options": ["Dumb-bell shaped", "Kidney shaped", "Rectangular", "Barrel shaped"],
        "correct_option_id": 0,
        "explanation": "Guard cells in grasses (and other Poaceae) are dumb-bell shaped, unlike the kidney-shaped guard cells typical of dicots.",
    },
    {
        "question": "Which among the following is not a prokaryote?",
        "options": ["Saccharomyces", "Mycobacterium", "Nostoc", "Oscillatoria"],
        "correct_option_id": 0,
        "explanation": "Saccharomyces is a yeast, a unicellular eukaryotic fungus, while Mycobacterium, Nostoc, and Oscillatoria are prokaryotes (bacteria/cyanobacteria).",
    },
    {
        "question": "Which of the following is true for nucleolus?",
        "options": ["Larger nucleoli are present in dividing cells.", "It is a membrane-bound structure.", "It takes part in spindle formation.", "It is a site for active ribosomal RNA synthesis."],
        "correct_option_id": 3,
        "explanation": "The nucleolus is the site of rRNA synthesis and ribosomal subunit assembly. It is not membrane-bound, and larger nucleoli are found in metabolically active (protein-synthesizing) cells, not specifically dividing ones.",
    },
    {
        "question": "The Golgi complex participates in",
        "options": ["Fatty acid breakdown", "Formation of secretory vesicles", "Respiration in bacteria", "Activation of amino acid"],
        "correct_option_id": 1,
        "explanation": "The Golgi apparatus packages and modifies materials from the endoplasmic reticulum and forms secretory vesicles for transport out of the cell.",
    },
    {
        "question": "In stratosphere, which of the following element acts as a catalyst in degradation of ozone and release of molecular oxygen?",
        "options": ["Carbon", "Cl", "Fe", "Oxygen"],
        "correct_option_id": 1,
        "explanation": "Chlorine atoms (released from CFCs) catalytically break down ozone into molecular oxygen, contributing to ozone layer depletion.",
    },
    {
        "question": "Which of the following is a secondary pollutant?",
        "options": ["CO", "CO2", "SO2", "O3"],
        "correct_option_id": 3,
        "explanation": "Ozone (O3) is a secondary pollutant formed by photochemical reactions of primary pollutants (like NOx and hydrocarbons) in the presence of sunlight.",
    },
    {
        "question": "Niche is",
        "options": ["All the biological factors in the organism environment", "The physical space where an organism lives", "The range of temperature that the organism needs to live", "The functional role played by the organism where it lives"],
        "correct_option_id": 3,
        "explanation": "An ecological niche refers to the functional role and position of an organism within its habitat, including its activities and interactions, not just its physical location.",
    },
    {
        "question": "Natality refers to",
        "options": ["Death rate", "Birth rate", "Number of individuals leaving the habitat", "Number of individuals entering the habitat"],
        "correct_option_id": 1,
        "explanation": "Natality is the birth rate, i.e., the number of births in a population during a given time period.",
    },
    {
        "question": "What type of ecological pyramid would be obtained with the following data? Secondary consumer: 120 g, Primary consumer: 60 g, Primary producer: 10 g",
        "options": ["Inverted pyramid of biomass", "Pyramid of energy", "Upright pyramid of numbers", "Upright pyramid of biomass"],
        "correct_option_id": 0,
        "explanation": "Since biomass increases from producer to secondary consumer (10g < 60g < 120g) instead of decreasing, this gives an inverted pyramid of biomass, typical of aquatic ecosystems.",
    },
    {
        "question": "World Ozone Day is celebrated on",
        "options": ["5th June", "21st April", "16th September", "22nd April"],
        "correct_option_id": 2,
        "explanation": "World Ozone Day is observed on 16th September each year, commemorating the signing of the Montreal Protocol.",
    },
    {
        "question": "Which of the following is commonly used as a vector for introducing a DNA fragment in human Lymphocytes?",
        "options": ["Retrovirus", "Ti plasmid", "λ phage", "pBR 322"],
        "correct_option_id": 0,
        "explanation": "Retroviral vectors are commonly used for gene delivery into human cells, including lymphocytes, since they can integrate into the host genome.",
    },
    {
        "question": "In India, the organization responsible for assessing the safety of introducing genetically modified organisms for public use is",
        "options": ["Indian Council of Medical Research (ICMR)", "Council for Scientific and Industrial Research (CSIR)", "Research Committee on Genetic Manipulation (RCGM)", "Genetic Engineering Appraisal Committee (GEAC)"],
        "correct_option_id": 3,
        "explanation": "GEAC, under the Ministry of Environment, Forest and Climate Change, is responsible for approving the release of GMOs for public/commercial use in India.",
    },
    {
        "question": "A 'new' variety of rice was patented by a foreign company though such varieties have been present in India for a long time. This is related to",
        "options": ["Co-667", "Sharbati Sonora", "Lerma Rojo", "Basmati"],
        "correct_option_id": 3,
        "explanation": "This refers to the well-known Basmati rice patent controversy, where a US company attempted to patent basmati rice varieties already traditionally grown in India.",
    },
    {
        "question": "Use of bioresources by multinational companies and organizations without authorization from the concerned country and its people is called",
        "options": ["Bio-infringement", "Biopiracy", "Biodegradation", "Bioexploitation"],
        "correct_option_id": 1,
        "explanation": "This unauthorized commercial use of a country's biological resources and traditional knowledge without proper compensation is termed biopiracy.",
    },
    {
        "question": "Select the correct Match:",
        "options": ["Ribozyme - Nucleic acid", "F2 × Recessive parent - Dihybrid cross", "T.H. Morgan - Transduction", "G. Mendel - Transformation"],
        "correct_option_id": 0,
        "explanation": "Ribozymes are catalytic RNA molecules, hence \"nucleic acid\" is correctly matched. F1 (not F2) × recessive parent defines a test cross, Morgan is known for linkage (not transduction), and Mendel is known for laws of inheritance (not transformation).",
    },
    {
        "question": "The correct order of steps in Polymerase Chain Reaction (PCR) is",
        "options": ["Extension, Denaturation, Annealing", "Annealing, Extension, Denaturation", "Denaturation, Extension, Annealing", "Denaturation, Annealing, Extension"],
        "correct_option_id": 3,
        "explanation": "PCR proceeds in the cyclic order: Denaturation (strand separation) → Annealing (primer binding) → Extension (DNA polymerase synthesizes new strand).",
    },
    {
        "question": "Secondary xylem and phloem in dicot stem are produced by",
        "options": ["Apical meristems", "Vascular cambium", "Phellogen", "Axillary meristems"],
        "correct_option_id": 1,
        "explanation": "The vascular cambium, a lateral meristem, produces secondary xylem toward the inside and secondary phloem toward the outside during secondary growth.",
    },
    {
        "question": "Pneumatophores occur in",
        "options": ["Halophytes", "Free-floating hydrophytes", "Carnivorous plants", "Submerged hydrophytes"],
        "correct_option_id": 0,
        "explanation": "Pneumatophores (breathing roots) are found in halophytes like mangrove plants growing in saline, waterlogged soils, helping them obtain atmospheric oxygen.",
    },
    {
        "question": "Sweet potato is a modified",
        "options": ["Stem", "Adventitious root", "Tap root", "Rhizome"],
        "correct_option_id": 1,
        "explanation": "Sweet potato (Ipomoea batatas) is a modified adventitious root that stores food.",
    },
    {
        "question": "Which of the following statements is correct?",
        "options": ["Ovules are not enclosed by ovary wall in gymnosperms", "Selaginella is heterosporous, while Salvinia is homosporous", "Horsetails are gymnosperms", "Stems are usually unbranched in both Cycas and Cedrus"],
        "correct_option_id": 0,
        "explanation": "In gymnosperms, ovules are naked (not enclosed within an ovary), unlike angiosperms. Both Selaginella and Salvinia are heterosporous, horsetails belong to Pteridophyta, and Cycas/Cedrus differ in branching pattern.",
    },
    {
        "question": "Select the wrong statement:",
        "options": ["Cell wall is present in members of Fungi and Plantae", "Mushrooms belong to Basidiomycetes", "Pseudopodia are locomotory and feeding structures in Sporozoans", "Mitochondria are the powerhouse of the cell in all kingdoms except Monera"],
        "correct_option_id": 2,
        "explanation": "Sporozoans (Apicomplexa) lack pseudopodia and other prominent locomotory organelles in their mature stage; pseudopodia are characteristic of amoeboid protists, not sporozoans.",
    },
    {
        "question": "Casparian strips occur in",
        "options": ["Epidermis", "Pericycle", "Cortex", "Endodermis"],
        "correct_option_id": 3,
        "explanation": "Casparian strips are band-like thickenings of suberin found in the radial and transverse walls of endodermal cells in roots, regulating water/mineral movement into the vascular tissue.",
    },
    {
        "question": "Plants having little or no secondary growth are",
        "options": ["Grasses", "Deciduous angiosperms", "Conifers", "Cycads"],
        "correct_option_id": 0,
        "explanation": "Grasses are monocots, which generally lack a vascular cambium and thus show little or no secondary growth, unlike woody dicots/gymnosperms.",
    },
    {
        "question": "Which one is wrongly matched?",
        "options": ["Uniflagellate gametes - Polysiphonia", "Biflagellate zoospores - Brown algae", "Gemma cups - Marchantia", "Unicellular organism - Chlorella"],
        "correct_option_id": 0,
        "explanation": "Red algae such as Polysiphonia produce non-flagellated (naked) gametes, so pairing them with \"uniflagellate gametes\" is incorrect.",
    },
    {
        "question": "Winged pollen grains are present in",
        "options": ["Mustard", "Cycas", "Mango", "Pinus"],
        "correct_option_id": 3,
        "explanation": "Pinus (pine) pollen grains have two air sacs/wings that aid in wind dispersal.",
    },
    {
        "question": "After karyogamy followed by meiosis, spores are produced exogenously in",
        "options": ["Neurospora", "Alternaria", "Agaricus", "Saccharomyces"],
        "correct_option_id": 2,
        "explanation": "In Agaricus (a basidiomycete), following karyogamy and meiosis, basidiospores are produced exogenously on the basidium, unlike ascomycetes where ascospores form endogenously.",
    },
    {
        "question": "What is the role of NAD+ in cellular respiration?",
        "options": ["It functions as enzymes", "It functions as an electron carrier", "It is a nucleotide source for ATP synthesis", "It is the final electron acceptor for anaerobic respiration"],
        "correct_option_id": 1,
        "explanation": "NAD+ acts as an electron/hydrogen carrier, getting reduced to NADH during glycolysis and the Krebs cycle, later donating electrons to the electron transport chain.",
    },
    {
        "question": "Oxygen is not produced during photosynthesis by",
        "options": ["Green sulphur bacteria", "Nostoc", "Cycas", "Chara"],
        "correct_option_id": 0,
        "explanation": "Green sulphur bacteria perform anoxygenic photosynthesis using H2S instead of water as an electron donor, so they do not release oxygen; the others perform oxygenic photosynthesis.",
    },
    {
        "question": "Pollen grains can be stored for several years in liquid nitrogen having a temperature of",
        "options": ["–120 °C", "–80 °C", "–196 °C", "–160 °C"],
        "correct_option_id": 2,
        "explanation": "Liquid nitrogen, used for cryopreservation of pollen (pollen banks), has a temperature of about –196°C.",
    },
    {
        "question": "In which of the following forms is iron absorbed by plants?",
        "options": ["Ferric", "Ferrous", "Free element", "Both ferric and ferrous"],
        "correct_option_id": 1,
        "explanation": "Plants absorb iron mainly in the ferrous (Fe2+) form, which is more soluble and readily taken up by roots.",
    },
    {
        "question": "Double fertilization is",
        "options": ["Fusion of two male gametes of a pollen tube with two different eggs", "Fusion of one male gamete with two polar nuclei", "Fusion of two male gametes with one egg", "Syngamy and triple fusion"],
        "correct_option_id": 3,
        "explanation": "Double fertilization involves two fusion events: syngamy (male gamete + egg forming zygote) and triple fusion (second male gamete + two polar nuclei forming the primary endosperm nucleus).",
    },
    {
        "question": "Which of the following elements is responsible for maintaining turgor in cells?",
        "options": ["Magnesium", "Sodium", "Potassium", "Calcium"],
        "correct_option_id": 2,
        "explanation": "Potassium is the key ion responsible for maintaining cell turgor and regulating osmotic balance, particularly in guard cells for stomatal movement.",
    },
    {
        "question": "Which one of the following plants shows a very close relationship with a species of moth, where none of the two can complete its life cycle without the other?",
        "options": ["Hydrilla", "Yucca", "Banana", "Viola"],
        "correct_option_id": 1,
        "explanation": "Yucca plants and Yucca moths share an obligate mutualistic relationship: the moth pollinates the flower while laying eggs, and its larvae feed on some seeds, with neither species able to complete its life cycle without the other.",
    },
    {
        "question": "Hormones secreted by the placenta to maintain pregnancy are",
        "options": ["hCG, hPL, progesterone, prolactin", "hCG, hPL, estrogens, relaxin, oxytocin", "hCG, hPL, progesterone, estrogens", "hCG, progesterone, estrogens, glucocorticoids"],
        "correct_option_id": 2,
        "explanation": "The placenta acts as an endocrine tissue, producing hCG, human placental lactogen (hPL), progesterone, and estrogens to support and maintain pregnancy.",
    },
    {
        "question": "The contraceptive 'SAHELI'",
        "options": ["blocks estrogen receptors in the uterus, preventing implantation.", "increases the concentration of estrogen and prevents ovulation in females.", "is an IUD", "is a post-coital contraceptive."],
        "correct_option_id": 0,
        "explanation": "Saheli is a non-steroidal, once-a-week oral contraceptive (centchroman) with anti-estrogenic activity that blocks estrogen receptors in the uterus, preventing implantation.",
    },
    {
        "question": "The difference between spermiogenesis and spermiation is",
        "options": ["In spermiogenesis spermatids are formed, while in spermiation spermatozoa are formed.", "In spermiogenesis spermatozoa are formed, while in spermiation spermatids are formed.", "In spermiogenesis spermatozoa from Sertoli cells are released into the cavity of seminiferous tubules, while in spermiation spermatozoa are formed.", "In spermiogenesis, spermatozoa are formed, while in spermiation spermatozoa are released from Sertoli cells into the cavity of seminiferous tubules."],
        "correct_option_id": 3,
        "explanation": "Spermiogenesis is the transformation of spermatids into mature spermatozoa, while spermiation is the subsequent release of these mature spermatozoa from Sertoli cells into the lumen of the seminiferous tubules.",
    },
    {
        "question": "The amnion of mammalian embryo is derived from",
        "options": ["ectoderm and mesoderm", "endoderm and mesoderm", "mesoderm and trophoblast", "ectoderm and endoderm"],
        "correct_option_id": 0,
        "explanation": "The amnion, an extra-embryonic membrane, develops from the ectoderm and mesoderm.",
    },
    {
        "question": "In a growing population of a country",
        "options": ["pre-reproductive individuals are more than the reproductive individuals.", "reproductive individuals are less than the post-reproductive individuals.", "reproductive and pre-reproductive individuals are equal in number.", "pre-reproductive individuals are less than the reproductive individuals."],
        "correct_option_id": 0,
        "explanation": "In an expanding/growing population, the age pyramid is broad-based, meaning the pre-reproductive (younger) age group outnumbers the reproductive group.",
    },
    {
        "question": "All of the following are included in 'Ex-situ conservation' except",
        "options": ["Wildlife safari parks", "Sacred groves", "Botanical Gardens", "Seed banks"],
        "correct_option_id": 1,
        "explanation": "Sacred groves are protected forest patches conserved in their natural habitat, making them an example of in-situ (not ex-situ) conservation.",
    },
    {
        "question": "Which part of poppy plant is used to obtain the drug Smack?",
        "options": ["Flowers", "Latex", "Roots", "Leaves"],
        "correct_option_id": 1,
        "explanation": "Smack (diacetylmorphine/heroin) is obtained from the latex of the poppy plant (Papaver somniferum).",
    },
    {
        "question": "Which one of the following population interactions is widely used in medical science for the production of antibiotics?",
        "options": ["Commensalism", "Mutualism", "Parasitism", "Amensalism"],
        "correct_option_id": 3,
        "explanation": "Amensalism, where one organism is harmed and the other unaffected (e.g., Penicillium producing penicillin that inhibits bacterial growth), is exploited in antibiotic production.",
    },
    {
        "question": "Which of the following events does not occur in rough endoplasmic reticulum?",
        "options": ["Protein folding", "Protein glycosylation", "Cleavage of signal peptide", "Phospholipid synthesis"],
        "correct_option_id": 3,
        "explanation": "Phospholipid synthesis occurs mainly in the smooth endoplasmic reticulum, while protein folding, glycosylation, and signal peptide cleavage occur in the rough ER.",
    },
    {
        "question": "Which of these statements is incorrect?",
        "options": ["Enzymes of TCA cycle are present in mitochondrial matrix.", "Glycolysis occurs in cytosol.", "Glycolysis operates as long as it is supplied with NAD that can pick up hydrogen atoms.", "Oxidative phosphorylation takes place in outer mitochondrial membrane."],
        "correct_option_id": 3,
        "explanation": "Oxidative phosphorylation actually occurs on the inner mitochondrial membrane (where the electron transport chain and ATP synthase are located), not the outer membrane, making this statement incorrect.",
    },
    {
        "question": "Many ribosomes may associate with a single mRNA to form multiple copies of a polypeptide simultaneously. Such strings of ribosomes are termed as",
        "options": ["Polysome", "Polyhedral bodies", "Plastidome", "Nucleosome"],
        "correct_option_id": 0,
        "explanation": "A polysome (polyribosome) is a cluster of ribosomes attached to the same mRNA strand, enabling simultaneous translation into multiple polypeptide copies.",
    },
    {
        "question": "Select the incorrect match:",
        "options": ["Lampbrush – Diplotene bivalents chromosomes", "Allosomes – Sex chromosomes", "Submetacentric – L-shaped chromosomes", "Polytene – Oocytes of amphibians chromosomes"],
        "correct_option_id": 3,
        "explanation": "Polytene chromosomes are typically found in the salivary glands of dipteran insect larvae, not in amphibian oocytes; lampbrush chromosomes, in contrast, occur in diplotene-stage amphibian oocytes.",
    },
    {
        "question": "Nissl bodies are mainly composed of",
        "options": ["Proteins and lipids", "DNA and RNA", "Nucleic acids and SER", "Free ribosomes and RER"],
        "correct_option_id": 3,
        "explanation": "Nissl bodies (Nissl granules), found in neuron cell bodies, are composed of rough endoplasmic reticulum studded with free ribosomes, involved in protein synthesis.",
    },
    {
        "question": "Which of the following terms describe human dentition?",
        "options": ["Thecodont, Diphyodont, Homodont", "Thecodont, Diphyodont, Heterodont", "Pleurodont, Monophyodont, Homodont", "Pleurodont, Diphyodont, Heterodont"],
        "correct_option_id": 1,
        "explanation": "Human teeth are set in sockets (thecodont), replaced once during life (diphyodont), and are of different types—incisors, canines, premolars, molars (heterodont).",
    },
    {
        "question": "The similarity of bone structure in the forelimbs of many vertebrates is an example of",
        "options": ["evolution", "Analogy", "Convergent evolution", "Adaptive radiation"],
        "correct_option_id": 0,
        "explanation": "Similarity in the fundamental bone structure of forelimbs across different vertebrates (homology) is strong evidence of evolution from a common ancestor, and reflects divergent evolution.",
    },
    {
        "question": "Which of the following is not an autoimmune disease?",
        "options": ["Psoriasis", "Rheumatoid arthritis", "Alzheimer's disease", "Vitiligo"],
        "correct_option_id": 2,
        "explanation": "Alzheimer's disease is a neurodegenerative disorder, not caused by an autoimmune response, unlike psoriasis, rheumatoid arthritis, and vitiligo.",
    },
    {
        "question": "Among the following sets of examples for divergent evolution, select the incorrect option:",
        "options": ["Forelimbs of man, bat and cheetah", "Heart of bat, man and cheetah", "Brain of bat, man and cheetah", "Eye of octopus, bat and man"],
        "correct_option_id": 3,
        "explanation": "The eyes of octopus, bat, and man evolved independently and are structurally different despite performing a similar function—this is an example of convergent (analogous) evolution, not divergent evolution.",
    },
    {
        "question": "Which of the following characteristics represent 'Inheritance of blood groups' in humans? a. Dominance b. Co-dominance c. Multiple dominance d. Incomplete dominance e. Polygenic inheritance",
        "options": ["b, c and e", "a, b and c", "b, d and e", "a, c and e"],
        "correct_option_id": 1,
        "explanation": "ABO blood group inheritance shows dominance (IA, IB dominant over i), co-dominance (IA and IB expressed together in AB group), and multiple allelism (three alleles IA, IB, i), corresponding to options a, b, and c.",
    },
    {
        "question": "In which disease does mosquito transmitted pathogen cause chronic inflammation of lymphatic vessels?",
        "options": ["Elephantiasis", "Ascariasis", "Ringworm disease", "Amoebiasis"],
        "correct_option_id": 0,
        "explanation": "Elephantiasis (filariasis) is caused by filarial worms transmitted by mosquitoes, leading to chronic inflammation and blockage of the lymphatic system.",
    },
    {
        "question": "Conversion of milk to curd improves its nutritional value by increasing the amount of",
        "options": ["Vitamin D", "Vitamin A", "Vitamin B12", "Vitamin E"],
        "correct_option_id": 2,
        "explanation": "Lactic acid bacteria involved in curd formation enhance its nutritional quality by increasing Vitamin B12 content.",
    },
    {
        "question": "Which of the following is an amino acid derived hormone?",
        "options": ["Epinephrine", "Ecdysone", "Estradiol", "Estriol"],
        "correct_option_id": 0,
        "explanation": "Epinephrine (adrenaline) is derived from the amino acid tyrosine, while ecdysone, estradiol, and estriol are steroid hormones.",
    },
    {
        "question": "Which of the following structures or regions is incorrectly paired with its function?",
        "options": ["Medulla oblongata: controls respiration and cardiovascular reflexes.", "Limbic system: consists of fibre tracts that interconnect different regions of brain; controls movement.", "Hypothalamus: production of releasing hormones and regulation of temperature, hunger and thirst.", "Corpus callosum: band of fibers connecting left and right cerebral hemispheres."],
        "correct_option_id": 1,
        "explanation": "The limbic system, along with the hypothalamus, is primarily involved in regulating emotions (fear, rage, sexual behaviour, etc.), not voluntary movement control.",
    },
    {
        "question": "Which of the following hormones can play a significant role in osteoporosis?",
        "options": ["Aldosterone and Prolactin", "Progesterone and Aldosterone", "Estrogen and Parathyroid hormone", "Parathyroid hormone and Prolactin"],
        "correct_option_id": 2,
        "explanation": "Reduced estrogen levels (e.g., post-menopause) and altered parathyroid hormone activity affect bone calcium balance, contributing significantly to osteoporosis.",
    },
    {
        "question": "The transparent lens in the human eye is held in its place by",
        "options": ["ligaments attached to the ciliary body", "ligaments attached to the iris", "smooth muscles attached to the iris", "smooth muscles attached to the ciliary body"],
        "correct_option_id": 0,
        "explanation": "The eye lens is held in position by suspensory ligaments attached to the ciliary body, which also help adjust the lens shape during accommodation.",
    },
    {
        "question": "Which of the following animals does not undergo metamorphosis?",
        "options": ["Earthworm", "Tunicate", "Moth", "Starfish"],
        "correct_option_id": 0,
        "explanation": "Earthworms undergo direct development without a larval stage, unlike tunicates, moths, and starfish, all of which pass through a larval stage and metamorphosis.",
    },
    {
        "question": "Identify the vertebrate group of animals characterized by crop and gizzard in its digestive system.",
        "options": ["Amphibia", "Reptilia", "Aves", "Osteichthyes"],
        "correct_option_id": 2,
        "explanation": "Birds (Aves) have a specialized digestive system with a crop for temporary food storage and a muscular gizzard for grinding food, since they lack teeth.",
    },
    {
        "question": "Which of the following organisms are known as chief producers in the oceans?",
        "options": ["Dinoflagellates", "Diatoms", "Cyanobacteria", "Euglenoids"],
        "correct_option_id": 1,
        "explanation": "Diatoms are the major primary producers of marine phytoplankton and form the base of oceanic food chains, also contributing largely to global oxygen production.",
    },
    {
        "question": "Which one of these animals is not a homeotherm?",
        "options": ["Macropus", "Chelone", "Camelus", "Psittacula"],
        "correct_option_id": 1,
        "explanation": "Chelone (turtle) is a reptile and hence a poikilotherm (cold-blooded, ectotherm), unlike the mammals (Macropus - kangaroo, Camelus - camel) and birds (Psittacula - parakeet) listed, which are homeothermic.",
    },
    {
        "question": "Ciliates differ from all other protozoans in",
        "options": ["using flagella for locomotion", "having a contractile vacuole for removing excess water", "using pseudopodia for capturing prey", "having two types of nuclei"],
        "correct_option_id": 3,
        "explanation": "Ciliates (e.g., Paramecium) are unique among protozoans in possessing two types of nuclei — a macronucleus (vegetative functions) and a micronucleus (reproductive functions).",
    },
    {
        "question": "Which of the following features is used to identify a male cockroach from a female cockroach?",
        "options": ["Presence of a boat shaped sternum on the 9th abdominal segment", "Presence of caudal styles", "Forewings with darker tegmina", "Presence of anal cerci"],
        "correct_option_id": 1,
        "explanation": "Male cockroaches possess a pair of thread-like anal/caudal styles on the 9th abdominal segment, which are absent in females, serving as a distinguishing feature.",
    },
    {
        "question": "Which of the following options correctly represents the lung conditions in asthma and emphysema, respectively?",
        "options": ["Inflammation of bronchioles; Decreased respiratory surface", "Increased number of bronchioles; Increased respiratory surface", "Increased respiratory surface; Inflammation of bronchioles", "Decreased respiratory surface; Inflammation of bronchioles"],
        "correct_option_id": 0,
        "explanation": "Asthma involves inflammation and constriction of the bronchioles causing difficulty in breathing, while emphysema involves alveolar wall damage that decreases the total respiratory surface area.",
    },
    {
        "question": "AGGTATCGCAT is a sequence from the coding strand of a gene. What will be the corresponding sequence of the transcribed mRNA?",
        "options": ["AGGUAUCGCAU", "UGGTUTCGCAT", "ACCUAUGCGAU", "UCCAUAGCGUA"],
        "correct_option_id": 0,
        "explanation": "Since mRNA has the same sequence as the coding strand except thymine (T) is replaced by uracil (U), AGGTATCGCAT becomes AGGUAUCGCAU.",
    },
    {
        "question": "According to Hugo de Vries, the mechanism of evolution is:-",
        "options": ["Multiple step mutations", "Saltation", "Phenotypic variations", "Minor mutations"],
        "correct_option_id": 1,
        "explanation": "Hugo de Vries proposed the mutation theory of evolution, suggesting that evolution occurs through sudden, large discontinuous variations called saltations, not gradual changes.",
    },
    {
        "question": "A woman has an X-linked condition on one of her X chromosomes. This chromosome can be inherited by:-",
        "options": ["Only daughters", "Only sons", "Only grandchildren", "Both sons and daughters"],
        "correct_option_id": 3,
        "explanation": "Since a woman's affected X chromosome can be passed to any of her offspring (sons receive one X from mother, daughters receive one X from each parent), it can be inherited by both sons and daughters.",
    },
    {
        "question": "All of the following are part of an operon except:-",
        "options": ["an operator", "structural genes", "an enhancer", "a promoter"],
        "correct_option_id": 2,
        "explanation": "An operon (a prokaryotic gene expression unit) consists of a promoter, an operator, and structural genes; enhancers are regulatory elements typically associated with eukaryotic gene expression, not bacterial operons.",
    },
    {
        "question": "Which of the following gastric cells indirectly help in erythropoiesis?",
        "options": ["Chief cells", "Mucous cells", "Goblet cells", "Parietal cells"],
        "correct_option_id": 3,
        "explanation": "Parietal cells secrete intrinsic factor, essential for the absorption of vitamin B12 in the intestine, which is in turn needed for proper red blood cell (erythrocyte) formation.",
    },
    {
        "question": "Calcium is important in skeletal muscle contraction because it:-",
        "options": ["binds to troponin to remove the masking of active sites on actin for myosin.", "activates the myosin ATPase by binding to it.", "detaches the myosin head from the actin filament.", "prevents the formation of bonds between the myosin cross bridges and the actin filament."],
        "correct_option_id": 0,
        "explanation": "Calcium ions bind to troponin, causing a conformational change that shifts tropomyosin away from the myosin-binding sites on actin, thus exposing them for cross-bridge formation.",
    },
    {
        "question": "Which of the following is an occupational respiratory disorder?",
        "options": ["Anthracis", "Silicosis", "Botulism", "Emphysema"],
        "correct_option_id": 1,
        "explanation": "Silicosis is an occupational lung disease caused by prolonged inhalation of silica dust, commonly affecting workers in mining and stone-cutting industries.",
    },
]
