"""
Question bank: NEET 2019 (Odisha) - Biology (Solved Answers).

75 questions parsed from NEET 2019 (Odisha)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Which of the following cell organelles is present in the highest number in secretory cells?",
        "options": ["Mitochondria", "Golgi complex", "Endoplasmic reticulum", "Lysosomes"],
        "correct_option_id": 1,
        "explanation": "Secretory cells (e.g., glandular cells) contain numerous Golgi complexes/bodies, as they are essential for packaging and secretion of cellular products.",
    },
    {
        "question": "Non-membranous nucleoplasmic structures in nucleus are the site for active synthesis of",
        "options": ["protein synthesis", "mRNA", "rRNA", "tRNA"],
        "correct_option_id": 2,
        "explanation": "The nucleolus, a non-membrane bound nucleoplasmic structure, is the site of active rRNA synthesis and ribosome assembly.",
    },
    {
        "question": "Which of the following nucleic acids is present in an organism having 70 S ribosomes only?",
        "options": ["Single stranded DNA with protein coat", "Double stranded circular naked DNA", "Double stranded DNA enclosed in nuclear membrane", "Double stranded circular DNA with histone proteins"],
        "correct_option_id": 1,
        "explanation": "Organisms with only 70S ribosomes are prokaryotes (bacteria), which possess double stranded circular naked (non-histone-associated) DNA and lack a nuclear membrane.",
    },
    {
        "question": "After meiosis I, the resultant daughter cells have",
        "options": ["same amount of DNA as in the parent cell in S", "twice the amount of DNA in comparison to haploid", "same amount of DNA in comparison to haploid gamete", "four times the amount of DNA in comparison to haploid gamete"],
        "correct_option_id": 1,
        "explanation": "After meiosis I, each daughter cell has half the chromosome number but each chromosome still has two chromatids, so the DNA content is twice that of a haploid gamete.",
    },
    {
        "question": "Which of the following organic compounds is the main constituent of Lecithin?",
        "options": ["Arachidonic acid", "Phospholipid", "Cholesterol", "Phosphoprotein"],
        "correct_option_id": 1,
        "explanation": "Lecithin (phosphatidylcholine) is a phospholipid, the major constituent of cell membranes.",
    },
    {
        "question": "The main difference between active and passive transport across cell membrane is :",
        "options": ["passive transport is non-selective whereas active transport is selective", "passive transport requires a concentration gradient across a biological membrane whereas active transport requires energy to move solutes.", "passive transport is confined to anionic carrier proteins whereas active transport is confined to cationic channel.", "active transport occurs more rapidly than passive"],
        "correct_option_id": 1,
        "explanation": "Passive transport moves solutes along a concentration gradient without energy, whereas active transport uses ATP to move solutes, often against the gradient.",
    },
    {
        "question": "Kwashiorkor disease is due to",
        "options": ["simultaneous deficiency of proteins and fats", "simultaneous deficiency of proteins and calories", "deficiency of carbohydrates", "protein deficiency not accompanied by calorie deficiency"],
        "correct_option_id": 3,
        "explanation": "Kwashiorkor results from severe protein deficiency in the diet while overall calorie intake remains largely adequate, unlike marasmus which involves both protein and calorie deficiency.",
    },
    {
        "question": "Select the correct sequence of events.",
        "options": ["Gametogenesis → Gamete transfer → Syngamy → Zygote → Cell division (Cleavage) → Cell differentiation → Organogenesis", "Gametogenesis → Gamete transfer → Syngamy → Zygote → Cell division (Cleavage) → Organogenesis → Cell differentiation", "Gametogenesis → Syngamy → Gamete transfer → Zygote → Cell division (Cleavage) → Cell differentiation → Organogenesis", "Gametogenesis → Gamete transfer → Syngamy → Zygote → Cell differentiation → Cell division (Cleavage) → Organogenesis"],
        "correct_option_id": 0,
        "explanation": "This is the correct developmental sequence: gametes form, transfer, fuse (syngamy) to form a zygote, which undergoes cleavage, then cell differentiation, and finally organ formation (organogenesis).",
    },
    {
        "question": "Which of the following hormones is responsible for both the milk ejection reflex and the foetal ejection reflex?",
        "options": ["Estrogen", "Prolactin", "Oxytocin", "Relaxin"],
        "correct_option_id": 2,
        "explanation": "Oxytocin stimulates uterine contractions during parturition (foetal ejection reflex) and causes milk ejection from mammary glands.",
    },
    {
        "question": "No new follicles develop in the luteal phase of the menstrual cycle because :",
        "options": ["Follicles do not remain in the ovary after", "FSH levels are high in the luteal phase", "LH levels are high in the luteal phase", "Both FSH and LH levels are low in the luteal phase"],
        "correct_option_id": 3,
        "explanation": "During the luteal phase, negative feedback from progesterone and estrogen keeps FSH and LH levels low, preventing new follicle development.",
    },
    {
        "question": "In Australia, marsupials and placental mammals have evolved to share many similar characteristics. This type of evolution may be referred to as -",
        "options": ["Adaptive Radiation", "Divergent Evolution", "Cyclical Evolution", "Convergent Evolution"],
        "correct_option_id": 3,
        "explanation": "Convergent evolution occurs when unrelated species (like Australian marsupials and placental mammals elsewhere) independently evolve similar traits due to similar environmental pressures.",
    },
    {
        "question": "What will be the sequence of mRNA produced by the following stretch of DNA? (NEET 2019) 3' ATGCATGCATGCATG 5' TEMPLATE STRAND 5' TACGTACGTACGTAC 3' CODING STRAND",
        "options": ["3' AUGCAUGCAUGCAUG 5'", "5' UACGUACGUACGUAC 3'", "3' UACGUACGUACGUAC 5'", "5' AUGCAUGCAUGCAUG 3'"],
        "correct_option_id": 1,
        "explanation": "mRNA is synthesized complementary and antiparallel to the template strand (with U replacing T), giving the same sequence as the coding strand but with U instead of T: 5' UACGUACGUACGUAC 3'.",
    },
    {
        "question": "Select the incorrect statement regarding inbreeding:",
        "options": ["Inbreeding helps in elimination of deleterious alleles from the population", "Inbreeding is necessary to evolve a pure-line in any animal", "Continued inbreeding reduces fertility and leads to inbreeding depression.", "Inbreeding depression cannot be overcome by Out-crossing."],
        "correct_option_id": 3,
        "explanation": "Inbreeding depression can actually be overcome by out-crossing (mating unrelated individuals), which restores heterozygosity and vigor; hence statement 4 is incorrect.",
    },
    {
        "question": "A biocontrol agent to be a part of an integrated pest management should be",
        "options": ["species-specific and symbiotic", "free living and broad spectrum", "narrow spectrum and symbiotic", "species-specific and inactive on non-target organisms"],
        "correct_option_id": 3,
        "explanation": "An ideal biocontrol agent must specifically target the pest species while remaining harmless to non-target organisms, ensuring ecological safety.",
    },
    {
        "question": "The two antibiotic resistance genes on vector pBR 322 are for",
        "options": ["Ampicillin and Tetracycline", "Ampicillin and Chloramphenicol", "Chloramphenicol and Tetracycline", "Tetracycline and Kanamycin"],
        "correct_option_id": 0,
        "explanation": "The cloning vector pBR322 carries genes conferring resistance to ampicillin (ampR) and tetracycline (tetR), used as selectable markers.",
    },
    {
        "question": "Exploitation of bioresources of a nation by multinational companies without authorization from the concerned country is referred to as",
        "options": ["Bioweapon", "Biopiracy", "Bioethics", "Biowar"],
        "correct_option_id": 1,
        "explanation": "Biopiracy refers to the unauthorized use/exploitation of a nation's bioresources and traditional knowledge by other entities, typically without fair compensation.",
    },
    {
        "question": "Carnivorous animals - lions and leopards, occupy the same niche but lions predate mostly larger animals and leopards take smaller ones. This mechanism of competition is referred to as -",
        "options": ["Character displacement", "Altruism", "Resource partitioning", "Competitive exclusion"],
        "correct_option_id": 2,
        "explanation": "Resource partitioning allows competing species to coexist by using different portions of a shared resource (here, prey of different sizes), reducing direct competition.",
    },
    {
        "question": "Decline in the population of Indian native fishes due to introduction of Clarias gariepinus in river Yamuna can be categorised as",
        "options": ["Co-extinction", "Habitat fragmentation", "Over exploitation", "Alien species invasion"],
        "correct_option_id": 3,
        "explanation": "The introduction of the exotic African catfish Clarias gariepinus into Indian rivers is an example of alien/invasive species invasion, which threatens native biodiversity.",
    },
    {
        "question": "In a marriage between male with blood group A and female with blood group B, the progeny had either blood group AB or B. What could be the possible genotype of parents?",
        "options": ["I^A i (Male) ; I^B I^B (Female)", "I^A I^A (Male) ; I^B I^B (Female)", "I^A I^A (Male) ; I^B i (Female)", "I^A i (Male) ; I^B i (Female)"],
        "correct_option_id": 0,
        "explanation": "With male I^A i and female I^B I^B, possible offspring genotypes are I^A I^B (blood group AB) and I^B i (blood group B), matching the observed progeny.",
    },
    {
        "question": "A population of a species invades a new area. Which of the following condition will lead to Adaptive Radiation?",
        "options": ["Area with large number of habitats having very low food supply.", "Area with a single type of vacant habitat", "Area with many types of vacant habitats.", "Area with many habitats occupied by a large number of species."],
        "correct_option_id": 2,
        "explanation": "Adaptive radiation occurs when a species diversifies rapidly to fill many different vacant ecological niches/habitats, as with Darwin's finches on the Galapagos Islands.",
    },
    {
        "question": "Humans have acquired immune system that produces antibodies to neutralize pathogens. Still innate immune system is present at the time of birth because it",
        "options": ["is very specific and uses different macrophages,", "produces memory cells for mounting fast secondary response.", "has natural killer cells which can phagocytose and destroy microbes", "provides passive immunity."],
        "correct_option_id": 2,
        "explanation": "The innate immune system provides immediate, non-specific defense from birth, including cells such as natural killer cells and phagocytes that act against pathogens before the adaptive response develops.",
    },
    {
        "question": "Which of the following statements is not correct?",
        "options": ["An action potential in an axon does not move backward because the segment behind is in a refractory phase.", "Depolarization of hair cells of cochlea results in the opening of the mechanically gated Potassium- ion channels.", "Rods are very sensitive and contribute to daylight vision.", "In the knee-jerk reflex, stimulus is the stretching of muscle and response is its contraction."],
        "correct_option_id": 2,
        "explanation": "Rods are highly sensitive to dim light and are responsible for vision in low-light (scotopic) conditions, not daylight vision, which is mediated by cones; hence this statement is incorrect.",
    },
    {
        "question": "Which of the following diseases is an auto-immune disorder?",
        "options": ["Myasthenia gravis", "Arthritis", "Osteoporosis", "Gout"],
        "correct_option_id": 0,
        "explanation": "Myasthenia gravis is an autoimmune disorder in which antibodies attack acetylcholine receptors at the neuromuscular junction, causing muscle weakness.",
    },
    {
        "question": "Artificial light, extended work-time and reduced sleep-time disrupt the activity of",
        "options": ["Thymus gland", "Pineal gland", "Adrenal gland", "Posterior pituitary gland"],
        "correct_option_id": 1,
        "explanation": "The pineal gland regulates circadian rhythms via melatonin secretion, which is influenced by light exposure; artificial light and irregular schedules disrupt its normal activity.",
    },
    {
        "question": "Which of the following conditions will stimulate parathyroid gland to release parathyroid hormone ?",
        "options": ["Fall in active Vitamin D levels", "Fall in blood Ca+2 levels", "Fall in bone Ca+2 levels", "Rise in blood Ca+2 levels"],
        "correct_option_id": 1,
        "explanation": "A decrease in blood calcium levels stimulates the parathyroid gland to secrete PTH, which acts to raise blood calcium levels back to normal.",
    },
    {
        "question": "Which of the following is a correct statement?",
        "options": ["IUDs once inserted need not be replaced.", "IUDs are generally inserted by the user herself.", "IUDs increase phagocytosis of sperms in the uterus.", "IUDs suppress gametogenesis."],
        "correct_option_id": 2,
        "explanation": "Copper-releasing IUDs increase phagocytosis of sperm within the uterus and also suppress sperm motility/fertilizing capacity, acting as an effective contraceptive.",
    },
    {
        "question": "Which of the following sexually transmitted diseases do not specifically affect reproductive organs ?",
        "options": ["Genital warts and Hepatitis-B", "Syphilis and Genital herpes", "AIDS and Hepatitis B", "Chlamydiasis and AIDS"],
        "correct_option_id": 2,
        "explanation": "AIDS and Hepatitis B are systemic viral infections that affect the immune system and liver respectively, rather than being localized specifically to the reproductive organs, even though they are sexually transmitted.",
    },
    {
        "question": "Which of the following animals are true coelomates with bilateral symmetry ?",
        "options": ["Adult Echinoderms", "Aschelminthes", "Platyhelminthes", "Annelids"],
        "correct_option_id": 3,
        "explanation": "Annelids are true coelomates (schizocoelomate) with bilateral symmetry, unlike echinoderms (radial symmetry as adults), aschelminthes (pseudocoelomate), and platyhelminthes (acoelomate).",
    },
    {
        "question": "The contrasting characteristics generally in a pair used for identification of animals in Taxonomic Key are referred to as :",
        "options": ["Lead", "Couplet", "Doublet", "Alternate"],
        "correct_option_id": 1,
        "explanation": "In a taxonomic key, each pair of contrasting characters used to make identification choices is called a couplet.",
    },
    {
        "question": "Which of the following statements is INCORRECT ?",
        "options": ["Cockroaches exhibit mosaic vision with less sensitivity and more resolution", "A mushroom-shaped gland is present in the 6th-7th abdominal segments of male", "A pair of spermatheca is present in the 6th segment of female cockroach", "Female cockroach possesses sixteen ovarioles in the ovaries."],
        "correct_option_id": 2,
        "explanation": "Female cockroaches have a single (unpaired) spermatheca located in the 6th segment, not a pair; hence this statement is incorrect.",
    },
    {
        "question": "Select the correct statement.",
        "options": ["Expiration occurs due to external intercostal muscles.", "Intrapulmonary pressure is lower than the atmospheric pressure during inspiration.", "Inspiration occurs when atmospheric pressure is less than intrapulmonary pressure.", "Expiration is initiated due to contraction of diaphragm."],
        "correct_option_id": 1,
        "explanation": "During inspiration, the thoracic cavity expands, lowering intrapulmonary pressure below atmospheric pressure, causing air to flow into the lungs.",
    },
    {
        "question": "The maximum volume of air a person can breathe in after a forced expiration is known as :",
        "options": ["Expiratory Capacity", "Vital Capacity", "Inspiratory Capacity", "Total Lung Capacity"],
        "correct_option_id": 1,
        "explanation": "Vital capacity is the maximum volume of air that can be inhaled after a forced maximum expiration; it includes tidal volume, inspiratory reserve volume, and expiratory reserve volume.",
    },
    {
        "question": "All the components of the nodal tissue are autoexcitable. Why does the SA node act as the normal pacemaker ?",
        "options": ["SA node has the lowest rate of depolarisation", "SA node is the only component to generate the threshold potential.", "Only SA node can convey the action potential to the other", "SA node has the highest rate of depolarisation."],
        "correct_option_id": 3,
        "explanation": "The SA node depolarizes faster than other nodal tissues, generating impulses at the highest rate, so it sets the pace for the heartbeat and is called the natural pacemaker.",
    },
    {
        "question": "A specialised nodal tissue embedded in the lower corner of the right atrium, close to Atrio-ventricular septum, delays the spreading of impulses to heart apex for about 0.1 sec. This delay allows -",
        "options": ["blood to enter aorta.", "the ventricles to empty completely.", "blood to enter pulmonary arteries.", "the atria to empty completely."],
        "correct_option_id": 3,
        "explanation": "The AV node delay ensures that the atria finish contracting and emptying blood into the ventricles before ventricular contraction begins.",
    },
    {
        "question": "Which of the following receptors are specifically responsible for maintenance of balance of body and posture ?",
        "options": ["Basilar membrane and otoliths", "Hair cells and organ of corti", "Tectorial membrane and macula", "Crista ampullaris and macula"],
        "correct_option_id": 3,
        "explanation": "The crista ampullaris (in semicircular canals) and macula (in utricle and saccule) are vestibular receptors responsible for detecting rotational and linear movements, thereby maintaining body balance and posture.",
    },
    {
        "question": "Mad cow disease in cattle is caused by an organism which has :",
        "options": ["Inert crystalline", "Abnormally folded protein", "Free RNA without protein coat", "Free DNA without protein coat"],
        "correct_option_id": 1,
        "explanation": "Mad cow disease (bovine spongiform encephalopathy) is caused by prions, which are abnormally folded infectious proteins.",
    },
    {
        "question": "Which of the following statements is correct?",
        "options": ["Lichens do not grow in polluted areas.", "Algal component of lichens is called mycobiont", "Fungal component of lichens is called phycobiont", "Lichens are not good pollution indicators."],
        "correct_option_id": 0,
        "explanation": "Lichens are highly sensitive to pollutants like sulphur dioxide and do not grow in polluted areas, making them good bioindicators of air pollution.",
    },
    {
        "question": "In the dicot root the vascular cambium originates from :",
        "options": ["Tissue located below the phloem bundles and a portion of pericycle tissue above protoxylem.", "Cortical region", "Parenchyma between endodermis and pericycle", "Intrafascicular and interfascicular tissue in a ring"],
        "correct_option_id": 0,
        "explanation": "In a dicot root, the vascular cambium develops from conjunctive tissue (parenchyma) located beneath the phloem bundles, along with a portion of pericycle cells lying just above the protoxylem.",
    },
    {
        "question": "Which of the following shows whorled phyllotaxy ?",
        "options": ["Mustard", "China rose", "Alstonia", "Calotropis"],
        "correct_option_id": 2,
        "explanation": "In Alstonia, more than two leaves arise at each node forming a whorl, which is characteristic of whorled phyllotaxy.",
    },
    {
        "question": "Regeneration of damaged growing grass following grazing is largely due to :",
        "options": ["Lateral meristem", "Apical meristem", "Intercalary meristem", "Secondary meristem"],
        "correct_option_id": 2,
        "explanation": "Intercalary meristem, present at the base of leaves/internodes in grasses, allows quick regeneration of grass blades after grazing or mowing.",
    },
    {
        "question": "Bicarpellary ovary with obliquely placed septum is seen in :",
        "options": ["Brassica", "Aloe", "Solanum", "Sesbania"],
        "correct_option_id": 2,
        "explanation": "Solanum (family Solanaceae) has a bicarpellary, syncarpous ovary with the septum placed obliquely relative to the median plane of the flower.",
    },
    {
        "question": "Which is the most common type of embryo sac in angiosperms?",
        "options": ["Tetrasporic with one mitotic stage of divisions", "Monosporic with three sequential mitotic divisions", "Monosporic with two sequential mitotic divisions", "Bisporic with two sequential mitotic divisions"],
        "correct_option_id": 1,
        "explanation": "The most common type of embryo sac development is monosporic (Polygonum type), involving three successive mitotic divisions of a single functional megaspore to form the 8-nucleate, 7-celled embryo sac.",
    },
    {
        "question": "From the following, identify the correct combination of salient features of Genetic Code",
        "options": ["Universal, Non-ambiguous,Overlapping", "Degenerate, Overlapping, Commaless", "Universal, Ambiguous, Degenerate", "Degenerate, Non-overlapping, Non ambiguous"],
        "correct_option_id": 3,
        "explanation": "The genetic code is degenerate (multiple codons for one amino acid), non-overlapping (codons read in a sequence without sharing bases), and non-ambiguous (a codon codes for only one amino acid).",
    },
    {
        "question": "Which scientist experimentally proved that DNA is the sole genetic material in bacteriophage ?",
        "options": ["Beadle and Tatum", "Messelson and Stahl", "Hershey and Chase", "Jacob and Monod"],
        "correct_option_id": 2,
        "explanation": "Hershey and Chase's blender experiment using radioactively labeled bacteriophages demonstrated that DNA, not protein, is the genetic material transmitted during infection.",
    },
    {
        "question": "In the process of transcription in Eukaryotes, the RNA polymerase I transcribes -",
        "options": ["mRNA with additional processing, capping and tailing", "tRNA, 5 S rRNA and snRNAs", "rRNAs - 28 S, 18 S and 5.8 S", "Precursor of mRNA, hnRNA"],
        "correct_option_id": 2,
        "explanation": "In eukaryotes, RNA polymerase I is located in the nucleolus and transcribes the larger ribosomal RNAs: 28S, 18S, and 5.8S rRNA.",
    },
    {
        "question": "In which genetic condition, each cell in the affected person, has three sex chromosomes XXY?",
        "options": ["Thalassemia", "Klinefelter's Syndrome", "Phenylketonuria", "Turner's Syndrome"],
        "correct_option_id": 1,
        "explanation": "Klinefelter's syndrome results from an extra X chromosome in males, giving a karyotype of 47, XXY.",
    },
    {
        "question": "Which of the following statements is correct about the origin and evolution of men ?",
        "options": ["Agriculture came around 50,000 years back.", "The Dryopithecus and Ramapithecus primates existing 15 million years ago, walked like men.", "Homo habilis probably ate meat.", "Neanderthal men lived in Asia between 100000 and 40000 years back"],
        "correct_option_id": 2,
        "explanation": "Fossil and dietary evidence suggest that Homo habilis, an early hominid, likely included meat in its diet, distinguishing it from earlier purely herbivorous ancestors.",
    },
    {
        "question": "The production of gametes by the parents the formation of zygotes, the F1 and F2 plants can be understood using",
        "options": ["Pie diagram", "A pyramid diagram", "Punnett square", "Wenn diagram"],
        "correct_option_id": 2,
        "explanation": "A Punnett square is used to predict the genotypic and phenotypic ratios of gametes, zygotes, and F1/F2 generations resulting from a genetic cross.",
    },
    {
        "question": "Prosthetic groups differ from co-enzymes in that",
        "options": ["they require metal ions for their activity", "they (prosthetic groups) are tightly bound to apoenzymes.", "their association with apoenzymes is transient.", "they can serve as co-factors in a number of enzyme-catalyzed reactions."],
        "correct_option_id": 1,
        "explanation": "Unlike coenzymes, which associate loosely and transiently with the enzyme, prosthetic groups are tightly and often covalently bound to the apoenzyme.",
    },
    {
        "question": "Crossing over takes place between which chromatids and in which stage of the cell cycle?",
        "options": ["Non-sister chromatids of non-homologous chromosomes at Zygotene stage of prophase I.", "Non-sister chromatids of homologous chromosomes at Pachytene stage of prophase I.", "Non-sister chromatids of homologous chromosomes at Zygotene stage of prophase I.", "Non-sister chromatids of non-homologous chromosomes at Pachytene stage of prophase I."],
        "correct_option_id": 1,
        "explanation": "Crossing over occurs between non-sister chromatids of homologous chromosomes during the pachytene stage of prophase I of meiosis, facilitated by the synaptonemal complex.",
    },
    {
        "question": "\"Ramachandran plot\" is used to confirm the structure of",
        "options": ["RNA", "Proteins", "Triacylglycerides", "DNA"],
        "correct_option_id": 1,
        "explanation": "The Ramachandran plot is used to visualize the allowed and disallowed torsion angles (phi and psi) in protein backbones, helping validate protein structure.",
    },
    {
        "question": "Which of the following is not a feature of active transport of solutes in plants ?",
        "options": ["Occurs against concentration gradient", "Non-selective", "Occurs through membranes", "Requires ATP"],
        "correct_option_id": 1,
        "explanation": "Active transport is highly selective, using specific membrane carrier proteins to move particular solutes, unlike passive diffusion which is non-selective.",
    },
    {
        "question": "Which of the following bacteria reduce nitrate in soil into nitrogen ?",
        "options": ["Nitrobacter", "Thiobacillus", "Nitrococcus", "Nitrosomonas"],
        "correct_option_id": 1,
        "explanation": "Thiobacillus (denitrificans) is a denitrifying bacterium that reduces soil nitrate back into gaseous nitrogen, completing the nitrogen cycle, unlike Nitrobacter, Nitrococcus, and Nitrosomonas which are nitrifying bacteria.",
    },
    {
        "question": "What will be the direction of flow of water when a plant cell is placed in a Hypotonic solution?",
        "options": ["Water will flow in both directions.", "Water will flow out of the cell.", "Water will flow into the cell.", "No flow of water in any direction."],
        "correct_option_id": 2,
        "explanation": "In a hypotonic solution, the external water potential is higher than inside the cell, so water moves into the cell by osmosis, causing it to swell (and become turgid).",
    },
    {
        "question": "Where is the respiratory electron transport system (ETS) located in plants?",
        "options": ["Mitochondrial matrix", "Outer mitochondrial membrane", "Inner mitochondrial membrane", "Intermembrane space"],
        "correct_option_id": 2,
        "explanation": "The electron transport system, comprising complexes I-IV, is embedded in the inner mitochondrial membrane, where oxidative phosphorylation occurs.",
    },
    {
        "question": "In Hatch and Slack pathway, the primary CO2 acceptor is -",
        "options": ["Oxaloacetic acid", "Phosphoglyceric acid", "Phosphoenol pyruvate", "Rubisco"],
        "correct_option_id": 2,
        "explanation": "In C4 plants (Hatch and Slack pathway), phosphoenol pyruvate (PEP) is the primary CO2 acceptor, catalyzed by the enzyme PEP carboxylase, forming oxaloacetic acid.",
    },
    {
        "question": "Removal of shoot tips is a very useful technique to boost the production of tea- leaves. This is because",
        "options": ["Gibberellins prevent bolting and are inactivated.", "Auxins prevent leaf drop at early stages.", "Effect of auxins is removed and growth of lateral buds is enhanced.", "Gibberellins delay senescence of leaves."],
        "correct_option_id": 2,
        "explanation": "Removing the shoot tip eliminates apical dominance (maintained by auxin), allowing lateral/axillary buds to grow, increasing leaf (tea leaf) production.",
    },
    {
        "question": "One scientist cultured Cladophora in a suspension of Azotobacter and illuminated the culture by splitting light through a prism. He observed that bacteria accumulated mainly in the region of :",
        "options": ["Violet and green light", "Indigo and green light", "Orange and yellow light", "Blue and red light"],
        "correct_option_id": 3,
        "explanation": "This describes Engelmann's classic experiment demonstrating the action spectrum of photosynthesis; oxygen-releasing Azotobacter bacteria accumulated mainly in the blue and red light regions, where photosynthetic activity (and hence oxygen evolution) is highest.",
    },
    {
        "question": "In order to increase the yield of sugarcane crop, which of the following plant growth regulators should be sprayed ?",
        "options": ["Ethylene", "Auxins", "Gibberellins", "Cytokinins"],
        "correct_option_id": 2,
        "explanation": "Spraying gibberellins on sugarcane increases the length of the stem, thereby increasing cane yield and sugar production.",
    },
    {
        "question": "What type of pollination takes place in Vallisneria ?",
        "options": ["Pollination occurs in submerged condition by water.", "Flowers emerge above surface of Water and pollination occurs by insects.", "Flowers emerge above water surface and pollen is carried by wind.", "Male flowers are carried by water currents to female flowers at surface of water."],
        "correct_option_id": 3,
        "explanation": "In Vallisneria, male flowers detach and float to the water surface, where water currents carry them to the female flowers, achieving pollination at the surface of the water.",
    },
    {
        "question": "In which one of the following, both autogamy and geitonogamy are prevented?",
        "options": ["Wheat", "Papaya", "Castor", "Maize"],
        "correct_option_id": 1,
        "explanation": "Papaya is dioecious, with male and female flowers borne on separate plants, which prevents both self-pollination within the same flower (autogamy) and between flowers of the same plant (geitonogamy).",
    },
    {
        "question": "A selectable marker is used to :",
        "options": ["help in eliminating the non transformants so that the transformants can be regenerated", "identify the gene for a desired trait in an alien organism", "select a suitable vector for transformation in a specific crop", "mark a gene on a chromosome for isolation using restriction enzyme"],
        "correct_option_id": 0,
        "explanation": "Selectable markers (such as antibiotic resistance genes) allow identification and elimination of non-transformed cells, so only successfully transformed cells are selected and regenerated.",
    },
    {
        "question": "Western Ghats have a large number of plant and animal species that are not found anywhere else. Which of the following terms will you use to notify such species ?",
        "options": ["Endemic", "Vulnerable", "Threatened", "Keystone"],
        "correct_option_id": 0,
        "explanation": "Species restricted to a particular geographic region and found nowhere else are called endemic species.",
    },
    {
        "question": "Which of the following statements about ozone is correct ?",
        "options": ["Tropospheric ozone protects us from UV radiations.", "Stratospheric ozone is 'bad'.", "Tropospheric ozone is 'good'", "Stratospheric ozone protects us from UV radiations."],
        "correct_option_id": 3,
        "explanation": "Stratospheric ozone forms a protective layer that absorbs harmful ultraviolet radiation from the sun, whereas tropospheric ozone is a harmful pollutant.",
    },
    {
        "question": "Exploration of molecular, genetic and species level diversity for novel products of economic importance is known as :",
        "options": ["Biopiracy", "Bioenergetics", "Bioremediation", "Bioprospecting"],
        "correct_option_id": 3,
        "explanation": "Bioprospecting involves exploring biodiversity at the molecular, genetic, and species levels to discover economically valuable products, such as new drugs or genes.",
    },
    {
        "question": "Which of the following is an innovative remedy for plastic waste ?",
        "options": ["Burning in the absence of oxygen", "Burrying 500 m deep below soil surface", "Polyblend", "Electrostatic precipitator"],
        "correct_option_id": 2,
        "explanation": "Polyblend, a mixture of finely shredded plastic waste with bitumen, is used in road construction, offering an innovative solution to manage plastic waste.",
    },
    {
        "question": "Between which among the following, the relationship is not an example of commensalism?",
        "options": ["Orchid and the tree on which it grows", "Cattle Egret and grazing cattle", "Sea Anemone and Clown fish", "Female wasp and fig species"],
        "correct_option_id": 3,
        "explanation": "The relationship between the fig wasp and fig species is an example of mutualism (both partners benefit through pollination and reproduction), not commensalism.",
    },
    {
        "question": "If an agricultural field is liberally, irrigated for a prolonged period of time, it is likely to face a problem of :",
        "options": ["Metal toxicity", "Alkalinity", "Acidity", "Salinity"],
        "correct_option_id": 3,
        "explanation": "Prolonged excessive irrigation without proper drainage leads to waterlogging and the accumulation of salts near the root zone, resulting in soil salinity.",
    },
    {
        "question": "Which of the following statements about methanogens is not correct?",
        "options": ["They can be used to produce biogas,", "They are found in the rumen of cattle and their excreta.", "They grow aerobically and breakdown cellulose-rich food.", "They produce methane gas."],
        "correct_option_id": 2,
        "explanation": "Methanogens are strictly anaerobic archaea; they do not grow aerobically, making this statement incorrect.",
    },
    {
        "question": "In mung bean, resistance to yellow mosaic, virus and powdery mildew were brought about by :",
        "options": ["Mutation breeding", "Biofortification", "Tissue culture", "Hybridization and selection"],
        "correct_option_id": 3,
        "explanation": "Resistant mung bean varieties against yellow mosaic virus and powdery mildew were developed through conventional hybridization and selection breeding techniques.",
    },
    {
        "question": "Coca alkaloid or cocaine is obtained from",
        "options": ["Papaver somniferum", "Atropha belladona", "Erythroxylum coca", "Datura"],
        "correct_option_id": 2,
        "explanation": "Cocaine, a narcotic alkaloid, is extracted from the leaves of Erythroxylum coca, a plant native to South America.",
    },
    {
        "question": "Among the following pairs of microbes, which pair has both the microbes that can be used as biofertilizers ?",
        "options": ["Aspergillus and Rhizopus", "Rhizobium and Rhizopus", "Cyanobacteria and Rhizobium", "Aspergillus and Cyanobacteria"],
        "correct_option_id": 2,
        "explanation": "Both Cyanobacteria (blue-green algae, nitrogen fixers) and Rhizobium (symbiotic nitrogen-fixing bacteria in legume root nodules) function as effective biofertilizers.",
    },
    {
        "question": "Given below are four statements pertaining to separation of DNA fragments using Gel electrophoresis. Identify the incorrect statements.",
        "options": ["(a), (c) and (d)", "(a), (b) and (c)", "(b), (c) and (d)", "(a), (b) and (d)"],
        "correct_option_id": 2,
        "explanation": "Statements (b) [gel concentration does not affect DNA movement], (c), and (d) [pure DNA can be seen directly without staining under UV] are incorrect; DNA fragments actually require staining (e.g., with ethidium bromide) to be visualized under UV, and gel concentration does influence fragment separation.",
    },
    {
        "question": "An enzyme catalysing the removal of nucleotides from ends of DNA is :",
        "options": ["DNA ligase", "Endonuclease", "Exonuclease", "Protease"],
        "correct_option_id": 2,
        "explanation": "Exonucleases remove nucleotides from the ends (termini) of a DNA strand, unlike endonucleases which cut within the strand.",
    },
    {
        "question": "In RNAi, the genes are silenced using :",
        "options": ["dsRNA", "ssDNA", "ssRNA", "dsDNA"],
        "correct_option_id": 0,
        "explanation": "RNA interference (RNAi) is triggered by double-stranded RNA (dsRNA), which is processed into small interfering RNAs that bind and degrade complementary mRNA, silencing gene expression.",
    },
]
