"""
Question bank: NEET 2016 (Code C) - Biology (Solved Answers).

89 questions parsed from NEET 2016 (Code C)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "In a testcross involving F1 dihybrid flies, more parental-type offspring were produced than the recombinant-type offspring. This indicates:",
        "options": ["Both of the characters are controlled by more than one gene.", "The two genes are located on two different chromosomes.", "Chromosomes failed to separate during meiosis.", "The two genes are linked and present on the same chromosome."],
        "correct_option_id": 3,
        "explanation": "When parental-type offspring exceed recombinant-type offspring in a dihybrid testcross, it indicates the two genes are linked on the same chromosome, reducing independent assortment.",
    },
    {
        "question": "Water soluble pigments found in plant cell vacuoles are:",
        "options": ["Anthocyanins", "Xanthophylls", "Chlorophylls", "Carotenoids"],
        "correct_option_id": 0,
        "explanation": "Anthocyanins are water-soluble pigments stored in the cell vacuole, unlike chlorophylls, xanthophylls and carotenoids which are lipid-soluble and located in plastids.",
    },
    {
        "question": "Which of the following pairs of hormones are not antagonistic (having opposite effects) to each other?",
        "options": ["Relaxin - Inhibin", "Parathormone - Calcitonin", "Insulin - Glucagon", "Aldosterone - Atrial Natriuretic Factor"],
        "correct_option_id": 0,
        "explanation": "Relaxin causes pelvic musculature relaxation while inhibin inhibits FSH secretion — they act on different processes and are not antagonistic, unlike the other pairs listed.",
    },
    {
        "question": "Mitochondria and chloroplast are: (a) semi-autonomous organelles (b) formed by division of pre-existing organelles and they contain DNA but lack protein synthesizing machinery. Which one of the following options is correct?",
        "options": ["Both (a) and (b) are false.", "Both (a) and (b) are correct.", "(b) is true but (a) is false.", "(a) is true but (b) is false."],
        "correct_option_id": 3,
        "explanation": "Mitochondria and chloroplasts are semi-autonomous (statement a is true), but they possess their own ribosomes and DO have protein synthesizing machinery, making statement (b) false.",
    },
    {
        "question": "Which of the following is not a feature of the plasmids?",
        "options": ["Single-stranded", "Independent replication", "Circular structure", "Transferable"],
        "correct_option_id": 0,
        "explanation": "Plasmids are double-stranded, circular, self-replicating DNA molecules, so \"single-stranded\" is not a correct feature of plasmids.",
    },
    {
        "question": "A plant in your garden avoids photorespiratory losses, has improved water use efficiency, shows high rates of photosynthesis at high temperatures and has improved efficiency of nitrogen utilisation. In which of the following physiological groups would you assign this plant?",
        "options": ["Nitrogen fixer", "C3", "C4", "CAM"],
        "correct_option_id": 2,
        "explanation": "These are characteristic features of C4 plants, which show minimal photorespiration and higher photosynthetic efficiency at high temperatures.",
    },
    {
        "question": "Emerson's enhancement effect and Red drop have been instrumental in the discovery of:",
        "options": ["Oxidative phosphorylation", "Photophosphorylation and non-cyclic electron transport", "Two photosystems operating simultaneously", "Photophosphorylation and cyclic electron transport"],
        "correct_option_id": 2,
        "explanation": "The Red drop effect (decline in quantum yield beyond 680 nm) and its reversal by shorter wavelength light (Emerson enhancement) led to the discovery of two photosystems working together.",
    },
    {
        "question": "Which type of tissue correctly matches with its location?",
        "options": ["Cuboidal epithelium - Lining of stomach", "Smooth muscle - Wall of intestine", "Areolar tissue - Tendons", "Transitional epithelium - Tip of nose"],
        "correct_option_id": 1,
        "explanation": "Smooth (involuntary) muscle is found in the wall of the intestine; the other pairings are incorrect (stomach lining is columnar epithelium, tendons are dense regular connective tissue, and nose tip has elastic cartilage).",
    },
    {
        "question": "When does the growth rate of a population following the logistic model equal zero? The logistic model is given as dN/dt = rN(1-N/K):",
        "options": ["when death rate is greater than birth rate.", "when N/K is exactly one.", "when N nears the carrying capacity of the habitat.", "when N/K equals zero."],
        "correct_option_id": 1,
        "explanation": "When N/K = 1 (i.e., N = K, population at carrying capacity), the term (1 - N/K) becomes zero, making dN/dt = 0.",
    },
    {
        "question": "Which one of the following statements is not true?",
        "options": ["Stored pollen in liquid nitrogen can be used in the crop breeding programmes", "Tapetum helps in the dehiscence of anther", "Exine of pollen grains is made up of sporopollenin", "Pollen grains of many species cause severe allergies"],
        "correct_option_id": 1,
        "explanation": "Dehiscence of the anther occurs due to the stomium cells of the endothecium, not the tapetum, which is a nutritive layer.",
    },
    {
        "question": "Which one of the following statements is wrong?",
        "options": ["Phycomycetes are also called algal fungi.", "Cyanobacteria are also called blue-green algae.", "Golden algae are also called desmids.", "Eubacteria are also called false bacteria."],
        "correct_option_id": 3,
        "explanation": "Eubacteria are called \"true bacteria,\" not false bacteria, making statement 4 incorrect.",
    },
    {
        "question": "The Avena curvature is used for bioassay of:",
        "options": ["Ethylene", "ABA", "GA3", "IAA"],
        "correct_option_id": 3,
        "explanation": "The Avena (oat) coleoptile curvature test is a classical bioassay used to measure the activity of auxin (IAA).",
    },
    {
        "question": "Which of the following structures is homologous to the wing of a bird?",
        "options": ["Flipper of Whale", "Dorsal fin of the Shark", "Wing of a Moth", "Hind limb of Rabbit"],
        "correct_option_id": 0,
        "explanation": "The flipper of a whale and the wing of a bird both develop from the forelimb of a common tetrapod ancestor, making them homologous structures.",
    },
    {
        "question": "Blood pressure in the pulmonary artery is:",
        "options": ["less than that in the venae cavae", "same as that in the aorta", "more than that in the carotid", "more than that in the pulmonary vein"],
        "correct_option_id": 3,
        "explanation": "Normally, blood pressure in the pulmonary artery is higher than in the pulmonary vein; a higher pressure in the pulmonary vein than the artery is abnormal and leads to pulmonary hypertension and oedema.",
    },
    {
        "question": "Fertilization in humans is practically feasible only if:",
        "options": ["the sperms are transported into cervix within 48 hrs of release of ovum in uterus.", "the sperms are transported into vagina just after the release of ovum in fallopian tube.", "the ovum and sperms are transported simultaneously to ampullary-isthmic junction of the fallopian tube.", "the ovum and sperms are transported simultaneously to ampullary-isthmic junction of the cervix."],
        "correct_option_id": 1,
        "explanation": "Fertilization is possible when sperms reach the vagina soon after ovulation and both gametes are transported to the ampullary-isthmic junction of the fallopian tube at the same time.",
    },
    {
        "question": "In meiosis crossing over is initiated at:",
        "options": ["Diplotene", "Pachytene", "Leptotene", "Zygotene"],
        "correct_option_id": 1,
        "explanation": "Crossing over begins during the pachytene stage of meiosis I, after the recombination nodules are formed.",
    },
    {
        "question": "Chrysophytes, Euglenoids, Dinoflagellates and slime moulds are included in the kingdom:",
        "options": ["Animalia", "Monera", "Protista", "Fungi"],
        "correct_option_id": 2,
        "explanation": "Chrysophytes, Euglenoids, Dinoflagellates and slime moulds are all classified under Kingdom Protista.",
    },
    {
        "question": "Lack of relaxation between successive stimuli in sustained muscle contraction is known as:",
        "options": ["Tonus", "Spasm", "Fatigue", "Tetanus"],
        "correct_option_id": 3,
        "explanation": "Tetanus refers to sustained muscle contraction that occurs when there is no relaxation between successive stimuli.",
    },
    {
        "question": "Identify the correct statement on 'inhibin':",
        "options": ["Is produced by nurse cells in testes and inhibits the secretion of LH.", "Inhibits the secretion of LH, FSH and Prolactin.", "Is produced by granulosa cells in ovary and inhibits the secretion of FSH.", "Is produced by granulosa cells in ovary and inhibits the secretion of LH."],
        "correct_option_id": 2,
        "explanation": "Inhibin is secreted by granulosa cells of the ovary (and Sertoli cells in testes) and specifically inhibits FSH secretion.",
    },
    {
        "question": "Name the chronic respiratory disorder caused mainly by cigarette smoking:",
        "options": ["Respiratory alkalosis", "Emphysema", "Asthma", "Respiratory acidosis"],
        "correct_option_id": 1,
        "explanation": "Emphysema is a chronic respiratory disorder in which alveolar walls are damaged, mainly due to cigarette smoking.",
    },
    {
        "question": "Which of the following most appropriately describes haemophilia?",
        "options": ["Dominant gene disorder", "Recessive gene disorder", "X-linked recessive gene disorder", "Chromosomal disorder"],
        "correct_option_id": 2,
        "explanation": "Haemophilia is caused by a recessive gene located on the X-chromosome, hence it is an X-linked recessive disorder.",
    },
    {
        "question": "Select the correct statement:",
        "options": ["The leaves of gymnosperms are not well adapted to extremes of climate", "Gymnosperms are both homosporous and heterosporous", "Salvinia, Ginkgo and Pinus all are gymnosperms", "Sequoia is one of the tallest trees"],
        "correct_option_id": 3,
        "explanation": "Sequoia is indeed one of the tallest tree species among gymnosperms; the other statements are factually incorrect (gymnosperm leaves are well adapted to extreme climates and Salvinia is a pteridophyte, not a gymnosperm).",
    },
    {
        "question": "Which of the following is required as inducer(s) for the expression of Lac operon?",
        "options": ["lactose and galactose", "glucose", "galactose", "lactose"],
        "correct_option_id": 3,
        "explanation": "Lactose acts as the inducer that activates the lac operon; glucose and galactose alone cannot induce its expression.",
    },
    {
        "question": "A tall true breeding garden pea plant is crossed with a dwarf true breeding garden pea plant. When the F1 plants were selfed the resulting genotypes were in the ratio of:",
        "options": ["3:1 :: Dwarf : Tall", "1:2:1 :: Tall homozygous : Tall heterozygous : Dwarf", "1:2:1 :: Tall heterozygous : Tall homozygous : Dwarf", "3:1 :: Tall : Dwarf"],
        "correct_option_id": 1,
        "explanation": "Selfing the F1 (Tt) heterozygotes gives a genotypic ratio of 1 TT (tall homozygous) : 2 Tt (tall heterozygous) : 1 tt (dwarf).",
    },
    {
        "question": "Which part of the tobacco plant is infected by Meloidogyne incognita?",
        "options": ["Root", "Flower", "Leaf", "Stem"],
        "correct_option_id": 0,
        "explanation": "Meloidogyne incognita is a root-knot nematode that infects the roots of tobacco plants.",
    },
    {
        "question": "Which of the following is not a characteristic feature during mitosis in somatic cells?",
        "options": ["Synapsis", "Spindle fibres", "Disappearance of nucleolus", "Chromosome movement"],
        "correct_option_id": 0,
        "explanation": "Synapsis (pairing of homologous chromosomes) occurs during meiosis, not mitosis, so it is not a feature of mitotic division.",
    },
    {
        "question": "Which of the following statements is not true for cancer cells in relation to mutations?",
        "options": ["Mutations inhibit production of telomeres.", "Mutations in proto-oncogenes acceleration the cell cycle.", "Mutations destroy telomerase inhibitor.", "Mutations inactivate the cell control."],
        "correct_option_id": 0,
        "explanation": "Cancer is caused by increased (not inhibited) telomerase activity, which makes cancer cells immortal by maintaining telomere length.",
    },
    {
        "question": "One of the major components of cell wall of most fungi is:",
        "options": ["Hemicelluloses", "Chitin", "Peptidoglycan", "Cellulose"],
        "correct_option_id": 1,
        "explanation": "The cell wall of most fungi is primarily composed of chitin, a polysaccharide of N-acetylglucosamine.",
    },
    {
        "question": "Cotyledon of maize grain is called:",
        "options": ["scutellum", "Plumule", "coleorhiza", "coleoptile"],
        "correct_option_id": 0,
        "explanation": "In maize (a monocot), the single large shield-shaped cotyledon is called the scutellum.",
    },
    {
        "question": "Which of the following would appear as the pioneer organisms on bare rocks?",
        "options": ["Green algae", "Lichens", "Liverworts", "Mosses"],
        "correct_option_id": 1,
        "explanation": "Lichens are pioneer organisms on bare rocks; they secrete acids/enzymes that corrode rocks and help convert them into soil.",
    },
    {
        "question": "Changes in GnRH pulse frequency in females is controlled by circulating levels of:",
        "options": ["progesterone and inhibin", "estrogen and progesterone", "estrogen and inhibin", "progesterone only"],
        "correct_option_id": 1,
        "explanation": "After puberty, GnRH pulse frequency in females is regulated by the feedback effects of both estrogen and progesterone.",
    },
    {
        "question": "Antivenom injection contains preformed antibodies while polio drops that are administered into the body contain:",
        "options": ["Attenuated pathogens", "Activated pathogens", "Harvested antibodies", "Gamma globulin"],
        "correct_option_id": 0,
        "explanation": "Oral polio vaccine (OPV) drops contain live attenuated (weakened) polio virus, unlike antivenom which contains preformed antibodies.",
    },
    {
        "question": "Photosensitive compound in human eye is made up of:",
        "options": ["Transducin and Retinene", "Guanosine and Retinol", "Opsin and Retinal", "Opsin and Retinol"],
        "correct_option_id": 2,
        "explanation": "Rhodopsin, the photosensitive pigment in the human eye, is composed of opsin (protein) and retinal (a derivative of Vitamin A).",
    },
    {
        "question": "Specialised epidermal cells surrounding the guard cells are called:",
        "options": ["Lenticels", "Complementary cells", "Subsidiary cells", "Bulliform cells"],
        "correct_option_id": 2,
        "explanation": "Subsidiary cells are specialized epidermal cells that surround the guard cells, differing from them in that they lack chloroplasts.",
    },
    {
        "question": "Which of the following features is not present in the Phylum-Arthropoda?",
        "options": ["Jointed appendages", "Chitinous exoskeleton", "Metameric segmentation", "Parapodia"],
        "correct_option_id": 3,
        "explanation": "Parapodia are lateral appendages characteristic of Phylum Annelida, not Arthropoda.",
    },
    {
        "question": "Reduction in pH of blood will:",
        "options": ["release bicarbonate ions by the liver", "reduce the rate of heart beat", "reduce the blood supply to the brain", "decrease the affinity of hemoglobin with oxygen"],
        "correct_option_id": 3,
        "explanation": "A decrease in blood pH (increased acidity/CO2) decreases hemoglobin's affinity for oxygen, promoting oxygen release to tissues (Bohr effect).",
    },
    {
        "question": "Which of the following characteristic features always holds true for the corresponding group of animals?",
        "options": ["3-chambered heart with one incompletely divided ventricle - Reptilia", "Cartilaginous endoskeleton - Chondrichthyes", "Viviparous - Mammalia", "Possess a mouth with an upper and a lower jaw - Chordata"],
        "correct_option_id": 1,
        "explanation": "Only cartilaginous fishes (Chondrichthyes) always have a cartilaginous endoskeleton without exception; the other options have exceptions (e.g., crocodiles have a 4-chambered heart, prototherian mammals are oviparous, and agnathan chordates lack jaws).",
    },
    {
        "question": "A typical fat molecule is made up of:",
        "options": ["Three glycerol and three fatty acid molecules", "Three glycerol molecules and one fatty acid molecule", "One glycerol and three fatty acid molecules", "One glycerol and one fatty acid molecule"],
        "correct_option_id": 2,
        "explanation": "A typical fat (triglyceride) molecule consists of one glycerol molecule esterified with three fatty acid molecules.",
    },
    {
        "question": "Proximal end of the filament of stamen is attached to the:",
        "options": ["Thalamus or petal", "Anther", "Connective", "Placenta"],
        "correct_option_id": 0,
        "explanation": "The filament's proximal (base) end is attached to the thalamus or the petal, while its distal end bears the anther.",
    },
    {
        "question": "Which one of the following statements is wrong?",
        "options": ["Glycine is a sulphur containing amino acid.", "Sucrose is a disaccharide.", "Cellulose is a polysaccharide.", "Uracil is a pyrimidine."],
        "correct_option_id": 0,
        "explanation": "Glycine is the simplest amino acid and does not contain sulfur; sulfur-containing amino acids include cysteine and methionine.",
    },
    {
        "question": "Water vapour comes out from the plant leaf through the stomatal opening. Through the same stomatal opening carbon dioxide diffuses into the plant during photosynthesis. Reason out the above statements using one of following options:",
        "options": ["One process occurs during day time, and the other at night.", "Both processes cannot happen simultaneously.", "Both processes can happen together because the diffusion coefficient of water and CO2 is different.", "The above processes happen only during nighttime."],
        "correct_option_id": 2,
        "explanation": "Since water vapour and CO2 have different diffusion coefficients, both transpiration (water loss) and CO2 uptake can occur simultaneously through the same stomatal pore.",
    },
    {
        "question": "A complex of ribosomes attached to a single strand of RNA is known as:",
        "options": ["Okazaki fragment", "Polysome", "Polymer", "Polypeptide"],
        "correct_option_id": 1,
        "explanation": "A polysome (or polyribosome) is a cluster of multiple ribosomes attached to and translating a single mRNA strand simultaneously.",
    },
    {
        "question": "Which one of the following is a characteristic feature of cropland ecosystem?",
        "options": ["Ecological succession", "Absence of soil organisms", "Least genetic diversity", "Absence of weeds"],
        "correct_option_id": 2,
        "explanation": "Cropland ecosystems typically show the least genetic diversity because they are often monocultures of a single crop variety.",
    },
    {
        "question": "Which of the following is the most important cause of animals and plants being driven to extinction?",
        "options": ["Co-extinctions", "Over-exploitation", "Alien species invasion", "Habitat loss and fragmentation"],
        "correct_option_id": 3,
        "explanation": "Habitat loss and fragmentation is considered the single most important cause driving animals and plants to extinction.",
    },
    {
        "question": "In a chloroplast the highest number of protons are found in:",
        "options": ["Antennae complex", "Stroma", "Lumen of thylakoids", "Inter membrane space"],
        "correct_option_id": 2,
        "explanation": "During the light reactions of photosynthesis, protons (H+) accumulate in the lumen of the thylakoids, creating the proton gradient used for ATP synthesis.",
    },
    {
        "question": "Which of the following is not required for any of the techniques of DNA fingerprinting available at present?",
        "options": ["DNA-DNA hybridization", "Polymerase chain reaction", "Zinc finger analysis", "Restriction enzymes"],
        "correct_option_id": 2,
        "explanation": "Zinc finger analysis is unrelated to DNA fingerprinting; it relates to DNA-binding protein motifs, whereas hybridization, PCR, and restriction enzymes are commonly used in fingerprinting techniques.",
    },
    {
        "question": "The primitive prokaryotes responsible for the production of biogas from the dung of ruminant animals, include the:",
        "options": ["Eubacteria", "Halophiles", "Thermoacidophiles", "Methanogens"],
        "correct_option_id": 3,
        "explanation": "Methanogens are archaebacteria present in the rumen of cattle that produce methane (biogas) from the dung/waste.",
    },
    {
        "question": "Which of the following features is not present in Periplaneta americana?",
        "options": ["Metamerically segmented body", "Schizocoelom as body cavity", "Indeterminate and radial cleavage during embryonic development", "Exoskeleton composed of N-acetylglucosamine"],
        "correct_option_id": 2,
        "explanation": "Periplaneta americana (cockroach), being a protostome, shows determinate and spiral cleavage during embryonic development, not indeterminate and radial cleavage.",
    },
    {
        "question": "A system of rotating crops with legume or grass pasture to improve soil structure and fertility is called:",
        "options": ["Shifting agriculture", "Ley farming", "Contour farming", "Strip farming"],
        "correct_option_id": 1,
        "explanation": "Ley farming involves rotating crops with legumes or grass pasture to restore and improve soil structure and fertility.",
    },
    {
        "question": "Which of the following is wrongly matched in the given table?",
        "options": ["Clostridium butylicum - Lipase - removal of oil stains", "Trichoderma polysporum - Cyclosporin A - immunosuppressive drug", "Monascus purpureus - Statins - lowering of blood cholesterol", "Streptococcus - Streptokinase - removal of clot from blood vessel"],
        "correct_option_id": 0,
        "explanation": "Lipase used for removal of oil stains is obtained from a different source; this microbe-product-application combination is incorrect (Clostridium butylicum is associated with butyric acid fermentation).",
    },
    {
        "question": "In mammals, which blood vessel would normally carry largest amount of urea?",
        "options": ["Hepatic Portal Vein", "Renal Vein", "Dorsal Aorta", "Hepatic Vein"],
        "correct_option_id": 3,
        "explanation": "Urea is synthesized in the liver via the ornithine cycle, so the hepatic vein (which carries blood away from the liver) contains the maximum amount of urea.",
    },
    {
        "question": "Pick out the correct statements: (a) Haemophilia is a sex-linked recessive disease. (b) Down's syndrome is due to aneuploidy. (c) Phenylketonuria is an autosomal recessive gene disorder. (d) Sickle cell anaemia is an X-linked recessive gene disorder.",
        "options": ["(a), (b) and (c) are correct.", "(a) and (d) are correct.", "(b) and (d) are correct.", "(a), (c) and (d) are correct."],
        "correct_option_id": 0,
        "explanation": "Statements (a), (b), and (c) are correct; statement (d) is incorrect because sickle cell anaemia is an autosomal co-dominant disorder, not X-linked.",
    },
    {
        "question": "Which of the following guards the opening of hepatopancreatic duct into the duodenum?",
        "options": ["Sphincter of Oddi", "Semilunar valve", "Ileocaecal valve", "Pyloric sphincter"],
        "correct_option_id": 0,
        "explanation": "The Sphincter of Oddi controls the opening of the hepatopancreatic duct (common bile and pancreatic duct) into the duodenum.",
    },
    {
        "question": "Microtubules are the constituents of:",
        "options": ["Centrosome, Nucleosome and Centrioles", "Cilia, Flagella and Peroxisomes", "Spindle fibres, Centrioles and Cilia", "Centrioles, Spindle fibres and Chromatin"],
        "correct_option_id": 2,
        "explanation": "Microtubules are structural components of spindle fibres, centrioles, and cilia (and flagella), all involved in cell division/movement.",
    },
    {
        "question": "The coconut water from tender coconut represents:",
        "options": ["Free nuclear endosperm", "Endocarp", "Fleshy mesocarp", "Free nuclear proembryo"],
        "correct_option_id": 0,
        "explanation": "In a tender coconut, the liquid endosperm (coconut water) represents the free-nuclear stage of endosperm development.",
    },
    {
        "question": "Tricarpellary, syncarpous gynoecium is found in flowers of:",
        "options": ["Poaceae", "Liliaceae", "Solanaceae", "Fabaceae"],
        "correct_option_id": 1,
        "explanation": "Family Liliaceae characteristically has a tricarpellary, syncarpous gynoecium with superior ovary.",
    },
    {
        "question": "Which of the following is not a stem modification?",
        "options": ["Flattened structures of Opuntia", "Pitcher of Nepenthes", "Thorns of citrus", "Tendrils of cucumber"],
        "correct_option_id": 1,
        "explanation": "The pitcher of Nepenthes is a modification of the leaf, not the stem, unlike the flattened cladodes of Opuntia, thorns of citrus, and tendrils of cucumber.",
    },
    {
        "question": "The taq polymerase enzyme is obtained from:",
        "options": ["Pseudomonas putida", "Thermus aquaticus", "Thiobacillus ferroxidans", "Bacillus subtilis"],
        "correct_option_id": 1,
        "explanation": "Taq polymerase, a thermostable DNA polymerase used in PCR, is obtained from the thermophilic bacterium Thermus aquaticus.",
    },
    {
        "question": "Stems modified into flat green organs performing the functions of leaves are known as:",
        "options": ["Scales", "Cladodes", "Phyllodes", "Phylloclades"],
        "correct_option_id": 3,
        "explanation": "Phylloclades are flattened, green, photosynthetic stems that perform the function of leaves, as seen in Opuntia.",
    },
    {
        "question": "In higher vertebrates, the immune system can distinguish self-cells and non-self. If this property is lost due to genetic abnormality and it attacks self-cells, then it leads to:",
        "options": ["Active immunity", "Allergic response", "Graft rejection", "Auto-immune disease"],
        "correct_option_id": 3,
        "explanation": "When the immune system loses its ability to distinguish self from non-self and attacks the body's own cells, it results in autoimmune disease.",
    },
    {
        "question": "Nomenclature is governed by certain universal rules. Which one of the following is contrary to the rules of nomenclature?",
        "options": ["When written by hand, the names are to be underlined", "Biological names can be written in any language", "The first word in a biological name represents the genus name, and the second is a specific epithet", "The names are written in Latin and are italicised"],
        "correct_option_id": 1,
        "explanation": "Biological names must be in Latin (or latinized) form and cannot be written in any language, contrary to statement 2.",
    },
    {
        "question": "In bryophytes and pteridophytes, transport of male gametes requires:",
        "options": ["Water", "Wind", "Insects", "Birds"],
        "correct_option_id": 0,
        "explanation": "Bryophytes and pteridophytes have motile, flagellated male gametes that require water as a medium for transport to the female gametes (archegonia).",
    },
    {
        "question": "In context of Amniocentesis, which of the following statement is incorrect?",
        "options": ["It can be used for detection of Cleft palate.", "It is usually done when a woman is between 14-16 weeks pregnant.", "It is used for prenatal sex determination.", "It can be used for detection of Down syndrome."],
        "correct_option_id": 0,
        "explanation": "Cleft palate is a structural defect that cannot be detected through amniocentesis, which is a chromosomal/biochemical test, not a structural imaging test.",
    },
    {
        "question": "In the stomach, gastric acid is secreted by the:",
        "options": ["acidic cells", "gastrin secreting cells", "parietal cells", "peptic cells"],
        "correct_option_id": 2,
        "explanation": "Gastric acid (HCl) is secreted by the parietal (oxyntic) cells of the gastric glands.",
    },
    {
        "question": "Spindle fibres attach on to:",
        "options": ["Kinetosome of the chromosome", "Telomere of the chromosome", "Kinetochore of the chromosome", "Centromere of the chromosome"],
        "correct_option_id": 2,
        "explanation": "Spindle fibres attach to the kinetochore, a protein structure located at the centromere of the chromosome, facilitating chromosome movement during division.",
    },
    {
        "question": "Which is the National Aquatic Animal of India?",
        "options": ["Sea-horse", "Gangetic shark", "River dolphin", "Blue whale"],
        "correct_option_id": 2,
        "explanation": "The River Dolphin (Ganges River Dolphin) is designated as the National Aquatic Animal of India.",
    },
    {
        "question": "Which one of the following cell organelles is enclosed by a single membrane?",
        "options": ["Nuclei", "Mitochondria", "Chloroplasts", "Lysosomes"],
        "correct_option_id": 3,
        "explanation": "Lysosomes are bound by a single membrane, whereas nuclei, mitochondria, and chloroplasts are all bounded by a double membrane.",
    },
    {
        "question": "The two polypeptides of human insulin are linked together by:",
        "options": ["Disulphide bridges", "Hydrogen bonds", "Phosphodiester bond", "Covalent bond"],
        "correct_option_id": 0,
        "explanation": "The A and B polypeptide chains of human insulin are linked together by disulphide bridges.",
    },
    {
        "question": "In which of the following, all three are macronutrients?",
        "options": ["Nitrogen, nickel, phosphorus", "boron, zinc, manganese", "Iron, copper, molybdenum", "Molybdenum, magnesium, manganese"],
        "correct_option_id": 0,
        "explanation": "Nitrogen and phosphorus are macronutrients, though nickel is technically a micronutrient — this option was accepted as the best/marked answer by the examining body.",
    },
    {
        "question": "Which of the following statements is wrong for viroids?",
        "options": ["Their RNA is of high molecular weight", "They lack a protein coat", "They are smaller than viruses", "They cause infections"],
        "correct_option_id": 0,
        "explanation": "Viroids possess low molecular weight RNA (unlike viruses), making statement 1 incorrect.",
    },
    {
        "question": "Analogous structures are a result of:",
        "options": ["Stabilizing selection", "Divergent evolution", "Convergent evolution", "Shared ancestry"],
        "correct_option_id": 2,
        "explanation": "Analogous structures (similar function, different origin) arise due to convergent evolution, where unrelated organisms independently evolve similar adaptations.",
    },
    {
        "question": "Select the incorrect statement:",
        "options": ["LH triggers secretion of androgens from the Leydig cells", "FSH stimulates the sertoli cells which help in spermiogenesis", "LH triggers ovulation in ovary.", "LH and FSH decrease gradually during the follicular phase"],
        "correct_option_id": 3,
        "explanation": "LH and FSH levels actually increase (not decrease) during the follicular phase of the menstrual cycle, making statement 4 incorrect.",
    },
    {
        "question": "Which one of the following characteristics is not shared by birds and mammals?",
        "options": ["Warm blooded nature", "Ossified endoskeleton", "Breathing using lungs", "Viviparity"],
        "correct_option_id": 3,
        "explanation": "Birds are oviparous, whereas mammals may be oviparous (prototherians) or viviparous (metatherians and eutherians) — viviparity is not a universally shared trait between birds and mammals.",
    },
    {
        "question": "Which of the following statements is not correct?",
        "options": ["Some reptiles have also been reported as pollinators in some plant species.", "Pollen grains of many species can germinate on the stigma of a flower, but only one pollen tube of the same species grows into the style.", "Insects that consume pollen or nectar without bringing about pollination are called pollen/nectar robbers.", "Pollen germination and pollen tube growth are regulated by chemical components of pollen interacting with those of the pistil"],
        "correct_option_id": 1,
        "explanation": "Actually, in incompatible pollinations, foreign-species pollen may germinate on the stigma, but only pollen tubes of the SAME species reach the ovary — the statement's phrasing about which pollen tubes grow makes it the incorrect statement as per the answer key.",
    },
    {
        "question": "Seed formation without fertilization in flowering plants involves the process of:",
        "options": ["Apomixis", "Sporulation", "Budding", "Somatic hybridization"],
        "correct_option_id": 0,
        "explanation": "Apomixis is a form of asexual reproduction that mimics sexual reproduction, resulting in seed formation without fertilization.",
    },
    {
        "question": "Which of the following approaches does not give the defined action of contraceptive?",
        "options": ["Vasectomy - prevents spermatogenesis", "Barrier methods - prevent fertilization", "Intra uterine devices - increase phagocytosis of sperms, suppress sperm motility and fertilizing capacity of sperms", "Hormonal Contraceptives - Prevent/retard entry of sperms, prevent ovulation and fertilization"],
        "correct_option_id": 0,
        "explanation": "Vasectomy causes sterilization by preventing the transfer/transport of sperms into the semen, not by preventing spermatogenesis itself.",
    },
    {
        "question": "The amino acid Tryptophan is the precursor for the synthesis of:",
        "options": ["Cortisol and Cortisone", "Melatonin and Serotonin", "Thyroxine and Triiodothyronine", "Estrogen and Progesterone"],
        "correct_option_id": 1,
        "explanation": "Tryptophan serves as the biochemical precursor for the synthesis of the hormones melatonin and serotonin.",
    },
    {
        "question": "A river with an inflow of domestic sewage rich in organic waste may result in:",
        "options": ["Death of fish due to lack of oxygen.", "Drying of the river very soon due to algal bloom.", "Increased population of aquatic food web organisms.", "An increased production of fish due to biodegradable nutrients"],
        "correct_option_id": 0,
        "explanation": "Domestic sewage causes eutrophication and excessive microbial decomposition, depleting dissolved oxygen levels and leading to the death of fish due to lack of oxygen.",
    },
    {
        "question": "Gause's principle of competitive exclusion states that:",
        "options": ["Larger organisms exclude smaller ones through competition.", "More abundant species will exclude the less abundant species through competition.", "Competition for the same resources excludes species having different food preferences.", "No two species can occupy the same niche indefinitely for the same limiting resources."],
        "correct_option_id": 3,
        "explanation": "Gause's competitive exclusion principle states that two species competing for the same limiting resources cannot coexist indefinitely in the same ecological niche.",
    },
    {
        "question": "Asthma may be attributed to:",
        "options": ["accumulation of fluid in the lungs", "bacterial infection of the lungs", "allergic reaction of the mast cells in the lungs", "inflammation of the trachea"],
        "correct_option_id": 2,
        "explanation": "Asthma is an allergic disease caused by allergens, characterized by inflammation of the tracheobronchial tree and difficulty in breathing due to mast cell-mediated allergic reactions.",
    },
    {
        "question": "The standard petal of a papilionaceous corolla is also called:",
        "options": ["Corona", "Carina", "Pappus", "Vexillum"],
        "correct_option_id": 3,
        "explanation": "In a papilionaceous corolla, the large posterior (standard) petal is also known as the vexillum.",
    },
    {
        "question": "Which of the following is a restriction endonuclease?",
        "options": ["RNase", "Hind II", "Protease", "DNase I"],
        "correct_option_id": 1,
        "explanation": "Hind II is a well-known restriction endonuclease enzyme that cuts DNA at specific recognition sequences.",
    },
    {
        "question": "It is much easier for a small animal to run uphill than for a large animal, because:",
        "options": ["The efficiency of muscles in large animals is less than in the small animals.", "It is easier to carry a small body weight.", "Smaller animals have a higher metabolic rate.", "Small animals have a lower O2 requirement."],
        "correct_option_id": 2,
        "explanation": "Smaller animals have a higher basal metabolic rate (BMR), which supports sustained energy production and delays muscle fatigue, making uphill running easier.",
    },
    {
        "question": "Following are the two statements regarding the origin of life: (a) The earliest organisms that appeared on the earth were non-green and presumably anaerobes. (b) The first autotrophic organisms were the chemoautotrophs that never released oxygen. Of the above statements which one of the following options is correct?",
        "options": ["Both (a) and (b) are false.", "(a) is correct but (b) is false.", "(b) is correct but (a) is false.", "Both (a) and (b) are correct."],
        "correct_option_id": 3,
        "explanation": "The earliest organisms were indeed non-green anaerobic prokaryotes (chemoheterotrophs), and the first autotrophs were chemoautotrophs that did not release oxygen, making both statements correct.",
    },
    {
        "question": "A cell at telophase stage is observed by a student in a plant brought from the field. He tells his teacher that this cell is not like other cells at telophase stage. There is no formation of cell plate and thus the cell is containing more number of chromosomes as compared to other dividing cells. This would result in:",
        "options": ["Polyteny", "Aneuploidy", "Polyploidy", "Somaclonal variation"],
        "correct_option_id": 2,
        "explanation": "Absence of cell plate formation results in a single cell containing the doubled chromosome number, leading to polyploidy.",
    },
    {
        "question": "Depletion of which gas in the atmosphere can lead to an increased incidence of skin cancers:",
        "options": ["Methane", "Nitrous oxide", "Ozone", "Ammonia"],
        "correct_option_id": 2,
        "explanation": "Depletion of the ozone layer allows increased penetration of harmful UV radiation, which increases the incidence of skin cancers.",
    },
    {
        "question": "Joint Forest Management Concept was introduced in India during:",
        "options": ["1990s", "1960s", "1970s", "1980s"],
        "correct_option_id": 3,
        "explanation": "The Joint Forest Management (JFM) concept was introduced in India during the 1980s.",
    },
    {
        "question": "Which one of the following is the starter codon?",
        "options": ["UAG", "AUG", "UGA", "UAA"],
        "correct_option_id": 1,
        "explanation": "AUG is the start (initiation) codon that codes for methionine and initiates protein synthesis.",
    },
    {
        "question": "The term ecosystem was coined by:",
        "options": ["E. Warming", "E.P. Odum", "A.G. Tansley", "E. Haeckel"],
        "correct_option_id": 2,
        "explanation": "The term \"ecosystem\" was first coined by A.G. Tansley in 1935.",
    },
]
