"""
Question bank: NEET 2020 (Code E1) - Biology (Solved Answers).

75 questions parsed from NEET 2020 (Code E1)'s solved-answers compilation.
Match-the-following and diagram-based questions were excluded at the
source (per the original compilation), since they require an image.

Each entry:
    question           -> str, <= 300 chars (Telegram poll limit)
    options             -> list[str], 2-10 items, each <= 100 chars
    correct_option_id   -> int, 0-indexed position in `options`
    explanation         -> str, <= 200 chars, shown after answering (optional)
"""

QUESTIONS = [
    {
        "question": "Which of the following is not an attribute of a population?",
        "options": ["Sex ratio", "Natality", "Mortality", "Species interaction"],
        "correct_option_id": 3,
        "explanation": "Population attributes are natality, mortality, sex ratio, age distribution and population density. Species interaction is a community-level, not population-level, characteristic.",
    },
    {
        "question": "The process of growth is maximum during:",
        "options": ["Log phase", "Lag phase", "Senescence", "Dormancy"],
        "correct_option_id": 0,
        "explanation": "The log (exponential) phase is when cells/organisms divide and grow at their maximum rate.",
    },
    {
        "question": "The roots that originate from the base of the stem are:",
        "options": ["Fibrous roots", "Primary roots", "Prop roots", "Lateral roots"],
        "correct_option_id": 0,
        "explanation": "Fibrous roots arise in clusters from the base of the stem, typically seen in monocots.",
    },
    {
        "question": "In which of the following techniques, the embryos are transferred to assist those females who cannot conceive?",
        "options": ["ZIFT and IUT", "GIFT and ZIFT", "ICSI and ZIFT", "GIFT and ICSI"],
        "correct_option_id": 0,
        "explanation": "In ZIFT, the zygote/early embryo is transferred into the fallopian tube; in IUT, the embryo is transferred into the uterus. Both involve transfer of the embryo itself, unlike GIFT (gamete transfer).",
    },
    {
        "question": "Identify the wrong statement with reference to the gene 'I' that controls ABO blood groups.",
        "options": ["The gene (I) has three alleles.", "A person will have only two of the three alleles.", "When IA and IB are present together, they express same type of sugar.", "Allele 'i' does not produce any sugar."],
        "correct_option_id": 2,
        "explanation": "IA and IB are codominant alleles; when present together they express two different sugars (A and B), not the same type.",
    },
    {
        "question": "Choose the correct pair from the following:",
        "options": ["Ligases - Join the two DNA molecules", "Polymerases - Break the DNA into fragments", "Nucleases - Separate the two strands of DNA", "Exonucleases - Make cuts at specific positions within DNA"],
        "correct_option_id": 0,
        "explanation": "Ligases join two DNA fragments/molecules together. Polymerases synthesize DNA, nucleases (endonucleases) cut DNA, and exonucleases remove nucleotides from the ends - not as described in the other options.",
    },
    {
        "question": "Select the correct match.",
        "options": ["Haemophilia - Y linked", "Phenylketonuria - Autosomal dominant trait", "Sickle cell anaemia - Autosomal recessive trait, chromosome-11", "Thalassemia - X linked"],
        "correct_option_id": 2,
        "explanation": "Sickle cell anaemia is an autosomal recessive disorder caused by a defect in the beta-globin gene located on chromosome 11. Haemophilia is X-linked, PKU is autosomal recessive, and thalassemia is autosomal recessive.",
    },
    {
        "question": "The infectious stage of Plasmodium that enters the human body is:",
        "options": ["Trophozoites", "Sporozoites", "Female gametocytes", "Male gametocytes"],
        "correct_option_id": 1,
        "explanation": "Sporozoites are injected into the human bloodstream through the bite of an infected female Anopheles mosquito.",
    },
    {
        "question": "Identify the substances having glycosidic bond and peptide bond, respectively, in their structure:",
        "options": ["Chitin, cholesterol", "Glycerol, trypsin", "Cellulose, lecithin", "Inulin, insulin"],
        "correct_option_id": 3,
        "explanation": "Inulin is a polysaccharide (fructose polymer) held together by glycosidic bonds, while insulin is a protein held together by peptide bonds.",
    },
    {
        "question": "The plant parts which consist of two generations - one within the other: (NEET 2020) (a) Pollen grains inside the anther (b) Germinated pollen grain with two male gametes (c) Seed inside the fruit (d) Embryo sac inside the ovule",
        "options": ["(a) only", "(a), (b) and (c)", "(c) and (d)", "(a) and (d)"],
        "correct_option_id": 3,
        "explanation": "Pollen grains (male gametophyte generation) develop inside the anther (sporophyte), and the embryo sac (female gametophyte generation) develops inside the ovule (sporophyte) - representing gametophyte generation within the sporophyte generation.",
    },
    {
        "question": "The product(s) of reaction catalyzed by nitrogenase in root nodules of leguminous plants is/are:",
        "options": ["Ammonia alone", "Nitrate alone", "Ammonia and oxygen", "Ammonia and hydrogen"],
        "correct_option_id": 3,
        "explanation": "Nitrogenase catalyzes: N2 + 8H+ + 8e- + 16ATP → 2NH3 + H2 + 16ADP + 16Pi, producing ammonia and hydrogen.",
    },
    {
        "question": "Identify the correct statement with regard to G1 phase (Gap 1) of interphase.",
        "options": ["DNA synthesis or replication takes place.", "Reorganisation of all cell components takes place.", "Cell is metabolically active, grows but does not replicate its DNA.", "Nuclear Division takes place."],
        "correct_option_id": 2,
        "explanation": "During G1, the cell grows and is metabolically active but DNA replication has not yet begun (that occurs in S phase).",
    },
    {
        "question": "Cuboidal epithelium with brush border of microvilli is found in:",
        "options": ["lining of intestine", "ducts of salivary glands", "proximal convoluted tubule of nephron", "eustachian tube"],
        "correct_option_id": 2,
        "explanation": "The proximal convoluted tubule (PCT) is lined by cuboidal epithelial cells with a brush border of microvilli that increases the absorptive surface area.",
    },
    {
        "question": "Which of the following statements about inclusion bodies is incorrect?",
        "options": ["They are not bound by any membrane.", "These are involved in ingestion of food particles.", "They lie free in the cytoplasm.", "These represent reserve material in cytoplasm."],
        "correct_option_id": 1,
        "explanation": "Inclusion bodies (e.g., starch grains, glycogen granules) are non-membrane bound reserve materials lying free in the cytoplasm; they are not involved in ingestion of food particles.",
    },
    {
        "question": "Which is the important site of formation of glycoproteins and glycolipids in eukaryotic cells?",
        "options": ["Endoplasmic reticulum", "Peroxisomes", "Golgi bodies", "Polysomes"],
        "correct_option_id": 2,
        "explanation": "The Golgi apparatus is the major site for the formation of glycoproteins and glycolipids.",
    },
    {
        "question": "In gel electrophoresis, separated DNA fragments can be visualized with the help of:",
        "options": ["Acetocarmine in bright blue light", "Ethidium bromide in UV radiation", "Acetocarmine in UV radiation", "Ethidium bromide in infrared radiation"],
        "correct_option_id": 1,
        "explanation": "DNA fragments stained with ethidium bromide fluoresce under UV radiation, allowing visualization.",
    },
    {
        "question": "Identify the wrong statement with reference to transport of oxygen.",
        "options": ["Binding of oxygen with haemoglobin is mainly related to partial pressure of O2.", "Partial pressure of CO2 can interfere with O2 binding with haemoglobin.", "Higher H+ conc. in alveoli favours the formation of oxyhaemoglobin.", "Low pCO2 in alveoli favours the formation of oxyhaemoglobin."],
        "correct_option_id": 2,
        "explanation": "A higher H+ concentration (lower pH) actually favours the dissociation of oxygen from haemoglobin (Bohr effect), not the formation of oxyhaemoglobin.",
    },
    {
        "question": "Ray florets have:",
        "options": ["Inferior ovary", "Superior ovary", "Hypogynous ovary", "Half inferior ovary"],
        "correct_option_id": 0,
        "explanation": "Ray florets (as in sunflower, family Asteraceae) have an inferior ovary.",
    },
    {
        "question": "The specific palindromic sequence which is recognized by EcoRI is:",
        "options": ["5'-GAATTC-3' / 3'-CTTAAG-5'", "5'-GGAACC-3' / 3'-CCTTGG-5'", "5'-CTTAAG-3' / 3'-GAATTC-5'", "5'-GGATCC-3' / 3'-CCTAGG-5'"],
        "correct_option_id": 0,
        "explanation": "EcoRI recognizes the palindromic sequence 5'-GAATTC-3' (complementary strand 3'-CTTAAG-5') and cuts between G and A.",
    },
    {
        "question": "Identify the wrong statement with regard to Restriction Enzymes.",
        "options": ["Each restriction enzyme functions by inspecting the length of a DNA sequence.", "They cut the strand of DNA at palindromic sites.", "They are useful in genetic engineering.", "Sticky ends can be joined by using DNA ligases."],
        "correct_option_id": 0,
        "explanation": "Restriction enzymes recognize and cut at specific DNA sequences (palindromic recognition sites), not by inspecting the \"length\" of a DNA sequence.",
    },
    {
        "question": "Which of the following is put into anaerobic sludge digester for further sewage treatment?",
        "options": ["Primary sludge", "Floating debris", "Effluents of primary treatment", "Activated sludge"],
        "correct_option_id": 3,
        "explanation": "The activated sludge (settled bacterial flocs formed during secondary treatment) is passed into anaerobic sludge digesters.",
    },
    {
        "question": "Select the correct events that occur during inspiration. (NEET 2020) (a) Contraction of diaphragm (b) Contraction of external inter-costal muscles (c) Pulmonary volume decreases (d) Intra pulmonary pressure increases",
        "options": ["(a) and (b)", "(c) and (d)", "(a), (b) and (d)", "only (d)"],
        "correct_option_id": 0,
        "explanation": "During inspiration, the diaphragm and external intercostal muscles contract, increasing (not decreasing) pulmonary volume and decreasing (not increasing) intrapulmonary pressure.",
    },
    {
        "question": "If the head of cockroach is removed, it may live for a few days because:",
        "options": ["the supra-oesophageal ganglia of the cockroach are situated in ventral part of abdomen.", "the cockroach does not have nervous system.", "the head holds a small proportion of a nervous system while the rest is situated along the ventral part of its body.", "the head holds a 1/3rd proportion of a nervous system while the rest is situated along the dorsal part of its body."],
        "correct_option_id": 2,
        "explanation": "Only a small fraction of the cockroach's nervous system is in the head; most of it lies along the ventral nerve cord, so the body can survive briefly without the head.",
    },
    {
        "question": "Which of the following statements are true for the phylum Chordata? (NEET 2020) (a) In Urochordata notochord extends from head to tail and it is present throughout their life. (b) In Vertebrata notochord is present during the embryonic period only. (c) Central nervous system is dorsal and hollow. (d) Chordata is divided into 3 subphyla: Hemichordata, Tunicata and Cephalochordata.",
        "options": ["(d) and (c)", "(c) and (a)", "(a) and (b)", "(b) and (c)"],
        "correct_option_id": 3,
        "explanation": "In Urochordata, the notochord is present only in the larval tail, not throughout life. Chordata's three subphyla are Urochordata, Cephalochordata and Vertebrata (Hemichordata is a separate phylum). Statements (b) and (c) are correct.",
    },
    {
        "question": "Identify the incorrect statement.",
        "options": ["Heart wood does not conduct water but gives mechanical support.", "Sapwood is involved in conduction of water and minerals from root to leaf.", "Sapwood is the innermost secondary xylem and is lighter in colour.", "Due to deposition of tannins, resins, oils etc., heart wood is dark in colour."],
        "correct_option_id": 2,
        "explanation": "Sapwood is the outer, peripheral part of the secondary xylem, not the innermost - heartwood is the innermost part.",
    },
    {
        "question": "Meiotic division of the secondary oocyte is completed:",
        "options": ["Prior to ovulation", "At the time of copulation", "After zygote formation", "At the time of fusion of a sperm with an ovum"],
        "correct_option_id": 3,
        "explanation": "The secondary oocyte is arrested at metaphase II and completes meiosis II only after a sperm fuses with it (fertilization).",
    },
    {
        "question": "According to Robert May, the global species diversity is about:",
        "options": ["1.5 million", "20 million", "50 million", "7 million"],
        "correct_option_id": 3,
        "explanation": "Robert May's estimate of global species diversity is about 7 million species.",
    },
    {
        "question": "The first phase of translation is:",
        "options": ["Binding of mRNA to ribosome", "Recognition of DNA molecule", "Aminoacylation of tRNA", "Recognition of an anti-codon"],
        "correct_option_id": 2,
        "explanation": "The first step of translation is the charging (aminoacylation) of tRNA with its specific amino acid, which requires ATP.",
    },
    {
        "question": "Which of the following regions of the globe exhibits highest species diversity?",
        "options": ["Western Ghats of India", "Madagascar", "Himalayas", "Amazon forests"],
        "correct_option_id": 3,
        "explanation": "The Amazon rainforest has the highest species diversity among the given options.",
    },
    {
        "question": "Which of the following statements is not correct?",
        "options": ["In man insulin is synthesised as a proinsulin.", "The proinsulin has an extra peptide called C-peptide.", "The functional insulin has A and B chains linked together by hydrogen bonds.", "Genetically engineered insulin is produced in E. Coli."],
        "correct_option_id": 2,
        "explanation": "The A and B chains of functional insulin are linked by disulphide bonds, not hydrogen bonds.",
    },
    {
        "question": "The transverse section of a plant shows the following anatomical features: large number of scattered vascular bundles surrounded by bundle sheath, large conspicuous parenchymatous ground tissue, vascular bundles conjoint and closed, phloem parenchyma absent. Identify the category of plant and its part:",
        "options": ["Monocotyledonous stem", "Monocotyledonous root", "Dicotyledonous stem", "Dicotyledonous root"],
        "correct_option_id": 0,
        "explanation": "Scattered closed conjoint vascular bundles, each surrounded by a bundle sheath, with absent phloem parenchyma are characteristic features of a monocotyledonous stem.",
    },
    {
        "question": "From his experiments, S.L. Miller produced amino acids by mixing the following in a closed flask:",
        "options": ["CH4, H2, NH3 and water vapor at 800°C", "CH3, H2, NH4 and water vapor at 800°C", "CH4, H2, NH3 and water vapor at 600°C", "CH3, H2, NH3 and water vapor at 600°C"],
        "correct_option_id": 0,
        "explanation": "Miller's classic experiment used a mixture of CH4, H2, NH3 and water vapor subjected to an electric discharge at about 800°C to simulate primitive earth conditions and produced amino acids.",
    },
    {
        "question": "Embryological support for evolution was disapproved by:",
        "options": ["Karl Ernst von Baer", "Alfred Wallace", "Charles Darwin", "Oparin"],
        "correct_option_id": 0,
        "explanation": "Embryologist Karl Ernst von Baer disapproved the idea that embryological development recapitulates evolutionary history.",
    },
    {
        "question": "The process responsible for facilitating loss of water in liquid form from the tip of grass blades at night and in early morning is:",
        "options": ["Transpiration", "Root pressure", "Imbibition", "Plasmolysis"],
        "correct_option_id": 1,
        "explanation": "This phenomenon is guttation, which is caused by root pressure pushing water (with dissolved solutes) out through hydathodes at leaf tips.",
    },
    {
        "question": "Secondary metabolites such as nicotine, strychnine and caffeine are produced by plants for their:",
        "options": ["Nutritive value", "Growth response", "Defence action", "Effect on reproduction"],
        "correct_option_id": 2,
        "explanation": "Secondary metabolites like nicotine, strychnine and caffeine serve primarily as defence compounds against herbivores and pathogens.",
    },
    {
        "question": "The oxygenation activity of RuBisCo enzyme in photorespiration leads to the formation of:",
        "options": ["2 molecules of 3-C compound", "1 molecule of 3-C compound", "1 molecule of 6-C compound", "1 molecule of 4-C compound and 1 molecule of 2-C compound"],
        "correct_option_id": 1,
        "explanation": "Oxygenation of RuBP by RuBisCo produces one molecule of 3-phosphoglyceric acid (3-C) and one molecule of phosphoglycolate (2-C); the significant product highlighted here is the 3-C compound.",
    },
    {
        "question": "Bt cotton variety that was developed by the introduction of toxin gene of Bacillus thuringiensis (Bt) is resistant to:",
        "options": ["Insect pests", "Fungal diseases", "Plant nematodes", "Insect predators"],
        "correct_option_id": 0,
        "explanation": "The Bt toxin gene confers resistance against certain insect pests (bollworms) by producing a toxin that kills the larvae.",
    },
    {
        "question": "Which of the following refer to correct example(s) of organisms which have evolved due to changes in environment brought about by anthropogenic action? (NEET 2020) (a) Darwin's Finches of Galapagos islands. (b) Herbicide resistant weeds. (c) Drug resistant eukaryotes. (d) Man-created breeds of domesticated animals like dogs.",
        "options": ["only (a)", "(a) and (c)", "(b), (c) and (d)", "only (d)"],
        "correct_option_id": 2,
        "explanation": "Herbicide-resistant weeds, drug-resistant pathogens, and man-made dog breeds all arose due to human (anthropogenic) influence. Darwin's finches evolved through natural selection, not anthropogenic action.",
    },
    {
        "question": "Identify the wrong statement with reference to immunity.",
        "options": ["When exposed to antigen (living or dead), antibodies are produced in the host's body. It is called \"Active immunity\".", "When ready-made antibodies are given directly, it is an example for passive immunity.", "Active immunity is quick and gives full response.", "Foetus receives some antibodies from mother, it is an example of passive immunity."],
        "correct_option_id": 2,
        "explanation": "Active immunity takes time to develop since the body must produce antibodies itself; passive immunity (ready-made antibodies) acts quickly.",
    },
    {
        "question": "By which method was a new breed 'Hisardale' of sheep formed by using Bikaneri ewes and Marino rams?",
        "options": ["Out crossing", "Mutational breeding", "Cross breeding", "Inbreeding"],
        "correct_option_id": 2,
        "explanation": "Hisardale is a new breed of sheep produced by crossbreeding Bikaneri ewes with Marino rams.",
    },
    {
        "question": "Identify the correct statement with reference to human digestive system.",
        "options": ["Ileum opens into small intestine.", "Serosa is the innermost layer of the alimentary canal.", "Ileum is a highly coiled part.", "Vermiform appendix arises from duodenum."],
        "correct_option_id": 2,
        "explanation": "The ileum is the highly coiled terminal part of the small intestine. (Serosa is the outermost layer, ileum opens into the large intestine, and the vermiform appendix arises from the caecum.)",
    },
    {
        "question": "Presence of which of the following conditions in urine are indicative of Diabetes Mellitus?",
        "options": ["Uremia and Ketonuria", "Uremia and Renal Calculi", "Ketonuria and Glycosuria", "Renal calculi and Hyperglycaemia"],
        "correct_option_id": 2,
        "explanation": "Diabetes mellitus is characterized by the presence of glucose (glycosuria) and ketone bodies (ketonuria) in urine.",
    },
    {
        "question": "Floridean starch has structure similar to:",
        "options": ["Starch and cellulose", "Amylopectin and glycogen", "Mannitol and algin", "Laminarin and cellulose"],
        "correct_option_id": 1,
        "explanation": "Floridean starch, found in red algae, is structurally similar to amylopectin and glycogen.",
    },
    {
        "question": "Select the option including all sexually transmitted diseases.",
        "options": ["Gonorrhoea, Syphilis, Genital herpes", "Gonorrhoea, Malaria, Genital herpes", "AIDS, Malaria, Filaria", "Cancer, AIDS, Syphilis"],
        "correct_option_id": 0,
        "explanation": "Gonorrhoea, Syphilis and Genital herpes are all sexually transmitted diseases. Malaria and Filaria are vector-borne, not sexually transmitted.",
    },
    {
        "question": "Which of the following pairs is of unicellular algae?",
        "options": ["Laminaria and Sargassum", "Gelidium and Gracilaria", "Anabaena and Volvox", "Chlorella and Spirulina"],
        "correct_option_id": 3,
        "explanation": "Chlorella and Spirulina are unicellular/simple algal forms; the other pairs listed are multicellular brown or red algae, or filamentous/colonial forms.",
    },
    {
        "question": "Which of the following hormone levels will cause release of ovum (ovulation) from the graafian follicle?",
        "options": ["High concentration of Estrogen", "High concentration of Progesterone", "Low concentration of LH", "Low concentration of FSH"],
        "correct_option_id": 0,
        "explanation": "A rapid rise in estrogen level triggers an LH surge at mid-cycle, which induces rupture of the Graafian follicle and release of the ovum.",
    },
    {
        "question": "Montreal protocol was signed in 1987 for control of:",
        "options": ["Transport of Genetically Modified Organisms from one country to another", "Emission of ozone depleting substances", "Release of Green House gases", "Disposal of e-wastes"],
        "correct_option_id": 1,
        "explanation": "The Montreal Protocol (1987) is an international treaty for phasing out the production and consumption of ozone-depleting substances.",
    },
    {
        "question": "Which of the following is correct about viroids?",
        "options": ["They have RNA with protein coat.", "Only have free RNA without protein coat.", "They have DNA with protein coat.", "They have free DNA without protein coat."],
        "correct_option_id": 1,
        "explanation": "Viroids consist of free, low molecular weight RNA without a protein coat, unlike viruses.",
    },
    {
        "question": "The ovary is half inferior in:",
        "options": ["Brinjal", "Mustard", "Sunflower", "Plum"],
        "correct_option_id": 3,
        "explanation": "Plum has a half-inferior (perigynous) ovary.",
    },
    {
        "question": "The enzyme enterokinase helps in conversion of:",
        "options": ["protein into polypeptides", "trypsinogen into trypsin", "caseinogen into casein", "pepsinogen into pepsin"],
        "correct_option_id": 1,
        "explanation": "Enterokinase, secreted by the intestinal mucosa, converts inactive trypsinogen into active trypsin.",
    },
    {
        "question": "How many true breeding pea plant varieties did Mendel select as pairs, which were similar except in one character with contrasting traits?",
        "options": ["4", "2", "14", "8"],
        "correct_option_id": 2,
        "explanation": "Mendel selected 14 true-breeding pea varieties, forming 7 contrasting character pairs, for his experiments.",
    },
    {
        "question": "In water hyacinth and water lily, pollination takes place by:",
        "options": ["insects or wind", "water currents only", "wind and water", "insects and water"],
        "correct_option_id": 0,
        "explanation": "Although aquatic, water hyacinth and water lily are pollinated by insects or wind, like most land plants, rather than by water.",
    },
    {
        "question": "Name the plant growth regulator which upon spraying on sugarcane crop increases the length of stem, thus increasing the yield of sugarcane crop.",
        "options": ["Cytokinin", "Gibberellin", "Ethylene", "Abscisic acid"],
        "correct_option_id": 1,
        "explanation": "Gibberellins are commercially sprayed on sugarcane to increase internodal length/stem length, thereby increasing cane yield.",
    },
    {
        "question": "In light reaction, plastoquinone facilitates the transfer of electrons from:",
        "options": ["PS-II to Cytb6f complex", "Cytb6f complex to PS-I", "PS-I to NADP+", "PS-I to ATP synthase"],
        "correct_option_id": 0,
        "explanation": "Plastoquinone shuttles electrons from Photosystem II to the cytochrome b6f complex in the electron transport chain.",
    },
    {
        "question": "Which of the following is not an inhibitory substance governing seed dormancy?",
        "options": ["Gibberellic acid", "Abscisic acid", "Phenolic acid", "Para-ascorbic acid"],
        "correct_option_id": 0,
        "explanation": "Gibberellic acid promotes seed germination (breaks dormancy); it is not an inhibitor.",
    },
    {
        "question": "Name the enzyme that facilitates opening of DNA helix during transcription.",
        "options": ["DNA ligase", "DNA helicase", "DNA polymerase", "RNA polymerase"],
        "correct_option_id": 3,
        "explanation": "RNA polymerase itself unwinds the DNA double helix at the promoter region to form a transcription bubble during transcription.",
    },
    {
        "question": "Which of the following would help in prevention of diuresis?",
        "options": ["More water reabsorption due to undersecretion of ADH", "Reabsorption of Na+ and water from renal tubules due to aldosterone", "Atrial natriuretic factor causes vasoconstriction", "Decrease in secretion of renin by JG cells"],
        "correct_option_id": 1,
        "explanation": "Aldosterone promotes reabsorption of Na+ (and consequently water) from renal tubules, reducing urine output and preventing diuresis.",
    },
    {
        "question": "In relation to Gross primary productivity (GPP) of an ecosystem, which one of the following statements is correct?",
        "options": ["Gross primary productivity is always less than net primary productivity.", "Gross primary productivity is always more than net primary productivity.", "Gross primary productivity and Net primary productivity are one and the same.", "There is no relationship between Gross primary productivity and net primary productivity."],
        "correct_option_id": 1,
        "explanation": "NPP = GPP - respiratory losses, so GPP is always more than NPP.",
    },
    {
        "question": "Strobili or cones are found in:",
        "options": ["Salvinia", "Pteris", "Marchantia", "Equisetum"],
        "correct_option_id": 3,
        "explanation": "Equisetum bears cone-like strobili at the tips of its stems.",
    },
    {
        "question": "Some dividing cells exit the cell cycle and enter a vegetative inactive stage. This process occurs at the end of:",
        "options": ["M phase", "G1 phase", "S phase", "G2 phase"],
        "correct_option_id": 1,
        "explanation": "Cells exit the cell cycle at the end of G1 phase and enter a quiescent stage (G0).",
    },
    {
        "question": "Flippers of Penguins and Dolphins are examples of:",
        "options": ["Adaptive radiation", "Convergent evolution", "Industrial melanism", "Natural selection"],
        "correct_option_id": 1,
        "explanation": "Flippers in penguins (birds) and dolphins (mammals) are analogous structures that arose independently to serve a similar function - an example of convergent evolution.",
    },
    {
        "question": "If the distance between two consecutive base pairs is 0.34 nm and the total number of base pairs of a DNA double helix in a typical mammalian cell is 6.6 × 10^9 bp, then the length of the DNA is approximately:",
        "options": ["2.0 meters", "2.5 meters", "2.2 meters", "2.7 meters"],
        "correct_option_id": 2,
        "explanation": "Length = 6.6 × 10^9 × 0.34 × 10^-9 m ≈ 2.2 metres.",
    },
    {
        "question": "The QRS complex in a standard ECG represents:",
        "options": ["Repolarisation of auricles", "Depolarisation of auricles", "Depolarisation of ventricles", "Repolarisation of ventricles"],
        "correct_option_id": 2,
        "explanation": "The QRS complex represents ventricular depolarisation.",
    },
    {
        "question": "Which of the following statements is correct?",
        "options": ["Adenine pairs with thymine through two H-bonds.", "Adenine pairs with thymine through one H-bond.", "Adenine pairs with thymine through three H-bonds.", "Adenine does not pair with thymine."],
        "correct_option_id": 0,
        "explanation": "Adenine pairs with thymine through two hydrogen bonds (while guanine pairs with cytosine through three).",
    },
    {
        "question": "The sequence that controls the copy number of the linked DNA in the vector, is termed:",
        "options": ["Selectable marker", "Ori site", "Palindromic sequence", "Recognition site"],
        "correct_option_id": 1,
        "explanation": "The origin of replication (ori) controls how many copies of the linked DNA are produced within the host cell.",
    },
    {
        "question": "Identify the basic amino acid from the following.",
        "options": ["Tyrosine", "Glutamic Acid", "Lysine", "Valine"],
        "correct_option_id": 2,
        "explanation": "Lysine is a basic amino acid (has an additional amino group in its side chain).",
    },
    {
        "question": "Select the correct statement.",
        "options": ["Glucocorticoids stimulate gluconeogenesis.", "Glucagon is associated with hypoglycemia.", "Insulin acts on pancreatic cells and adipocytes.", "Insulin is associated with hyperglycemia."],
        "correct_option_id": 0,
        "explanation": "Glucocorticoids (like cortisol) stimulate gluconeogenesis. (Glucagon causes hyperglycemia, insulin acts mainly on hepatocytes/adipocytes/muscle cells and is associated with hypoglycemia.)",
    },
    {
        "question": "Which one of the following is the most abundant protein in the animals?",
        "options": ["Haemoglobin", "Collagen", "Lectin", "Insulin"],
        "correct_option_id": 1,
        "explanation": "Collagen is the most abundant protein in the animal kingdom.",
    },
    {
        "question": "Experimental verification of the chromosomal theory of inheritance was done by:",
        "options": ["Mendel", "Sutton", "Boveri", "Morgan"],
        "correct_option_id": 3,
        "explanation": "While Sutton and Boveri proposed the chromosomal theory of inheritance, Thomas Hunt Morgan provided its experimental verification using Drosophila.",
    },
    {
        "question": "The number of substrate level phosphorylations in one turn of citric acid cycle is:",
        "options": ["Zero", "One", "Two", "Three"],
        "correct_option_id": 1,
        "explanation": "One substrate-level phosphorylation occurs per turn of the citric acid cycle (conversion of succinyl-CoA to succinate, generating one GTP/ATP).",
    },
    {
        "question": "Dissolution of the synaptonemal complex occurs during:",
        "options": ["Pachytene", "Zygotene", "Diplotene", "Leptotene"],
        "correct_option_id": 2,
        "explanation": "The synaptonemal complex dissolves during diplotene, after which the paired homologous chromosomes (bivalents) begin to separate and chiasmata become visible.",
    },
    {
        "question": "Bilaterally symmetrical and acoelomate animals are exemplified by:",
        "options": ["Ctenophora", "Platyhelminthes", "Aschelminthes", "Annelida"],
        "correct_option_id": 1,
        "explanation": "Platyhelminthes (flatworms) are bilaterally symmetrical and acoelomate (lack a body cavity).",
    },
    {
        "question": "The body of the ovule is fused within the funicle at:",
        "options": ["Hilum", "Micropyle", "Nucellus", "Chalaza"],
        "correct_option_id": 3,
        "explanation": "The chalaza is the basal region where the body of the ovule is fused with the funicle.",
    },
    {
        "question": "Goblet cells of alimentary canal are modified from:",
        "options": ["Squamous epithelial cells", "Columnar epithelial cells", "Chondrocytes", "Compound epithelial cells"],
        "correct_option_id": 1,
        "explanation": "Goblet cells are modified (specialized) columnar epithelial cells that secrete mucus.",
    },
    {
        "question": "Snow-blindness in Antarctic region is due to:",
        "options": ["Freezing of fluids in the eye by low temperature", "Inflammation of cornea due to high dose of UV-B radiation", "High reflection of light from snow", "Damage to retina caused by infra-red rays"],
        "correct_option_id": 1,
        "explanation": "Increased UV-B radiation (due to ozone depletion) causes inflammation of the cornea, resulting in snow-blindness.",
    },
]
